{
 "title": "Kubernetes: Cluster / Nodes",
 "tags": [
  "maintainer:danil",
  "k8s-cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "query_result(label_join(up{job=\"kubelet-main\"}, \"human_name\", \"/\", \"cluster_type\", \"cluster\"))"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_info{cluster=\"$cluster\"},node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 11, "w": 22, "x": 1, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by (node, internal_ip, kernel_version, kubelet_version, os_image, pod_cidr, system_uuid) (last_over_time(kube_node_info{cluster=\"$cluster\", node=~\"$node\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(node) (max_over_time(node_namespace:container_cpu_usage_seconds:irate{cluster=\"$cluster\", node=~\"$node\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (node) (last_over_time(node_namespace:kube_pod_container_resource_requests{cluster=\"$cluster\", node=~\"$node\", resource=\"cpu\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (node) (last_over_time(node_namespace:container_memory_rss{cluster=\"$cluster\", node=~\"$node\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (node) (last_over_time(node_namespace:kube_pod_container_resource_requests{cluster=\"$cluster\", node=~\"$node\", resource=\"memory\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (node) (last_over_time(kube_node_created{cluster=\"$cluster\", node=~\"$node\"}[$__range])) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - sum by (node) (last_over_time(kube_node_created:last_seen{cluster=\"$cluster\", node=~\"$node\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by(node) (max_over_time(kube_pod_info{cluster=\"$cluster\", node=~\"$node\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ephemeral Storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (node) (max_over_time(ephemeral_storage_pod_usage{cluster=\"$cluster\", node=~\"$node\"}[$__interval]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Compute", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(node) (max_over_time(node_namespace:container_cpu_usage_seconds:irate{cluster=\"$cluster\", node=~\"$node\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory RAW",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (node) (max_over_time(node_namespace:container_memory_usage_bytes{cluster=\"$cluster\", node=~\"$node\"}[$__interval]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory RSS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (node) (max_over_time(node_namespace:container_memory_rss{cluster=\"$cluster\", node=~\"$node\"}[$__interval]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (node) (max_over_time(node_namespace:container_network_receive_bytes:irate{cluster=\"$cluster\", node=~\"$node\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (node) (max_over_time(node_namespace:container_network_transmit_bytes:irate{cluster=\"$cluster\", node=~\"$node\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}