{
 "title": "Cluster / Namespaces",
 "tags": [
  "maintainer:danil",
  "k8s-cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "query_result(label_join(up{job=\"kubelet-main\"}, \"human_name\", \"/\", \"cluster_type\", \"cluster\"))"
    }
   },
   { "name": "namespace_filter", "label": "filter" },
   {
    "name": "namespace",
    "query": {
     "query": "query_result(last_over_time(kube_namespace_created{cluster=\"$cluster\", namespace=~\".*($namespace_filter).*\"}[$__range]))"
    }
   },
   {
    "name": "_safe_interval_200",
    "query": {
     "query": "query_result(((($__range_ms / 200) > bool ($__interval_ms * 2))* scalar(round(vector($__range_ms / 200 / 1000)))+(($__range_ms / 200) <= bool ($__interval_ms * 2))* scalar(round(vector($__interval_ms * 2 / 1000))))# original structure of query is here because in the query input panel line breaks are automatically removed# scalar(round(vector)) is needed because prometheus 2 can't use intervals with non-integer values)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 11, "w": 18, "x": 1, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by (namespace) (last_over_time(kube_pod_owner{cluster=\"$cluster\", namespace=~\"$namespace\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(namespace) (avg_over_time(node_namespace:container_cpu_usage_seconds:irate{cluster=\"$cluster\", namespace=~\"$namespace\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (namespace) (last_over_time(node_namespace:kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=~\"$namespace\", resource=\"cpu\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (namespace) (last_over_time(node_namespace:container_memory_rss{cluster=\"$cluster\", namespace=~\"$namespace\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (namespace) (last_over_time(node_namespace:kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=~\"$namespace\", resource=\"memory\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (namespace) (last_over_time(kube_namespace_created{cluster=\"$cluster\", namespace=~\"$namespace\"}[$__range])) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by(namespace) (max_over_time(kube_pod_owner{cluster=\"$cluster\", namespace=~\"$namespace\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by(namespace) (increase(kube_pod_container_status_restarts_total{cluster=\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ephemeral Storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace) (max_over_time(ephemeral_storage_pod_usage{cluster=\"$cluster\", namespace=~\"$namespace\"}[$__interval]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Compute", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(namespace) (max_over_time(node_namespace:container_cpu_usage_seconds:irate{cluster=\"$cluster\", namespace=~\"$namespace\"}[${_safe_interval_200}s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory RAW",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace) (max_over_time(node_namespace:container_memory_usage_bytes{cluster=\"$cluster\", namespace=~\"$namespace\"}[$__interval]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory RSS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace) (max_over_time(node_namespace:container_memory_rss{cluster=\"$cluster\", namespace=~\"$namespace\"}[$__interval]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (namespace) (max_over_time(node_namespace:container_network_receive_bytes:irate{cluster=\"$cluster\", namespace=~\"$namespace\"}[$_safe_interval_200]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (namespace) (max_over_time(node_namespace:container_network_transmit_bytes:irate{cluster=\"$cluster\", namespace=~\"$namespace\"}[$_safe_interval_200]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}