{
 "title": "Kubernetes / Namespace (Workloads)",
 "tags": [
  "k8s-cluster",
  "maintainer:danil"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "query_result(label_join(up{job=\"kube-state-metrics\", endpoint=\"\"}, \"human_name\", \"/\", \"cluster_type\", \"cluster\"))"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "workload",
    "label": "Workload",
    "query": {
     "query": "query_result(label_join(namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\"}, \"human_name\", \"/\", \"workload_type\", \"workload\"))"
    }
   },
   {
    "name": "workloadSum",
    "label": "Sum",
    "query": "Show : \"\", Hide : \"invalid123\""
   },
   {
    "name": "workloadAvg",
    "label": "Avg/Max",
    "query": "Show : \"\", Hide : \"invalid123\""
   }
  ]
 },
 "panels": [
  {
   "title": "Status ready",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (workload_type, workload) (\r\n    min by (cluster, namespace, pod) (min_over_time(kube_pod_container_status_ready{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))\r\n    * on(cluster, namespace, pod) group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"$workload\", workload_type=\"deployment\"}\r\n) / sum by(workload_type, workload) (label_replace(label_replace(kube_deployment_spec_replicas{cluster=\"$cluster\", namespace=\"$namespace\"}, \"workload_type\",\"deployment\",\"\", \"\"), \"workload\",\"$1\",\"deployment\", \"(.+)\"))",
     "legendFormat": "{{workload_type}}/{{workload}}"
    },
    {
     "expr": "sum by (workload_type, workload) (\r\n    min by (cluster, namespace, pod) (min_over_time(kube_pod_container_status_ready{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))\r\n    * on(cluster, namespace, pod) group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"$workload\", workload_type=\"daemonset\"}\r\n) / sum by(workload_type, workload) (label_replace(label_replace(kube_daemonset_status_desired_number_scheduled{cluster=\"$cluster\", namespace=\"$namespace\"}, \"workload_type\",\"daemonset\",\"\", \"\"), \"workload\",\"$1\",\"daemonset\", \"(.+)\"))",
     "legendFormat": "{{workload_type}}/{{workload}} 2"
    }
   ]
  },
  {
   "title": "CPU Utilization (from requests)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) / sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilisation (from limits)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilisation (from requests)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\",container!=\"\", image!=\"\"}) / sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilisation (from limits)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\",container!=\"\", image!=\"\"}) / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by (workload_type, workload) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$namespace\"} * on(cluster, namespace, pod) group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"$workload\", invalid=$workloadSum})",
     "legendFormat": "{{workload_type}}/{{workload}} (sum)"
    },
    {
     "expr": "avg by (workload_type, workload) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$namespace\"} * on(cluster, namespace, pod) group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"$workload\", invalid=$workloadAvg})",
     "legendFormat": "{{workload_type}}/{{workload}} (avg)"
    },
    {
     "expr": "max by (workload_type, workload) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$namespace\"} * on(cluster, namespace, pod) group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"$workload\", invalid=$workloadAvg})",
     "legendFormat": "{{workload_type}}/{{workload}} (max)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "table",
   "gridPos": { "h": 10, "w": 17, "x": 1, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by (workload_type, workload) (avg_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$namespace\"}[$__range]) * on(cluster, namespace, pod) group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"$workload\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (workload_type, workload) (avg_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$namespace\"}[$__range]) * on(cluster, namespace, pod) group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"$workload\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (workload_type, workload) (last_over_time(kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", resource=\"cpu\"}[$__range]) * on(cluster, namespace, pod) group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"$workload\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (workload_type, workload) (avg_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$namespace\"}[$__range]) / on(cluster, namespace, pod, container) kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", resource=\"cpu\"} * on(cluster, namespace, pod) group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"$workload\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (workload_type, workload) (last_over_time(kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", resource=\"cpu\"}[$__range]) * on(cluster, namespace, pod) group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"$workload\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (workload_type, workload) (avg_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$namespace\"}[$__range]) / on(cluster, namespace, pod, container) kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", resource=\"cpu\"} * on(cluster, namespace, pod) group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"$workload\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Memory",
   "type": "table",
   "gridPos": { "h": 10, "w": 17, "x": 1, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (workload_type, workload) (container_memory_rss{cluster=\"$cluster\", namespace=\"$namespace\"} * on(cluster, namespace, pod) group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"$workload\"})"
    },
    {
     "expr": "sum by (workload_type, workload) (kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", resource=\"memory\"} * on(cluster, namespace, pod) group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"$workload\"})"
    },
    {
     "expr": "max by (workload_type, workload) (container_memory_rss{cluster=\"$cluster\", namespace=\"$namespace\"} / on(cluster, namespace, pod, container) group_left kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", resource=\"memory\"} * on(cluster, namespace, pod) group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"$workload\"})"
    },
    {
     "expr": "sum by (workload_type, workload) (kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", resource=\"memory\"} * on(cluster, namespace, pod) group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"$workload\"})"
    },
    {
     "expr": "max by (workload_type, workload) (container_memory_rss{cluster=\"$cluster\", namespace=\"$namespace\"} / on(cluster, namespace, pod, container) group_left kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", resource=\"memory\"} * on(cluster, namespace, pod) group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"$workload\"})"
    },
    {
     "expr": "sum by (workload_type, workload) (container_memory_usage_bytes{cluster=\"$cluster\", namespace=\"$namespace\"} * on(cluster, namespace, pod) group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"$workload\"})"
    }
   ]
  },
  {
   "title": "Memory notes",
   "type": "text",
   "gridPos": { "h": 10, "w": 5, "x": 18, "y": 28 },
   "options": {
    "content": "- Raw usage = RSS + Cache\n- RSS is actually allocated memory\n- Cache = Active + Inactive file\n- WSS = Raw usage - Inactive file = RSS + Active file\n\nWhat to look for:\n- WSS reaching limit causes file garbage collection\n- RSS reaching limit causes OOM\n"
   }
  },
  {
   "title": "Memory Usage (Raw)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "# max by(pod, container) should fix overlapping data on container restarts\r\nsum by (workload_type, workload) (max by(cluster, namespace, pod, container) (max_over_time(container_memory_usage_bytes{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) * on(cluster, namespace, pod) group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"$workload\", invalid=$workloadSum})",
     "legendFormat": "{{workload_type}}/{{workload}} (sum)"
    },
    {
     "expr": "# max by(pod, container) should fix overlapping data on container restarts\r\navg by (workload_type, workload) (max by(cluster, namespace, pod, container) (max_over_time(container_memory_usage_bytes{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) * on(cluster, namespace, pod) group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"$workload\", invalid=$workloadAvg})",
     "legendFormat": "{{workload_type}}/{{workload}} (avg)"
    },
    {
     "expr": "# max by(pod, container) should fix overlapping data on container restarts\r\nmax by (workload_type, workload) (max by(cluster, namespace, pod, container) (max_over_time(container_memory_usage_bytes{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) * on(cluster, namespace, pod) group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"$workload\", invalid=$workloadAvg})",
     "legendFormat": "{{workload_type}}/{{workload}} (max)"
    }
   ]
  },
  {
   "title": "Memory Usage (RSS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "# max by(pod, container) should fix overlapping data on container restarts\r\nsum by (workload_type, workload) (max by(cluster, namespace, pod, container) (max_over_time(container_memory_rss{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) * on(cluster, namespace, pod) group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"$workload\", invalid=$workloadSum})",
     "legendFormat": "{{workload_type}}/{{workload}} (sum)"
    },
    {
     "expr": "# max by(pod, container) should fix overlapping data on container restarts\r\navg by (workload_type, workload) (max by(cluster, namespace, pod, container) (max_over_time(container_memory_rss{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) * on(cluster, namespace, pod) group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"$workload\", invalid=$workloadAvg})",
     "legendFormat": "{{workload_type}}/{{workload}} (avg)"
    },
    {
     "expr": "# max by(pod, container) should fix overlapping data on container restarts\r\nmax by (workload_type, workload) (max by(cluster, namespace, pod, container) (max_over_time(container_memory_rss{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) * on(cluster, namespace, pod) group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"$workload\", invalid=$workloadAvg})",
     "legendFormat": "{{workload_type}}/{{workload}} (max)"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Current Network Usage",
   "type": "table",
   "gridPos": { "h": 10, "w": 17, "x": 1, "y": 47 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_network_transmit_packets_dropped_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Received Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_packets_dropped_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}