{
 "title": "Kubernetes / Node (Pods)",
 "tags": [
  "maintainer:danil",
  "k8s-cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "query_result(label_join(up{job=\"kube-state-metrics\", endpoint=\"\"}, \"human_name\", \"/\", \"cluster_type\", \"cluster\"))"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(kube_node_info{cluster=\"$cluster\"}, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{cluster=\"$cluster\", job=\"kube-state-metrics\", node=~\"$node\", resource=\"cpu\"})",
     "legendFormat": "max capacity"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", node=~\"$node\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 13, "w": 18, "x": 1, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", node=~\"$node\"})"
    },
    {
     "expr": "sum by (namespace, pod) (kube_pod_container_resource_requests{cluster=\"$cluster\", node=~\"$node\", resource=\"cpu\"})"
    },
    {
     "expr": "max by (namespace, pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", node=~\"$node\"} / on(namespace, pod, container) kube_pod_container_resource_requests{cluster=\"$cluster\", node=~\"$node\", resource=\"cpu\"})"
    },
    {
     "expr": "sum by (namespace, pod) (kube_pod_container_resource_limits{cluster=\"$cluster\", node=~\"$node\", resource=\"cpu\"})"
    },
    {
     "expr": "max by (namespace, pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", node=~\"$node\"} / on(namespace, pod, container) kube_pod_container_resource_limits{cluster=\"$cluster\", node=~\"$node\", resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Memory Usage (raw)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{cluster=\"$cluster\", job=\"kube-state-metrics\", node=~\"$node\", resource=\"memory\"})",
     "legendFormat": "max capacity"
    },
    {
     "expr": "sum by (pod) (container_memory_usage_bytes{cluster=\"$cluster\", instance=~\"$node\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "(\r\n  node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"$node\", cluster=\"$cluster\"}\r\n-\r\n  node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"$node\", cluster=\"$cluster\"}\r\n)\r\n",
     "legendFormat": "node usage"
    },
    {
     "expr": "sum (kube_pod_container_resource_limits{cluster=\"$cluster\", node=\"$node\", resource=\"memory\"})",
     "legendFormat": "pod limits"
    }
   ]
  },
  {
   "title": "Memory Usage (rss)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{cluster=\"$cluster\", job=\"kube-state-metrics\", node=~\"$node\", resource=\"memory\"})",
     "legendFormat": "max capacity"
    },
    {
     "expr": "sum(container_memory_rss{cluster=\"$cluster\", instance=~\"$node\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "(\r\n  node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"$node\", cluster=\"$cluster\"}\r\n-\r\n  node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"$node\", cluster=\"$cluster\"}\r\n-\r\n  node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"$node\", cluster=\"$cluster\"}\r\n-\r\n  node_memory_Cached_bytes{job=\"node-exporter\", instance=\"$node\", cluster=\"$cluster\"}\r\n)\r\n",
     "legendFormat": "node usage"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests{cluster=\"$cluster\", node=\"$node\", resource=\"memory\"})",
     "legendFormat": "pod requests"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 11, "w": 18, "x": 1, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod) (container_memory_usage_bytes{cluster=\"$cluster\", instance=\"$node\"})"
    },
    {
     "expr": "sum by (namespace, pod) (kube_pod_container_resource_requests{cluster=\"$cluster\", node=\"$node\", resource=\"memory\"})"
    },
    {
     "expr": "max by (namespace, pod) (container_memory_usage_bytes{cluster=\"$cluster\", node=\"$node\",container!=\"\"} / on(namespace, pod, container) kube_pod_container_resource_requests{cluster=\"$cluster\", node=~\"$node\", resource=\"memory\"})"
    },
    {
     "expr": "sum by (namespace, pod) (kube_pod_container_resource_limits{cluster=\"$cluster\", node=\"$node\", resource=\"memory\"})"
    },
    {
     "expr": "max by (namespace, pod) (container_memory_usage_bytes{cluster=\"$cluster\", node=\"$node\"} / on(namespace, pod, container) kube_pod_container_resource_limits{cluster=\"$cluster\", node=~\"$node\", resource=\"memory\"})"
    },
    {
     "expr": "sum by (namespace, pod) (container_memory_rss{cluster=\"$cluster\", instance=\"$node\"})"
    },
    {
     "expr": "sum by (namespace, pod) (container_memory_cache{cluster=\"$cluster\", instance=\"$node\"})"
    }
   ]
  }
 ]
}