{
 "title": "cert-manager",
 "description": "Monitors Certificates managed by cert-manager",
 "tags": [ "maintainer:danil" ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(certmanager_certificate_expiration_timestamp_seconds[$__range])))"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "query_result(group by(namespace) (last_over_time(certmanager_certificate_expiration_timestamp_seconds{location=\"$location\"}[$__range])))"
    }
   },
   {
    "name": "issuer",
    "query": {
     "query": "query_result(label_join(last_over_time(certmanager_certificate_ready_status{location=\"$location\", namespace=~\"$namespace\", condition=\"True\"}[$__range]), \"human_name\", \"/\", \"issuer_kind\", \"issuer_name\"))"
    }
   },
   {
    "name": "certificate",
    "query": {
     "query": "query_result(last_over_time(certmanager_certificate_ready_status{location=\"$location\", namespace=~\"$namespace\", issuer_name=~\"$issuer\", condition=\"True\"}[$__range]))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Certificates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Currently active certificates",
   "type": "table",
   "gridPos": { "h": 13, "w": 22, "x": 1, "y": 1 },
   "targets": [
    {
     "expr": "min by (name, namespace, issuer_kind, issuer_name) (certmanager_certificate_expiration_timestamp_seconds{location=\"$location\", namespace=~\"$namespace\", issuer_name=~\"$issuer\", name=~\"$certificate\"} - time())",
     "legendFormat": "__auto"
    },
    {
     "expr": "min by (name, namespace) (certmanager_certificate_ready_status{location=\"$location\", namespace=~\"$namespace\", issuer_name=~\"$issuer\", name=~\"$certificate\", condition=\"True\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "min by (name, namespace) (certmanager_certificate_renewal_timestamp_seconds{location=\"$location\", namespace=~\"$namespace\", issuer_name=~\"$issuer\", name=~\"$certificate\"} - time())",
     "legendFormat": "__auto"
    },
    {
     "expr": "min by (name, namespace) (\r\n  (certmanager_certificate_expiration_timestamp_seconds{location=\"$location\", namespace=~\"$namespace\", issuer_name=~\"$issuer\", name=~\"$certificate\"} - time())\r\n  /\r\n  (certmanager_certificate_expiration_timestamp_seconds - certmanager_certificate_renewal_timestamp_seconds)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Certificate Status Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (condition) (certmanager_certificate_ready_status{location=\"$location\", namespace=~\"$namespace\", issuer_name=~\"$issuer\", name=~\"$certificate\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Certificate Ready Status",
   "type": "state-timeline",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min by (namespace, name) (min_over_time(certmanager_certificate_ready_status{location=\"$location\", namespace=~\"$namespace\", issuer_name=~\"$issuer\", name=~\"$certificate\", condition=\"True\"}[$__interval]))",
     "legendFormat": "{{namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "Renewal % Left",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (name, namespace) (\r\n  (certmanager_certificate_expiration_timestamp_seconds{location=\"$location\", namespace=~\"$namespace\", issuer_name=~\"$issuer\", name=~\"$certificate\"} - time())\r\n  /\r\n  (certmanager_certificate_expiration_timestamp_seconds - certmanager_certificate_renewal_timestamp_seconds)\r\n)",
     "legendFormat": "{{namespace}} / {{name}}"
    }
   ]
  },
  {
   "title": "Time Left",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(namespace, name) (min_over_time(certmanager_certificate_expiration_timestamp_seconds{location=\"$location\", namespace=~\"$namespace\", issuer_name=~\"$issuer\", name=~\"$certificate\"}[$__interval]) - time())",
     "legendFormat": "{{namespace}} / {{name}}"
    }
   ]
  },
  {
   "title": "ACME Requests",
   "type": "timeseries",
   "description": "Can be empty if current instance of cert-manager has not made any requests",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status, path) (rate(certmanager_http_acme_client_request_count{location=\"$location\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "{{status}} {{path}}"
    }
   ]
  }
 ]
}