---
apiVersion: v1
kind: Service
metadata:
  name: authelia
  namespace: authelia
  labels:
    app.kubernetes.io/name: authelia
    app.kubernetes.io/instance: authelia
spec:
  selector:
    app: authelia
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  - name: metrics
    protocol: TCP
    port: 9959
    targetPort: metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authelia
  namespace: authelia
spec:
  selector:
    matchLabels:
      app: authelia
  revisionHistoryLimit: 00
  replicas: 1
  minReadySeconds: 0
  template:
    metadata:
      labels:
        app: authelia
    spec:
      containers:
      - name: authelia
        image: ghcr.io/authelia/authelia:4.39.12
        ports:
        - name: http
          containerPort: 9091
          protocol: TCP
        - name: metrics
          containerPort: 9959
          protocol: TCP
        command:
        - /entrypoint.sh
        resources:
          requests:
            memory: 50Mi
            cpu: 10m
          limits:
            memory: 100Mi
        securityContext:
          readOnlyRootFilesystem: true
        env:
        - name: AUTHELIA_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: authelia-domain
              key: domain
        - name: AUTHELIA_NAME
          valueFrom:
            configMapKeyRef:
              name: authelia-domain
              key: name
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-authelia-app
              key: password
        - name: AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE
          value: /secrets/internal/identity_validation.reset_password.jwt_secret
        - name: AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE
          value: /secrets/internal/identity_providers.oidc.hmac_secret
        - name: AUTHELIA_SESSION_SECRET_FILE
          value: /secrets/internal/session.secret
        - name: AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE
          value: /secrets/internal/storage.encryption_key
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dragonfly-auth
              key: password
        - name: LDAP_USER
          valueFrom:
            secretKeyRef:
              name: authelia-ldap-auth
              key: user
        - name: LDAP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: authelia-ldap-auth
              key: password
        - name: X_AUTHELIA_CONFIG
          value: /config
        - name: X_AUTHELIA_CONFIG_FILTERS
          value: template
        startupProbe:
          httpGet:
            path: /api/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 1
          failureThreshold: 300
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /api/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 10
          failureThreshold: 5
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /api/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 5
          failureThreshold: 5
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /run
          name: tmp
        - mountPath: /notifications
          name: config-dir
        - mountPath: /config
          name: config
        - mountPath: /secrets/internal
          name: secrets
        - mountPath: /secrets/keys
          name: keys
        - mountPath: /entrypoint.sh
          name: entrypoint
          subPath: entrypoint.sh
      volumes:
      - name: config-dir
        emptyDir:
          sizeLimit: 100Mi
      - name: config
        configMap:
          name: authelia-config
      - name: secrets
        secret:
          secretName: authelia-secrets
      - name: keys
        secret:
          secretName: authelia-keys
      - name: entrypoint
        configMap:
          name: authelia-entrypoint
          defaultMode: 0555
      - name: tmp
        emptyDir: {}
