{
 "title": "Container / Logs",
 "tags": [
  "maintainer:danil",
  "type:logs",
  "k8s-cluster"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "360d",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "logs_source",
    "label": "Logs source",
    "query": "victoriametrics-logs-datasource"
   },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(up{job=\"kube-state-metrics\", endpoint=\"\"}[$__range])))"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{location=\"$location\"},namespace)"
    }
   },
   {
    "name": "workload",
    "query": {
     "query": "query_result(label_join(last_over_time(namespace_workload_pod:kube_pod_owner:relabel{location=\"$location\", namespace=\"$namespace\"}[$__range]), \"human_name\", \"/\", \"workload_type\", \"workload\"))"
    }
   },
   {
    "name": "pod0",
    "label": "pod0",
    "query": {
     "query": "query_result(last_over_time(namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"$workload\"}[$__range]) * on(cluster, namespace, pod, uid) group_left() max by(cluster, namespace, pod, uid) (last_over_time(kube_pod_container_status_ready{cluster=\"$cluster\", namespace=\"$namespace\"}[$__range])))"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "kubernetes.pod_namespace:$namespace"
    }
   },
   {
    "name": "pod_uid",
    "label": "UID",
    "query": {
     "query": "query_result(last_over_time(kube_pod_info{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\"}[$__range]))"
    }
   },
   {
    "name": "container",
    "label": "container",
    "query": {
     "query": "query_result(group by(human_name, container) (  label_replace(    last_over_time(      kube_pod_container_info{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\"}[$__range]    ),    \"human_name\",    \"main/$1\",    \"container\",    \"(.*)\"  )or  (        (            max_over_time(              kube_pod_status_phase{location=\"$location\", namespace=\"$namespace\", phase=\"Pending\", pod=~\"$pod\", uid=~\"$pod_uid\"}[$__range]            )          ==            1        )      *        0    + on (uid) group_right()      label_replace(        last_over_time(          kube_pod_init_container_info{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", restart_policy!=\"Always\"}[$__range]        ),        \"human_name\",        \"init/$1\",        \"container\",        \"(.*)\"      )  )  or (      label_replace(        last_over_time(          kube_pod_init_container_info{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", restart_policy=\"Always\"}[$__range]        ),        \"human_name\",        \"sidecar/$1\",        \"container\",        \"(.*)\"      )      )))"
    }
   },
   {
    "name": "id_query",
    "query": {
     "query": "query_result(label_replace(label_replace(last_over_time(container_cpu_usage_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\"}[$__range]),\"human_name\", \"$1\",\"name\", \"(.{8}).*\"),\"id_query\", \"containerd://$1\",\"name\", \"(.+)\"))"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{\r\nkubernetes.pod_namespace=$namespace\r\n,kubernetes.pod_name=$pod\r\n,kubernetes.container_name=$container\r\n}\r\nkubernetes.container_id:in($id_query)\r\n| stats by(stream) count()",
     "legendFormat": "{{stream}}"
    }
   ]
  },
  {
   "title": "stdout",
   "type": "logs",
   "gridPos": { "h": 21, "w": 21, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{\r\nkubernetes.pod_namespace=$namespace,\r\nkubernetes.pod_name=$pod,\r\nkubernetes.container_name=$container,\r\nstream=\"stdout\"\r\n}\r\nkubernetes.container_id:in($id_query)\r\n| drop file, ingest_timestamp, _stream_id, kubernetes.container_image_id, kubernetes.namespace_labels.kubernetes.io/metadata.name, kubernetes.namespace_labels.pod-security.kubernetes.io/enforce, kubernetes.pod_annotations.kubectl.kubernetes.io/default-container, kubernetes.pod_labels.controller-revision-hash, kubernetes.pod_labels.app.kubernetes.io/instance, kubernetes.pod_labels.app.kubernetes.io/managed-by, kubernetes.pod_labels.apps.kubernetes.io/pod-index, kubernetes.pod_labels.app.kubernetes.io/name, kubernetes.pod_labels.app.kubernetes.io/version, kubernetes.pod_labels.statefulset.kubernetes.io/pod-name, kubernetes.pod_owner, source_type"
    }
   ]
  },
  {
   "title": "stderr",
   "type": "logs",
   "gridPos": { "h": 21, "w": 21, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "{\r\nkubernetes.pod_namespace=$namespace,\r\nkubernetes.pod_name=$pod,\r\nkubernetes.container_name=$container,\r\nstream=\"stderr\"\r\n}\r\nkubernetes.container_id:in($id_query)\r\n| drop file, ingest_timestamp, _stream_id, kubernetes.container_image_id, kubernetes.namespace_labels.kubernetes.io/metadata.name, kubernetes.namespace_labels.pod-security.kubernetes.io/enforce, kubernetes.pod_annotations.kubectl.kubernetes.io/default-container, kubernetes.pod_labels.controller-revision-hash, kubernetes.pod_labels.app.kubernetes.io/instance, kubernetes.pod_labels.app.kubernetes.io/managed-by, kubernetes.pod_labels.apps.kubernetes.io/pod-index, kubernetes.pod_labels.app.kubernetes.io/name, kubernetes.pod_labels.app.kubernetes.io/version, kubernetes.pod_labels.statefulset.kubernetes.io/pod-name, kubernetes.pod_owner, source_type, kubernetes.pod_annotations.cnpg.io/podSpec"
    }
   ]
  }
 ]
}