{
 "title": "k8s apiserver resources",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(up{job=\"kube-apiserver\"}[$__range])))"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(group by(instance) (last_over_time(up{job=\"kube-apiserver\", location=\"$location\"}[$__range])))"
    }
   },
   { "name": "resource_filter" },
   {
    "name": "resource",
    "query": {
     "query": "query_result(group by(resource) (max_over_time(apiserver_storage_objects{instance=\"$instance\", resource=~\".*($resource_filter).*\"}[$__range]) != 0))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "response size (median)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(group, resource, verb, quantile) (\r\nmax_over_time(apiserver_response_sizes_bucket:quantile_irate{instance=\"$instance\", resource=~\"$resource\", group!=\"\", quantile=\"0.5\"}[$__interval])\r\n)",
     "legendFormat": "{{group}}/{{resource}} {{verb}}"
    },
    {
     "expr": "sum by(group, resource, verb, quantile) (\r\nmax_over_time(apiserver_response_sizes_bucket:quantile_irate{instance=\"$instance\", resource=~\"$resource\", group=\"\", quantile=\"0.5\"}[$__interval])\r\n)",
     "legendFormat": "{{resource}} {{verb}}"
    }
   ]
  },
  {
   "title": "response size q99",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(group, resource, verb) (\r\nmax_over_time(apiserver_response_sizes_bucket:quantile_irate{instance=\"$instance\", resource=~\"$resource\", group!=\"\", quantile=\"0.99\"}[$__interval])\r\n)",
     "legendFormat": "{{group}}/{{resource}} {{verb}}"
    },
    {
     "expr": "sum by(group, resource, verb) (\r\nmax_over_time(apiserver_response_sizes_bucket:quantile_irate{instance=\"$instance\", resource=~\"$resource\", group=\"\", quantile=\"0.99\"}[$__interval])\r\n)",
     "legendFormat": "{{resource}} {{verb}}"
    }
   ]
  },
  {
   "title": "requests total",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(group, resource, verb) (rate(apiserver_request_total{instance=\"$instance\", resource=~\"$resource\", group!=\"\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "{{group}}/{{resource}} {{verb}}"
    },
    {
     "expr": "sum by(group, resource, verb) (rate(apiserver_request_total{instance=\"$instance\", resource=~\"$resource\", group=\"\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "{{resource}} {{verb}}"
    }
   ]
  },
  {
   "title": "terminated requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(group, resource, verb) (rate(apiserver_request_terminations_total{instance=\"$instance\", resource=~\"$resource\", group!=\"\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "{{group}}/{{resource}} {{verb}}"
    },
    {
     "expr": "sum by(group, resource, verb) (rate(apiserver_request_terminations_total{instance=\"$instance\", resource=~\"$resource\", group=\"\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "{{resource}} {{verb}}"
    }
   ]
  },
  {
   "title": "terminated request %",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(group, resource, verb) (\r\n  rate(apiserver_request_total{instance=\"$instance\", resource=~\"$resource\", group!=\"\"}[$__rate_interval])\r\n  /\r\n  (rate(apiserver_request_terminations_total[$__rate_interval]) + 1e-6)\r\n)",
     "legendFormat": "{{group}}/{{resource}} {{verb}}"
    },
    {
     "expr": "sum by(group, resource, verb) (\r\n  rate(apiserver_request_total{instance=\"$instance\", resource=~\"$resource\", group=\"\"}[$__rate_interval])\r\n  /\r\n  (rate(apiserver_request_terminations_total[$__rate_interval]) + 1e-6)\r\n)",
     "legendFormat": "{{resource}} {{verb}}"
    }
   ]
  },
  {
   "title": "storage objects",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "max by(group, resource) (\r\n  max_over_time(apiserver_storage_objects{instance=\"$instance\", resource=~\"$resource\", group!=\"\"}[$__interval])\r\n)",
     "legendFormat": "{{group}}/{{resource}}"
    },
    {
     "expr": "max by(group, resource) (\r\n  max_over_time(apiserver_storage_objects{instance=\"$instance\", resource=~\"$resource\", group=\"\"}[$__interval])\r\n)",
     "legendFormat": "{{resource}}"
    }
   ]
  }
 ]
}