{
 "title": "k8s apiserver flow control",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "query_result(label_join(last_over_time(up{job=\"kube-apiserver\"}[$__range]), \"human_name\", \"/\", \"cluster_type\", \"cluster\"))"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(last_over_time(up{job=\"kube-apiserver\", cluster=\"$cluster\"}[$__range]))"
    }
   },
   {
    "name": "priority_level",
    "query": {
     "query": "query_result(last_over_time(apiserver_flowcontrol_dispatched_requests_total{instance=\"$instance\"}[$__range]))"
    }
   },
   {
    "name": "flow_schema",
    "query": {
     "query": "query_result(last_over_time(apiserver_flowcontrol_dispatched_requests_total{instance=\"$instance\", priority_level=~\"$priority_level\"}[$__range]))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "dispatched requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(flow_schema, priority_level) (\r\nmax by(instance, flow_schema, priority_level) (rate(apiserver_flowcontrol_dispatched_requests_total{instance=\"$instance\", priority_level=~\"$priority_level\", flow_schema=~\"$flow_schema\"}[$__rate_interval]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rejected requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(flow_schema, priority_level, reason) (\r\nmax by(instance, flow_schema, priority_level, reason) (rate(apiserver_flowcontrol_rejected_requests_total{instance=\"$instance\", priority_level=~\"$priority_level\", flow_schema=~\"$flow_schema\"}[$__rate_interval]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "execution time p99",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(flow_schema, priority_level, type) (\r\nmax by(instance, flow_schema, priority_level, type) (max_over_time(apiserver_flowcontrol_request_execution_seconds_bucket:quantile_irate{instance=\"$instance\", priority_level=~\"$priority_level\", flow_schema=~\"$flow_schema\", quantile=\"0.99\"}[$__interval]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "wait duration p99",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(flow_schema, priority_level) (\r\nmax by(instance, flow_schema, priority_level) (max_over_time(apiserver_flowcontrol_request_wait_duration_seconds_bucket:quantile_irate{instance=\"$instance\", priority_level=~\"$priority_level\", flow_schema=~\"$flow_schema\", quantile=\"0.99\"}[$__interval]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Seats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "seats: demand average",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(priority_level) (\r\nmax by(instance, priority_level) (max_over_time(apiserver_flowcontrol_demand_seats_average{instance=\"$instance\", priority_level=~\"$priority_level\"}[$__interval]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "seats: demand high watermark",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(priority_level) (\r\nmax by(instance, priority_level) (max_over_time(apiserver_flowcontrol_demand_seats_high_watermark{instance=\"$instance\", priority_level=~\"$priority_level\"}[$__interval]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "seats: lower limit",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(priority_level) (\r\nmax by(instance, priority_level) (max_over_time(apiserver_flowcontrol_lower_limit_seats{instance=\"$instance\", priority_level=~\"$priority_level\"}[$__interval]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "seats: nominal limit",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(priority_level) (\r\nmax by(instance, priority_level) (max_over_time(apiserver_flowcontrol_nominal_limit_seats{instance=\"$instance\", priority_level=~\"$priority_level\"}[$__interval]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "seats: target",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(priority_level) (\r\nmax by(instance, priority_level) (max_over_time(apiserver_flowcontrol_target_seats{instance=\"$instance\", priority_level=~\"$priority_level\"}[$__interval]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "seats: upper limit",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(priority_level) (\r\nmax by(instance, priority_level) (max_over_time(apiserver_flowcontrol_upper_limit_seats{instance=\"$instance\", priority_level=~\"$priority_level\"}[$__interval]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}