---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: immich

resources:
- ./env/dragonfly-immich.yaml

secretGenerator:
- name: dragonfly-auth
  envs:
  - ./env/password.env
  options:
    disableNameSuffixHash: true
