---
apiVersion: v1
kind: Service
metadata:
  name: dex
  namespace: auth-dex
  labels:
    app.kubernetes.io/name: dex
    app.kubernetes.io/instance: dex
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
    appProtocol: http
  - name: telemetry
    port: 5558
    targetPort: telemetry
    protocol: TCP
    appProtocol: http
  selector:
    app.kubernetes.io/name: dex
    app.kubernetes.io/instance: dex
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex
  namespace: auth-dex
  labels:
    app.kubernetes.io/name: dex
    app.kubernetes.io/instance: dex
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: dex
      app.kubernetes.io/instance: dex
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dex
        app.kubernetes.io/instance: dex
    spec:
      securityContext:
        fsGroup: 0
      containers:
      - name: dex
        securityContext:
          readOnlyRootFilesystem: true
        image: ghcr.io/dexidp/dex:v2.44.0
        imagePullPolicy: IfNotPresent
        command:
        - /entrypoint.sh
        # args: []
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-dex-app
              key: password
        ports:
        - name: http
          containerPort: 5556
          protocol: TCP
        - name: telemetry
          containerPort: 5558
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz/live
            port: telemetry
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: telemetry
        resources:
          requests:
            memory: 15Mi
          limits:
            memory: 30Mi
        volumeMounts:
        - mountPath: /run
          name: tmp
        - mountPath: /etc/dex
          name: config
        - mountPath: /entrypoint.sh
          name: entrypoint
          subPath: entrypoint.sh
      volumes:
      - name: config
        secret:
          secretName: dex-config
      - name: entrypoint
        configMap:
          name: dex-entrypoint
          defaultMode: 0555
      - name: tmp
        emptyDir: {}
