{
 "title": "Harbor",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(harbor_system_info[$__range])))"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "query_result(last_over_time(harbor_system_info{location=~\"$location\"}[$__range]))"
    }
   },
   {
    "name": "project",
    "query": {
     "query": "query_result(last_over_time(harbor_project_member_total{instance=~\"$instance\"}[$__range]))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "version",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "harbor_system_info{instance=\"$instance\"}",
     "legendFormat": "version"
    }
   ]
  },
  {
   "title": "projects",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "max by(project_name) (harbor_project_quota_usage_byte{instance=\"$instance\", project_name=~\"$project\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(project_name) (harbor_project_quota_byte{instance=\"$instance\", project_name=~\"$project\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(project_name, public) (harbor_project_repo_total{instance=\"$instance\", project_name=~\"$project\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(project_name, public) (harbor_project_artifact_total{instance=\"$instance\", project_name=~\"$project\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(project_name, public) (harbor_project_member_total{instance=\"$instance\", project_name=~\"$project\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "project used space",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(project_name) (max_over_time(harbor_project_quota_usage_byte{instance=\"$instance\", project_name=~\"$project\"}[$__interval]))",
     "legendFormat": "{{project_name}}"
    }
   ]
  },
  {
   "title": "project repositories",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "max by(project_name) (avg_over_time(harbor_project_repo_total{instance=\"$instance\", project_name=~\"$project\"}[$__interval]))",
     "legendFormat": "{{project_name}}"
    }
   ]
  },
  {
   "title": "project used space %",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "harbor_project_quota_usage_byte{instance=\"$instance\", project_name=~\"$project\"}\r\n/\r\n(harbor_project_quota_byte{instance=\"$instance\", project_name=~\"$project\"} != -1)",
     "legendFormat": "{{project_name}}"
    }
   ]
  },
  {
   "title": "project artifacts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "max by(project_name) (max_over_time(harbor_project_artifact_total{instance=\"$instance\", project_name=~\"$project\"}[$__interval]))",
     "legendFormat": "{{project_name}}"
    }
   ]
  },
  {
   "title": "artifacts pulled",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "max by(project_name) (rate(harbor_artifact_pulled{instance=\"$instance\", project_name=~\"$project\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "{{project_name}}"
    }
   ]
  }
 ]
}