
operator:
  # Name that will be assigned to most of internal Kubernetes objects like
  # Deployment, ServiceAccount, Role etc.
  name: mongo-operator

  # Name of the operator image
  operatorImageName: mongodb-kubernetes-operator

  # Name of the deployment of the operator pod
  deploymentName: mongo-operator

  # Version of mongodb-kubernetes-operator
  version: 0.10.0

  # Uncomment this line to watch all namespaces
  watchNamespace: "*"

  # Resources allocated to Operator Pod
  resources:
    limits:
      cpu: 0m
      memory: 1Gi
    requests:
      cpu: 0m
      memory: 200Mi

  # replicas deployed for the operator pod. Running 1 is optimal and suggested.
  replicas: 1

## Operator's database
database:
  name: mongodb-database
  # set this to the namespace where you would like
  # to deploy the MongoDB database,
  # Note if the database namespace is not same
  # as the operator namespace,
  # make sure to set "watchNamespace" to "*"
  # to ensure that the operator has the
  # permission to reconcile resources in other namespaces
  # namespace: mongodb-database

agent:
  name: mongodb-agent-ubi
  version: 107.0.1.8507-1
versionUpgradeHook:
  name: mongodb-kubernetes-operator-version-upgrade-post-start-hook
  version: 1.0.8
readinessProbe:
  name: mongodb-kubernetes-readinessprobe
  version: 1.0.19
mongodb:
  name: mongo
  repo: docker.io

registry:
  agent: quay.io/mongodb
  versionUpgradeHook: quay.io/mongodb
  readinessProbe: quay.io/mongodb
  operator: quay.io/mongodb
  pullPolicy: Always

# Set to false if CRDs have been installed already. The CRDs can be installed
# manually from the code repo: github.com/mongodb/mongodb-kubernetes-operator or
# using the `community-operator-crds` Helm chart.
community-operator-crds:
  enabled: false

# Deploys MongoDB with `resource` attributes.
createResource: false
resource:
  name: mongodb-replica-set
  version: 4.4.0
  members: 3
  tls:
    enabled: false

    # Installs Cert-Manager in this cluster.
    useX509: false
    sampleX509User: false
    useCertManager: true
    certificateKeySecretRef: tls-certificate
    caCertificateSecretRef: tls-ca-key-pair
    certManager:
      certDuration: 8760h   # 365 days
      renewCertBefore: 720h   # 30 days

  users: []
  # if using the MongoDBCommunity Resource, list any users to be added to the resource
  # users:
  # - name: my-user
  #   db: admin
  #   passwordSecretRef: # a reference to the secret that will be used to generate the user's password
  #     name: <secretName>
  #   roles:
  #     - name: clusterAdmin
  #       db: admin
  #     - name: userAdminAnyDatabase
  #       db: admin
  #     - name: readWriteAnyDatabase
  #       db: admin
  #     - name: dbAdminAnyDatabase
  #       db: admin
  #   scramCredentialsSecretName: my-scram

