{
 "title": "proxmox / guest details",
 "tags": [
  "proxmox",
  "maintainer:danil",
  "node"
 ],
 "time": { "from": "now-1d", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(pve_node_info{}[$__range])))"
    }
   },
   {
    "name": "node_name",
    "label": "Node",
    "query": {
     "query": "query_result(group by(name) (last_over_time(pve_node_info{location=\"$location\"}[$__range])))"
    }
   },
   {
    "name": "guest",
    "label": "Guest",
    "query": {
     "query": "query_result(pve_guest_info{location=\"$location\", node=~\"$node_name\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_up{location=\"$location\", id=\"$guest\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Guest info",
   "type": "stat",
   "gridPos": { "h": 6, "w": 14, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_guest_info{location=\"$location\", id=\"${guest}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_uptime_seconds{location=\"$location\", id=\"$guest\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_memory_size_bytes{location=\"$location\", id=\"$guest\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_memory_usage_bytes{location=\"$location\", id=\"$guest\"}",
     "legendFormat": "{{id}}"
    },
    {
     "expr": "pve_memory_size_bytes{location=\"$location\", id=\"$guest\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory history",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max_over_time(pve_memory_usage_bytes{location=\"$location\", id=\"$guest\"}[$__interval])",
     "legendFormat": "${guest:text} Memory Usage"
    },
    {
     "expr": "max_over_time(pve_memory_size_bytes{location=\"$location\", id=\"$guest\"}[$__interval])",
     "legendFormat": "${guest:text} Total Memory"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_cpu_usage_limit{location=\"$location\", id=\"$guest\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current CPU usage (in cores)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_cpu_usage_ratio{location=\"$location\", id=\"$guest\"} * pve_cpu_usage_limit",
     "legendFormat": "{{id}}"
    },
    {
     "expr": "pve_cpu_usage_limit{location=\"$location\", id=\"$guest\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU history",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(pve_cpu_usage_ratio{location=\"$location\", id=\"$guest\"}[$__interval])\r\n*\r\nmax_over_time(pve_cpu_usage_limit{location=\"$location\", id=\"$guest\"}[$__interval])",
     "legendFormat": "${guest:text} CPU usage"
    },
    {
     "expr": "max_over_time(pve_cpu_usage_limit{location=\"$location\", id=\"$guest\"}[$__interval])",
     "legendFormat": "${guest:text} CPU cores"
    }
   ]
  },
  {
   "title": "Disk size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_disk_size_bytes{location=\"$location\", id=\"$guest\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pve_disk_usage_bytes{location=\"$location\", id=\"$guest\"}",
     "legendFormat": "{{storage}}"
    },
    {
     "expr": "pve_disk_size_bytes{location=\"$location\", id=\"$guest\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk usage history",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max_over_time(pve_disk_usage_bytes{location=\"$location\", id=\"$guest\"}[$__interval])",
     "legendFormat": "${guest:text} disk usage"
    },
    {
     "expr": "max_over_time(pve_disk_size_bytes{location=\"$location\", id=\"$guest\"}[$__interval])",
     "legendFormat": "${guest:text} disk size"
    }
   ]
  },
  {
   "title": "Network IO/s",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(pve_network_receive_bytes{location=\"$location\", id=\"$guest\"}[$__rate_interval])",
     "legendFormat": "receive"
    },
    {
     "expr": "rate(pve_network_transmit_bytes{location=\"$location\", id=\"$guest\"}[$__rate_interval])",
     "legendFormat": "transmit"
    }
   ]
  },
  {
   "title": "Disk IO/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(pve_disk_read_bytes{location=\"$location\", id=\"$guest\"}[$__rate_interval])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(pve_disk_write_bytes{location=\"$location\", id=\"$guest\"}[$__rate_interval])",
     "legendFormat": "write"
    }
   ]
  }
 ]
}