{
 "title": "proxmox / guest list",
 "tags": [
  "proxmox",
  "maintainer:danil",
  "node"
 ],
 "time": { "from": "now-1d", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(pve_node_info{}[$__range])))"
    }
   },
   {
    "name": "node_name",
    "label": "Node",
    "query": {
     "query": "query_result(group by(name) (last_over_time(pve_node_info{location=\"$location\"}[$__range])))"
    }
   },
   { "name": "type", "query": "qemu, lxc" },
   { "name": "state", "query": "up : == 1, down : == 0" },
   { "name": "id_filter" },
   { "name": "name_filter" },
   {
    "name": "guest",
    "query": {
     "query": "query_result(label_join((last_over_time(pve_guest_info{location=\"$location\", node=~\"$node_name\", id=~\"($type)/($id_filter)\", name=~\".*($name_filter).*\"}[$__range]) or last_over_time(pve_guest_info{location=\"$location\", node=~\"$node_name\", id=~\"($type)/.*\", invalid=~\"$id_filter\", name=~\".*($name_filter).*\"}[$__range])) and on(id) (last_over_time(pve_up{location=\"$location\"}[$__range]) $state), \"human_name\", \": \", \"name\", \"id\"))"
    }
   }
  ]
 },
 "panels": [
  { "title": "general", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Guests",
   "type": "table",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max by(id, name, type, node, cgroup) (\r\n  label_replace(\r\n    label_replace(\r\n      last_over_time(pve_guest_info{location=\"$location\", id=~\"$guest\", name!=\"\"}[$__range])\r\n      or on(id)\r\n      last_over_time(pve_guest_info{location=\"$location\", id=~\"$guest\"}[$__range])\r\n      , \"cgroup\", \"/lxc/$1\", \"id\", \"lxc/(.*)\")\r\n  , \"cgroup\", \"/qemu.slice/$1.scope\", \"id\", \"qemu/(.*)\")\r\n)"
    },
    {
     "expr": "max by(id) (pve_up{location=\"$location\", id=~\"$guest\"})"
    },
    {
     "expr": "max by(id) (pve_cpu_usage_limit{location=\"$location\", id=~\"$guest\"})"
    },
    {
     "expr": "max by(id) (pve_cpu_usage_ratio{location=\"$location\", id=~\"$guest\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(id) (pve_memory_size_bytes{location=\"$location\", id=~\"$guest\"} and on (id, cluster) pve_guest_info{location=\"$location\", node=~\"$node_name\"})"
    },
    {
     "expr": "sum by(id) (pve_memory_usage_bytes{location=\"$location\", id=~\"$guest\", template!=\"1\"} / pve_memory_size_bytes and on (id) pve_up==1)"
    },
    {
     "expr": "sum by(id) (pve_disk_size_bytes{location=\"$location\", id=~\"$guest\"})"
    },
    {
     "expr": "sum by(id) (pve_disk_usage_bytes{location=\"$location\", id=~\"$guest\"} / pve_disk_size_bytes and on (id, cluster) pve_guest_info{location=\"$location\", node=~\"$node_name\", type=\"lxc\"})"
    },
    {
     "expr": "sum by(id) (increase(pve_network_receive_bytes{location=\"$location\", id=~\"$guest\"}[$__range]))"
    },
    {
     "expr": "sum by(id) (increase(pve_network_transmit_bytes{location=\"$location\", id=~\"$guest\"}[$__range]))"
    },
    {
     "expr": "sum by(id) (increase(pve_disk_read_bytes{location=\"$location\", id=~\"$guest\"}[$__range]))"
    },
    {
     "expr": "sum by(id) (increase(pve_disk_write_bytes{location=\"$location\", id=~\"$guest\"}[$__range]))"
    }
   ]
  },
  {
   "title": "VM state",
   "type": "state-timeline",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "max by(human_name) (\r\n  label_join(\r\n    min_over_time(pve_up{location=\"$location\", id=~\"$guest\"}[$__interval])\r\n    * on(id) group_right\r\n    last_over_time(pve_guest_info{location=\"$location\", id=~\"$guest\", name!=\"\"}[$__interval]),\r\n    \"human_name\", \": \", \"node\", \"name\", \"id\"\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "(\r\n  avg_over_time(pve_cpu_usage_ratio{location=\"$location\", id=~\"$guest\"}[$__interval])\r\n  *\r\n  avg_over_time(pve_cpu_usage_limit{location=\"$location\", id=~\"$guest\"}[$__interval])\r\n  * on(id, cluster) group_left(name, type)\r\n  count without(node) (topk by(id, node) (1, sum_over_time(pve_guest_info{location=\"$location\", id=~\"$guest\", name!=\"\"}[$__interval])))\r\n) and on(id, cluster)\r\nmax_over_time(pve_up{location=\"$location\", id=~\"$guest\"}[$__interval]) == 1",
     "legendFormat": "{{name}} ({{type}})"
    }
   ]
  },
  {
   "title": "CPU usage %",
   "type": "timeseries",
   "description": "can be above 100% because it also accounts for hypervisor overhead",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\r\n  max_over_time(pve_cpu_usage_ratio{location=\"$location\", id=~\"$guest\"}[$__interval])\r\n  * on(id, cluster) group_left(name, type)\r\n  count without(node) (topk by(id, node) (1, sum_over_time(pve_guest_info{location=\"$location\", id=~\"$guest\", name!=\"\"}[$__interval])))\r\n) and on(id, cluster)\r\nmax_over_time(pve_up{location=\"$location\", id=~\"$guest\"}[$__interval]) == 1",
     "legendFormat": "{{name}} ({{type}})"
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\r\n  max_over_time(pve_memory_usage_bytes{location=\"$location\", id=~\"$guest\"}[$__interval])\r\n  * on(id, cluster) group_left(name, type)\r\n  count without(node) (topk by(id, node) (1, sum_over_time(pve_guest_info{location=\"$location\", id=~\"$guest\", name!=\"\"}[$__interval])))\r\n) and on(id, cluster)\r\nmax_over_time(pve_up{location=\"$location\", id=~\"$guest\"}[$__interval]) == 1",
     "legendFormat": "{{name}} ({{type}})"
    }
   ]
  },
  {
   "title": "memory usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\r\n  max_over_time(pve_memory_usage_bytes{location=\"$location\", id=~\"$guest\"}[$__interval])\r\n  /\r\n  max_over_time(pve_memory_size_bytes{location=\"$location\", id=~\"$guest\"}[$__interval])\r\n  * on(id, cluster) group_left(name, type)\r\n  count without(node) (topk by(id, node) (1, sum_over_time(pve_guest_info{location=\"$location\", id=~\"$guest\", name!=\"\"}[$__interval])))\r\n) and on(id, cluster)\r\nmax_over_time(pve_up{location=\"$location\", id=~\"$guest\"}[$__interval]) == 1",
     "legendFormat": "{{name}} ({{type}})"
    }
   ]
  },
  {
   "title": "Network receive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(pve_network_receive_bytes{location=\"$location\", id=~\"$guest\"}[$__rate_interval])\r\n* on(id, cluster) group_left(name, type)\r\ncount without(node) (topk by(id, node) (1, sum_over_time(pve_guest_info{location=\"$location\", id=~\"$guest\", name!=\"\"}[$__interval])))\r\nand on(id, cluster)\r\nmax_over_time(pve_up{location=\"$location\", id=~\"$guest\"}[$__interval]) == 1",
     "legendFormat": "{{name}} ({{type}})"
    }
   ]
  },
  {
   "title": "Network transmit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(pve_network_transmit_bytes{location=\"$location\", id=~\"$guest\"}[$__rate_interval])\r\n* on(id, cluster) group_left(name, type)\r\ncount without(node) (topk by(id, node) (1, sum_over_time(pve_guest_info{location=\"$location\", id=~\"$guest\", name!=\"\"}[$__interval])))\r\nand on(id, cluster)\r\nmax_over_time(pve_up{location=\"$location\", id=~\"$guest\"}[$__interval]) == 1",
     "legendFormat": "{{name}} ({{type}})"
    }
   ]
  },
  {
   "title": "Disk read",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(pve_disk_read_bytes{location=\"$location\", id=~\"$guest\"}[$__rate_interval])\r\n* on(id, cluster) group_left(name, type)\r\ncount without(node) (topk by(id, node) (1, sum_over_time(pve_guest_info{location=\"$location\", id=~\"$guest\", name!=\"\"}[$__interval])))\r\nand on(id, cluster)\r\nmax_over_time(pve_up{location=\"$location\", id=~\"$guest\"}[$__interval]) == 1",
     "legendFormat": "{{name}} ({{type}})"
    }
   ]
  },
  {
   "title": "Disk write",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(pve_disk_write_bytes{location=\"$location\", id=~\"$guest\"}[$__rate_interval])\r\n* on(id, cluster) group_left(name, type)\r\ncount without(node) (topk by(id, node) (1, sum_over_time(pve_guest_info{location=\"$location\", id=~\"$guest\", name!=\"\"}[$__interval])))\r\nand on(id, cluster)\r\nmax_over_time(pve_up{location=\"$location\", id=~\"$guest\"}[$__interval]) == 1",
     "legendFormat": "{{name}} ({{type}})"
    }
   ]
  }
 ]
}