{
 "title": "proxmox / node details",
 "tags": [
  "proxmox",
  "maintainer:danil",
  "node"
 ],
 "time": { "from": "now-1d", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(pve_node_info{}[$__range])))"
    }
   },
   {
    "name": "node_name",
    "label": "Node",
    "query": {
     "query": "query_result(group by(name) (last_over_time(pve_node_info{location=\"$location\"}[$__range])))"
    }
   }
  ]
 },
 "panels": [
  { "title": "general", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node info",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by(id, nodeid, node) (label_replace(last_over_time(pve_node_info{location=\"$location\", id=~\"node/$node_name\"}[$__range]), \"node\", \"$1\", \"name\", \"(.*)\"))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(id) (last_over_time(pve_up{location=\"$location\", id=~\"node/$node_name\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(id) (pve_uptime_seconds{location=\"$location\", id=~\"node/$node_name\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(id) (last_over_time(pve_memory_size_bytes{location=\"$location\", id=~\"node/$node_name\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(id) (last_over_time(pve_cpu_usage_limit{location=\"$location\", id=~\"node/$node_name\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(node) (pve_guest_info{location=\"$location\", node=~\"$node_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "proxmox version history",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "max by(instance, version) (last_over_time(pve_version_info{location=\"$location\"}[$__interval]))\r\nor on()\r\n(\r\n  vector(0) unless on() last_over_time(pve_version_info{location=\"$location\"}[$__interval])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "state",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max by(id) (min_over_time(pve_up{location=\"$location\", id=~\"node/$node_name\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\r\n  sum by(id) (avg_over_time(pve_memory_size_bytes{location=\"$location\", id=~\"qemu/.*|lxc/.*\"}[$__interval]))\r\n  * on(id) group_left(node)\r\n  topk by(id, node) (1, max_over_time(pve_guest_info{location=\"$location\", id=~\"qemu/.*|lxc/.*\", template=\"0\", node=\"$node_name\"}[$__interval]))\r\n  * on(id) group_left()\r\n  avg_over_time(pve_up{location=\"$location\", id=~\"qemu/.*|lxc/.*\"}[$__interval])\r\n)",
     "legendFormat": "allocated"
    },
    {
     "expr": "avg(avg_over_time(pve_memory_size_bytes{location=\"$location\", id=\"node/$node_name\"}[$__interval]))",
     "legendFormat": "node memory"
    },
    {
     "expr": "avg(avg_over_time(pve_memory_usage_bytes{location=\"$location\", id=~\"node/$node_name\"}[$__interval]))",
     "legendFormat": "usage"
    },
    {
     "expr": "+ avg(avg_over_time(pve_memory_size_bytes{location=\"$location\", id=\"node/$node_name\"}[$__interval]))\r\n- sum(\r\n  avg_over_time(pve_memory_size_bytes{location=\"$location\", id=~\"qemu/.*|lxc/.*\"}[$__interval])\r\n  * on(id) group_left(node)\r\n  topk by(id, node) (1, max_over_time(pve_guest_info{location=\"$location\", id=~\"qemu/.*|lxc/.*\", template=\"0\", node=\"$node_name\"}[$__interval]))\r\n  * on(id) group_left()\r\n  avg_over_time(pve_up{location=\"$location\", id=~\"qemu/.*|lxc/.*\"}[$__interval])\r\n)",
     "legendFormat": "available"
    }
   ]
  },
  {
   "title": "cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(node) (\r\n  avg_over_time(pve_cpu_usage_limit{location=\"$location\", id=~\"qemu/.*|lxc/.*\"}[$__interval])\r\n  * on(id) group_left(node)\r\n  topk by(id, node) (1, max_over_time(pve_guest_info{location=\"$location\", id=~\"qemu/.*|lxc/.*\", template=\"0\", node=\"$node_name\"}[$__interval]))\r\n  * on(id) group_left()\r\n  avg_over_time(pve_up{location=\"$location\", id=~\"qemu/.*|lxc/.*\"}[$__interval])\r\n)",
     "legendFormat": "allocated"
    },
    {
     "expr": "avg(avg_over_time(pve_cpu_usage_limit{location=\"$location\", id=\"node/$node_name\"}[$__interval]))",
     "legendFormat": "node cores"
    },
    {
     "expr": "+ avg(avg_over_time(pve_cpu_usage_ratio{location=\"$location\", id=~\"node/$node_name\"}[$__interval]))\r\n* avg(avg_over_time(pve_cpu_usage_limit{location=\"$location\", id=\"node/$node_name\"}[$__interval]))",
     "legendFormat": "usage"
    }
   ]
  },
  { "title": "storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Storage usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(location, id) (pve_disk_usage_bytes{location=\"$location\", id=~\"storage/$node_name/.+\"} / pve_disk_size_bytes{location=\"$location\", id=~\"storage/$node_name/.+\"}) * on (location, id) group_left(storage, node) pve_storage_info{location=\"$location\", id=~\"storage/$node_name/.+\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max_over_time(pve_disk_usage_bytes{location=\"$location\", id=~\"storage/$node_name/.+\"}[$__interval])\r\n/\r\nmax_over_time(pve_disk_size_bytes{location=\"$location\", id=~\"storage/$node_name/.+\"}[$__interval])",
     "legendFormat": "{{id}}"
    }
   ]
  },
  { "title": "guests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Guests",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "max by(id, name, type, node, cgroup) (\r\n  label_replace(\r\n    label_replace(\r\n      last_over_time(pve_guest_info{location=\"$location\", node=\"$node_name\", name!=\"\"}[$__range])\r\n      or on(id)\r\n      last_over_time(pve_guest_info{location=\"$location\", node=\"$node_name\"}[$__range])\r\n      , \"cgroup\", \"/lxc/$1\", \"id\", \"lxc/(.*)\")\r\n  , \"cgroup\", \"/qemu.slice/$1.scope\", \"id\", \"qemu/(.*)\")\r\n)"
    },
    {
     "expr": "max by(id) (pve_up{location=\"$location\"} * on(id) pve_guest_info{location=\"$location\", node=\"$node_name\"})"
    },
    {
     "expr": "max by(id) (pve_cpu_usage_limit{location=\"$location\"} * on(id) pve_guest_info{location=\"$location\", node=\"$node_name\"})"
    },
    {
     "expr": "max by(id) (pve_cpu_usage_ratio{location=\"$location\"} * on(id) pve_guest_info{location=\"$location\", node=\"$node_name\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(id) (pve_memory_size_bytes{location=\"$location\"} * on(id) pve_guest_info{location=\"$location\", node=\"$node_name\"})"
    },
    {
     "expr": "sum by(id) (\r\n+ pve_memory_usage_bytes{location=\"$location\"}\r\n/ pve_memory_size_bytes{location=\"$location\"}\r\n* on(id) pve_guest_info{location=\"$location\", node=\"$node_name\", template=\"0\"}\r\nand on (id) pve_up{location=\"$location\"} == 1\r\n)"
    },
    {
     "expr": "sum by(id) (pve_disk_size_bytes{location=\"$location\", node=\"$node_name\"})"
    },
    {
     "expr": "sum by(id) (pve_disk_usage_bytes{location=\"$location\", node=\"$node_name\"} / pve_disk_size_bytes and on (id, cluster) pve_guest_info{location=\"$location\", node=~\"$node_name\", type=\"lxc\"})"
    },
    {
     "expr": "sum by(id) (increase(pve_network_receive_bytes{location=\"$location\", node=\"$node_name\"}[$__range]))"
    },
    {
     "expr": "sum by(id) (increase(pve_network_transmit_bytes{location=\"$location\", node=\"$node_name\"}[$__range]))"
    },
    {
     "expr": "sum by(id) (increase(pve_disk_read_bytes{location=\"$location\", node=\"$node_name\"}[$__range]))"
    },
    {
     "expr": "sum by(id) (increase(pve_disk_write_bytes{location=\"$location\", node=\"$node_name\"}[$__range]))"
    }
   ]
  },
  {
   "title": "memory by guest: allocated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(id, name) (\r\n  avg_over_time(pve_memory_size_bytes{location=\"$location\", id=~\"qemu/.*|lxc/.*\"}[$__interval])\r\n  * on(id) group_left(name)\r\n  topk by(id, node) (1, max_over_time(pve_guest_info{location=\"$location\", id=~\"qemu/.*|lxc/.*\", template=\"0\", node=\"$node_name\"}[$__interval]))\r\n  * on(id) group_left()\r\n  (max_over_time(pve_up{location=\"$location\", id=~\"qemu/.*|lxc/.*\"}[$__interval]) == 1)\r\n)",
     "legendFormat": "{{id}}: {{name}}"
    }
   ]
  },
  {
   "title": "cpu by guest: allocated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(id, name) (\r\n  avg_over_time(pve_cpu_usage_limit{location=\"$location\", id=~\"qemu/.*|lxc/.*\"}[$__interval])\r\n  * on(id) group_left(name)\r\n  topk by(id, node) (1, max_over_time(pve_guest_info{location=\"$location\", id=~\"qemu/.*|lxc/.*\", template=\"0\", node=\"$node_name\"}[$__interval]))\r\n  * on(id) group_left()\r\n  (max_over_time(pve_up{location=\"$location\", id=~\"qemu/.*|lxc/.*\"}[$__interval]) == 1)\r\n)",
     "legendFormat": "{{id}}: {{name}}"
    }
   ]
  },
  {
   "title": "memory by guest: used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(id, name) (\r\n  avg_over_time(pve_memory_usage_bytes{location=\"$location\", id=~\"qemu/.*|lxc/.*\"}[$__interval])\r\n  * on(id) group_left(name)\r\n  topk by(id, node) (1, max_over_time(pve_guest_info{location=\"$location\", id=~\"qemu/.*|lxc/.*\", template=\"0\", node=\"$node_name\"}[$__interval]))\r\n  * on(id) group_left()\r\n  (max_over_time(pve_up{location=\"$location\", id=~\"qemu/.*|lxc/.*\"}[$__interval]) == 1)\r\n)",
     "legendFormat": "{{id}}: {{name}}"
    }
   ]
  },
  {
   "title": "cpu by guest: used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(id, name) (\r\n+ avg_over_time(pve_cpu_usage_ratio{location=\"$location\", id=~\"qemu/.*|lxc/.*\"}[$__interval])\r\n* avg_over_time(pve_cpu_usage_limit{location=\"$location\", id=~\"qemu/.*|lxc/.*\"}[$__interval])\r\n  * on(id) group_left(name)\r\n  topk by(id, node) (1, max_over_time(pve_guest_info{location=\"$location\", id=~\"qemu/.*|lxc/.*\", template=\"0\", node=\"$node_name\"}[$__interval]))\r\n  * on(id) group_left()\r\n  (max_over_time(pve_up{location=\"$location\", id=~\"qemu/.*|lxc/.*\"}[$__interval]) == 1)\r\n)",
     "legendFormat": "{{id}}: {{name}}"
    }
   ]
  },
  {
   "title": "memory by guest: utilization %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(id, name) (\r\n  avg_over_time(pve_memory_usage_bytes{location=\"$location\", id=~\"qemu/.*|lxc/.*\"}[$__interval])\r\n/ avg_over_time(pve_memory_size_bytes{location=\"$location\", id=~\"qemu/.*|lxc/.*\"}[$__interval])\r\n  * on(id) group_left(name)\r\n  topk by(id, node) (1, max_over_time(pve_guest_info{location=\"$location\", id=~\"qemu/.*|lxc/.*\", template=\"0\", node=\"$node_name\"}[$__interval]))\r\n  * on(id) group_left()\r\n  (max_over_time(pve_up{location=\"$location\", id=~\"qemu/.*|lxc/.*\"}[$__interval]) == 1)\r\n)",
     "legendFormat": "{{id}}: {{name}}"
    }
   ]
  },
  {
   "title": "cpu by guest: utilization %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(id, name) (\r\n  avg_over_time(pve_cpu_usage_ratio{location=\"$location\", id=~\"qemu/.*|lxc/.*\"}[$__interval])\r\n  * on(id) group_left(name)\r\n  topk by(id, node) (1, max_over_time(pve_guest_info{location=\"$location\", id=~\"qemu/.*|lxc/.*\", template=\"0\", node=\"$node_name\"}[$__interval]))\r\n  * on(id) group_left()\r\n  (max_over_time(pve_up{location=\"$location\", id=~\"qemu/.*|lxc/.*\"}[$__interval]) == 1)\r\n)",
     "legendFormat": "{{id}}: {{name}}"
    }
   ]
  }
 ]
}