{
 "title": "proxmox / multi-node summary",
 "tags": [
  "proxmox",
  "maintainer:danil",
  "node"
 ],
 "time": { "from": "now-1d", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(pve_node_info{}[$__range])))"
    }
   },
   {
    "name": "node_name",
    "label": "Node",
    "query": {
     "query": "query_result(group by(name) (last_over_time(pve_node_info{location=\"$location\"}[$__range])))"
    }
   }
  ]
 },
 "panels": [
  { "title": "general", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node info",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by(id, nodeid, node) (label_replace(last_over_time(pve_node_info{location=\"$location\", id=~\"node/$node_name\"}[$__range]), \"node\", \"$1\", \"name\", \"(.*)\"))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(id) (last_over_time(pve_up{location=\"$location\", id=~\"node/$node_name\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(id) (pve_uptime_seconds{location=\"$location\", id=~\"node/$node_name\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(id) (last_over_time(pve_memory_size_bytes{location=\"$location\", id=~\"node/$node_name\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(id) (last_over_time(pve_cpu_usage_limit{location=\"$location\", id=~\"node/$node_name\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(node) (pve_guest_info{location=\"$location\", node=~\"$node_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "version history",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max by(instance, version) (last_over_time(pve_version_info{location=\"$location\"}[$__interval]))\r\nor on()\r\n(\r\n  vector(0) unless on() last_over_time(pve_version_info{location=\"$location\"}[$__interval])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "state",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "max by(id) (min_over_time(pve_up{location=\"$location\", id=~\"node/$node_name\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max_over_time(pve_memory_usage_bytes{location=\"$location\", id=~\"node/$node_name\"}[$__interval])\r\n/\r\nmax_over_time(pve_memory_size_bytes{location=\"$location\", id=~\"node/$node_name\"}[$__interval])",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max_over_time(pve_cpu_usage_ratio{location=\"$location\", id=~\"node/$node_name\"}[$__rate_interval])",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "memory allocated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(node) (\r\n  max_over_time(pve_memory_size_bytes{location=\"$location\", id=~\"qemu/.*|lxc/.*\"}[$__interval])\r\n  * on(id) group_left(node)\r\n  topk by(id, node) (1, max_over_time(pve_guest_info{location=\"$location\", id=~\"qemu/.*|lxc/.*\", template=\"0\"}[$__interval]))\r\n  * on(id) group_left()\r\n  avg_over_time(pve_up{location=\"$location\", id=~\"qemu/.*|lxc/.*\"}[$__interval])\r\n)\r\n/ max by(node) (\r\n  label_replace(\r\n    max_over_time(pve_memory_size_bytes{location=\"$location\", id=~\"node/$node_name\"}[$__interval])\r\n    , \"node\", \"$1\", \"id\", \"node/(.*)\"\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cpu allocated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(node) (\r\n  max_over_time(pve_cpu_usage_limit{location=\"$location\", id=~\"qemu/.*|lxc/.*\"}[$__interval])\r\n  * on(id) group_left(node)\r\n  topk by(id, node) (1, max_over_time(pve_guest_info{location=\"$location\", id=~\"qemu/.*|lxc/.*\", template=\"0\"}[$__interval]))\r\n  * on(id) group_left()\r\n  avg_over_time(pve_up{location=\"$location\", id=~\"qemu/.*|lxc/.*\"}[$__interval])\r\n)\r\n/ max by(node) (\r\n  label_replace(\r\n    max_over_time(pve_cpu_usage_limit{location=\"$location\", id=~\"node/$node_name\"}[$__interval])\r\n    , \"node\", \"$1\", \"id\", \"node/(.*)\"\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Storage usage",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(location, id) (pve_disk_usage_bytes{location=\"$location\", id=~\"storage/$node_name/.+\"} / pve_disk_size_bytes{location=\"$location\", id=~\"storage/$node_name/.+\"}) * on (location, id) group_left(storage, node) pve_storage_info{location=\"$location\", id=~\"storage/$node_name/.+\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max_over_time(pve_disk_usage_bytes{location=\"$location\", id=~\"storage/$node_name/.+\"}[$__interval])\r\n/\r\nmax_over_time(pve_disk_size_bytes{location=\"$location\", id=~\"storage/$node_name/.+\"}[$__interval])",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}