{
 "title": "Xray",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(v2ray_up[$__range])))"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(count_over_time(v2ray_up{location=~\"$location\"}[$__range]))"
    }
   },
   {
    "name": "dimension",
    "query": {
     "query": "query_result(count_over_time(v2ray_traffic_downlink_bytes_total{instance=~\"$instance\", target=~\".*($target_filter).*\"}[$__range]))"
    }
   },
   { "name": "target_filter" },
   {
    "name": "target",
    "query": {
     "query": "query_result(label_join(count_over_time(v2ray_traffic_downlink_bytes_total{instance=~\"$instance\", dimension=~\"$dimension\", target=~\".*($target_filter).*\"}[$__range]), \"human_name\", \"/\", \"dimension\", \"target\"))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "V2Ray Online",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(v2ray_up{instance=~\"$instance\"} == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by(location, instance) (v2ray_uptime_seconds{instance=~\"$instance\"})"
    },
    {
     "expr": "sum by(location, instance) (increase(v2ray_traffic_downlink_bytes_total{instance=~\"$instance\",dimension=\"inbound\"}[$__range]))"
    },
    {
     "expr": "sum by(location, instance) (increase(v2ray_traffic_uplink_bytes_total{instance=~\"$instance\",dimension=\"inbound\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(v2ray_traffic_downlink_bytes_total{instance=~\"$instance\", dimension=\"inbound\"}[$__rate_interval]))",
     "legendFormat": "Downlink Avg"
    },
    {
     "expr": "sum(rate(v2ray_traffic_uplink_bytes_total{instance=~\"$instance\", dimension=\"inbound\"}[$__rate_interval]))",
     "legendFormat": "Uplink Avg"
    },
    {
     "expr": "sum(quantile_over_time(0.99, dimension:v2ray_traffic_downlink_bytes_total:irate{instance=~\"$instance\", dimension=\"inbound\"}[$__rate_interval]))",
     "legendFormat": "Downlink p99"
    },
    {
     "expr": "sum(quantile_over_time(0.99, dimension:v2ray_traffic_uplink_bytes_total:irate{instance=~\"$instance\", dimension=\"inbound\"}[$__rate_interval]))",
     "legendFormat": "Uplink p99"
    }
   ]
  },
  {
   "title": "V2Ray Offline",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(v2ray_up{instance=~\"$instance\"}) - count(v2ray_up{instance=~\"$instance\"} == 1)"
    }
   ]
  },
  {
   "title": "Targets",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 1, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(location, instance, target, dimension) (increase(v2ray_traffic_downlink_bytes_total{instance=~\"$instance\", target=~\"$target\"}[$__range]))"
    },
    {
     "expr": "sum by(location, instance, target, dimension) (increase(v2ray_traffic_uplink_bytes_total{instance=~\"$instance\", target=~\"$target\"}[$__range]))"
    }
   ]
  },
  { "title": "$instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }, "repeat": "instance" },
  {
   "title": "down total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(dimension, target) (rate(v2ray_traffic_downlink_bytes_total{instance=~\"$instance\", target=~\"$target\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "{{dimension}}/{{target}}"
    }
   ]
  },
  {
   "title": "up total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(dimension, target) (rate(v2ray_traffic_uplink_bytes_total{instance=~\"$instance\", target=~\"$target\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "{{dimension}}/{{target}}"
    }
   ]
  },
  {
   "title": "Down speed / avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(dimension, target) (rate(v2ray_traffic_downlink_bytes_total{instance=~\"$instance\", target=~\"$target\"}[$__rate_interval]))",
     "legendFormat": "{{dimension}}/{{target}}"
    }
   ]
  },
  {
   "title": "Up speed / avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(dimension, target) (rate(v2ray_traffic_uplink_bytes_total{instance=~\"$instance\", target=~\"$target\"}[$__rate_interval]))",
     "legendFormat": "{{dimension}}/{{target}}"
    }
   ]
  },
  {
   "title": "Down speed / p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(dimension, target) (quantile_over_time(0.95, v2ray_traffic_downlink_bytes_total:irate{instance=~\"$instance\", target=~\"$target\"}[$__rate_interval]))",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Up speed / p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(dimension, target) (quantile_over_time(0.95, v2ray_traffic_uplink_bytes_total:irate{instance=~\"$instance\", target=~\"$target\"}[$__rate_interval]))",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Down speed / p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(dimension, target) (quantile_over_time(0.99, v2ray_traffic_downlink_bytes_total:irate{instance=~\"$instance\", target=~\"$target\"}[$__rate_interval]))",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Up speed / p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(dimension, target) (quantile_over_time(0.99, v2ray_traffic_uplink_bytes_total:irate{instance=~\"$instance\", target=~\"$target\"}[$__rate_interval]))",
     "legendFormat": "{{target}}"
    }
   ]
  }
 ]
}