{
 "title": "qBittorrent torrents list",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(qbittorrent_app_version{location!=\"\"}[$__range])))"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "query_result(count by(instance) (last_over_time(qbittorrent_app_version{location=~\"$location\"}[$__range])))"
    }
   },
   { "name": "name_filter" },
   { "name": "hash_filter" },
   { "name": "path_prefix" },
   {
    "name": "state",
    "query": {
     "query": "query_result(count by(name) (max_over_time(qbittorrent_torrent_states{instance=\"$instance\"}[$__range]) != 0))"
    }
   },
   {
    "name": "category",
    "query": {
     "query": "query_result(count by(human, category) (label_join(count_values by(category) (\"count\", count_values by(category) (\"__\", last_over_time(qbittorrent_torrent_info{instance=\"$instance\"}[$__range]))), \"human\", \": \", \"category\", \"count\")))"
    }
   },
   {
    "name": "torrent",
    "query": {
     "query": "query_result(count by(name, hash) (last_over_time(qbittorrent_torrent_save_path{instance=\"$instance\", hash=~\".*($hash_filter).*\", name=~\".*(?i:$name_filter).*\", save_path=~\"($path_prefix).*\"}[$__range])) * count by(name, hash) (last_over_time(qbittorrent_torrent_state{instance=\"$instance\", hash=~\".*($hash_filter).*\", name=~\".*(?i:$name_filter).*\", state=~\"($state).*\"}[$__range])) * count by(name, hash) (last_over_time(qbittorrent_torrent_info{instance=\"$instance\", hash=~\".*($hash_filter).*\", name=~\".*(?i:$name_filter).*\", category=~\"($category).*\"}[$__range])))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "selected torrents count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max by(hash) (last_over_time(qbittorrent_torrent_total_uploaded_bytes{instance=\"$instance\", hash=~\"$torrent\"}[$__range])))",
     "legendFormat": "selected torrents"
    }
   ]
  },
  {
   "title": "selected torrents size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by(hash) (last_over_time(qbittorrent_torrent_size_bytes{instance=\"$instance\", hash=~\"$torrent\"}[$__range])))",
     "legendFormat": "selected torrents size"
    }
   ]
  },
  {
   "title": "selected torrents uploaded",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by(hash) (increase(qbittorrent_torrent_total_uploaded_bytes{instance=\"$instance\", hash=~\"$torrent\"}[$__range])))",
     "legendFormat": "selected torrents uploaded (in time range)"
    }
   ]
  },
  {
   "title": "selected torrents downloaded",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by(hash) (increase(qbittorrent_torrent_total_downloaded_bytes{instance=\"$instance\", hash=~\"$torrent\"}[$__range])))",
     "legendFormat": "selected torrents downloaded (in time range)"
    }
   ]
  },
  {
   "title": "Torrents",
   "type": "table",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "max by(instance, name, hash) (qbittorrent_torrent_added_on{instance=\"$instance\", hash=~\"$torrent\"}) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, name, hash) (qbittorrent_torrent_completed_on{instance=\"$instance\", hash=~\"$torrent\"} != -1) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, name, hash) (qbittorrent_torrent_ratio{instance=\"$instance\", hash=~\"$torrent\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, name, hash) (qbittorrent_torrent_size_bytes{instance=\"$instance\", hash=~\"$torrent\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, name, hash) (qbittorrent_torrent_progress{instance=\"$instance\", hash=~\"$torrent\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, name, hash, category) (qbittorrent_torrent_info{instance=\"$instance\", hash=~\"$torrent\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, name, hash) (qbittorrent_torrent_eta{instance=\"$instance\", hash=~\"$torrent\"}) != 8640000",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, name, hash, state) (topk by(instance, name, hash) (1, timestamp(qbittorrent_torrent_state{instance=\"$instance\", hash=~\"$torrent\"})))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, name, hash) (qbittorrent_torrent_time_active{instance=\"$instance\", hash=~\"$torrent\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, name, hash) (qbittorrent_torrent_total_uploaded_bytes{instance=\"$instance\", hash=~\"$torrent\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, name, hash) (increase(qbittorrent_torrent_total_uploaded_bytes{instance=\"$instance\", hash=~\"$torrent\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, name, hash, save_path) (qbittorrent_torrent_save_path{instance=\"$instance\", hash=~\"$torrent\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, name, hash) (rate(qbittorrent_torrent_total_uploaded_bytes{instance=\"$instance\", hash=~\"$torrent\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "State",
   "type": "state-timeline",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "max by(name, hash) (\r\nmax_over_time(qbittorrent_torrent_state{instance=\"$instance\", hash=~\"$torrent\", state=\"allocating\"}[$__interval]) * 1\r\nor\r\nmax_over_time(qbittorrent_torrent_state{instance=\"$instance\", hash=~\"$torrent\", state=\"checkingDL\"}[$__interval]) * 2\r\nor\r\nmax_over_time(qbittorrent_torrent_state{instance=\"$instance\", hash=~\"$torrent\", state=\"checkingResumeData\"}[$__interval]) * 3\r\nor\r\nmax_over_time(qbittorrent_torrent_state{instance=\"$instance\", hash=~\"$torrent\", state=\"checkingUP\"}[$__interval]) * 4\r\nor\r\nmax_over_time(qbittorrent_torrent_state{instance=\"$instance\", hash=~\"$torrent\", state=~\"downloading|forcedDL|queuedDL\"}[$__interval]) * 5\r\nor\r\nmax_over_time(qbittorrent_torrent_state{instance=\"$instance\", hash=~\"$torrent\", state=~\"error|missingFiles\"}[$__interval]) * 6\r\nor\r\nmax_over_time(qbittorrent_torrent_state{instance=\"$instance\", hash=~\"$torrent\", state=\"metaDL\"}[$__interval]) * 7\r\nor\r\nmax_over_time(qbittorrent_torrent_state{instance=\"$instance\", hash=~\"$torrent\", state=~\"uploading|forcedUP|queuedUP\"}[$__interval]) * 8\r\nor\r\nmax_over_time(qbittorrent_torrent_state{instance=\"$instance\", hash=~\"$torrent\", state=\"stalledDL\"}[$__interval]) * 9\r\nor\r\nmax_over_time(qbittorrent_torrent_state{instance=\"$instance\", hash=~\"$torrent\", state=\"stalledUP\"}[$__interval]) * 10\r\nor\r\nmax_over_time(qbittorrent_torrent_state{instance=\"$instance\", hash=~\"$torrent\", state=\"stoppedDL\"}[$__interval]) * 11\r\nor\r\nmax_over_time(qbittorrent_torrent_state{instance=\"$instance\", hash=~\"$torrent\", state=\"stoppedUP\"}[$__interval]) * 12\r\nor\r\nmax_over_time(qbittorrent_torrent_state{instance=\"$instance\", hash=~\"$torrent\", state=\"unknown\"}[$__interval]) * 13\r\n)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "progress %",
   "type": "timeseries",
   "description": "Can be empty when nothing is downloading",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(name) (\r\navg_over_time(qbittorrent_torrent_progress{instance=\"$instance\", hash=~\"$torrent\"}[$__interval])\r\nand (\r\n  min_over_time(qbittorrent_torrent_progress{instance=\"$instance\", hash=~\"$torrent\"}[$__interval]) < 1\r\n  or min_over_time(qbittorrent_torrent_progress{instance=\"$instance\", hash=~\"$torrent\"}[$__interval] offset $__interval) < 1\r\n)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "download ETA",
   "type": "timeseries",
   "description": "Can be empty when nothing is downloading",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(name) (\r\nmax_over_time(qbittorrent_torrent_eta{instance=\"$instance\", hash=~\"$torrent\"}[$__interval]) != 0 < 8640000\r\nand max_over_time(qbittorrent_torrent_eta{instance=\"$instance\", hash=~\"$torrent\"}[$__interval] offset $__interval) != 0 < 8640000\r\nand on(instance, hash)\r\nmax_over_time(qbittorrent_torrent_state{instance=\"$instance\", hash=~\"$torrent\", state=~\"downloading|forcedDL|queuedDL\"}[$__interval]) == 1\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "download ETA: 5 minute delta",
   "type": "timeseries",
   "description": "Can be empty when nothing is downloading",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(name) (\r\n+ (avg_over_time(qbittorrent_torrent_eta{instance=\"$instance\", hash=~\"$torrent\"}[2m]) != 0)\r\n- avg_over_time(qbittorrent_torrent_eta{instance=\"$instance\", hash=~\"$torrent\"}[2m] offset 5m)\r\nand max_over_time(qbittorrent_torrent_eta{instance=\"$instance\", hash=~\"$torrent\"}[5m]) != 8640000\r\nand abs(\r\n+ (avg_over_time(qbittorrent_torrent_eta{instance=\"$instance\", hash=~\"$torrent\"}[2m]) != 0)\r\n- avg_over_time(qbittorrent_torrent_eta{instance=\"$instance\", hash=~\"$torrent\"}[2m] offset 5m)\r\n) < 60*60*24*7\r\nand on(instalce, hash) (max_over_time(qbittorrent_torrent_state{instance=\"$instance\", hash=~\"$torrent\", state=~\"downloading|forcedDL|queuedDL\"}[$__interval]) == 1)\r\nunless (max_over_time(qbittorrent_torrent_state{instance=\"$instance\", hash=~\"$torrent\", state!~\"downloading|forcedDL|queuedDL\"}[$__interval]) == 1)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload Speed by Torrent",
   "type": "timeseries",
   "description": "Can be empty when nothing is uploading",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(name) (rate(qbittorrent_torrent_total_uploaded_bytes{instance=\"$instance\", hash=~\"$torrent\"}[$__rate_interval]) != 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(qbittorrent_torrent_total_uploaded_bytes{instance=\"$instance\", hash=~\"$torrent\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Leechers",
   "type": "timeseries",
   "description": "Can be empty when nothing is uploading",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "avg by(name) (avg_over_time(qbittorrent_torrent_leechers{instance=\"$instance\", hash=~\"$torrent\"}[$__interval]) != 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Download Speed by Torrent",
   "type": "timeseries",
   "description": "Can be empty when nothing is downloading",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(name) (rate(qbittorrent_torrent_total_downloaded_bytes{instance=\"$instance\", hash=~\"$torrent\"}[$__rate_interval]) != 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(qbittorrent_torrent_total_downloaded_bytes{instance=\"$instance\", hash=~\"$torrent\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Seeders",
   "type": "timeseries",
   "description": "Can be empty when nothing is downloading",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "avg by(name) (avg_over_time(qbittorrent_torrent_seeders{instance=\"$instance\", hash=~\"$torrent\"}[$__interval]) != 0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}