{
 "title": "qBittorrent",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(qbittorrent_app_version{location!=\"\"}[$__range])))"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "query_result(count by(instance) (last_over_time(qbittorrent_app_version{location=~\"$location\"}[$__range])))"
    }
   },
   {
    "name": "active_states",
    "query": {
     "query": "query_result(count by(name) (max_over_time(qbittorrent_torrent_states{instance=\"$instance\"}[$__range]) != 0))"
    }
   }
  ]
 },
 "panels": [
  { "title": "general", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "qBittorrent Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "max by(version) (last_over_time(qbittorrent_app_version{instance=\"$instance\"}[$__range]))",
     "legendFormat": "qBittorrent version"
    }
   ]
  },
  {
   "title": "Total Torrents",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(last_over_time(qbittorrent_global_torrents{instance=\"$instance\"}[$__range]))",
     "legendFormat": "Total torrents"
    }
   ]
  },
  {
   "title": "States",
   "type": "table",
   "gridPos": { "h": 15, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by(name) (qbittorrent_torrent_states{instance=\"$instance\", name=~\"$active_states\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "categories",
   "type": "table",
   "gridPos": { "h": 15, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by(category) (qbittorrent_torrent_info{instance=\"$instance\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "uploaded (real)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(increase(qbittorrent_global_alltime_uploaded_bytes{instance=\"$instance\"}[$__range]))",
     "legendFormat": "uploaded (real)"
    }
   ]
  },
  {
   "title": "uploaded (logical)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(increase(qbittorrent_global_session_uploaded_bytes{instance=\"$instance\"}[$__range]))",
     "legendFormat": "uploaded (logical)"
    }
   ]
  },
  {
   "title": "uploaded since installation",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(last_over_time(qbittorrent_global_alltime_uploaded_bytes{instance=\"$instance\"}[$__range]))",
     "legendFormat": "uploaded since installation"
    }
   ]
  },
  {
   "title": "total torrents size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(qbittorrent_torrent_size_bytes{instance=\"$instance\"}[$__range]))",
     "legendFormat": "All-time downloaded"
    }
   ]
  },
  {
   "title": "downloaded (real)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(increase(qbittorrent_global_alltime_downloaded_bytes{instance=\"$instance\"}[$__range]))",
     "legendFormat": "downloaded (real)"
    }
   ]
  },
  {
   "title": "downloaded (logical)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(increase(qbittorrent_global_session_downloaded_bytes{instance=\"$instance\"}[$__range]))",
     "legendFormat": "downloaded (logical)"
    }
   ]
  },
  {
   "title": "downloaded since installation",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(last_over_time(qbittorrent_global_alltime_downloaded_bytes{instance=\"$instance\"}[$__range]))",
     "legendFormat": "downloaded since installation"
    }
   ]
  },
  {
   "title": "max active torrents",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "max by(type) (label_replace(qbittorrent_global_max_active_downloads{instance=\"$instance\"}, \"type\", \"download\", \"invalid\", \"\"))\r\nor\r\nmax by(type) (label_replace(qbittorrent_global_max_active_uploads{instance=\"$instance\"}, \"type\", \"upload\", \"invalid\", \"\"))\r\nor\r\nmax by(type) (label_replace(qbittorrent_global_max_active_torrents{instance=\"$instance\"}, \"type\", \"total\", \"invalid\", \"\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ratio (real)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\r\nincrease(qbittorrent_global_alltime_uploaded_bytes{instance=\"$instance\"}[$__range])\r\n/\r\nincrease(qbittorrent_global_alltime_downloaded_bytes{instance=\"$instance\"}[$__range])\r\n)",
     "legendFormat": "ratio (real)"
    }
   ]
  },
  {
   "title": "ratio (logical)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\r\nincrease(qbittorrent_global_session_uploaded_bytes{instance=\"$instance\"}[$__range])\r\n/\r\nincrease(qbittorrent_global_session_downloaded_bytes{instance=\"$instance\"}[$__range])\r\n)",
     "legendFormat": "ratio (logical)"
    }
   ]
  },
  {
   "title": "ratio since installation",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\r\nlast_over_time(qbittorrent_global_alltime_uploaded_bytes{instance=\"$instance\"}[$__range])\r\n/\r\nlast_over_time(qbittorrent_global_alltime_downloaded_bytes{instance=\"$instance\"}[$__range])\r\n)",
     "legendFormat": "ratio since installation"
    }
   ]
  },
  {
   "title": "version history",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max by(instance, version) (last_over_time(qbittorrent_app_version{instance=\"$instance\"}[$__interval]))\r\nor vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notes",
   "type": "text",
   "gridPos": { "h": 7, "w": 10, "x": 13, "y": 16 },
   "options": {
    "content": "qbittorrent has 3 ways of reporting speed:\r\n\r\n1. Instantaneous speed, shown in the footer in webUI.\r\nIt fluctuates a lot, and it isn't really useful.\r\nPrometheus scrapes data once every N seconds. It can be that your speed is 10 MiB/s on average,\r\nbut rigth before the scrape the speed increased to 20 MiB/s. And before next scrape it increased to 15 MiB/s.\r\nYou would think that the average is 15+ MiB/s.\r\n\r\n2. Logical speed.\r\nqbittorrent reports how many data bytes it has transferred.\r\nYou can then get average speed as `delta_bytes / delta_time`.\r\nThe result is less detailed, but it's mathematically accurate.\r\nOnly actual transferred data blocks are counted.\r\n\r\n3. Real speed. Similar to logical speed, but protocol overhead is now counted.\r\nIt is always bigger than logical speed.\r\nEven if all torents are finished, but you are seeding some torrents,\r\nyou will see non-zero download speed\r\nbecause you are exchanging metadata with other peers."
   }
  },
  {
   "title": "torrents by state",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "avg by(name) (avg_over_time(qbittorrent_torrent_states{instance=\"$instance\", name=~\"$active_states\"}[$__interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(max_over_time(qbittorrent_global_torrents{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "speed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Upload Speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(qbittorrent_global_alltime_uploaded_bytes{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "upload (real)"
    },
    {
     "expr": "sum(rate(qbittorrent_global_session_uploaded_bytes{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "upload (logical)"
    },
    {
     "expr": "max(\r\navg_over_time(qbittorrent_global_upload_rate_limit_bytes{instance=\"$instance\"}[$__interval]) != 0 and max_over_time(qbittorrent_app_alt_rate_limits_enabled[$__interval]) == 0\r\nor\r\navg_over_time(qbittorrent_global_alt_upload_rate_limit_bytes{instance=\"$instance\"}[$__interval]) != 0 and max_over_time(qbittorrent_app_alt_rate_limits_enabled[$__interval]) == 1\r\n)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Download Speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(qbittorrent_global_alltime_downloaded_bytes{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "download (real)"
    },
    {
     "expr": "sum(rate(qbittorrent_global_session_downloaded_bytes{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "download (logical)"
    },
    {
     "expr": "max(\r\navg_over_time(qbittorrent_global_download_rate_limit_bytes{instance=\"$instance\"}[$__interval]) != 0 and max_over_time(qbittorrent_app_alt_rate_limits_enabled[$__interval]) == 0\r\nor\r\navg_over_time(qbittorrent_global_alt_download_rate_limit_bytes{instance=\"$instance\"}[$__interval]) != 0 and max_over_time(qbittorrent_app_alt_rate_limits_enabled[$__interval]) == 1\r\n)",
     "legendFormat": "limit"
    }
   ]
  },
  { "title": "peers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum(avg_over_time(qbittorrent_torrent_leechers{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "Leechers"
    },
    {
     "expr": "sum(avg_over_time(qbittorrent_torrent_seeders{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "Seeders"
    }
   ]
  },
  {
   "title": "DHT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "avg(avg_over_time(qbittorrent_global_dht_nodes{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "DHT nodes"
    }
   ]
  }
 ]
}