---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: 3xui
spec:
  secretName: 3xui-cert
  duration: 8760h0m0s
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cluster-ca
  dnsNames:
  - s3xui.vpn-xray.svc.cluster.local
  ipAddresses:
  - 127.0.0.1
