---
apiVersion: v1
kind: Service
metadata:
  name: s3xui
spec:
  clusterIP: None
  selector:
    app: 3xui
  ports:
  - name: panel
    port: 2053
    targetPort: 12053
  - name: sub
    port: 2096
  - name: in-http-1
    port: 2054
    targetPort: 2054
  - name: in-http-2
    port: 2055
    targetPort: 2055
  - name: in-http-3
    port: 2056
    targetPort: 2056
  - name: in-http-4
    port: 2057
    targetPort: 2057
  - name: in-http-5
    port: 2058
    targetPort: 2058
  - name: in-http-6
    port: 2059
    targetPort: 2059
