---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: alert-cadvisor-cpu-throttling
  namespace: metrics-cadvisor
  labels:
    prometheus.io/instance: main
    instance.prometheus.io/main: enable
    instance.prometheus.io/prompp: enable
spec:
  groups:
  - name: alert-cadvisor-cpu-throttling
    rules:
    - alert: K8sCpuThrottling
      annotations:
        description: >-
          {{ $labels.namespace }}/{{ $labels.pod }}/{{ $labels.container }}:
          {{ $value | humanizePercentage }}
        summary: K8s container is throttling on > 30% of scheduling periods
      expr: |-
        (
          increase(container_cpu_cfs_throttled_periods_total{namespace!=""}[5m])
          /
          increase(container_cpu_cfs_periods_total{namespace!=""}[5m])
        ) > 0.3
        # cut removed containers instantly
        and container_cpu_cfs_throttled_periods_total{namespace!=""}
      for: 15m
      labels:
        severity: info
    - alert: DockerCpuThrottling
      annotations:
        description: >-
          instance {{ $labels.instance }}: {{ $labels.name }}:
          {{ $value | humanizePercentage }}
        summary: Docker container is throttling on > 30% of scheduling periods
      expr: |-
        (
          increase(container_cpu_cfs_throttled_periods_total{namespace="", name!=""}[5m])
          /
          increase(container_cpu_cfs_periods_total{namespace="", name!=""}[5m])
        ) > 0.3
        # cut removed containers instantly
        and container_cpu_cfs_throttled_periods_total{namespace="", name!=""}
      for: 15m
      labels:
        severity: info
    - alert: CgroupCpuThrottling
      annotations:
        description: >-
          instance {{ $labels.instance }}: {{ $labels.id }}:
          {{ $value | humanizePercentage }}
        summary: Cgroup is throttling on > 80% of scheduling periods
      expr: |-
        (
          increase(container_cpu_cfs_throttled_periods_total{namespace="", name=""}[5m])
          /
          increase(container_cpu_cfs_periods_total{namespace="", name=""}[5m])
        ) > 0.8
        # cut removed containers instantly
        and container_cpu_cfs_throttled_periods_total{namespace="", name=""}
      for: 15m
      labels:
        severity: info
    - alert: CgroupCpuThrottlingDuration
      annotations:
        description: >-
          instance {{ $labels.instance }}: {{ $labels.id }}:
          {{ $value | humanizeDuration }}
        summary: Cgroup spent >30s throttling over the last 5 minutes
      expr: |-
        (
          increase(container_cpu_cfs_throttled_seconds_total{namespace="", name=""}[5m]) > 30
          # cut removed containers instantly
          and container_cpu_cfs_throttled_periods_total{namespace="", name=""}
        ) or (
          increase(container_cpu_cfs_throttled_seconds_total{namespace="", name=""}[5m]) > 10
          # cut removed containers instantly
          and container_cpu_cfs_throttled_periods_total{namespace="", name=""}
          and ignoring(alertname, alertstate, severity)
          ALERTS{alertname="CgroupCpuThrottlingDuration", alertstate="firing"}
        )
      for: 15m
      labels:
        severity: info
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: alert-cadvisor-memory
  namespace: metrics-cadvisor
  labels:
    prometheus.io/instance: main
    instance.prometheus.io/main: enable
    instance.prometheus.io/prompp: enable
spec:
  groups:
  - name: alert-cadvisor-memory
    rules:
    - alert: K8sContainerMemoryAbove90
      annotations:
        description: >-
          {{ $labels.namespace }}/{{ $labels.pod }}/{{ $labels.container }}:
          {{ $value | humanizePercentage }}
        summary: Container RSS + kernel memory usage is above 90% of memory limit
      expr: |-
        (
          (container_memory_usage_bytes{namespace!="", pod!="", container!=""} - container_memory_cache{namespace!="", pod!="", container!=""}) / container_spec_memory_limit_bytes{namespace!="", pod!="", container!=""} > 0.9
          and
          container_spec_memory_limit_bytes != 0
        ) or (
          (container_memory_usage_bytes{namespace!="", pod!="", container!=""} - container_memory_cache{namespace!="", pod!="", container!=""}) / container_spec_memory_limit_bytes{namespace!="", pod!="", container!=""} > 0.8
          and
          container_spec_memory_limit_bytes != 0
          and ignoring(alertname, alertstate, severity)
          ALERTS{alertname="K8sContainerMemoryAbove90", alertstate="firing"}
        )
      for: 5m
      labels:
        severity: warning
    - alert: DockerContainerMemoryAbove90
      annotations:
        description: >-
          {{ $labels.instance }}:
          {{ $labels.container_label_com_docker_compose_project }}/{{ $labels.container_label_com_docker_compose_service }}:
          {{ $value | humanizePercentage }}
        summary: Container RSS + kernel memory usage is above 90% of memory limit
      expr: |-
        (
          (container_memory_usage_bytes{container_label_com_docker_compose_image!=""} - container_memory_cache{container_label_com_docker_compose_image!=""}) / container_spec_memory_limit_bytes{container_label_com_docker_compose_image!=""} > 0.9
          and
          container_spec_memory_limit_bytes != 0
        ) or (
          (container_memory_usage_bytes{container_label_com_docker_compose_image!=""} - container_memory_cache{container_label_com_docker_compose_image!=""}) / container_spec_memory_limit_bytes{container_label_com_docker_compose_image!=""} > 0.8
          and
          container_spec_memory_limit_bytes != 0
          and ignoring(alertname, alertstate, severity)
          ALERTS{alertname="DockerContainerMemoryAbove90", alertstate="firing"}
        )
      for: 5m
      labels:
        severity: warning
    - alert: CgroupContainerMemoryAbove90
      annotations:
        description: >-
          {{ $labels.instance }}:
          {{ $labels.id }}:
          {{ $value | humanizePercentage }}
        summary: Container RSS + kernel memory usage is above 90% of memory limit
      expr: |-
        (
          (container_memory_usage_bytes{container_label_com_docker_compose_image="", namespace="", pod=""} - container_memory_cache{container_label_com_docker_compose_image="", namespace="", pod=""}) / container_spec_memory_limit_bytes{container_label_com_docker_compose_image="", namespace="", pod=""} > 0.9
          and
          container_spec_memory_limit_bytes != 0
        ) or (
          (container_memory_usage_bytes{container_label_com_docker_compose_image="", namespace="", pod=""} - container_memory_cache{container_label_com_docker_compose_image="", namespace="", pod=""}) / container_spec_memory_limit_bytes{container_label_com_docker_compose_image="", namespace="", pod=""} > 0.8
          and
          container_spec_memory_limit_bytes != 0
          and ignoring(alertname, alertstate, severity)
          ALERTS{alertname="CgroupContainerMemoryAbove90", alertstate="firing"}
        )
      for: 5m
      labels:
        severity: warning
