{
 "title": "OPNSense",
 "description": "Dashboard for the OPNsense Prometheus Exporter\r\n\r\nhttps://github.com/AthennaMind/opnsense-exporter\r\n\r\nFrom the AthennaMind \r\n   Team",
 "tags": [
  "opnsense",
  "firewall",
  "networking",
  "prometheus-exporter"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "query": "prometheus" },
   {
    "name": "opnsense_instance",
    "label": "OPNSense Instance",
    "query": {
     "query": "label_values(opnsense_up,opnsense_instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "min(min_over_time(opnsense_up{opnsense_instance=\"$opnsense_instance\"}[$__interval]))",
     "legendFormat": "status"
    }
   ]
  },
  {
   "title": "endpoint scrape errors (sum over time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(endpoint) (rate(opnsense_exporter_endpoint_errors_total{opnsense_instance=\"$opnsense_instance\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "version history",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "label_replace(label_replace(max_over_time(opnsense_firmware_os_version{opnsense_instance=\"$opnsense_instance\", os_version!=\"\"}[$__interval]), \"version\", \"$1\", \"os_version\", \"(.*)\"), \"name\", \"OS version\", \"invalid\", \"\")\r\nor\r\nlabel_replace(label_replace(max_over_time(opnsense_firmware_product_version{opnsense_instance=\"$opnsense_instance\", product_version!=\"\"}[$__interval]), \"version\", \"$1\", \"product_version\", \"(.*)\"), \"name\", \"opnsense version\", \"invalid\", \"\")\r\nor on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Services Status History",
   "type": "state-timeline",
   "description": "Status points of services uptime\n\n1 - Available \n0 - Unavailable",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "min by(name) (min_over_time(opnsense_services_status{opnsense_instance=\"$opnsense_instance\"}[$__interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Gateways",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gateway RTT",
     "type": "timeseries",
     "description": "RTT is the average (mean) of the round trip time in milliseconds by name",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "opnsense_gateways_rtt_milliseconds{opnsense_instance=\"$opnsense_instance\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Gateway RTTd",
     "type": "timeseries",
     "description": "RTTd is the standard deviation of the round trip time in milliseconds by name",
     "gridPos": { "h": 9, "w": 9, "x": 9, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "opnsense_gateways_rttd_milliseconds{opnsense_instance=\"$opnsense_instance\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Gateway Loss Percentage",
     "type": "timeseries",
     "description": "Gateway Loss Percentage by Gateway Name",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "opnsense_gateways_loss_percentage{opnsense_instance=\"$opnsense_instance\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Gateway Status History",
     "type": "status-history",
     "description": "Status points of the gateway uptime. \n\n1 - Available \n0 - Unavailable",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "opnsense_gateways_status{opnsense_instance=\"$opnsense_instance\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  { "title": "Interfaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "receive total",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(device, interface) (increase(opnsense_interfaces_received_bytes_total{opnsense_instance=\"$opnsense_instance\"}[$__range]))",
     "legendFormat": "{{device}} - {{interface}}"
    }
   ]
  },
  {
   "title": "transmit total",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(device, interface) (increase(opnsense_interfaces_transmitted_bytes_total{opnsense_instance=\"$opnsense_instance\"}[$__range]))",
     "legendFormat": "{{device}} - {{interface}}"
    }
   ]
  },
  {
   "title": "receive rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(device, interface) (rate(opnsense_interfaces_received_bytes_total{opnsense_instance=\"$opnsense_instance\"}[$__rate_interval]))",
     "legendFormat": "{{device}} - {{interface}}"
    }
   ]
  },
  {
   "title": "transmit rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(device, interface) (rate(opnsense_interfaces_transmitted_bytes_total{opnsense_instance=\"$opnsense_instance\"}[$__rate_interval]))",
     "legendFormat": "{{device}} - {{interface}}"
    }
   ]
  },
  {
   "title": "network interface mtu",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "max by(device, interface) (max_over_time(opnsense_interfaces_mtu_bytes{opnsense_instance=\"$opnsense_instance\"}[$__interval]))",
     "legendFormat": "{{device}} - {{interface}}"
    }
   ]
  },
  {
   "title": "[TOTAL] Errors By Interface",
   "type": "timeseries",
   "description": "Total transmitted data by interface",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "opnsense_interfaces_input_errors_total{opnsense_instance=\"$opnsense_instance\"}",
     "legendFormat": "INPUT Errors {{device}} - {{interface}}"
    },
    {
     "expr": "opnsense_interfaces_input_errors_total{opnsense_instance=\"$opnsense_instance\"}",
     "legendFormat": "OUTPUT Errors  {{device}} - {{interface}}"
    }
   ]
  },
  { "title": "ARP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "ARP Table Entries ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "count by(interface_description) (avg_over_time(opnsense_arp_table_entries{opnsense_instance=\"$opnsense_instance\"}[$__interval]))",
     "legendFormat": "{{interface_description}}"
    }
   ]
  },
  {
   "title": "ARP request rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum(rate(opnsense_protocol_arp_sent_requests_total{opnsense_instance=\"$opnsense_instance\"}[$__rate_interval]))",
     "legendFormat": "send"
    },
    {
     "expr": "sum(rate(opnsense_protocol_arp_received_requests_total{opnsense_instance=\"$opnsense_instance\"}[$__rate_interval]))",
     "legendFormat": "receive"
    }
   ]
  }
 ]
}