
nameOverride: dem
fullnameOverride: dem

csiDriver:
  # should be globally unique for a given cluster
  name: org.democratic-csi.proxy
  storageCapacity: true

driver:
  existingConfigSecret: main-config
  config:
    driver: proxy

controller:
  extraVolumes:
  - name: connections
    secret:
      secretName: connections

  # extraEnv:
  # - name: SSH_REUSE_CONNECTION
  #   value: '0'
  driver:
    logLevel: debug
    extraVolumeMounts:
    - name: connections
      mountPath: /mnt/connections
    image:
      registry: docker.io/daniluzlov/k8s-snippets
      tag: dcsi-next-with-proxy-v1
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: 70Mi
      limits:
        memory: 100Mi
  externalAttacher:
    resources:
      requests:
        memory: 20Mi
      limits:
        memory: 30Mi
  externalProvisioner:
    extraArgs:
    - --enable-capacity=true
    - --capacity-ownerref-level=2
    # - --capacity-for-immediate-binding
    resources:
      requests:
        memory: 25Mi
      limits:
        memory: 30Mi
  externalResizer:
    resources:
      requests:
        memory: 25Mi
      limits:
        # it is getting OOMKilled when limit is 25Mi
        memory: 50Mi
  externalSnapshotter:
    resources:
      requests:
        memory: 25Mi
      limits:
        memory: 25Mi

node:
  extraVolumes:
  - name: etc-iscsi
    hostPath:
      path: /etc/iscsi/
      type: ""

  driver:
    logLevel: debug
    nvmeDirMountEnabled: true
    extraVolumeMounts:
    - name: etc-iscsi
      mountPath: /etc/iscsi/
      readOnly: true
    image:
      registry: docker.io/daniluzlov/k8s-snippets
      tag: dcsi-next-with-proxy-v1
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: 70Mi
        cpu: 50m
      limits:
        memory: 100Mi
  tolerations:
  - operator: Exists
    effect: NoSchedule
  driverRegistrar:
    resources:
      requests:
        cpu: ~
        memory: 20Mi
      limits:
        cpu: ~
        memory: 30Mi

csiProxy:
  # csi-proxy doesn't seem to do anything in current version of k8s and democratic-csi
  enabled: false
