{
 "title": "Smartctl / Overview",
 "tags": [ "smartctl" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(smartctl_version[$__range])))"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(group by(instance) (last_over_time(smartctl_version{location=~\"$location\"}[$__range])))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "instance summary",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count by(instance) (last_over_time(smartctl_device{instance=~\"$instance\"}[$__range]))",
     "legendFormat": "value"
    },
    {
     "expr": "count by(instance) (smartctl_device{instance=~\"$instance\", device=~\"$device\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by(instance) (last_over_time(smartctl_device{instance=~\"$instance\"}[$__range]) unless on (instance, device) last_over_time(smartctl_device_smart_status{instance=~\"$instance\"}[$__range]))",
     "legendFormat": "value"
    },
    {
     "expr": "(sum by(instance) (last_over_time(smartctl_device_num_err_log_entries{instance=~\"$instance\"}[$__range])) or sum by(instance) (smartctl_devices{instance=~\"$instance\"} * 0))\r\n+\r\n(sum by(instance) (last_over_time(smartctl_device_media_errors{instance=~\"$instance\"}[$__range])) or sum by(instance) (smartctl_devices{instance=~\"$instance\"} * 0))\r\n+\r\n(sum by(instance) (last_over_time(smartctl_device_error_log_count{instance=~\"$instance\"}[$__range])) or sum by(instance) (smartctl_devices{instance=~\"$instance\"} * 0))",
     "legendFormat": "value"
    },
    {
     "expr": "max by(instance) (smartctl_devices{instance=~\"$instance\"})\r\n-\r\nsum by(instance) (smartctl_device{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "smartctl exporter version history",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "max by(instance, version) (label_replace(last_over_time(smartctl_exporter_build_info{instance=~\"$instance\"}[$__interval]), \"version\", \"<missing>\", \"version\", \"\"))\r\nor on()\r\n(\r\n  vector(0) unless on() last_over_time(smartctl_exporter_build_info{instance=~\"$instance\"}[$__interval])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "device status",
   "type": "state-timeline",
   "description": "ok is all devices ok, error if any device has error state",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "min by(instance) (min_over_time(smartctl_device_smart_status{instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "write rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "max by(instance) (rate(smartctl_device_bytes_written{instance=~\"$instance\"}[$__rate_interval]))\r\nor\r\nmax by(instance) (rate(mined:smartctl_device_bytes_written{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "temperature (max)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by(instance) (max_over_time(smartctl_device_temperature{instance=~\"$instance\", temperature_type=\"current\"}[$__interval]) != 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "read rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "max by(instance) (rate(smartctl_device_bytes_read{instance=~\"$instance\"}[$__rate_interval]))\r\nor\r\nmax by(instance) (rate(mined:smartctl_device_bytes_read{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "temperature (avg)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by(instance) (avg_over_time(smartctl_device_temperature{instance=~\"$instance\", temperature_type=\"current\"}[$__interval]) != 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "new media errors",
   "type": "timeseries",
   "description": "Contains the number of occurrences where the controller detected an unrecovered data integrity error. Errors such as uncorrectable ECC, CRC checksum failure, or LBA tag mismatch are included in this field",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(smartctl_device_media_errors{instance=~\"$instance\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "temperature to limit delta (min over devices in instance)",
   "type": "timeseries",
   "description": "scaling is inversed, negative values means temperature is above limit",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "min by(instance) (\r\nmax by(instance, device) (max_over_time(smartctl_device_temperature{instance=~\"$instance\", temperature_type=\"op_limit_max\"}[$__interval]) != 0)\r\n-\r\nmax by(instance, device) (max_over_time(smartctl_device_temperature{instance=~\"$instance\", temperature_type=\"current\"}[$__interval]) != 0)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "new error log entries",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(smartctl_device_num_err_log_entries{instance=~\"$instance\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "temperature to critical limit delta (min over devices in instance)",
   "type": "timeseries",
   "description": "scaling is inversed, negative values means temperature is above limit",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "min by(instance) (\r\nmax by(instance, device) (max_over_time(smartctl_device_temperature{instance=~\"$instance\", temperature_type=\"critical_limit_max\"}[$__interval]) != 0)\r\n-\r\nmax by(instance, device) (max_over_time(smartctl_device_temperature{instance=~\"$instance\", temperature_type=\"current\"}[$__interval]) != 0)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "new SMART error log entries",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(smartctl_device_error_log_count{instance=~\"$instance\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}