{
 "title": "Smartctl / Details",
 "tags": [ "smartctl" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(smartctl_version[$__range])))"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(group by(instance) (last_over_time(smartctl_version{location=~\"$location\"}[$__range])))"
    }
   },
   {
    "name": "interface",
    "label": "Device Interface",
    "query": {
     "query": "query_result(group by(interface) (last_over_time(smartctl_device{instance=~\"$instance\"}[$__range])))"
    }
   },
   {
    "name": "only_present",
    "query": "all : \"invalid123\", only present : \"\""
   },
   {
    "name": "model_name",
    "label": "Model Name",
    "query": {
     "query": "query_result(group by(model_name) ((smartctl_device{instance=~\"$instance\", interface=~\"$interface\", invalid=$only_present})) or group by(model_name) (last_over_time(smartctl_device{instance=~\"$instance\", interface=~\"$interface\", invalid!=$only_present}[$__range])))"
    }
   },
   {
    "name": "device",
    "query": {
     "query": "query_result(sum by(device) ((smartctl_device{instance=~\"$instance\", interface=~\"$interface\", model_name=~\"$model_name\", invalid=$only_present})) or sum by(device) (last_over_time(smartctl_device{instance=~\"$instance\", interface=~\"$interface\", model_name=~\"$model_name\", invalid!=$only_present}[$__range])))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "device count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(avg_over_time(smartctl_devices{instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "devices"
    }
   ]
  },
  {
   "title": "Media errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(smartctl_device_media_errors{instance=~\"$instance\", device=~\"$device\"})"
    }
   ]
  },
  {
   "title": "SMART error log count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(smartctl_device_error_log_count{instance=~\"$instance\", device=~\"$device\"})"
    }
   ]
  },
  {
   "title": "Error log entries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(smartctl_device_num_err_log_entries{instance=~\"$instance\", device=~\"$device\"})"
    }
   ]
  },
  {
   "title": "device status",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "min by(device) (min_over_time(smartctl_device_smart_status{instance=~\"$instance\", device=~\"$device\"}[$__interval]))",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Smartctl exit status",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "max by(device) (max_over_time(smartctl_device_smartctl_exit_status{instance=~\"$instance\", device=~\"$device\"}[$__interval]))",
     "legendFormat": "{{ device }})"
    }
   ]
  },
  {
   "title": "Device Info",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "max by(instance, device, model_family, model_name, serial_number, form_factor, protocol, firmware_version, interface) (last_over_time(smartctl_device{instance=~\"$instance\", device=~\"$device\"}[$__range]))",
     "legendFormat": "value"
    },
    {
     "expr": "sum by(instance, device) (last_over_time(smartctl_device_smart_status{instance=~\"$instance\", device=~\"$device\"}[$__range]))",
     "legendFormat": "value"
    },
    {
     "expr": "sum by(instance, device) ((smartctl_device{instance=~\"$instance\", device=~\"$device\"}) or last_over_time(smartctl_device{instance=~\"$instance\", device=~\"$device\"}[$__range]) * 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SMART overview",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum by(instance, device) (last_over_time(smartctl_device{instance=~\"$instance\", device=~\"$device\"}[$__range]))",
     "legendFormat": "{{instance}} - {{device}} - {{model_name}}"
    },
    {
     "expr": "max by(device) ((smartctl_device{instance=~\"$instance\", device=~\"$device\"}) or last_over_time(smartctl_device{instance=~\"$instance\", device=~\"$device\"}[$__range]) * 0)",
     "legendFormat": "{{instance}} - {{device}} - {{model_name}}"
    },
    {
     "expr": "max by(device) (last_over_time(smartctl_device_temperature{instance=~\"$instance\", device=~\"$device\", temperature_type=\"op_limit_max\"}[$__range]))\r\nor\r\nmax by(device) (last_over_time(smartctl_device_temperature{instance=~\"$instance\", device=~\"$device\", temperature_type=\"critical_limit_max\"}[$__range]))\r\nor\r\nmax by(device) (last_over_time(smartctl_device_temperature{instance=~\"$instance\", device=~\"$device\", temperature_type=\"drive_trip\"}[$__range]))"
    },
    {
     "expr": "max by(device) (max_over_time(smartctl_device_percentage_used{instance=~\"$instance\", device=~\"$device\"}[$__range]))"
    },
    {
     "expr": "max by(device) (max_over_time(smartctl_device_power_on_seconds{instance=~\"$instance\", device=~\"$device\"}[$__range]))"
    },
    {
     "expr": "max by(device) (max_over_time(smartctl_device_power_cycle_count{instance=~\"$instance\", device=~\"$device\"}[$__range]))"
    },
    {
     "expr": "max by(device) (smartctl_device_interface_speed{instance=~\"$instance\", device=~\"$device\", speed_type=\"current\"})"
    },
    {
     "expr": "max by(device) (last_over_time(smartctl_device_capacity_bytes{instance=~\"$instance\", device=~\"$device\"}[$__range]))"
    },
    {
     "expr": "max by(device) (last_over_time(smartctl_device_block_size{instance=~\"$instance\", device=~\"$device\", blocks_type=\"logical\"}[$__range]) != 0)"
    },
    {
     "expr": "max by(device) (last_over_time(smartctl_device_block_size{instance=~\"$instance\", device=~\"$device\", blocks_type=\"physical\"}[$__range]) != 0)"
    },
    {
     "expr": "max by(device) (last_over_time(smartctl_device_error_log_count{instance=~\"$instance\", device=~\"$device\"}[$__range]))"
    },
    {
     "expr": "max by(device) (last_over_time(mined:smartctl_device_bytes_written{instance=~\"$instance\", device=~\"$device\"}[$__range]))"
    },
    {
     "expr": "max by(device) (last_over_time(mined:smartctl_device_bytes_read{instance=~\"$instance\", device=~\"$device\"}[$__range]))"
    },
    {
     "expr": "max by(device) (last_over_time(smartctl_device_attribute{instance=~\"$instance\", device=~\"$device\", attribute_name=\"Offline_Uncorrectable\", attribute_value_type=\"raw\"}[$__range]))"
    },
    {
     "expr": "max by(device) (last_over_time(smartctl_device_attribute{instance=~\"$instance\", device=~\"$device\", attribute_name=\"Reallocated_Sector_Ct\", attribute_value_type=\"raw\"}[$__range]))"
    },
    {
     "expr": "max by(device) (last_over_time(smartctl_device_attribute{instance=~\"$instance\", device=~\"$device\", attribute_name=\"Current_Pending_Sector\", attribute_value_type=\"raw\"}[$__range]))"
    },
    {
     "expr": "max by(device) (last_over_time(smartctl_device_attribute{instance=~\"$instance\", device=~\"$device\", attribute_name=\"UDMA_CRC_Error_Count\", attribute_value_type=\"raw\"}[$__range]))"
    },
    {
     "expr": "max by(device) (increase(smartctl_device_attribute{instance=~\"$instance\", device=~\"$device\", attribute_name=\"Hardware_ECC_Recovered\", attribute_value_type=\"raw\"}[$__range]))"
    },
    {
     "expr": "max by(device) (last_over_time(smartctl_device_attribute{instance=~\"$instance\", device=~\"$device\", attribute_name=\"Reported_Uncorrect\", attribute_value_type=\"raw\"}[$__range]))"
    },
    {
     "expr": "max by(device) (last_over_time(smartctl_device_attribute{instance=~\"$instance\", device=~\"$device\", attribute_name=\"Command_Timeout\", attribute_value_type=\"raw\"}[$__range]))"
    },
    {
     "expr": "max by(device) (last_over_time(smartctl_device_attribute{instance=~\"$instance\", device=~\"$device\", attribute_name=\"Reallocated_Event_Count\", attribute_value_type=\"raw\"}[$__range]))"
    },
    {
     "expr": "max by(device) (last_over_time(smartctl_device_num_err_log_entries{instance=~\"$instance\", device=~\"$device\"}[$__range]))"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "write rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "max by(device) (rate(smartctl_device_bytes_written{instance=~\"$instance\", device=~\"$device\"}[$__rate_interval]))\r\nor\r\nmax by(device) (rate(mined:smartctl_device_bytes_written{instance=~\"$instance\", device=~\"$device\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "temperature (max)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by(device) (max_over_time(smartctl_device_temperature{instance=~\"$instance\", device=~\"$device\",temperature_type=\"current\"}[$__interval]) != 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "read rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "max by(device) (rate(smartctl_device_bytes_read{instance=~\"$instance\", device=~\"$device\"}[$__rate_interval]))\r\nor\r\nmax by(device) (rate(mined:smartctl_device_bytes_read{instance=~\"$instance\", device=~\"$device\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "temperature (avg)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by(device) (avg_over_time(smartctl_device_temperature{instance=~\"$instance\", device=~\"$device\",temperature_type=\"current\"}[$__interval]) != 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "new media errors",
   "type": "timeseries",
   "description": "Contains the number of occurrences where the controller detected an unrecovered data integrity error. Errors such as uncorrectable ECC, CRC checksum failure, or LBA tag mismatch are included in this field",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "sum by(device) (rate(smartctl_device_media_errors{instance=~\"$instance\", device=~\"$device\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "temperature to limit delta",
   "type": "timeseries",
   "description": "scaling is inversed, negative values means temperature is above limit",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by(device) (max_over_time(smartctl_device_temperature{instance=~\"$instance\", device=~\"$device\",temperature_type=\"op_limit_max\"}[$__interval]) != 0)\r\n-\r\nmax by(device) (max_over_time(smartctl_device_temperature{instance=~\"$instance\", device=~\"$device\",temperature_type=\"current\"}[$__interval]) != 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "new error log entries",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "sum by(device) (rate(smartctl_device_num_err_log_entries{instance=~\"$instance\", device=~\"$device\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "temperature to critical limit delta",
   "type": "timeseries",
   "description": "scaling is inversed, negative values means temperature is above limit",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by(device) (max_over_time(smartctl_device_temperature{instance=~\"$instance\", device=~\"$device\",temperature_type=\"critical_limit_max\"}[$__interval]) != 0)\r\n-\r\nmax by(device) (max_over_time(smartctl_device_temperature{instance=~\"$instance\", device=~\"$device\",temperature_type=\"current\"}[$__interval]) != 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "new SMART error log entries",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "sum by(device) (rate(smartctl_device_error_log_count{instance=~\"$instance\", device=~\"$device\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Critical warnings for state of controller",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 97 },
   "targets": [
    {
     "expr": "max by(device) (max_over_time(smartctl_device_critical_warning{instance=~\"$instance\", device=~\"$device\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "remaining spare",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "min by(device) (min_over_time(smartctl_device_available_spare{instance=~\"$instance\", device=~\"$device\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "remaining spare above threshold",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "min by(device) (\r\n  min_over_time(smartctl_device_available_spare{instance=~\"$instance\", device=~\"$device\"}[$__interval])\r\n  -\r\n  last_over_time(smartctl_device_available_spare_threshold{instance=~\"$instance\", device=~\"$device\"}[$__interval])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}