---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: immich
  name: user-data
spec:
  storageClassName: REPLACE_ME
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: REPLACE_ME
