{
 "title": "ZFS vdev",
 "description": "ZFS monitoring dashboard",
 "tags": [
  "ZFS",
  "node"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(zfs_pool_vdevs{}[$__range])))"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(group by(instance) (last_over_time(zfs_pool_vdevs{location=~\"$location\"}[$__range])))"
    }
   },
   {
    "name": "pool",
    "query": {
     "query": "query_result(group by(zpool) (last_over_time(zfs_pool_vdevs{instance=~\"$instance\"}[$__range])))"
    }
   },
   {
    "name": "vdev",
    "query": {
     "query": "query_result(group by(vdev) (last_over_time(zfs_vdev_ashift_configured{instance=~\"$instance\", zpool=~\"$pool\"}[$__range])))"
    }
   },
   {
    "name": "disk",
    "query": {
     "query": "query_result(label_replace(last_over_time(zfs_vdev_ashift_configured{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\"}[$__range]), \"disk\", \"$1\", \"path\", \".*/([^/]*)\"))"
    }
   }
  ]
 },
 "panels": [
  { "title": "info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "pool list",
   "type": "table",
   "gridPos": { "h": 10, "w": 13, "x": 1, "y": 1 },
   "targets": [
    {
     "expr": "max by(instance, zpool, state) (zfs_pool_size_bytes{instance=~\"$instance\", pool=~\"$pool\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, zpool) (zfs_pool_vdevs{instance=~\"$instance\", zpool=~\"$pool\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, zpool) (zfs_pool_load_time_seconds{instance=~\"$instance\", zpool=~\"$pool\"}) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, zpool) (zfs_pool_errors{instance=~\"$instance\", zpool=~\"$pool\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(zpool, state) (node_zfs_zpool_state{instance=~\"$instance\", zpool=~\"$pool\"} == 1)",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - max by(instance, zpool) (zfs_pool_load_time_seconds{instance=~\"$instance\", zpool=~\"$pool\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notes",
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 15, "y": 1 },
   "options": {
    "content": "`allocated` property is only tracked for devices directly under root.\r\nThis is usually vdevs (mirror, raidz, etc), but if you don't have redundancy,\r\nit is tracked at the disk level.\r\n\r\nRead from vdev is usually much smaller than read from dataset,\r\nbecause the majority of data is cached in ARC.\r\n\r\nL2ARC vdev is not tracked by the exporter,\r\nand ZFS doesn't expose separate per-pool statistics for L2ARC.\r\n\r\nRead/write latency can be missing in case there were no corresponding operations.\r\n"
   }
  },
  {
   "title": "pool state",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 21, "x": 1, "y": 11 },
   "targets": [
    {
     "expr": "max by(instance, zpool, state) (\r\nmax without(state) (max_over_time(node_zfs_zpool_state{instance=~\"$instance\", zpool=~\"$pool\", state=\"online\"}[$__interval]) == 1) * 2\r\nor\r\nmax without(state) (max_over_time(node_zfs_zpool_state{instance=~\"$instance\", zpool=~\"$pool\", state=\"offline\"}[$__interval]) == 1) * 3\r\nor\r\nmax without(state) (max_over_time(node_zfs_zpool_state{instance=~\"$instance\", zpool=~\"$pool\", state=\"removed\"}[$__interval]) == 1) * 4\r\nor\r\nmax without(state) (max_over_time(node_zfs_zpool_state{instance=~\"$instance\", zpool=~\"$pool\", state=\"suspended\"}[$__interval]) == 1) * 5\r\nor\r\nmax without(state) (max_over_time(node_zfs_zpool_state{instance=~\"$instance\", zpool=~\"$pool\", state=\"degraded\"}[$__interval]) == 1) * 6\r\nor\r\nmax without(state) (max_over_time(node_zfs_zpool_state{instance=~\"$instance\", zpool=~\"$pool\", state=\"faulted\"}[$__interval]) == 1) * 7\r\nor\r\nmax without(state) (max_over_time(node_zfs_zpool_state{instance=~\"$instance\", zpool=~\"$pool\", state=\"unavail\"}[$__interval]) == 1) * 8\r\n)",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "vdev list",
   "type": "table",
   "gridPos": { "h": 13, "w": 21, "x": 1, "y": 19 },
   "targets": [
    {
     "expr": "max by(instance, zpool, vdev) (max_over_time(zfs_vdev_space_capacity_bytes{instance=~\"$instance\", zpool=~\"$pool\", path=\"\", vdev=~\"$vdev\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, zpool, vdev) (max_over_time(zfs_vdev_space_allocated_bytes{instance=~\"$instance\", zpool=~\"$pool\", path=\"\", vdev=~\"$vdev\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, zpool, vdev) (\r\nmax_over_time(zfs_vdev_space_allocated_bytes{instance=~\"$instance\", zpool=~\"$pool\", path=\"\", vdev=~\"$vdev\"}[$__range])\r\n/\r\n(max_over_time(zfs_vdev_space_capacity_bytes{instance=~\"$instance\", zpool=~\"$pool\", path=\"\", vdev=~\"$vdev\"}[$__range]) != 0)\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, zpool, vdev) (max_over_time(zfs_vdev_ashift_configured{instance=~\"$instance\", zpool=~\"$pool\", path=\"\", vdev=~\"$vdev\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, zpool, vdev) (max_over_time(zfs_vdev_children{instance=~\"$instance\", zpool=~\"$pool\", path=\"\", vdev=~\"$vdev\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, zpool, vdev) (max_over_time(zfs_vdev_errors{instance=~\"$instance\", zpool=~\"$pool\", path=\"\", vdev=~\"$vdev\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, zpool, vdev) (avg_over_time(zfs_vdev_fragmentation{instance=~\"$instance\", zpool=~\"$pool\", path=\"\", vdev=~\"$vdev\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, zpool, vdev) (max_over_time(zfs_vdev_rebuild_processed_bytes{instance=~\"$instance\", zpool=~\"$pool\", path=\"\", vdev=~\"$vdev\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, zpool, vdev) (zfs_vdev_scan_processed_bytes{instance=~\"$instance\", zpool=~\"$pool\", path=\"\", vdev=~\"$vdev\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, zpool, vdev) (zfs_vdev_self_healed_bytes{instance=~\"$instance\", zpool=~\"$pool\", path=\"\", vdev=~\"$vdev\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, zpool, vdev) (max_over_time(zfs_vdev_slow_ios{instance=~\"$instance\", zpool=~\"$pool\", path=\"\", vdev=~\"$vdev\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, zpool, vdev) (min_over_time(zfs_vdev_state{instance=~\"$instance\", zpool=~\"$pool\", path=\"\", vdev=~\"$vdev\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vdev state",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 21, "x": 1, "y": 32 },
   "targets": [
    {
     "expr": "min by(instance, zpool, vdev) (min_over_time(zfs_vdev_state{instance=~\"$instance\", zpool=~\"$pool\", path=\"\", vdev=~\"$vdev\"}[$__interval]))",
     "legendFormat": "{{instance}}/{{zpool}}/{{vdev}}"
    }
   ]
  },
  {
   "title": "physical devices",
   "type": "table",
   "gridPos": { "h": 19, "w": 21, "x": 1, "y": 43 },
   "targets": [
    {
     "expr": "max by(instance, zpool, vdev, path) (max_over_time(zfs_vdev_devsize_replaceable{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, zpool, vdev, path) (max_over_time(zfs_vdev_physical_capacity_bytes{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, zpool, vdev, path) (avg_over_time(zfs_vdev_space_allocated_bytes{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, zpool, vdev, path) (max_over_time(zfs_vdev_ashift_configured{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, zpool, vdev, path) (max_over_time(zfs_vdev_errors{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, zpool, vdev, path) (avg_over_time(zfs_vdev_fragmentation{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, zpool, vdev, path) (min_over_time(zfs_vdev_state{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, zpool, vdev, path) (\r\n  max_over_time(zfs_vdev_trim_errors{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\"}[$__range])\r\n  and\r\n  (max_over_time(zfs_vdev_trim_unsupported{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\"}[$__range]) == 0)\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "1 - max by(instance, zpool, vdev, path) (max_over_time(zfs_vdev_trim_unsupported{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "disk state",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 21, "x": 1, "y": 62 },
   "targets": [
    {
     "expr": "min by(instance, zpool, vdev, path) (label_replace(min_over_time(zfs_vdev_state{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\"}[$__interval]), \"path\", \"$1\", \"path\", \".*/([^/]*)\"))",
     "legendFormat": "{{zpool}}/{{vdev}}/{{path}}"
    }
   ]
  },
  {
   "title": "errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 21, "x": 1, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "max by(instance, zpool, vdev, path, type) (\r\n  label_replace(\r\n    rate(zfs_vdev_errors{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\"}[$__rate_interval])\r\n    , \"path\", \"$1\", \"path\", \".*/([^/]*)\"\r\n  )\r\n) * $__interval_ms / 1000",
     "legendFormat": "{{zpool}}/{{vdev}}/{{path}}: {{type}}"
    }
   ]
  },
  { "title": "read/write", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "read speed (vdevs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "max by(instance, zpool, vdev) (rate(zfs_vdev_bytes{instance=~\"$instance\", zpool=~\"$pool\", path=\"\", vdev=~\"$vdev\", type=\"read\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}/{{zpool}}/{{vdev}}"
    }
   ]
  },
  {
   "title": "write speed (vdevs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "max by(instance, zpool, vdev) (rate(zfs_vdev_bytes{instance=~\"$instance\", zpool=~\"$pool\", path=\"\", vdev=~\"$vdev\", type=\"read\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}/{{zpool}}/{{vdev}}"
    }
   ]
  },
  {
   "title": "read speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "max by(instance, zpool, vdev, path) (label_replace(rate(zfs_vdev_bytes{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\", type=\"read\"}[$__rate_interval]), \"path\", \"$1\", \"path\", \".*/([^/]*)\"))",
     "legendFormat": "{{zpool}}/{{vdev}}/{{path}}"
    }
   ]
  },
  {
   "title": "write speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "max by(instance, zpool, vdev, path) (label_replace(rate(zfs_vdev_bytes{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\", type=\"write\"}[$__rate_interval]), \"path\", \"$1\", \"path\", \".*/([^/]*)\"))",
     "legendFormat": "{{zpool}}/{{vdev}}/{{path}}"
    }
   ]
  },
  {
   "title": "read IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "max by(instance, zpool, vdev, path) (label_replace(rate(zfs_vdev_ops{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\", type=\"read\"}[$__rate_interval]), \"path\", \"$1\", \"path\", \".*/([^/]*)\"))",
     "legendFormat": "{{zpool}}/{{vdev}}/{{path}}"
    }
   ]
  },
  {
   "title": "write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "max by(instance, zpool, vdev, path) (label_replace(rate(zfs_vdev_ops{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\", type=\"write\"}[$__rate_interval]), \"path\", \"$1\", \"path\", \".*/([^/]*)\"))",
     "legendFormat": "{{zpool}}/{{vdev}}/{{path}}"
    }
   ]
  },
  {
   "title": "read latency p99 (zio)",
   "type": "timeseries",
   "description": "includes queue and disk read itself",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(instance, zpool, vdev, path) (label_replace(max_over_time(zfs_vdev_zio_latency_total_bucket:quantile_irate{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\", type=\"read\", quantile=\"0.99\"}[$__rate_interval]), \"path\", \"$1\", \"path\", \".*/([^/]*)\"))",
     "legendFormat": "{{zpool}}/{{vdev}}/{{path}}"
    }
   ]
  },
  {
   "title": "write latency p99 (zio)",
   "type": "timeseries",
   "description": "includes queue and disk read itself",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(instance, zpool, vdev, path) (label_replace(max_over_time(zfs_vdev_zio_latency_total_bucket:quantile_irate{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\", type=\"write\", quantile=\"0.99\"}[$__rate_interval]), \"path\", \"$1\", \"path\", \".*/([^/]*)\"))",
     "legendFormat": "{{zpool}}/{{vdev}}/{{path}}"
    }
   ]
  },
  {
   "title": "read latency p99 (disk)",
   "type": "timeseries",
   "description": "includes only disk operation",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(instance, zpool, vdev, path) (label_replace(max_over_time(zfs_vdev_latency_disk_bucket:quantile_irate{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\", type=\"read\", quantile=\"0.99\"}[$__rate_interval]), \"path\", \"$1\", \"path\", \".*/([^/]*)\"))",
     "legendFormat": "{{zpool}}/{{vdev}}/{{path}}"
    }
   ]
  },
  {
   "title": "write latency p99 (disk)",
   "type": "timeseries",
   "description": "includes only disk operation",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(instance, zpool, vdev, path) (label_replace(max_over_time(zfs_vdev_latency_disk_bucket:quantile_irate{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\", type=\"write\", quantile=\"0.99\"}[$__rate_interval]), \"path\", \"$1\", \"path\", \".*/([^/]*)\"))",
     "legendFormat": "{{zpool}}/{{vdev}}/{{path}}"
    }
   ]
  },
  { "title": "trim", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 } },
  {
   "title": "scan: repaired bytes rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "max by(instance, zpool, vdev, path) (label_replace(rate(zfs_vdev_scan_processed_bytes{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\"}[$__rate_interval]), \"path\", \"$1\", \"path\", \".*/([^/]*)\"))",
     "legendFormat": "{{zpool}}/{{vdev}}/{{path}}"
    }
   ]
  },
  {
   "title": "trim state",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 130 },
   "targets": [
    {
     "expr": "max by(instance, zpool, vdev, path) (label_replace(\r\n  ((min_over_time(zfs_vdev_trim_unsupported{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\"}[$__interval]) == 1) * 10)\r\n  or\r\n  min_over_time(zfs_vdev_trim_state{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\"}[$__interval])\r\n  , \"path\", \"$1\", \"path\", \".*/([^/]*)\")\r\n)",
     "legendFormat": "{{zpool}}/{{vdev}}/{{path}}"
    }
   ]
  },
  {
   "title": "trim start time (ago)",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "$__to / 1000 - max by(zpool, vdev, path) (max_over_time(zfs_vdev_trim_action_time{instance=~\"$instance\", zpool=~\"$pool\", vdev=~\"$vdev\", path=~\"$disk\"}[$__interval]) != 0)",
     "legendFormat": "{{zpool}}/{{vdev}}/{{path}}"
    }
   ]
  },
  {
   "title": "trim: completed %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "min by (instance, zpool, vdev, path) (\r\nlabel_replace(\r\n  avg_over_time(zfs_vdev_trim_processed_bytes{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval])\r\n  /\r\n  (max_over_time(zfs_vdev_trim_estimated_bytes{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]) != 0)\r\n, \"path\", \"$1\", \"path\", \".*/([^/]*)\")\r\n)",
     "legendFormat": "{{zpool}}/{{vdev}}/{{path}}"
    }
   ]
  },
  {
   "title": "trim estimated size",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(zpool, vdev, path) (max_over_time(zfs_vdev_trim_estimated_bytes{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]) != 0)",
     "legendFormat": "{{zpool}}/{{vdev}}/{{path}}"
    }
   ]
  },
  {
   "title": "trim processed bytes rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance, zpool, vdev, path) (label_replace(\r\n  rate(zfs_vdev_trim_processed_bytes{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\"}[$__rate_interval])\r\n  and\r\n  (min_over_time(zfs_vdev_trim_unsupported{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\"}[$__interval]) == 0)\r\n  , \"path\", \"$1\", \"path\", \".*/([^/]*)\")\r\n)",
     "legendFormat": "{{zpool}}/{{vdev}}/{{path}}"
    }
   ]
  },
  {
   "title": "trim: estimated remaining time",
   "type": "timeseries",
   "description": "Empty, unless trim ran in time range. Requires a custom recording rule",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(instance, zpool, vdev, path) (\r\nlabel_replace(\r\n  max_over_time(zfs_vdev_trim_estimated_remaining_seconds{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval])\r\n, \"path\", \"$1\", \"path\", \".*/([^/]*)\")\r\n)",
     "legendFormat": "{{zpool}}/{{vdev}}/{{path}}"
    }
   ]
  }
 ]
}