{
 "title": "ZFS Dataset Details",
 "description": "ZFS monitoring dashboard",
 "tags": [
  "ZFS",
  "node"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "query_result(label_join(zfs_exporter_build_info, \"human_name\", \"/\", \"cluster_type\", \"cluster\"))"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(last_over_time(zfs_exporter_build_info{cluster=~\"$cluster\"}[$__range]))"
    }
   },
   {
    "name": "pool",
    "query": {
     "query": "query_result(zfs_dataset_used_bytes{instance=\"$instance\"})"
    }
   },
   { "name": "dataset_filter", "label": "Dataset selector" },
   {
    "name": "type",
    "query": {
     "query": "query_result(zfs_dataset_used_bytes{instance=\"$instance\", pool=\"$pool\"})"
    }
   },
   {
    "name": "dataset",
    "query": {
     "query": "query_result(zfs_dataset_used_bytes{instance=\"$instance\", pool=\"$pool\", name=~\".*(${dataset_filter}).*\", type=~\"$type\"})"
    }
   },
   { "name": "enable_children", "label": "Show children", "query": "Show : .*, Hide : invalid123" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pool List",
   "type": "table",
   "gridPos": { "h": 16, "w": 18, "x": 1, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pool, name, type) (zfs_dataset_used_bytes{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset\"})\r\nor\r\nmax by(pool, name, type) (zfs_dataset_used_bytes{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset/.*\", invalid=~\"$enable_children\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(pool, name, type) (zfs_dataset_logical_used_bytes{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset\"})\r\nor\r\nmax by(pool, name, type) (zfs_dataset_logical_used_bytes{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset/.*\", invalid=~\"$enable_children\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(pool, name, type) (zfs_dataset_referenced_bytes{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset\"})\r\nor\r\nmax by(pool, name, type) (zfs_dataset_referenced_bytes{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset/.*\", invalid=~\"$enable_children\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(pool, name, type) (zfs_dataset_quota_bytes{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset\"})\r\nor\r\nmax by(pool, name, type) (zfs_dataset_quota_bytes{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset/.*\", invalid=~\"$enable_children\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(pool, name, type) (zfs_dataset_referenced_quota_bytes{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset\"})\r\nor\r\nmax by(pool, name, type) (zfs_dataset_volume_size_bytes{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset\"})\r\nor\r\nmax by(pool, name, type) (zfs_dataset_referenced_quota_bytes{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset/.*\", invalid=~\"$enable_children\"})\r\nor\r\nmax by(pool, name, type) (zfs_dataset_volume_size_bytes{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset/.*\", invalid=~\"$enable_children\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(pool, name, type) (zfs_dataset_written_bytes{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset\"})\r\nor\r\nmax by(pool, name, type) (zfs_dataset_written_bytes{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset/.*\", invalid=~\"$enable_children\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(pool, name, type) (zfs_dataset_referenced_reservation_bytes{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset\"})\r\nor\r\nmax by(pool, name, type) (zfs_dataset_referenced_reservation_bytes{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset/.*\", invalid=~\"$enable_children\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(pool, name, type) (zfs_dataset_available_bytes{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset\"})\r\nor\r\nmax by(pool, name, type) (zfs_dataset_available_bytes{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset/.*\", invalid=~\"$enable_children\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(pool, name, type) (zfs_dataset_creation{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset\"}) * 1000\r\nor\r\nmax by(pool, name, type) (zfs_dataset_creation{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset/.*\", invalid=~\"$enable_children\"}) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(pool, name, type) (zfs_dataset_creation{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset\"}) * 1000\r\nor\r\nmax by(pool, name, type) (zfs_dataset_creation{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset/.*\", invalid=~\"$enable_children\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Space", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Used delta",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(delta(zfs_dataset_logical_referenced_bytes{instance=\"$instance\", pool=~\"$pool\", type=~\"$type\", name=~\"$dataset\"}[$__interval]))",
     "legendFormat": "self"
    },
    {
     "expr": "sum(delta(zfs_dataset_logical_referenced_bytes{instance=\"$instance\", pool=~\"$pool\", type=~\"$type\", name=~\"$dataset/.*\", invalid=~\"$enable_children\"}[$__interval]))",
     "legendFormat": "children"
    }
   ]
  },
  {
   "title": "Used %",
   "type": "timeseries",
   "description": "When quota is not set, this is expected to be empty.\nVolumes without discard can have \"volume\" value artificially high.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(\r\nmax_over_time(zfs_dataset_referenced_bytes{instance=\"$instance\", pool=~\"$pool\", type=~\"$type\", name=~\"$dataset\"}[$__interval])\r\n/\r\n(max_over_time(zfs_dataset_quota_bytes{instance=\"$instance\", pool=~\"$pool\", type=~\"$type\", name=~\"$dataset\"}[$__interval]) != 0)\r\n)",
     "legendFormat": "quota (self)"
    },
    {
     "expr": "max(\r\nmax_over_time(zfs_dataset_referenced_bytes{instance=\"$instance\", pool=~\"$pool\", type=~\"$type\", name=~\"$dataset\"}[$__interval])\r\n/\r\n(max_over_time(zfs_dataset_referenced_quota_bytes{instance=\"$instance\", pool=~\"$pool\", type=~\"$type\", name=~\"$dataset\"}[$__interval]) != 0)\r\n)",
     "legendFormat": "ref quota"
    },
    {
     "expr": "max(\r\nmax_over_time(zfs_dataset_used_bytes{instance=\"$instance\", pool=~\"$pool\", type=~\"$type\", name=~\"$dataset\"}[$__interval])\r\n/\r\n(max_over_time(zfs_dataset_quota_bytes{instance=\"$instance\", pool=~\"$pool\", type=~\"$type\", name=~\"$dataset\"}[$__interval]) != 0)\r\n)",
     "legendFormat": "quota (total)"
    },
    {
     "expr": "max(\r\nmax by(cluster_type, cluster, instance, pool) (max_over_time(zfs_dataset_used_bytes{instance=\"$instance\", pool=~\"$pool\", type=~\"$type\", name=~\"$dataset\"}[$__interval]))\r\n/ on(cluster_type, cluster, instance, pool)\r\nmax by(cluster_type, cluster, instance, pool) (max_over_time(zfs_pool_size_bytes{instance=\"$instance\", pool=~\"$pool\"}[$__interval]))\r\n)",
     "legendFormat": "pool (total)"
    },
    {
     "expr": "# using zfs_dataset_logical_used_bytes here because volumes run out of space when allocated, regardless of compressed size\r\nmax(\r\nmax_over_time(zfs_dataset_logical_used_bytes{instance=\"$instance\", pool=~\"$pool\", type=~\"$type\", name=~\"$dataset\"}[$__interval])\r\n/\r\nmax_over_time(zfs_dataset_volume_size_bytes{instance=\"$instance\", pool=~\"$pool\", type=~\"$type\", name=~\"$dataset\"}[$__interval])\r\n)",
     "legendFormat": "volume allocated"
    }
   ]
  },
  { "title": "Speed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Read Speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(dataset) (rate(node_zfs_zpool_dataset_nread{instance=\"$instance\", zpool=~\"$pool\", dataset=~\"$dataset\"}[$__rate_interval]))",
     "legendFormat": "self"
    },
    {
     "expr": "sum(rate(node_zfs_zpool_dataset_nread{instance=\"$instance\", zpool=~\"$pool\", dataset=~\"$dataset/.*\", invalid=~\"$enable_children\"}[$__rate_interval]))",
     "legendFormat": "children"
    }
   ]
  },
  {
   "title": "Write Speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(dataset) (rate(node_zfs_zpool_dataset_nwritten{instance=~\"$instance\", zpool=~\"$pool\", dataset=~\"$dataset\"}[$__rate_interval]))",
     "legendFormat": "self"
    },
    {
     "expr": "sum(rate(node_zfs_zpool_dataset_nwritten{instance=\"$instance\", zpool=~\"$pool\", dataset=~\"$dataset/.*\", invalid=~\"$enable_children\"}[$__rate_interval]))",
     "legendFormat": "children"
    }
   ]
  },
  { "title": "IOPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Read IOPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(dataset) (rate(node_zfs_zpool_dataset_reads{instance=\"$instance\", zpool=~\"$pool\", dataset=~\"$dataset\"}[$__rate_interval]))",
     "legendFormat": "self"
    },
    {
     "expr": "sum(rate(node_zfs_zpool_dataset_reads{instance=\"$instance\", zpool=~\"$pool\", dataset=~\"$dataset/.*\", invalid=~\"$enable_children\"}[$__rate_interval]))",
     "legendFormat": "children"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(dataset) (rate(node_zfs_zpool_dataset_writes{instance=~\"$instance\", dataset=~\"$dataset\"}[$__rate_interval]))",
     "legendFormat": "self"
    },
    {
     "expr": "sum(rate(node_zfs_zpool_dataset_writes{instance=~\"$instance\", dataset=~\"$dataset/.*\", invalid=~\"$enable_children\"}[$__rate_interval]))",
     "legendFormat": "children"
    }
   ]
  },
  {
   "title": "Read IO average size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(dataset) (\r\n  rate(node_zfs_zpool_dataset_nread{instance=\"$instance\", zpool=~\"$pool\", dataset=~\"$dataset\"}[$__rate_interval])\r\n  /\r\n  (rate(node_zfs_zpool_dataset_reads{instance=\"$instance\", zpool=~\"$pool\", dataset=~\"$dataset\"}[$__rate_interval]) + 1e-6)\r\n)",
     "legendFormat": "self"
    },
    {
     "expr": "avg(\r\n  rate(node_zfs_zpool_dataset_nread{instance=\"$instance\", zpool=~\"$pool\", dataset=~\"$dataset/.*\", invalid=~\"$enable_children\"}[$__rate_interval])\r\n  /\r\n  (rate(node_zfs_zpool_dataset_reads{instance=\"$instance\", zpool=~\"$pool\", dataset=~\"$dataset/.*\", invalid=~\"$enable_children\"}[$__rate_interval]) + 1e-6)\r\n)",
     "legendFormat": "children"
    }
   ]
  },
  {
   "title": "Write IO average size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(dataset) (\r\n  rate(node_zfs_zpool_dataset_nwritten{instance=\"$instance\", zpool=~\"$pool\", dataset=~\"$dataset\"}[$__rate_interval])\r\n  /\r\n  (rate(node_zfs_zpool_dataset_writes{instance=\"$instance\", zpool=~\"$pool\", dataset=~\"$dataset\"}[$__rate_interval]) + 1e-6)\r\n)",
     "legendFormat": "self"
    },
    {
     "expr": "sum(\r\n  rate(node_zfs_zpool_dataset_nwritten{instance=\"$instance\", zpool=~\"$pool\", dataset=~\"$dataset/.*\", invalid=~\"$enable_children\"}[$__rate_interval])\r\n  /\r\n  (rate(node_zfs_zpool_dataset_writes{instance=\"$instance\", zpool=~\"$pool\", dataset=~\"$dataset/.*\", invalid=~\"$enable_children\"}[$__rate_interval]) + 1e-6)\r\n)",
     "legendFormat": "children"
    }
   ]
  }
 ]
}