{
 "title": "ZFS Details",
 "description": "ZFS monitoring dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "pool",
    "label": "Pool",
    "query": {
     "query": "label_values(zpool_stats_alloc{job='zfs-exporter'}, name)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "query_result(label_join(zfs_exporter_build_info, \"human_name\", \"/\", \"cluster_type\", \"cluster\"))"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(zfs_exporter_build_info{cluster=\"$cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ZFS Pool Detail",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "zfs_pool_allocated_bytes{job='zfs-exporter', cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "zpool_stats_checksum_errors{job='zfs-exporter', cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "zfs_pool_fragmentation_ratio{job='zfs-exporter', cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "zfs_pool_free_bytes{job='zfs-exporter', cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "zpool_stats_read_bytes{job='zfs-exporter', cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "zfs_pool_size_bytes{job='zfs-exporter', cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "zpool_stats_write_bytes{job='zfs-exporter', cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pool Growth by Day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "delta(zfs_pool_allocated_bytes{job='zfs-exporter', cluster=\"$cluster\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}/{{pool}}"
    }
   ]
  },
  {
   "title": "Pool Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "zfs_pool_allocated_bytes{job='zfs-exporter', cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}/{{pool}} - Used"
    },
    {
     "expr": "zfs_pool_size_bytes{job='zfs-exporter', cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}/{{pool}} - Size"
    },
    {
     "expr": "zfs_pool_free_bytes{job='zfs-exporter', cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}/{{pool}} - Free"
    }
   ]
  },
  { "title": "ARC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "ARC Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_zfs_arc_data_size{job=\"$job\", cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "Data"
    },
    {
     "expr": "node_zfs_arc_metadata_size{job=\"$job\", cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "Metadata"
    },
    {
     "expr": "node_zfs_arc_mfu_size{job=\"$job\", cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "Most Frequently Used"
    },
    {
     "expr": "node_zfs_arc_dnode_size{job=\"$job\", cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "Dnode Size"
    },
    {
     "expr": "node_zfs_arc_mru_size{job=\"$job\", cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "Most Recently Used"
    },
    {
     "expr": "node_zfs_arc_size{job=\"$job\", cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "ARC Size"
    }
   ]
  },
  {
   "title": "ARC Demand - Data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_zfs_arc_demand_data_hits{job=\"$job\", cluster=\"$cluster\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Hits"
    },
    {
     "expr": "rate(node_zfs_arc_demand_data_misses{job=\"$job\", cluster=\"$cluster\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Misses"
    },
    {
     "expr": "rate(node_zfs_arc_demand_data_hits{job=\"$job\", cluster=\"$cluster\", instance=~\"$instance\"}[$__rate_interval])/(rate(node_zfs_arc_demand_data_misses[$__rate_interval])+rate(node_zfs_arc_demand_data_hits[$__rate_interval]))",
     "legendFormat": "Hit Ratio"
    }
   ]
  },
  {
   "title": "ARC Demand - Metadata",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_zfs_arc_demand_metadata_hits{job=\"$job\", cluster=\"$cluster\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Hits"
    },
    {
     "expr": "rate(node_zfs_arc_demand_metadata_misses{job=\"$job\", cluster=\"$cluster\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Misses"
    },
    {
     "expr": "rate(node_zfs_arc_demand_metadata_hits{job=\"$job\", cluster=\"$cluster\", instance=~\"$instance\"}[$__rate_interval])/(rate(node_zfs_arc_demand_metadata_misses[$__rate_interval])+rate(node_zfs_arc_demand_metadata_hits[$__rate_interval]))",
     "legendFormat": "Hit Ratio"
    }
   ]
  },
  { "title": "Pool Stats - $pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 }, "repeat": "pool" },
  {
   "title": "Pool Space",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "zfs_pool_allocated_bytes{job='zfs-exporter', cluster=\"$cluster\", instance=~\"$instance\", name=\"$pool\"}",
     "legendFormat": "{{instance}} Used"
    },
    {
     "expr": "zfs_pool_size_bytes{job='zfs-exporter', cluster=\"$cluster\", instance=~\"$instance\", name=\"$pool\"}",
     "legendFormat": "{{instance}} Total"
    },
    {
     "expr": "zfs_pool_free_bytes{job='zfs-exporter', cluster=\"$cluster\", instance=~\"$instance\", name=\"$pool\"}",
     "legendFormat": "{{instance}} Free"
    }
   ]
  },
  {
   "title": "Pool Reads",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_zfs_zpool_dataset_reads{job='node-exporter', cluster=\"$cluster\", instance=~\"$instance\", name=\"$pool\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "rate(node_zfs_zpool_dataset_nread{job='node-exporter', cluster=\"$cluster\", instance=~\"$instance\", name=\"$pool\"}[$__rate_interval])",
     "legendFormat": "{{name}} IOPS"
    },
    {
     "expr": "rate(zpool_stats_read_errors{job='node-exporter', cluster=\"$cluster\", instance=~\"$instance\", name=\"$pool\"}[$__rate_interval])",
     "legendFormat": "{{name}} Errors"
    }
   ]
  },
  {
   "title": "Pool Writes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_zfs_zpool_dataset_writes{job='node-exporter', cluster=\"$cluster\", instance=~\"$instance\", name=\"$pool\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "rate(node_zfs_zpool_dataset_nwritten{job='node-exporter', cluster=\"$cluster\", instance=~\"$instance\", name=\"$pool\"}[$__rate_interval])",
     "legendFormat": "{{name}} IOPS"
    },
    {
     "expr": "rate(zpool_stats_write_errors{job='node-exporter', cluster=\"$cluster\", instance=~\"$instance\", name=\"$pool\"}[$__rate_interval])",
     "legendFormat": "{{name}} Errors"
    }
   ]
  }
 ]
}