{
 "title": "ZFS Pool details",
 "description": "ZFS monitoring dashboard",
 "tags": [ "ZFS" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "query_result(label_join(zfs_exporter_build_info, \"human_name\", \"/\", \"cluster_type\", \"cluster\"))"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(zfs_exporter_build_info{cluster=\"$cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pool List",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "zfs_pool_allocated_bytes{cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "zfs_pool_errors{cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "zfs_pool_fragmentation_ratio{cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "zfs_pool_free_bytes{cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "zfs_pool_size_bytes{cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pool Growth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "delta(zfs_pool_allocated_bytes{job='zfs-exporter', cluster=\"$cluster\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Pool Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "zfs_pool_allocated_bytes{job='zfs-exporter', cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{pool}} - Used"
    },
    {
     "expr": "zfs_pool_free_bytes{job='zfs-exporter', cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{pool}} - Free"
    }
   ]
  },
  {
   "title": "Pool Speed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (zpool) (rate(node_zfs_zpool_dataset_nwritten{cluster=\"$cluster\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{zpool}} write"
    },
    {
     "expr": "sum by (zpool) (rate(node_zfs_zpool_dataset_nread{cluster=\"$cluster\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{zpool}} read"
    },
    {
     "expr": "sum by (zpool) (rate(zfs_pool_scan_processed_bytes{cluster=\"$cluster\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{zpool}} scan"
    }
   ]
  },
  {
   "title": "Pool IOPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (zpool) (rate(node_zfs_zpool_dataset_writes{cluster=\"$cluster\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{zpool}} writes"
    },
    {
     "expr": "sum by (zpool) (rate(node_zfs_zpool_dataset_reads{cluster=\"$cluster\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{zpool}} reads"
    },
    {
     "expr": "rate(zfs_pool_errors{cluster=\"$cluster\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{zpool}} errors"
    },
    {
     "expr": "rate(zfs_pool_scan_errors{cluster=\"$cluster\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{zpool}} scan errors"
    }
   ]
  }
 ]
}