{
 "title": "ZFS Pool",
 "description": "ZFS monitoring dashboard",
 "tags": [
  "ZFS",
  "node"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "query_result(label_join(zfs_exporter_build_info, \"human_name\", \"/\", \"cluster_type\", \"cluster\"))"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(last_over_time(zfs_exporter_build_info{cluster=~\"$cluster\"}[$__range]))"
    }
   },
   {
    "name": "pool",
    "query": {
     "query": "query_result(zfs_dataset_used_bytes{instance=\"$instance\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pool List",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "zfs_pool_size_bytes{instance=~\"$instance\", pool=~\"$pool\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "zfs_pool_allocated_bytes{instance=~\"$instance\", pool=~\"$pool\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "zfs_pool_free_bytes{instance=~\"$instance\", pool=~\"$pool\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "zfs_pool_errors{instance=~\"$instance\", zpool=~\"$pool\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "zfs_pool_fragmentation_ratio{instance=~\"$instance\", pool=~\"$pool\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "zfs_pool_deduplication_ratio{instance=~\"$instance\", pool=~\"$pool\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pool Growth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "delta(zfs_pool_allocated_bytes{instance=\"$instance\", pool=~\"$pool\"}[$__rate_interval])",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Space %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "zfs_pool_allocated_bytes{instance=~\"$instance\", pool=~\"$pool\"} / zfs_pool_size_bytes",
     "legendFormat": "{{pool}} - Used"
    }
   ]
  },
  {
   "title": "Pool Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "zfs_pool_allocated_bytes{instance=~\"$instance\", pool=~\"$pool\"}",
     "legendFormat": "{{pool}} - Used"
    },
    {
     "expr": "zfs_pool_free_bytes{instance=~\"$instance\", pool=~\"$pool\"}",
     "legendFormat": "{{pool}} - Free"
    }
   ]
  },
  {
   "title": "Pool Speed (logical)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (zpool) (rate(node_zfs_zpool_dataset_nwritten{instance=~\"$instance\", zpool=~\"$pool\"}[$__rate_interval]))",
     "legendFormat": "{{zpool}} write"
    },
    {
     "expr": "sum by (zpool) (rate(node_zfs_zpool_dataset_nread{instance=\"$instance\", zpool=~\"$pool\"}[$__rate_interval]))",
     "legendFormat": "{{zpool}} read"
    },
    {
     "expr": "sum by (zpool) (rate(zfs_pool_scan_processed_bytes{instance=\"$instance\", zpool=~\"$pool\"}[$__rate_interval]))",
     "legendFormat": "{{zpool}} scan"
    }
   ]
  },
  {
   "title": "Pool Speed (vdev)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (zpool) (rate(zfs_vdev_bytes{instance=~\"$instance\", zpool=~\"$pool\", type=\"write\"}[$__rate_interval]))",
     "legendFormat": "{{zpool}} write"
    },
    {
     "expr": "sum by (zpool) (rate(zfs_vdev_bytes{instance=\"$instance\", zpool=~\"$pool\", type=\"read\"}[$__rate_interval]))",
     "legendFormat": "{{zpool}} read"
    }
   ]
  },
  {
   "title": "Pool IOPS (logical)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (zpool) (rate(node_zfs_zpool_dataset_writes{instance=~\"$instance\", zpool=~\"$pool\"}[$__rate_interval]))",
     "legendFormat": "{{zpool}} writes"
    },
    {
     "expr": "sum by (zpool) (rate(node_zfs_zpool_dataset_reads{instance=\"$instance\", zpool=~\"$pool\"}[$__rate_interval]))",
     "legendFormat": "{{zpool}} reads"
    }
   ]
  },
  {
   "title": "Pool IOPS (vdev)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (zpool) (rate(zfs_vdev_ops{instance=~\"$instance\", zpool=~\"$pool\", type=\"write\"}[$__rate_interval]))",
     "legendFormat": "{{zpool}} writes"
    },
    {
     "expr": "sum by (zpool) (rate(zfs_vdev_ops{instance=\"$instance\", zpool=~\"$pool\", type=\"read\"}[$__rate_interval]))",
     "legendFormat": "{{zpool}} reads"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(zfs_pool_errors{instance=~\"$instance\", zpool=~\"$pool\"}[$__rate_interval])",
     "legendFormat": "{{zpool}} errors"
    },
    {
     "expr": "rate(zfs_pool_scan_errors{instance=~\"$instance\", zpool=~\"$pool\"}[$__rate_interval])",
     "legendFormat": "{{zpool}} scan errors"
    }
   ]
  }
 ]
}