{
 "title": "ZFS vdev disks",
 "description": "ZFS monitoring dashboard",
 "tags": [
  "ZFS",
  "node"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(zfs_pool_vdevs{}[$__range])))"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(group by(instance) (last_over_time(zfs_pool_vdevs{location=~\"$location\"}[$__range])))"
    }
   },
   {
    "name": "pool",
    "query": {
     "query": "query_result(group by(zpool) (last_over_time(zfs_pool_vdevs{instance=~\"$instance\"}[$__range])))"
    }
   },
   {
    "name": "vdev",
    "query": {
     "query": "query_result(group by(vdev) (last_over_time(zfs_vdev_ashift_configured{instance=~\"$instance\", zpool=~\"$pool\"}[$__range])))"
    }
   },
   {
    "name": "disk",
    "query": {
     "query": "query_result(label_replace(last_over_time(zfs_vdev_ashift_configured{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\"}[$__range]), \"disk\", \"$1\", \"path\", \".*/([^/]*)\"))"
    }
   }
  ]
 },
 "panels": [
  { "title": "info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "pool list",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max by(instance, zpool, state) (max_over_time(zfs_pool_size_bytes{instance=~\"$instance\", pool=~\"$pool\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, zpool) (last_over_time(zfs_pool_vdevs{instance=~\"$instance\", zpool=~\"$pool\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, zpool) (last_over_time(zfs_pool_errors{instance=~\"$instance\", zpool=~\"$pool\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "physical devices",
   "type": "table",
   "gridPos": { "h": 14, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "max by(instance, zpool, vdev, path) (max_over_time(zfs_vdev_devsize_replaceable{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, zpool, vdev, path) (max_over_time(zfs_vdev_physical_capacity_bytes{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, zpool, vdev, path) (max_over_time(zfs_vdev_ashift_configured{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, zpool, vdev, path) (max_over_time(zfs_vdev_errors{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, zpool, vdev, path) (\r\n  max_over_time(zfs_vdev_trim_errors{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\"}[$__range])\r\n  and\r\n  (max_over_time(zfs_vdev_trim_unsupported{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\"}[$__range]) == 0)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notes",
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 2, "y": 9 },
   "options": {
    "content": "L2ARC vdev is not tracked by the exporter,\r\nand ZFS doesn't expose separate per-pool statistics for L2ARC.\r\n"
   }
  },
  {
   "title": "pool state",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "max by(instance, zpool) (\r\n(max_over_time(node_zfs_zpool_state{instance=~\"$instance\", zpool=~\"$pool\", state=\"online\"}[$__interval]) == 1) * 2\r\nor\r\n(max_over_time(node_zfs_zpool_state{instance=~\"$instance\", zpool=~\"$pool\", state=\"offline\"}[$__interval]) == 1) * 3\r\nor\r\n(max_over_time(node_zfs_zpool_state{instance=~\"$instance\", zpool=~\"$pool\", state=\"removed\"}[$__interval]) == 1) * 4\r\nor\r\n(max_over_time(node_zfs_zpool_state{instance=~\"$instance\", zpool=~\"$pool\", state=\"degraded\"}[$__interval]) == 1) * 5\r\nor\r\n(max_over_time(node_zfs_zpool_state{instance=~\"$instance\", zpool=~\"$pool\", state=\"faulted\"}[$__interval]) == 1) * 6\r\nor\r\n(max_over_time(node_zfs_zpool_state{instance=~\"$instance\", zpool=~\"$pool\", state=\"suspended\"}[$__interval]) == 1) * 7\r\nor\r\n(max_over_time(node_zfs_zpool_state{instance=~\"$instance\", zpool=~\"$pool\", state=\"unavail\"}[$__interval]) == 1) * 8\r\n)",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "errors: read",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "max by(instance, zpool, vdev, path, type) (\r\n  label_replace(\r\n    rate(zfs_vdev_errors{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\", type=\"read\"}[$__rate_interval])\r\n    , \"path\", \"$1\", \"path\", \".*/([^/]*)\"\r\n  )\r\n) * $__interval_ms / 1000",
     "legendFormat": "{{zpool}}/{{vdev}}/{{path}}"
    }
   ]
  },
  {
   "title": "errors: write",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "max by(instance, zpool, vdev, path, type) (\r\n  label_replace(\r\n    rate(zfs_vdev_errors{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\", type=\"write\"}[$__rate_interval])\r\n    , \"path\", \"$1\", \"path\", \".*/([^/]*)\"\r\n  )\r\n) * $__interval_ms / 1000",
     "legendFormat": "{{zpool}}/{{vdev}}/{{path}}"
    }
   ]
  },
  {
   "title": "disk state",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "min by(instance, zpool, vdev, path) (label_replace(min_over_time(zfs_vdev_state{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\"}[$__interval]), \"path\", \"$1\", \"path\", \".*/([^/]*)\"))",
     "legendFormat": "{{zpool}}/{{vdev}}/{{path}}"
    }
   ]
  },
  {
   "title": "errors: checksum",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "max by(instance, zpool, vdev, path, type) (\r\n  label_replace(\r\n    rate(zfs_vdev_errors{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\", type=\"checksum\"}[$__rate_interval])\r\n    , \"path\", \"$1\", \"path\", \".*/([^/]*)\"\r\n  )\r\n) * $__interval_ms / 1000",
     "legendFormat": "{{zpool}}/{{vdev}}/{{path}}"
    }
   ]
  },
  {
   "title": "errors: initialize",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "max by(instance, zpool, vdev, path, type) (\r\n  label_replace(\r\n    rate(zfs_vdev_errors{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\", type=\"initialize\"}[$__rate_interval])\r\n    , \"path\", \"$1\", \"path\", \".*/([^/]*)\"\r\n  )\r\n) * $__interval_ms / 1000",
     "legendFormat": "{{zpool}}/{{vdev}}/{{path}}"
    }
   ]
  },
  {
   "title": "fragmentation %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "min by(instance, zpool, vdev, path) (label_replace(\r\n  max_over_time(zfs_vdev_fragmentation{instance=~\"$instance\", zpool=~\"$pool\", vdev=~\"$vdev\", path=~\"$disk\"}[$__interval])\r\n, \"path\", \"$1\", \"path\", \".*/([^/]*)\"))",
     "legendFormat": "{{zpool}}/{{vdev}}/{{path}}"
    }
   ]
  },
  {
   "title": "errors: trim",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "max by(instance, zpool, vdev, path, type) (\r\n  label_replace(\r\n    rate(zfs_vdev_trim_errors{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\"}[$__rate_interval])\r\n    , \"path\", \"$1\", \"path\", \".*/([^/]*)\"\r\n  )\r\n) * $__interval_ms / 1000",
     "legendFormat": "{{zpool}}/{{vdev}}/{{path}}"
    }
   ]
  },
  {
   "title": "scan: resilver write rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "max by(instance, zpool, vdev, path) (label_replace(rate(zfs_vdev_scan_processed_bytes{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\"}[$__rate_interval]), \"path\", \"$1\", \"path\", \".*/([^/]*)\"))",
     "legendFormat": "{{zpool}}/{{vdev}}/{{path}}"
    }
   ]
  },
  { "title": "read/write", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "read speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "max by(instance, zpool, vdev, path) (label_replace(rate(zfs_vdev_bytes{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\", type=\"read\"}[$__rate_interval]), \"path\", \"$1\", \"path\", \".*/([^/]*)\"))",
     "legendFormat": "{{zpool}}/{{vdev}}/{{path}}"
    }
   ]
  },
  {
   "title": "write speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "max by(instance, zpool, vdev, path) (label_replace(rate(zfs_vdev_bytes{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\", type=\"write\"}[$__rate_interval]), \"path\", \"$1\", \"path\", \".*/([^/]*)\"))",
     "legendFormat": "{{zpool}}/{{vdev}}/{{path}}"
    }
   ]
  },
  {
   "title": "read IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "max by(instance, zpool, vdev, path) (label_replace(rate(zfs_vdev_ops{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\", type=\"read\"}[$__rate_interval]), \"path\", \"$1\", \"path\", \".*/([^/]*)\"))",
     "legendFormat": "{{zpool}}/{{vdev}}/{{path}}"
    }
   ]
  },
  {
   "title": "write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "max by(instance, zpool, vdev, path) (label_replace(rate(zfs_vdev_ops{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\", type=\"write\"}[$__rate_interval]), \"path\", \"$1\", \"path\", \".*/([^/]*)\"))",
     "legendFormat": "{{zpool}}/{{vdev}}/{{path}}"
    }
   ]
  },
  {
   "title": "read latency p99 (zio)",
   "type": "timeseries",
   "description": "Includes queue and disk read itself. Missing if there were no operation.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(instance, zpool, vdev, path) (label_replace(max_over_time(zfs_vdev_zio_latency_total_bucket:quantile_irate{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\", type=\"read\", quantile=\"0.99\"}[$__rate_interval]), \"path\", \"$1\", \"path\", \".*/([^/]*)\"))",
     "legendFormat": "{{zpool}}/{{vdev}}/{{path}}"
    }
   ]
  },
  {
   "title": "write latency p99 (zio)",
   "type": "timeseries",
   "description": "includes queue and disk read itself. Missing if there were no operation.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(instance, zpool, vdev, path) (label_replace(max_over_time(zfs_vdev_zio_latency_total_bucket:quantile_irate{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\", type=\"write\", quantile=\"0.99\"}[$__rate_interval]), \"path\", \"$1\", \"path\", \".*/([^/]*)\"))",
     "legendFormat": "{{zpool}}/{{vdev}}/{{path}}"
    }
   ]
  },
  {
   "title": "read latency p99 (disk)",
   "type": "timeseries",
   "description": "includes only disk operation. Missing if there were no operation.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(instance, zpool, vdev, path) (label_replace(max_over_time(zfs_vdev_latency_disk_bucket:quantile_irate{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\", type=\"read\", quantile=\"0.99\"}[$__rate_interval]), \"path\", \"$1\", \"path\", \".*/([^/]*)\"))",
     "legendFormat": "{{zpool}}/{{vdev}}/{{path}}"
    }
   ]
  },
  {
   "title": "write latency p99 (disk)",
   "type": "timeseries",
   "description": "includes only disk operation. Missing if there were no operation.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(instance, zpool, vdev, path) (label_replace(max_over_time(zfs_vdev_latency_disk_bucket:quantile_irate{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\", type=\"write\", quantile=\"0.99\"}[$__rate_interval]), \"path\", \"$1\", \"path\", \".*/([^/]*)\"))",
     "legendFormat": "{{zpool}}/{{vdev}}/{{path}}"
    }
   ]
  },
  { "title": "trim", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "trim state",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "max by(instance, zpool, vdev, path) (label_replace(\r\n  ((min_over_time(zfs_vdev_trim_unsupported{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\"}[$__interval]) == 1) * 10)\r\n  or\r\n  min_over_time(zfs_vdev_trim_state{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\"}[$__interval])\r\n  , \"path\", \"$1\", \"path\", \".*/([^/]*)\")\r\n)",
     "legendFormat": "{{zpool}}/{{vdev}}/{{path}}"
    }
   ]
  },
  {
   "title": "trim: completed %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "min by (instance, zpool, vdev, path) (\r\nlabel_replace(\r\n  avg_over_time(zfs_vdev_trim_processed_ratio{instance=~\"$instance\", zpool=~\"$pool\", path=~\"$disk\"}[$__interval])\r\n, \"path\", \"$1\", \"path\", \".*/([^/]*)\")\r\n)",
     "legendFormat": "{{zpool}}/{{vdev}}/{{path}}"
    }
   ]
  },
  {
   "title": "trim last action time (start/stop) (ago)",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "$__to / 1000 - max by(zpool, vdev, path) (\r\n  label_replace(\r\n    max_over_time(zfs_vdev_trim_action_time{instance=~\"$instance\", zpool=~\"$pool\", vdev=~\"$vdev\", path=~\"$disk\"}[$__interval]) != 0\r\n    , \"path\", \"$1\", \"path\", \".*/([^/]*)\"\r\n  )\r\n)",
     "legendFormat": "{{zpool}}/{{vdev}}/{{path}}"
    }
   ]
  },
  {
   "title": "trim process rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance, zpool, vdev, path) (label_replace(\r\n  rate(zfs_vdev_trim_processed_bytes{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\"}[$__rate_interval])\r\n  and\r\n  (min_over_time(zfs_vdev_trim_unsupported{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\", vdev=~\"$vdev\", path=~\"$disk\"}[$__interval]) == 0)\r\n  , \"path\", \"$1\", \"path\", \".*/([^/]*)\")\r\n)",
     "legendFormat": "{{zpool}}/{{vdev}}/{{path}}"
    }
   ]
  },
  {
   "title": "trim estimated size",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(zpool, vdev, path) (\r\n  label_replace(\r\n    max_over_time(zfs_vdev_trim_estimated_bytes{instance=~\"$instance\", zpool=~\"$pool\", path=~\"$disk\"}[$__interval]) != 0\r\n    , \"path\", \"$1\", \"path\", \".*/([^/]*)\"\r\n  )\r\n)",
     "legendFormat": "{{zpool}}/{{vdev}}/{{path}}"
    }
   ]
  },
  {
   "title": "trim: estimated remaining time",
   "type": "timeseries",
   "description": "Empty, unless trim ran in time range. Requires a custom recording rule",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(instance, zpool, vdev, path) (label_replace(\r\n  max_over_time(zfs_vdev_trim_estimated_remaining_seconds{instance=~\"$instance\", zpool=~\"$pool\", path=~\"$disk\"}[$__interval])\r\n, \"path\", \"$1\", \"path\", \".*/([^/]*)\")\r\n)",
     "legendFormat": "{{zpool}}/{{vdev}}/{{path}}"
    }
   ]
  }
 ]
}