{
 "title": "ZFS Pool Overview",
 "description": "ZFS monitoring dashboard",
 "tags": [
  "ZFS",
  "node"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(zfs_exporter_build_info{}[$__range])))"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(group by(instance) (last_over_time(zfs_exporter_build_info{location=~\"$location\"}[$__range])))"
    }
   },
   { "name": "pool_filter" },
   {
    "name": "pool",
    "query": {
     "query": "query_result(group by(pool) (last_over_time(zfs_dataset_used_bytes{instance=~\"$instance\", pool=~\".*($pool_filter).*\"}[$__range])))"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pool List",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg by(instance, pool) (\r\n  avg_over_time(zfs_pool_free_bytes{instance=~\"$instance\", pool=~\"$pool\"}[$__range])\r\n  /\r\n  avg_over_time(zfs_pool_size_bytes{instance=~\"$instance\", pool=~\"$pool\"}[$__range])\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, pool) (label_replace(increase(zfs_pool_errors{instance=~\"$instance\", zpool=~\"$pool\"}[$__range]), \"pool\", \"$1\", \"zpool\", \"(.*)\"))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, pool) (\r\n  max_over_time(zfs_dataset_creation_timestamp{instance=~\"$instance\", pool=~\"$pool\"}[$__range])\r\n  or\r\n  # zfs_dataset_creation was used before official support for creation was added\r\n  max_over_time(zfs_dataset_creation{instance=~\"$instance\", pool=~\"$pool\"}[$__range])\r\n) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "exporter version history",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "group by(instance, version) (label_replace(last_over_time(zfs_exporter_build_info{instance=~\"$instance\"}[$__interval]), \"version\", \"<missing>\", \"version\", \"\"))\r\nor on()\r\n(\r\n  vector(0) unless on() last_over_time(zfs_exporter_build_info{instance=~\"$instance\"}[$__interval])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pool state",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max by(instance, zpool) (\r\n(max_over_time(node_zfs_zpool_state{instance=~\"$instance\", zpool=~\"$pool\", state=\"online\"}[$__interval]) == 1) * 2\r\nor\r\n(max_over_time(node_zfs_zpool_state{instance=~\"$instance\", zpool=~\"$pool\", state=\"offline\"}[$__interval]) == 1) * 3\r\nor\r\n(max_over_time(node_zfs_zpool_state{instance=~\"$instance\", zpool=~\"$pool\", state=\"removed\"}[$__interval]) == 1) * 4\r\nor\r\n(max_over_time(node_zfs_zpool_state{instance=~\"$instance\", zpool=~\"$pool\", state=\"degraded\"}[$__interval]) == 1) * 5\r\nor\r\n(max_over_time(node_zfs_zpool_state{instance=~\"$instance\", zpool=~\"$pool\", state=\"faulted\"}[$__interval]) == 1) * 6\r\nor\r\n(max_over_time(node_zfs_zpool_state{instance=~\"$instance\", zpool=~\"$pool\", state=\"suspended\"}[$__interval]) == 1) * 7\r\nor\r\n(max_over_time(node_zfs_zpool_state{instance=~\"$instance\", zpool=~\"$pool\", state=\"unavail\"}[$__interval]) == 1) * 8\r\n)",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "pool size",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(instance, pool) (max_over_time(zfs_pool_size_bytes{instance=~\"$instance\", pool=~\"$pool\"}[$__interval]))",
     "legendFormat": "{{instance}}/{{pool}}"
    }
   ]
  },
  {
   "title": "last loaded (ago)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "$__to / 1000 - max by(instance, zpool) (max_over_time(zfs_pool_load_time_seconds{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]) != 0)",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "new errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(instance, zpool) (rate(zfs_pool_errors{instance=~\"$instance\", zpool=~\"$pool\"}[$__rate_interval])) * $__interval_ms",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "created (ago)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "# max_over_time to get the newest creation date in case pool with the same name was recreated\r\n# using name=~\"$pool\" selects root dataset of apool, which is always the oldest dataset\r\n$__to / 1000 - min by(instance, pool) (\r\n  max_over_time(zfs_dataset_creation_timestamp{instance=~\"$instance\", pool=~\"$pool\", name=~\"$pool\"}[$__interval])\r\n  or\r\n  # zfs_dataset_creation was used before official support for creation was added\r\n  max_over_time(zfs_dataset_creation{instance=~\"$instance\", pool=~\"$pool\", name=~\"$pool\"}[$__interval])\r\n)",
     "legendFormat": "{{instance}}/{{pool}}"
    }
   ]
  },
  {
   "title": "fragmentation %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(instance, pool) (avg_over_time(zfs_pool_fragmentation_ratio{instance=~\"$instance\", pool=~\"$pool\"}[$__interval]))",
     "legendFormat": "{{instance}}/{{pool}}"
    }
   ]
  },
  {
   "title": "Notes",
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 33 },
   "options": {
    "content": "zfs_exporter for vdevs doesn't have info about l2arc devices,\r\nso vdev read/write speed includes only main disks."
   }
  },
  {
   "title": "dedup ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "max by(instance, pool) (avg_over_time(zfs_pool_deduplication_ratio{instance=~\"$instance\", pool=~\"$pool\"}[$__interval]))",
     "legendFormat": "{{instance}}/{{pool}}"
    }
   ]
  },
  { "title": "Space", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "used %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(instance, pool) (\r\nmax_over_time(zfs_pool_allocated_bytes{instance=~\"$instance\", pool=~\"$pool\"}[$__interval])\r\n/\r\nmax_over_time(zfs_pool_size_bytes{instance=~\"$instance\", pool=~\"$pool\"}[$__interval])\r\n)",
     "legendFormat": "{{instance}}/{{pool}}"
    }
   ]
  },
  {
   "title": "usage delta",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(instance, pool) (delta(zfs_pool_allocated_bytes{instance=~\"$instance\", pool=~\"$pool\"}[$__rate_interval])) * ($__interval_ms / $__rate_interval_ms)",
     "legendFormat": "{{instance}}/{{pool}}"
    }
   ]
  },
  {
   "title": "used bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(instance, pool) (max_over_time(zfs_pool_allocated_bytes{instance=~\"$instance\", pool=~\"$pool\"}[$__interval]))",
     "legendFormat": "{{instance}}/{{pool}}"
    }
   ]
  },
  {
   "title": "free bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "min by(instance, pool) (min_over_time(zfs_pool_free_bytes{instance=~\"$instance\", pool=~\"$pool\"}[$__interval]))",
     "legendFormat": "{{instance}}/{{pool}}"
    }
   ]
  },
  { "title": "Speed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "read rate (logical)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (instance, zpool) (rate(node_zfs_zpool_dataset_nread{instance=~\"$instance\", zpool=~\"$pool\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "write rate (logical)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (instance, zpool) (rate(node_zfs_zpool_dataset_nwritten{instance=~\"$instance\", zpool=~\"$pool\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "read rate (vdev)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance, zpool) (rate(zfs_vdev_bytes{instance=~\"$instance\", zpool=~\"$pool\", type=\"read\", vdev=\"root\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "write rate (vdev)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance, zpool) (rate(zfs_vdev_bytes{instance=~\"$instance\", zpool=~\"$pool\", type=\"write\", vdev=\"root\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "scrub: approx read rate (vdev) divided by parity coefficient, without scrub",
   "type": "timeseries",
   "description": "empty when scrub is not running; draid is not supported",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance, zpool) (\r\n  # single-device coefficient: 1\r\n  rate(zfs_vdev_bytes{instance=~\"$instance\", zpool=~\"$pool\", type=\"read\", path!=\"\", vdev=~\"disk-.*\"}[$__rate_interval])\r\n  or\r\n  # mirror coefficient: 1/count\r\n  (\r\n    rate(zfs_vdev_bytes{instance=~\"$instance\", zpool=~\"$pool\", type=\"read\", path=\"\", vdev=~\"mirror-.*\"}[$__rate_interval])\r\n    / on(instance, zpool, vdev) group_left()\r\n    avg by(instance, zpool, vdev) (avg_over_time(zfs_vdev_children{instance=~\"$instance\", zpool=~\"$pool\", vdev=~\"mirror-.*\"}[$__rate_interval]))\r\n  )\r\n  or\r\n  # raid-z coefficient: (count-1)/count\r\n  (\r\n    rate(zfs_vdev_bytes{instance=~\"$instance\", zpool=~\"$pool\", type=\"read\", path=\"\", vdev=~\"raidz-.*\"}[$__rate_interval])\r\n    * on(instance, zpool, vdev) group_left()\r\n    avg by(instance, zpool, vdev) (1 - 1 / avg_over_time(zfs_vdev_children{instance=~\"$instance\", zpool=~\"$pool\", vdev=~\"raidz-.*\"}[$__rate_interval]))\r\n  )\r\n  or\r\n  # raid-z2 coefficient: (count-2)/count\r\n  (\r\n    rate(zfs_vdev_bytes{instance=~\"$instance\", zpool=~\"$pool\", type=\"read\", path=\"\", vdev=~\"raidz2-.*\"}[$__rate_interval])\r\n    * on(instance, zpool, vdev) group_left()\r\n    avg by(instance, zpool, vdev) (1 - 2 / avg_over_time(zfs_vdev_children{instance=~\"$instance\", zpool=~\"$pool\", vdev=~\"raidz2-.*\"}[$__rate_interval]))\r\n  )\r\n  or\r\n  # raid-z3 coefficient: (count-3)/count\r\n  (\r\n    rate(zfs_vdev_bytes{instance=~\"$instance\", zpool=~\"$pool\", type=\"read\", path=\"\", vdev=~\"raidz2-.*\"}[$__rate_interval])\r\n    * on(instance, zpool, vdev) group_left()\r\n    avg by(instance, zpool, vdev) (1 - 3 / avg_over_time(zfs_vdev_children{instance=~\"$instance\", zpool=~\"$pool\", vdev=~\"raidz2-.*\"}[$__rate_interval]))\r\n  )\r\n)\r\n-\r\nsum by (instance, zpool) (rate(zfs_pool_scan_issued_bytes{instance=~\"$instance\", zpool=~\"$pool\"}[$__rate_interval]))\r\nand\r\n(\r\n  min by(instance, zpool) (min_over_time(zfs_pool_scan_func{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval])) == 1\r\n  and\r\n  min by(instance, zpool) (min_over_time(zfs_pool_scan_state{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval])) == 1\r\n)",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "approx write rate (vdev) divided by parity coefficient",
   "type": "timeseries",
   "description": "draid is not supported",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance, zpool) (\r\n  # single-device coefficient: 1\r\n  rate(zfs_vdev_bytes{instance=~\"$instance\", zpool=~\"$pool\", type=\"write\", path!=\"\", vdev=~\"disk-.*\"}[$__rate_interval])\r\n  or\r\n  # mirror coefficient: 1/count\r\n  (\r\n    rate(zfs_vdev_bytes{instance=~\"$instance\", zpool=~\"$pool\", type=\"write\", path=\"\", vdev=~\"mirror-.*\"}[$__rate_interval])\r\n    / on(instance, zpool, vdev) group_left()\r\n    avg by(instance, zpool, vdev) (avg_over_time(zfs_vdev_children{instance=~\"$instance\", zpool=~\"$pool\", vdev=~\"mirror-.*\"}[$__rate_interval]))\r\n  )\r\n  or\r\n  # raid-z coefficient: (count-1)/count\r\n  (\r\n    rate(zfs_vdev_bytes{instance=~\"$instance\", zpool=~\"$pool\", type=\"write\", path=\"\", vdev=~\"raidz-.*\"}[$__rate_interval])\r\n    * on(instance, zpool, vdev) group_left()\r\n    avg by(instance, zpool, vdev) (1 - 1 / avg_over_time(zfs_vdev_children{instance=~\"$instance\", zpool=~\"$pool\", vdev=~\"raidz-.*\"}[$__rate_interval]))\r\n  )\r\n  or\r\n  # raid-z2 coefficient: (count-2)/count\r\n  (\r\n    rate(zfs_vdev_bytes{instance=~\"$instance\", zpool=~\"$pool\", type=\"write\", path=\"\", vdev=~\"raidz2-.*\"}[$__rate_interval])\r\n    * on(instance, zpool, vdev) group_left()\r\n    avg by(instance, zpool, vdev) (1 - 2 / avg_over_time(zfs_vdev_children{instance=~\"$instance\", zpool=~\"$pool\", vdev=~\"raidz2-.*\"}[$__rate_interval]))\r\n  )\r\n  or\r\n  # raid-z3 coefficient: (count-3)/count\r\n  (\r\n    rate(zfs_vdev_bytes{instance=~\"$instance\", zpool=~\"$pool\", type=\"write\", path=\"\", vdev=~\"raidz2-.*\"}[$__rate_interval])\r\n    * on(instance, zpool, vdev) group_left()\r\n    avg by(instance, zpool, vdev) (1 - 3 / avg_over_time(zfs_vdev_children{instance=~\"$instance\", zpool=~\"$pool\", vdev=~\"raidz2-.*\"}[$__rate_interval]))\r\n  )\r\n)",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "resilver: approx read rate (vdev), without resilver",
   "type": "timeseries",
   "description": "empty when resilver is not running; draid is not supported",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance, zpool) (\r\n  rate(zfs_vdev_bytes{instance=~\"$instance\", zpool=~\"$pool\", type=\"read\", vdev=\"root\"}[$__rate_interval])\r\n)\r\n-\r\nsum by (instance, zpool) (rate(zfs_pool_scan_issued_bytes{instance=~\"$instance\", zpool=~\"$pool\"}[$__rate_interval]))\r\nand\r\n(\r\n  min by(instance, zpool) (min_over_time(zfs_pool_scan_func{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval])) == 2\r\n  and\r\n  min by(instance, zpool) (min_over_time(zfs_pool_scan_state{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval])) == 1\r\n)",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "resilver: approx write rate (vdev), without resilver",
   "type": "timeseries",
   "description": "empty when resilver is not running; draid is not supported",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance, zpool) (\r\n  rate(zfs_vdev_bytes{instance=~\"$instance\", zpool=~\"$pool\", type=\"write\", vdev=\"root\"}[$__rate_interval])\r\n)\r\n-\r\nsum by (instance, zpool) (rate(zfs_pool_scan_issued_bytes{instance=~\"$instance\", zpool=~\"$pool\"}[$__rate_interval]))\r\nand\r\n(\r\n  min by(instance, zpool) (min_over_time(zfs_pool_scan_func{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval])) == 2\r\n  and\r\n  min by(instance, zpool) (min_over_time(zfs_pool_scan_state{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval])) == 1\r\n)",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  { "title": "IOPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "read IOPS (logical)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(instance, zpool) (rate(node_zfs_zpool_dataset_reads{instance=~\"$instance\", zpool=~\"$pool\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "write IOPS (logical)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(instance, zpool) (rate(node_zfs_zpool_dataset_writes{instance=~\"$instance\", zpool=~\"$pool\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "read IOPS (vdev)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(instance, zpool) (rate(zfs_vdev_ops{instance=~\"$instance\", zpool=~\"$pool\", type=\"read\", vdev=\"root\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "write IOPS (vdev)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(instance, zpool) (rate(zfs_vdev_ops{instance=~\"$instance\", zpool=~\"$pool\", type=\"write\", vdev=\"root\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  { "title": "trim", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "trim state",
   "type": "state-timeline",
   "description": "TRIM is performed per-vdev. This graph is an aggregation that show \"the worst\" TRIM state across all disks in a pool.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "targets": [
    {
     "expr": "min by(instance, zpool) (\r\n  min_over_time(zfs_vdev_trim_state{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\"}[$__interval])\r\n  and\r\n  (min_over_time(zfs_vdev_trim_unsupported{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\"}[$__interval]) == 0)\r\n)\r\n+\r\n# distinguish if not all devices have the same trim state\r\n(\r\n  ((stdvar by(instance, zpool) (\r\n    (min_over_time(zfs_vdev_trim_state{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\"}[$__interval]))\r\n    and\r\n    (min_over_time(zfs_vdev_trim_unsupported{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\"}[$__interval]) == 0)\r\n  ) == bool 0) * 10)\r\n)\r\nor\r\nmin by(instance, zpool) ((min_over_time(zfs_vdev_trim_unsupported{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\"}[$__interval]) == bool 1) + 100)",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "trim processed bytes rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance, zpool) (\r\nrate(zfs_vdev_trim_processed_bytes{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\"}[$__rate_interval])\r\nand\r\n(min_over_time(zfs_vdev_trim_unsupported{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\"}[$__interval]) == 0)\r\n)",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "last trim action time (start/stop)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "targets": [
    {
     "expr": "max by(instance, zpool) (max_over_time(zfs_vdev_trim_action_time{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]) != 0) * 1000",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "trim: completed %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "min by (instance, zpool) (\r\n  (\r\n    max_over_time(zfs_vdev_trim_processed_bytes{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval])\r\n    /\r\n    (max_over_time(zfs_vdev_trim_estimated_bytes{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]) != 0)\r\n  )\r\n  and\r\n  (\r\n    (min_over_time(zfs_vdev_trim_state{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\"}[$__rate_interval]) == 1)\r\n    or\r\n    (max_over_time(zfs_vdev_trim_state{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\"}[$__rate_interval]) != 4)\r\n  )\r\n)",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "last trim action time (start/stop) (ago)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "$__to / 1000 - max by(instance, zpool) (max_over_time(zfs_vdev_trim_action_time{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]) != 0)",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "trim: estimated remaining time",
   "type": "timeseries",
   "description": "Empty, unless trim ran in time range",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(instance, zpool) (max_over_time(zfs_vdev_trim_estimated_remaining_seconds{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]) != Inf)",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "trim estimated size",
   "type": "state-timeline",
   "description": "size of the relevant data in the pool when scan was started",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(instance, zpool) (max_over_time(zfs_vdev_trim_estimated_bytes{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]) != 0)",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "trim errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(instance, zpool) (max_over_time(zfs_vdev_trim_errors{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]))",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  { "title": "scan state (scrub/resilver)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 143 } },
  {
   "title": "notes",
   "type": "text",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 144 },
   "options": {
    "content": "Scan info is empty for pools\nthat have never run\nscrub or resilver\nin their lifetime.\n\n`examined` is about\ngathering metadata for scan.\n\n`issued` is actually\nreading/writing data."
   }
  },
  {
   "title": "scan state",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 149 },
   "targets": [
    {
     "expr": "# scan is finished or cancelled, show as is\r\nmin by(instance, zpool) (min_over_time(zfs_pool_scan_state{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]) > 1)\r\nor\r\n# scan is running but paused\r\n(group by(instance, zpool) (max_over_time(zfs_pool_scan_scrub_pause{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]) != 0) + 20)\r\nor\r\n# scan is running: show function (scrub/resilver)\r\n(\r\n  (\r\n    min by(instance, zpool) (min_over_time(zfs_pool_scan_func{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval])) + 10\r\n    +\r\n    # distinguish examine and issue stages\r\n    max by(instance, zpool) (max_over_time(zfs_pool_scan_pass_examined_bytes{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]) != bool 0) * 5\r\n  )\r\n  and\r\n  min by(instance, zpool) (min_over_time(zfs_pool_scan_state{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval])) == 1\r\n)\r\nor\r\n# pool was never scanned\r\nmin by(instance, zpool) ((min_over_time(zfs_pool_scan_state{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]) == 0) + 30)\r\nor\r\n# catch all unexpected values\r\nmin by(instance, zpool) (min_over_time(zfs_pool_scan_state{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]) + 40)",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "scan end time (ago)",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "$__to / 1000 - max by(instance, zpool) (max_over_time(zfs_pool_scan_end_time_seconds{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]) != 0)",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "last scan stage duration",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(instance, zpool) (\r\n  (\r\n    max_over_time(zfs_pool_scan_end_time_seconds{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval])\r\n    > on(instance, zpool) group_left()\r\n    max by(instance, zpool) (max_over_time(zfs_pool_load_time_seconds{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]))\r\n  )\r\n  -\r\n  max_over_time(zfs_pool_scan_start_time_seconds{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval])\r\n) >= 0\r\nor\r\nmax by(instance, zpool) (\r\n  max by(instance, zpool) (max_over_time(zfs_pool_scan_pass_start_seconds{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]))\r\n  -\r\n  max by(instance, zpool) (\r\n    # zfs_pool_load_time_seconds has different labels, so this max works as union\r\n    max_over_time(zfs_pool_load_time_seconds{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval])\r\n    or\r\n    max_over_time(zfs_pool_scan_start_time_seconds{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval])\r\n  )\r\n)",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "scan start time (ago)",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "$__to / 1000 - max by(instance, zpool) (max_over_time(zfs_pool_scan_start_time_seconds{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]))",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "scan: estimated size",
   "type": "state-timeline",
   "description": "size of the relevant data in the pool when scan was started",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(instance, zpool) (max_over_time(zfs_pool_scan_to_examine_bytes{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]))",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "scan pass start time (ago)",
   "type": "state-timeline",
   "description": "can be used to detect scan examine stage ending, also shows a brief scan when pool is imported",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "$__to / 1000 - max by(instance, zpool) (max_over_time(zfs_pool_scan_pass_start_seconds{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]))",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  { "title": "scan stats (scrub/resilver)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 176 } },
  {
   "title": "scan: examined: estimated remaining time",
   "type": "timeseries",
   "description": "empty if examine stage of scan was not running",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(instance, zpool) (\r\n  avg_over_time(zfs_pool_scan_examine_estimated_remaining_seconds{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]) != Inf\r\n  and\r\n  (max_over_time(zfs_pool_scan_pass_examined_bytes{instance=~\"$instance\", zpool=~\"$pool\"}[$__rate_interval]) != 0)\r\n)",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "scan: examine completed %",
   "type": "timeseries",
   "description": "empty if examine stage of scan was not running",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (instance, zpool) (\r\n  (\r\n    min_over_time(zfs_pool_scan_examined_bytes{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval])\r\n    /\r\n    (avg_over_time(zfs_pool_scan_to_examine_bytes{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]) != 0)\r\n  )\r\n  and\r\n  (max_over_time(zfs_pool_scan_pass_examined_bytes{instance=~\"$instance\", zpool=~\"$pool\"}[$__rate_interval]) != 0)\r\n)",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "scan: issued: estimated remaining time",
   "type": "timeseries",
   "description": "Empty, unless scan ran in time range",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(instance, zpool) (avg_over_time(zfs_pool_scan_issue_estimated_remaining_seconds{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]) != Inf)",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "scan: issued completed %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (instance, zpool) (\r\n  min_over_time(zfs_pool_scan_issued_bytes{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval])\r\n  /\r\n  (avg_over_time(zfs_pool_scan_to_examine_bytes{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]) != 0)\r\n)\r\nand\r\nmin by(instance, zpool) (min_over_time(zfs_pool_scan_state{instance=~\"$instance\", zpool=~\"$pool\"}[$__rate_interval]) == 1)",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "scan: resilver write rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (instance, zpool) (rate(zfs_pool_scan_processed_bytes{instance=~\"$instance\", zpool=~\"$pool\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "scan: issued rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (instance, zpool) (rate(zfs_pool_scan_issued_bytes{instance=~\"$instance\", zpool=~\"$pool\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "scan errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 201 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(instance, zpool) (max_over_time(zfs_pool_scan_errors{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]))",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "scan: examine rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 201 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (instance, zpool) (rate(zfs_pool_scan_examined_bytes{instance=~\"$instance\", zpool=~\"$pool\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  }
 ]
}