{
 "title": "ZFS Dataset List",
 "description": "ZFS monitoring dashboard",
 "tags": [
  "ZFS",
  "node"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "query_result(label_join(last_over_time(zfs_exporter_build_info[$__range]), \"human_name\", \"/\", \"cluster_type\", \"cluster\"))"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(last_over_time(zfs_exporter_build_info{cluster=~\"$cluster\"}[$__range]))"
    }
   },
   {
    "name": "pool",
    "query": {
     "query": "query_result(zfs_dataset_used_bytes{instance=\"$instance\"})"
    }
   },
   { "name": "dataset_filter", "label": "Dataset selector" },
   {
    "name": "type",
    "query": {
     "query": "query_result(zfs_dataset_used_bytes{instance=\"$instance\", pool=\"$pool\"})"
    }
   },
   { "name": "low_limit", "label": "Min volume size", "query": "10" },
   {
    "name": "limit_suffix",
    "label": "Size suffix",
    "query": "Byte : 1, KB : 1024, MB : 1048576, GB : 1073741824, TB : 1099511627776"
   },
   {
    "name": "dataset",
    "query": {
     "query": "query_result(zfs_dataset_used_bytes{instance=\"$instance\", pool=\"$pool\", name=~\".*(${dataset_filter}).*\", type=~\"$type\", type=\"filesystem\"} or zfs_dataset_volume_size_bytes{instance=\"$instance\", pool=\"$pool\", name=~\".*(${dataset_filter}).*\"} > ($low_limit + 0) * $limit_suffix)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pool List",
   "type": "table",
   "gridPos": { "h": 20, "w": 22, "x": 1, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pool, name, type) (zfs_dataset_used_bytes{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(pool, name, type) (\r\n  zfs_dataset_used_bytes{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset\"} /\r\n  on (cluster_type, cluster, instance, pool) group_left()\r\n  zfs_pool_size_bytes{instance=\"$instance\", pool=~\"$pool\"}\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(pool, name, type) (zfs_dataset_logical_used_bytes{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(pool, name, type) (zfs_dataset_referenced_bytes{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(pool, name, type) (zfs_dataset_quota_bytes{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(pool, name, type) (zfs_dataset_referenced_quota_bytes{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset\"})\r\nor\r\nmax by(pool, name, type) (zfs_dataset_volume_size_bytes{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(pool, name, type) (zfs_dataset_written_bytes{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(pool, name, type) (zfs_dataset_referenced_reservation_bytes{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(pool, name, type) (zfs_dataset_available_bytes{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(pool, name, type) (zfs_dataset_creation{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Space", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Quota %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "zfs_dataset_used_bytes{instance=\"$instance\", pool=~\"$pool\", type=~\"$type\", name=~\"$dataset\"} /\r\n(zfs_dataset_quota_bytes != 0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Ref Quota %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "zfs_dataset_referenced_bytes{instance=\"$instance\", pool=~\"$pool\", type=~\"$type\", name=~\"$dataset\"} /\r\n(zfs_dataset_referenced_quota_bytes != 0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Volume allocated %",
   "type": "timeseries",
   "description": "Amount of storage logically allocated to volume. Volumes without discard can have this value artificially high.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "zfs_dataset_logical_used_bytes{instance=\"$instance\", pool=~\"$pool\", type=~\"$type\", name=~\"$dataset\"} /\r\nzfs_dataset_volume_size_bytes",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Used delta (logical)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "delta(zfs_dataset_logical_referenced_bytes{instance=\"$instance\", pool=~\"$pool\", type=~\"$type\", name=~\"$dataset\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Speed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Read Speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (dataset) (rate(node_zfs_zpool_dataset_nread{instance=\"$instance\", dataset=~\"$dataset\"}[$__rate_interval]))",
     "legendFormat": "{{dataset}}"
    }
   ]
  },
  {
   "title": "Write Speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (dataset) (rate(node_zfs_zpool_dataset_nwritten{instance=~\"$instance\", dataset=~\"$dataset\"}[$__rate_interval]))",
     "legendFormat": "{{dataset}}"
    }
   ]
  },
  { "title": "IOPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Read IOPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by (dataset) (rate(node_zfs_zpool_dataset_reads{instance=\"$instance\", dataset=~\"$dataset\"}[$__rate_interval]))",
     "legendFormat": "{{dataset}}"
    }
   ]
  },
  {
   "title": "Read IO average size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by (dataset) (\r\n  rate(node_zfs_zpool_dataset_nread{instance=\"$instance\", dataset=~\"$dataset\"}[$__rate_interval]) /\r\n  (rate(node_zfs_zpool_dataset_reads{instance=\"$instance\", dataset=~\"$dataset\"}[$__rate_interval]) + 1e-6)\r\n)",
     "legendFormat": "{{dataset}}"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by (dataset) (rate(node_zfs_zpool_dataset_writes{instance=~\"$instance\", dataset=~\"$dataset\"}[$__rate_interval]))",
     "legendFormat": "{{dataset}}"
    }
   ]
  },
  {
   "title": "Write IO average size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by (dataset) (\r\n  rate(node_zfs_zpool_dataset_nwritten{instance=\"$instance\", dataset=~\"$dataset\"}[$__rate_interval]) /\r\n  (rate(node_zfs_zpool_dataset_writes{instance=\"$instance\", dataset=~\"$dataset\"}[$__rate_interval]) + 1e-6)\r\n)",
     "legendFormat": "{{dataset}}"
    }
   ]
  }
 ]
}