{
 "title": "ZFS ARC Statistics",
 "description": "ZFS metrics as extracted by node_exporter",
 "tags": [ "ZFS" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "data_source", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "query_result(label_join(node_zfs_arc_size{}, \"human_name\", \"/\", \"cluster_type\", \"cluster\"))"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "query_result(node_zfs_arc_size{cluster=\"$cluster\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "Arc Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ARC size (high level)",
   "type": "timeseries",
   "description": "arc_c == target ?==? arc current",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg_over_time(node_zfs_arc_size{instance=\"$instance\", cluster=\"$cluster\"}[$__interval])",
     "legendFormat": "ARC Size"
    },
    {
     "expr": "avg_over_time(node_zfs_arc_c{instance=\"$instance\", cluster=\"$cluster\"}[$__interval])",
     "legendFormat": "ARC Target"
    },
    {
     "expr": "max_over_time(node_zfs_arc_c_max{instance=\"$instance\", cluster=\"$cluster\"}[$__interval])",
     "legendFormat": "ARC Max"
    },
    {
     "expr": "min_over_time(node_zfs_arc_c_min{instance=\"$instance\", cluster=\"$cluster\"}[$__interval])",
     "legendFormat": "ARC Min"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\", cluster=\"$cluster\"}",
     "legendFormat": "node total"
    },
    {
     "expr": "node_zfs_arc_arc_sys_free{instance=\"$instance\", cluster=\"$cluster\"}",
     "legendFormat": "arc sys free"
    },
    {
     "expr": "# seems like in ZFS arc_sys_free targets MemFree, without accounting for Buffers and Cached\r\navg_over_time(node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"$instance\", cluster=\"$cluster\"}[$__interval])",
     "legendFormat": "node free"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"$instance\", cluster=\"$cluster\"}\r\n+\r\nnode_memory_Buffers_bytes{job=\"node-exporter\", instance=\"$instance\", cluster=\"$cluster\"}\r\n+\r\nnode_memory_Cached_bytes{job=\"node-exporter\", instance=\"$instance\", cluster=\"$cluster\"}",
     "legendFormat": "free+cache"
    }
   ]
  },
  {
   "title": "ARC size (percent)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(node_zfs_arc_size{instance=\"$instance\", cluster=\"$cluster\"}[$__interval]) / avg_over_time(node_zfs_arc_c{instance=\"$instance\", cluster=\"$cluster\"}[$__interval])",
     "legendFormat": "Size / Target"
    },
    {
     "expr": "avg_over_time(node_zfs_arc_c{instance=\"$instance\", cluster=\"$cluster\"}[$__interval]) / max_over_time(node_zfs_arc_c_max{instance=\"$instance\", cluster=\"$cluster\"}[$__interval])",
     "legendFormat": "Target / Max"
    },
    {
     "expr": "max_over_time(node_zfs_arc_c_max{instance=\"$instance\", cluster=\"$cluster\"}[$__interval]) / node_memory_MemTotal_bytes",
     "legendFormat": "Max / Node total"
    }
   ]
  },
  {
   "title": "ARC hit %",
   "type": "timeseries",
   "description": "When there is no demand, result value will be 0%",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(rate(node_zfs_arc_demand_data_hits{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])) / (rate(node_zfs_arc_demand_data_hits{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval]) + rate(node_zfs_arc_demand_data_misses{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval]) + 1)",
     "legendFormat": "data"
    },
    {
     "expr": "(rate(node_zfs_arc_demand_metadata_hits{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])) / (rate(node_zfs_arc_demand_metadata_hits{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval]) + rate(node_zfs_arc_demand_metadata_misses{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval]) + 1)",
     "legendFormat": "metadata"
    },
    {
     "expr": "(rate(node_zfs_arc_l2_hits{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])) / (rate(node_zfs_arc_l2_hits{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval]) + rate(node_zfs_arc_l2_misses{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval]) + 1)",
     "legendFormat": "L2"
    },
    {
     "expr": "(rate(node_zfs_arc_demand_hit_predictive_prefetch{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])) / (rate(node_zfs_arc_predictive_prefetch{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval]) + 1)",
     "legendFormat": "prefetch"
    },
    {
     "expr": "(rate(node_zfs_zfetch_hits{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])) / (rate(node_zfs_zfetch_hits{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval]) + rate(node_zfs_zfetch_misses{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval]) + 1)",
     "legendFormat": "zfetch"
    }
   ]
  },
  {
   "title": "ARC hits and misses",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_zfs_arc_demand_data_hits{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "data hits"
    },
    {
     "expr": "rate(node_zfs_arc_demand_data_misses{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "data misses"
    },
    {
     "expr": "rate(node_zfs_arc_demand_metadata_hits{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "meta hits"
    },
    {
     "expr": "rate(node_zfs_arc_demand_metadata_misses{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "meta misses"
    },
    {
     "expr": "rate(node_zfs_arc_l2_hits{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "L2 hits"
    },
    {
     "expr": "rate(node_zfs_arc_l2_misses{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "L2 misses"
    },
    {
     "expr": "rate(node_zfs_arc_demand_hit_predictive_prefetch{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "prefetch hits"
    },
    {
     "expr": "rate(node_zfs_arc_predictive_prefetch{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "prefetch issued"
    }
   ]
  },
  {
   "title": "ARC dirty bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max_over_time(node_zfs_arc_anon_size{instance=\"$instance\", cluster=\"$cluster\"}[$__interval]) + max_over_time(node_zfs_arc_arc_tempreserve[$__interval]) - min_over_time(node_zfs_arc_arc_loaned_bytes[$__interval])",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "ARC size details (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg_over_time(node_zfs_arc_dnode_size{instance=\"$instance\", cluster=\"$cluster\"}[$__interval])",
     "legendFormat": "dnode"
    },
    {
     "expr": "avg_over_time(node_zfs_arc_dbuf_size{instance=\"$instance\", cluster=\"$cluster\"}[$__interval])",
     "legendFormat": "dbuf"
    },
    {
     "expr": "avg_over_time(node_zfs_arc_size{instance=\"$instance\", cluster=\"$cluster\"}[$__interval])\r\n- avg_over_time(node_zfs_arc_data_size{instance=\"$instance\", cluster=\"$cluster\"}[$__interval])\r\n- avg_over_time(node_zfs_arc_metadata_size{instance=\"$instance\", cluster=\"$cluster\"}[$__interval])\r\n- avg_over_time(node_zfs_arc_hdr_size{instance=\"$instance\", cluster=\"$cluster\"}[$__interval])\r\n- avg_over_time(node_zfs_arc_l2_hdr_size{instance=\"$instance\", cluster=\"$cluster\"}[$__interval])\r\n- avg_over_time(node_zfs_arc_dnode_size{instance=\"$instance\", cluster=\"$cluster\"}[$__interval])\r\n- avg_over_time(node_zfs_arc_dbuf_size{instance=\"$instance\", cluster=\"$cluster\"}[$__interval])\r\n- avg_over_time(node_zfs_arc_abd_chunk_waste_size{instance=\"$instance\", cluster=\"$cluster\"}[$__interval])\r\n- avg_over_time(node_zfs_arc_anon_data[$__interval])",
     "legendFormat": "Remaining"
    },
    {
     "expr": "avg_over_time(node_zfs_arc_hdr_size{instance=\"$instance\", cluster=\"$cluster\"}[$__interval])",
     "legendFormat": "Headers"
    },
    {
     "expr": "avg_over_time(node_zfs_arc_abd_chunk_waste_size{instance=\"$instance\", cluster=\"$cluster\"}[$__interval])",
     "legendFormat": "ABD waste"
    },
    {
     "expr": "avg_over_time(node_zfs_arc_metadata_size{instance=\"$instance\", cluster=\"$cluster\"}[$__interval])",
     "legendFormat": "Meta"
    },
    {
     "expr": "avg_over_time(node_zfs_arc_l2_hdr_size{instance=\"$instance\", cluster=\"$cluster\"}[$__interval])",
     "legendFormat": "L2 headers"
    },
    {
     "expr": "avg_over_time(node_zfs_arc_data_size{instance=\"$instance\", cluster=\"$cluster\"}[$__interval])",
     "legendFormat": "Data"
    }
   ]
  },
  {
   "title": "arc_no_grow",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "max_over_time(node_zfs_arc_arc_no_grow{instance=\"$instance\", cluster=\"$cluster\"}[$__interval])",
     "legendFormat": "arc_no_grow"
    }
   ]
  },
  {
   "title": "ARC evictions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "rate(node_zfs_arc_deleted{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "deleted"
    }
   ]
  },
  {
   "title": "L2ARC evictions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_zfs_arc_evict_l2_cached{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "l2_cached"
    },
    {
     "expr": "rate(node_zfs_arc_evict_l2_eligible{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "l2_eligible"
    },
    {
     "expr": "rate(node_zfs_arc_evict_l2_ineligible{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "l2_ineligible"
    },
    {
     "expr": "node_zfs_arc_evict_l2_skip{instance=\"$instance\", cluster=\"$cluster\"}",
     "legendFormat": "l2_skip"
    },
    {
     "expr": "node_zfs_arc_evict_not_enough{instance=\"$instance\", cluster=\"$cluster\"}",
     "legendFormat": "not_enough"
    },
    {
     "expr": "node_zfs_arc_evict_skip{instance=\"$instance\", cluster=\"$cluster\"}",
     "legendFormat": "skip"
    }
   ]
  },
  {
   "title": "L2ARC size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg_over_time(node_zfs_arc_l2_asize{instance=\"$instance\", cluster=\"$cluster\"}[$__interval])",
     "legendFormat": "asize"
    },
    {
     "expr": "avg_over_time(node_zfs_arc_l2_size{instance=\"$instance\", cluster=\"$cluster\"}[$__interval])",
     "legendFormat": "size"
    },
    {
     "expr": "avg_over_time(node_zfs_arc_l2_hdr_size{instance=\"$instance\", cluster=\"$cluster\"}[$__interval])",
     "legendFormat": "Header size"
    }
   ]
  },
  {
   "title": "L2ARC operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_zfs_arc_l2_evict_l1cached{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "evict_l1cached"
    },
    {
     "expr": "rate(node_zfs_arc_l2_writes_lock_retry{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "write lock retry"
    },
    {
     "expr": "rate(node_zfs_arc_l2_evict_reading{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "evict_reading"
    },
    {
     "expr": "rate(node_zfs_arc_l2_feeds{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "feeds"
    },
    {
     "expr": "rate(node_zfs_arc_l2_writes_sent{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "write sent"
    },
    {
     "expr": "rate(node_zfs_arc_l2_writes_done{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "writes done"
    },
    {
     "expr": "rate(node_zfs_arc_l2_writes_error{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "writes error"
    },
    {
     "expr": "rate(node_zfs_arc_l2_io_error{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "IO errors"
    },
    {
     "expr": "rate(node_zfs_arc_l2_cksum_bad{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "Checksum errors"
    },
    {
     "expr": "rate(node_zfs_arc_l2_abort_lowmem{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "abort_lowmem"
    }
   ]
  },
  {
   "title": "L2ARC speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_zfs_arc_l2_read_bytes{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "Read"
    },
    {
     "expr": "rate(node_zfs_arc_l2_write_bytes{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "Write"
    }
   ]
  },
  { "title": "Misc Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "zil - bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "rate(node_zfs_zil_zil_itx_copied_bytes{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "itx_copied_bytes"
    },
    {
     "expr": "rate(node_zfs_zil_zil_itx_indirect_bytes{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "itx_indirect_bytes"
    },
    {
     "expr": "rate(node_zfs_zil_zil_itx_metaslab_normal_bytes{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "itx_metaslab_normal_bytes"
    },
    {
     "expr": "rate(node_zfs_zil_zil_itx_metaslab_slog_bytes{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "itx_metaslab_slog_bytes"
    },
    {
     "expr": "rate(node_zfs_zil_zil_itx_needcopy_bytes{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "itx_needcopy_bytes"
    }
   ]
  },
  {
   "title": "zil - count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "rate(node_zfs_zil_zil_commit_count{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "commit_count"
    },
    {
     "expr": "rate(node_zfs_zil_zil_commit_writer_count{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "commit_writer_count"
    },
    {
     "expr": "rate(node_zfs_zil_zil_itx_copied_count{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "itx_copied_count"
    },
    {
     "expr": "rate(node_zfs_zil_zil_itx_count{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "itx_count"
    },
    {
     "expr": "rate(node_zfs_zil_zil_itx_indirect_count{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "itx_indirect_count"
    },
    {
     "expr": "rate(node_zfs_zil_zil_itx_metaslab_normal_count{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "itx_metaslab_normal_count"
    },
    {
     "expr": "rate(node_zfs_zil_zil_itx_metaslab_slog_count{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "itx_metaslab_slog_count"
    },
    {
     "expr": "rate(node_zfs_zil_zil_itx_needcopy_count{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "itx_needcopy_count"
    }
   ]
  },
  {
   "title": "ZPOOL",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "rate(node_zfs_zpool_rcnt{instance=\"$instance\", cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{zpool}} - rcnt"
    },
    {
     "expr": "rate(node_zfs_zpool_reads{instance=\"$instance\", cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{zpool}} - reads"
    },
    {
     "expr": "rate(node_zfs_zpool_wcnt{instance=\"$instance\", cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{zpool}} - wcnt"
    },
    {
     "expr": "rate(node_zfs_zpool_writes{instance=\"$instance\", cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{zpool}} - writes"
    }
   ]
  },
  {
   "title": "ZPOOL - Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 107 },
   "targets": [
    {
     "expr": "rate(node_zfs_zpool_rlentime{instance=\"$instance\", cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{zpool}} - rlentime"
    },
    {
     "expr": "rate(node_zfs_zpool_rupdate{instance=\"$instance\", cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{zpool}} - rupdate"
    },
    {
     "expr": "rate(node_zfs_zpool_wlentime{instance=\"$instance\", cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{zpool}} - wlentime"
    },
    {
     "expr": "rate(node_zfs_zpool_wtime{instance=\"$instance\", cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{zpool}} - wtime"
    },
    {
     "expr": "rate(node_zfs_zpool_wupdate{instance=\"$instance\", cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{zpool}} - wupdate"
    }
   ]
  }
 ]
}