{
 "title": "prometheus scrape job details",
 "tags": [ "prometheus-self-monitoring" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "job_filter" },
   {
    "name": "job",
    "query": {
     "query": "query_result(count by(job) (last_over_time(up{job=~\".*($job_filter).*\"}[$__range])))"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "query_result(count by(human_name, cluster) (label_join(last_over_time(up{job=~\"$job\"}[$__range]), \"human_name\", \"/\", \"cluster_type\", \"cluster\")))"
    }
   },
   { "name": "instance_filter" },
   {
    "name": "instance",
    "query": {
     "query": "query_result(count by(instance) (last_over_time(up{job=~\"$job\", cluster=~\"$cluster\", instance=~\".*($instance_filter).*\"}[$__range])))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "targets",
   "type": "table",
   "gridPos": { "h": 26, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by(job, cluster_type, cluster, instance) (up{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(job, cluster_type, cluster, instance) (up{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(job, cluster_type, cluster, instance) (scrape_samples_post_metric_relabeling{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "top series from selected instance",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(count by(job, __name__) ({job=~\"$job\", instance=~\"$instance\"}), \"name\", \"$1\", \"__name__\", \"(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "top series without instance label",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "label_replace(count by(job, __name__) ({job=~\"$job\", instance=\"\"}), \"name\", \"$1\", \"__name__\", \"(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "state-timeline",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "min_over_time(up{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{job}}: {{instance}}"
    }
   ]
  },
  {
   "title": "scrape target count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "count by(job, instance) (last_over_time(up{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "{{job}}: {{instance}}"
    }
   ]
  },
  {
   "title": "samples in scrape (saved)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "avg_over_time(scrape_samples_post_metric_relabeling{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{job}}: {{instance}} / {{endpoint}}"
    }
   ]
  },
  {
   "title": "average samples in scrape (raw)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "avg_over_time(scrape_samples_scraped{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{job}}: {{instance}} / {{endpoint}}"
    }
   ]
  },
  {
   "title": "% of samples surviving relabeling",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(scrape_samples_post_metric_relabeling{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__interval])\r\n/\r\navg_over_time(scrape_samples_scraped{}[$__interval])",
     "legendFormat": "{{job}}: {{instance}} / {{endpoint}}"
    }
   ]
  },
  {
   "title": "new series (sum over time)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "sum_over_time(scrape_series_added{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{job}}: {{instance}} / {{endpoint}}"
    }
   ]
  },
  {
   "title": "scrape body size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max_over_time(scrape_body_size_bytes{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{job}}: {{instance}} / {{endpoint}}"
    }
   ]
  },
  {
   "title": "average scrape time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(scrape_duration_seconds{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{job}}: {{instance}} / {{endpoint}}"
    }
   ]
  }
 ]
}