{
 "title": "prometheus rule list",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "query_result(count by(human_name, cluster) (label_join(last_over_time(prometheus_build_info[$__range]), \"human_name\", \"/\", \"cluster_type\", \"cluster\")))"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "query_result(count by(instance) (last_over_time(prometheus_build_info{cluster=~\"$cluster\"}[$__range])))"
    }
   },
   { "name": "name_filter" },
   {
    "name": "rule",
    "query": {
     "query": "query_result(count by(rule_name) (label_replace(last_over_time(prometheus_rule_evaluations_total{instance=\"$instance\", rule_group=~\".*;.*($name_filter).*\"}[$__range]), \"rule_name\", \"$1\", \"rule_group\", \".*;(.*)\")))"
    }
   },
   {
    "name": "rule_group",
    "query": {
     "query": "query_result(count by(rule_group) (last_over_time(prometheus_rule_evaluations_total{instance=\"$instance\", rule_group=~\".*;($rule)\"}[$__range])))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Torrents",
   "type": "table",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(instance, rule_group, rule_group_name) (prometheus_rule_group_rules{instance=\"$instance\", rule_group=~\"$rule_group\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(instance, rule_group, rule_group_name) (prometheus_rule_evaluations_total{instance=\"$instance\", rule_group=~\"$rule_group\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(instance, rule_group, rule_group_name) (prometheus_rule_evaluation_failures_total{instance=\"$instance\", rule_group=~\"$rule_group\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(instance, rule_group, rule_group_name) (prometheus_rule_group_interval_seconds{instance=\"$instance\", rule_group=~\"$rule_group\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(instance, rule_group, rule_group_name) (prometheus_rule_group_iterations_missed_total{instance=\"$instance\", rule_group=~\"$rule_group\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(instance, rule_group, rule_group_name) (prometheus_rule_group_iterations_total{instance=\"$instance\", rule_group=~\"$rule_group\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(instance, rule_group, rule_group_name) (prometheus_rule_group_last_duration_seconds{instance=\"$instance\", rule_group=~\"$rule_group\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(instance, rule_group, rule_group_name) (prometheus_rule_group_last_evaluation_samples{instance=\"$instance\", rule_group=~\"$rule_group\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(instance, rule_group, rule_group_name) (prometheus_rule_group_last_evaluation_timestamp_seconds{instance=\"$instance\", rule_group=~\"$rule_group\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(instance, rule_group, rule_group_name) (prometheus_rule_group_last_rule_duration_sum_seconds{instance=\"$instance\", rule_group=~\"$rule_group\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "iterations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "max by(rule_group, rule_group_name) (rate(prometheus_rule_group_iterations_total{instance=\"$instance\", rule_group=~\"$rule_group\"}[$__rate_interval]))",
     "legendFormat": "{{rule_group_name}}"
    },
    {
     "expr": "max by(rule_group, rule_group_name) (sum(rate(prometheus_rule_group_iterations_total{instance=\"$instance\", rule_group=~\"$rule_group\"}[$__rate_interval])))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "evaluations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "max by(rule_group, rule_group_name) (rate(prometheus_rule_evaluations_total{instance=\"$instance\", rule_group=~\"$rule_group\"}[$__rate_interval]))",
     "legendFormat": "{{rule_group_name}}"
    },
    {
     "expr": "max by(rule_group, rule_group_name) (sum(rate(prometheus_rule_evaluations_total{instance=\"$instance\", rule_group=~\"$rule_group\"}[$__rate_interval])))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "evaluation failures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "max by(rule_group, rule_group_name) (rate(prometheus_rule_evaluation_failures_total{instance=\"$instance\", rule_group=~\"$rule_group\"}[$__rate_interval])) != 0",
     "legendFormat": "{{rule_group_name}}"
    },
    {
     "expr": "max by(rule_group, rule_group_name) (sum(rate(prometheus_rule_evaluation_failures_total{instance=\"$instance\", rule_group=~\"$rule_group\"}[$__rate_interval])))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "last eval duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(rule_group, rule_group_name) (max_over_time(prometheus_rule_group_last_duration_seconds{instance=\"$instance\", rule_group=~\"$rule_group\"}[$__interval]))",
     "legendFormat": "{{rule_group_name}}"
    }
   ]
  },
  {
   "title": "last eval duration sum",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(rule_group, rule_group_name) (max_over_time(prometheus_rule_group_last_rule_duration_sum_seconds{instance=\"$instance\", rule_group=~\"$rule_group\"}[$__interval]))",
     "legendFormat": "{{rule_group_name}}"
    }
   ]
  },
  {
   "title": "last eval samples",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "max by(rule_group, rule_group_name) (max_over_time(prometheus_rule_group_last_evaluation_samples{instance=\"$instance\", rule_group=~\"$rule_group\"}[$__interval]))",
     "legendFormat": "{{rule_group_name}}"
    }
   ]
  }
 ]
}