{
 "title": "prometheus",
 "tags": [ "prometheus-self-monitoring" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(prometheus_build_info[$__range])))"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "query_result(count by(instance) (last_over_time(prometheus_build_info{location=~\"$location\"}[$__range])))"
    }
   }
  ]
 },
 "panels": [
  { "title": "general", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_build_info{instance=\"$instance\"}",
     "legendFormat": "version"
    }
   ]
  },
  {
   "title": "config OK",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(prometheus_config_last_reload_successful{instance=\"$instance\"})",
     "legendFormat": "version"
    }
   ]
  },
  {
   "title": "instance OK",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(prometheus_ready{instance=\"$instance\"})",
     "legendFormat": "version"
    }
   ]
  },
  {
   "title": "retention time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(prometheus_tsdb_retention_limit_seconds{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "retention size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(prometheus_tsdb_retention_limit_bytes{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "db size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(prometheus_tsdb_storage_blocks_bytes{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "version history",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "max by(instance, version) (last_over_time(prometheus_build_info{instance=~\"$instance\"}[$__interval]))\r\nor on()\r\n(\r\n  vector(0) unless on() last_over_time(prometheus_build_info{instance=~\"$instance\"}[$__interval])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "started (ago)",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "$__to / 1000 - max(max_over_time(process_start_time_seconds{job=\"prometheus\", instance=\"$instance\"}[$__interval]))",
     "legendFormat": "started"
    }
   ]
  },
  {
   "title": "status",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "min(min_over_time(prometheus_ready{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "ready"
    },
    {
     "expr": "min(min_over_time(prometheus_config_last_reload_successful{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "config"
    }
   ]
  },
  {
   "title": "retention time",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(max_over_time(prometheus_tsdb_retention_limit_seconds{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "retention time"
    }
   ]
  },
  {
   "title": "targets",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum(max by(scrape_job) (avg_over_time(prometheus_target_scrape_pool_targets{instance=\"$instance\"}[$__interval])))",
     "legendFormat": "targets"
    }
   ]
  },
  {
   "title": "retention size",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(max_over_time(prometheus_tsdb_retention_limit_bytes{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "retention size"
    }
   ]
  },
  { "title": "storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "head chunks",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "max(max_over_time(prometheus_tsdb_head_chunks{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "head chunks"
    },
    {
     "expr": "max(max_over_time(prometheus_tsdb_head_series{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "series"
    },
    {
     "expr": "max(max_over_time(prometheus_tsdb_blocks_loaded{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "blocks loaded"
    }
   ]
  },
  {
   "title": "db size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(prometheus_tsdb_storage_blocks_bytes{instance=\"$instance\"})",
     "legendFormat": "storage size"
    }
   ]
  },
  {
   "title": "samples added",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "db delta",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(delta(prometheus_tsdb_storage_blocks_bytes{instance=\"$instance\"}[24h])) * group(last_over_time(prometheus_tsdb_storage_blocks_bytes{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "tsdb 24h delta"
    }
   ]
  },
  {
   "title": "compactions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "max(rate(prometheus_tsdb_vertical_compactions_total{instance=\"$instance\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "vertical"
    },
    {
     "expr": "max(rate(prometheus_tsdb_compactions_total{instance=\"$instance\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "total"
    },
    {
     "expr": "max(rate(prometheus_tsdb_compactions_failed_total{instance=\"$instance\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "storage size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(max_over_time(prometheus_tsdb_head_chunks_storage_size_bytes{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "head"
    },
    {
     "expr": "max(max_over_time(prometheus_tsdb_wal_storage_size_bytes{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "wal"
    }
   ]
  },
  {
   "title": "dropped out of order samples ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "max(rate(prometheus_tsdb_out_of_order_samples_total{instance=\"$instance\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "out of order"
    },
    {
     "expr": "max(rate(prometheus_tsdb_out_of_bound_samples_total{instance=\"$instance\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "out of bounds"
    }
   ]
  },
  { "title": "engine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "queries count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "max by(slice) (rate(prometheus_engine_query_duration_seconds_count{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{slice}}"
    }
   ]
  },
  {
   "title": "queries timing p50",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(slice) (prometheus_engine_query_duration_seconds{instance=\"$instance\", quantile=\"0.5\"})",
     "legendFormat": "{{slice}}"
    }
   ]
  },
  {
   "title": "queries duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(slice) (rate(prometheus_engine_query_duration_seconds_sum{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{slice}}"
    }
   ]
  },
  {
   "title": "queries timing p99",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(slice) (prometheus_engine_query_duration_seconds{instance=\"$instance\", quantile=\"0.99\"})",
     "legendFormat": "{{slice}}"
    }
   ]
  },
  {
   "title": "samples loaded by queries",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "max(rate(prometheus_engine_query_samples_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "rules",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true
  },
  {
   "title": "rule eval count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "max(rate(prometheus_rule_evaluation_duration_seconds_count{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "individual"
    },
    {
     "expr": "max(rate(prometheus_rule_group_duration_seconds_count{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "group"
    },
    {
     "expr": "sum(rate(prometheus_rule_evaluation_failures_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "fails"
    }
   ]
  },
  {
   "title": "rule timing p50",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(prometheus_rule_evaluation_duration_seconds{instance=\"$instance\", quantile=\"0.5\"})",
     "legendFormat": "individual"
    },
    {
     "expr": "max(prometheus_rule_group_duration_seconds{instance=\"$instance\", quantile=\"0.5\"})",
     "legendFormat": "group"
    }
   ]
  },
  {
   "title": "rule eval duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(rate(prometheus_rule_evaluation_duration_seconds_sum{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "individual"
    },
    {
     "expr": "max(rate(prometheus_rule_group_duration_seconds_sum{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "group"
    }
   ]
  },
  {
   "title": "rule timing p99",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(prometheus_rule_evaluation_duration_seconds{instance=\"$instance\", quantile=\"0.99\"})",
     "legendFormat": "individual"
    },
    {
     "expr": "max(prometheus_rule_group_duration_seconds{instance=\"$instance\", quantile=\"0.99\"})",
     "legendFormat": "group"
    }
   ]
  }
 ]
}