{
 "title": "prometheus alerts",
 "tags": [ "prometheus-self-monitoring" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "type",
    "query": "any : invalid=\"\", unique : instance=\"\"\\, namespace=\"\", instanced : instance!=\"\", namespaced : namespace!=\"\""
   },
   { "name": "name_filter" },
   {
    "name": "severity",
    "query": {
     "query": "query_result(group by(severity) (last_over_time(ALERTS{alertname=~\".*(?i:($name_filter)).*\", $type}[$__range])))"
    }
   },
   {
    "name": "alertname",
    "query": {
     "query": "query_result(count by(alertname) (last_over_time(ALERTS{alertname=~\".*(?i:($name_filter)).*\", severity=~\"$severity\", $type}[$__range])))"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "general", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "list",
   "type": "table",
   "gridPos": { "h": 22, "w": 21, "x": 1, "y": 1 },
   "targets": [
    {
     "expr": "count by(alertname, alertstate, location, namespace, instance, pod, severity) (last_over_time(ALERTS{alertname=~\"$alertname\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "# omitting last_over_time here, because we only need this for alerts existing right now\r\ntime() - max by(alertname, location, namespace, instance, pod, severity) (ALERTS_FOR_STATE{alertname=~\"$alertname\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "state/severity count",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "count by(severity, alertstate) (last_over_time(ALERTS{alertname=~\"$alertname\"}[$__interval]))",
     "legendFormat": "{{alertstate}} {{severity}}"
    }
   ]
  },
  {
   "title": "alert history",
   "type": "state-timeline",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "group by(alertname, namespace) (last_over_time(ALERTS{namespace!=\"\", alertname=~\"$alertname\", alertstate=\"firing\"}[$__interval])) * 2\r\nor\r\ngroup by(alertname, namespace) (last_over_time(ALERTS{namespace!=\"\", alertname=~\"$alertname\", alertstate=\"pending\"}[$__interval])) * 3",
     "legendFormat": "{{alertname}}: {{namespace}}"
    },
    {
     "expr": "group by(alertname, instance) (last_over_time(ALERTS{instance!=\"\", namespace=\"\", alertname=~\"$alertname\", alertstate=\"firing\"}[$__interval])) * 4\r\nor\r\ngroup by(alertname, instance) (last_over_time(ALERTS{instance!=\"\", namespace=\"\", alertname=~\"$alertname\", alertstate=\"pending\"}[$__interval])) * 5",
     "legendFormat": "{{alertname}}: {{instance}}"
    },
    {
     "expr": "group by(alertname) (last_over_time(ALERTS{instance=\"\", namespace=\"\", alertname=~\"$alertname\", alertstate=\"firing\"}[$__interval])) * 6\r\nor\r\ngroup by(alertname) (last_over_time(ALERTS{instance=\"\", namespace=\"\", alertname=~\"$alertname\", alertstate=\"pending\"}[$__interval])) * 7",
     "legendFormat": "{{alertname}}"
    }
   ]
  }
 ]
}