{
 "title": "prometheus scrape job list",
 "tags": [ "prometheus-self-monitoring" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "query": "prometheus" },
   { "name": "job_filter" },
   {
    "name": "job",
    "query": {
     "query": "query_result(count by(job) (last_over_time(up{job=~\".*($job_filter).*\"}[$__range])))"
    }
   },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(up{job=~\"$job\"}[$__range])))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "jobs",
   "type": "table",
   "gridPos": { "h": 25, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by(job) (up{job=~\"$job\", location=~\"$location\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(job) (up{job=~\"$job\", location=~\"$location\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jobs + cluster",
   "type": "table",
   "gridPos": { "h": 25, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(job, location) (up{job=~\"$job\", location=~\"$location\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "target state",
   "type": "state-timeline",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "min by(job) (min_over_time(up{job=~\"$job\", location=~\"$location\"}[$__interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "scrape target count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "count by(job) (last_over_time(up{job=~\"$job\", location=~\"$location\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "average samples in scrape",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "avg by(job, endpoint) (avg_over_time(scrape_samples_post_metric_relabeling{job=~\"$job\", location=~\"$location\"}[$__interval]))",
     "legendFormat": "{{job}} / {{endpoint}}"
    }
   ]
  },
  {
   "title": "samples from job (sum over all targets)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "sum by(job, endpoint) (avg_over_time(scrape_samples_post_metric_relabeling{job=~\"$job\", location=~\"$location\"}[$__interval]))",
     "legendFormat": "{{job}} / {{endpoint}}"
    }
   ]
  },
  {
   "title": "average samples in scrape (raw)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "avg by(job, endpoint) (avg_over_time(scrape_samples_scraped{job=~\"$job\", location=~\"$location\"}[$__interval]))",
     "legendFormat": "{{job}} / {{endpoint}}"
    }
   ]
  },
  {
   "title": "% of samples surviving relabeling",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(job, endpoint) (\r\navg_over_time(scrape_samples_post_metric_relabeling{job=~\"$job\", location=~\"$location\"}[$__interval])\r\n/\r\navg_over_time(scrape_samples_scraped{}[$__interval])\r\n)",
     "legendFormat": "{{job}} / {{endpoint}}"
    }
   ]
  },
  {
   "title": "new series (sum over time)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "sum by(job, endpoint) (sum_over_time(scrape_series_added{job=~\"$job\", location=~\"$location\"}[$__interval]))",
     "legendFormat": "{{job}} / {{endpoint}}"
    }
   ]
  },
  {
   "title": "max average scrape time",
   "type": "timeseries",
   "description": "average over time, max of all targets",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(job, endpoint) (avg_over_time(scrape_duration_seconds{job=~\"$job\", location=~\"$location\"}[$__interval]))",
     "legendFormat": "{{job}} / {{endpoint}}"
    }
   ]
  }
 ]
}