---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prometheus

resources:
- ./prompp.yaml
- ./service-monitor.yaml

secretGenerator:
- name: prometheus-prompp-extra-configs
  files:
  - ./alert-relabel.yaml
  options:
    disableNameSuffixHash: true

patches:
- path: ./env/patch.yaml
- target:
    kind: ServiceMonitor
    name: prompp
  path: ./env/patch-location-tag.yaml
