{
 "title": "zrepl target",
 "description": "ZFS metrics as extracted by node_exporter",
 "tags": [
  "ZFS",
  "node"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "data_source", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "query_result(label_join(last_over_time(up{job=\"zrepl\"}[$__range]), \"human_name\", \"/\", \"cluster_type\", \"cluster\"))"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "query_result(last_over_time(zrepl_pruning_time_count{cluster=~\"$cluster\"}[$__range]))"
    }
   },
   {
    "name": "zrepl_job",
    "query": {
     "query": "query_result(last_over_time(zrepl_replication_bytes_replicated{instance=\"$instance\"}[$__range]))"
    }
   },
   {
    "name": "filesystem",
    "query": {
     "query": "query_result(last_over_time(zrepl_replication_bytes_replicated{instance=\"$instance\", zrepl_job=~\"$zrepl_job\"}[$__range]))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Last successful replication",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "last_over_time(zrepl_replication_last_successful{instance=\"$instance\", zrepl_job=~\"$zrepl_job\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replication speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(zrepl_replication_bytes_replicated{instance=\"$instance\", filesystem=~\"$filesystem\"}[$__rate_interval])",
     "legendFormat": "{{filesystem}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(zrepl_replication_filesystem_errors{instance=\"$instance\", zrepl_job=~\"$zrepl_job\"}[$__rate_interval])",
     "legendFormat": "{{zrepl_job}}"
    }
   ]
  }
 ]
}