{
 "title": "minio / bucket details",
 "tags": [ "prometheus-self-monitoring" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(minio_cluster_usage_objects_count[$__range])))"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "query_result(count by(instance) (last_over_time(minio_cluster_usage_objects_count{location=~\"$location\"}[$__range])))"
    }
   },
   {
    "name": "bucket",
    "query": {
     "query": "query_result(count by(bucket) (last_over_time(minio_cluster_usage_buckets_objects_count{instance=~\"$instance\"}[$__range])))"
    }
   }
  ]
 },
 "panels": [
  { "title": "overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "space used (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(avg_over_time(minio_cluster_usage_buckets_total_bytes{instance=\"$instance\", bucket=\"$bucket\"}[$__rate_interval]))",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "object size distribution",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "max by(range) (max_over_time(minio_cluster_usage_buckets_object_size_distribution{instance=\"$instance\", bucket=\"$bucket\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "objects contained",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "max(avg_over_time(minio_cluster_usage_buckets_objects_count{instance=\"$instance\", bucket=\"$bucket\"}[$__rate_interval]))",
     "legendFormat": "objects"
    }
   ]
  },
  {
   "title": "object size distribution (percent)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(range) (max_over_time(minio_cluster_usage_buckets_object_size_distribution{instance=\"$instance\", bucket=\"$bucket\"}[$__interval]))\r\n/ on() group_left()\r\nmax(max_over_time(minio_cluster_usage_buckets_objects_count{instance=\"$instance\", bucket=\"$bucket\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "object version distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "max by(range) (max_over_time(minio_cluster_usage_buckets_object_version_count_distribution{instance=\"$instance\", bucket=\"$bucket\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}