{
 "title": "minio overview",
 "tags": [ "prometheus-self-monitoring" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(minio_cluster_usage_objects_count[$__range])))"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "query_result(count by(instance) (last_over_time(minio_cluster_usage_objects_count{location=~\"$location\"}[$__range])))"
    }
   }
  ]
 },
 "panels": [
  { "title": "overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "objects",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "max(max_over_time(minio_cluster_usage_objects_count{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "objects"
    }
   ]
  },
  {
   "title": "total object size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(max_over_time(minio_cluster_usage_objects_total_bytes{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "buckets",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "max(max_over_time(minio_cluster_usage_objects_buckets_count{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "buckets"
    }
   ]
  },
  {
   "title": "capacity: free",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(max_over_time(minio_cluster_health_capacity_usable_free_bytes{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "time since last metrics update",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(max_over_time(minio_cluster_usage_objects_since_last_update_seconds{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "capacity: total",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(max_over_time(minio_cluster_health_capacity_usable_total_bytes{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "nodes: online",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "max(max_over_time(minio_cluster_health_nodes_online_count{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "online"
    }
   ]
  },
  {
   "title": "drives: total",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "max(max_over_time(minio_cluster_health_drives_count{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "drives: online",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "max(max_over_time(minio_cluster_health_drives_online_count{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "online"
    }
   ]
  },
  { "title": "buckets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "New panel",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 2, "y": 27 },
   "targets": [
    {
     "expr": "max by(bucket) (avg_over_time(minio_cluster_usage_buckets_total_bytes{instance=\"$instance\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(bucket) (avg_over_time(minio_cluster_usage_buckets_objects_count{instance=\"$instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "space used (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(bucket) (avg_over_time(minio_cluster_usage_buckets_total_bytes{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "object size distribution",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "max by(range) (max_over_time(minio_cluster_usage_objects_size_distribution{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "objects contained",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "max by(bucket) (avg_over_time(minio_cluster_usage_buckets_objects_count{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "object size distribution (percent)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(range) (max_over_time(minio_cluster_usage_objects_size_distribution{instance=\"$instance\"}[$__interval]))\r\n/ on() group_left()\r\nmax(max_over_time(minio_cluster_usage_objects_count{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "average object size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(bucket) (avg_over_time(minio_cluster_usage_buckets_total_bytes{instance=\"$instance\"}[$__interval]))\r\n/\r\nmax by(bucket) (avg_over_time(minio_cluster_usage_buckets_objects_count{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}