---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: immich-statistics
  labels:
    prometheus.io/instance: main
    instance.prometheus.io/main: enable
    instance.prometheus.io/prompp: enable
spec:
  scheme: HTTP
  staticConfigs:
  - labels:
      job: immich-statistics
    targets:
    - metrics-exporter.immich
  relabelings:
  - targetLabel: instance
    sourceLabels: [ location, __address__ ]
    separator: ;
    regex: (.*);(.*):\d*
    action: replace
    replacement: $1/$2
  metricRelabelings:
  - action: labeldrop
    regex: instance
