{
 "title": "etcd",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(etcd_server_has_leader,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(etcd_server_has_leader,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(etcd_server_has_leader{job=\"$cluster\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk sync duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max_over_time(recording:quantile_099:etcd_disk_wal_fsync_duration_seconds{job=\"$cluster\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} WAL fsync"
    },
    {
     "expr": "max_over_time(recording:quantile_099:etcd_disk_backend_commit_duration_seconds{job=\"$cluster\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} DB fsync"
    }
   ]
  },
  {
   "title": "DB size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "etcd_mvcc_db_total_size_in_bytes{job=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} DB size"
    }
   ]
  },
  {
   "title": "Raft proposals",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 9 },
   "targets": [
    {
     "expr": "min_over_time(rate(etcd_server_proposals_committed_total{job=\"$cluster\", instance=~\"$instance\"}[60s])[$__rate_interval:])",
     "legendFormat": "{{instance}} committed"
    },
    {
     "expr": "max_over_time(etcd_server_proposals_pending{job=\"$cluster\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} pending"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max_over_time(process_resident_memory_bytes{job=\"$cluster\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active streams",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 10, "y": 19 },
   "targets": [
    {
     "expr": "avg(grpc_server_started_total{job=\"$cluster\", instance=~\"$instance\", grpc_service=\"etcdserverpb.Watch\", grpc_type=\"bidi_stream\"}) - avg(recording:grpc_server_handled_total{job=\"$cluster\", instance=~\"$instance\", grpc_service=\"etcdserverpb.Watch\", grpc_type=\"bidi_stream\"})",
     "legendFormat": "Watch streams"
    },
    {
     "expr": "avg(grpc_server_started_total{job=\"$cluster\", instance=~\"$instance\", grpc_service=\"etcdserverpb.Lease\", grpc_type=\"bidi_stream\"}) - avg(recording:grpc_server_handled_total{job=\"$cluster\", instance=~\"$instance\", grpc_service=\"etcdserverpb.Lease\", grpc_type=\"bidi_stream\"})",
     "legendFormat": "Lease streams"
    }
   ]
  },
  {
   "title": "RPC rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "min_over_time(avg(rate(recording:all_services:grpc_server_started_total{job=\"$cluster\", instance=~\"$instance\", grpc_type=\"unary\"}[20s]))[$__rate_interval:])",
     "legendFormat": "RPC rate"
    },
    {
     "expr": "max_over_time(avg(rate(recording:all_services:grpc_server_failed_total{job=\"$cluster\", instance=~\"$instance\", grpc_type=\"unary\"}[20s]))[$__rate_interval:])",
     "legendFormat": "RPC failed rate"
    }
   ]
  },
  {
   "title": "Peer round trip time",
   "type": "timeseries",
   "description": "disabled because:\n- etcd_network_peer_round_trip_time_seconds_bucket is buggy\n- - https://github.com/etcd-io/etcd/issues/17837\n- histogram_quantile is very slow\n- recording rule with histogram_quantile doesn't seem to work",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } }
  },
  {
   "title": "Total leader elections per day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 29 },
   "targets": [
    {
     "expr": "changes(etcd_server_leader_changes_seen_total{job=\"$cluster\", instance=~\"$instance\"}[1d])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}