{
 "title": "k8s features",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(kubernetes_feature_enabled{name=\"AllBeta\"}[$__range])))"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "query_result(group by(instance) (last_over_time(kubernetes_feature_enabled{name=\"AllBeta\", location=\"$location\"}[$__range])))"
    }
   },
   { "name": "feature_filter" },
   {
    "name": "feature",
    "query": {
     "query": "query_result(group by(name) (last_over_time(kubernetes_feature_enabled{instance=~\"$instance\", name=~\".*(?i:($feature_filter)).*\"}[$__range])))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "feature state (summary over instances)",
   "type": "state-timeline",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(avg by(name) (avg_over_time(kubernetes_feature_enabled{name=~\"$feature\", instance=~\"$instance\"}[$__interval])) == 0)\r\nor\r\n(avg by(name) (avg_over_time(kubernetes_feature_enabled{name=~\"$feature\", instance=~\"$instance\"}[$__interval])) == 1)\r\nor\r\n(avg by(name) (avg_over_time(kubernetes_feature_enabled{name=~\"$feature\", instance=~\"$instance\"}[$__interval])) * 0 + 2)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "feature state (instance details)",
   "type": "state-timeline",
   "gridPos": { "h": 32, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "max by(human_name) (label_join(\r\n  (avg by(instance, job, name) (avg_over_time(kubernetes_feature_enabled{name=~\"$feature\", instance=~\"$instance\"}[$__interval])) == 0)\r\n  or\r\n  (avg by(instance, job, name) (avg_over_time(kubernetes_feature_enabled{name=~\"$feature\", instance=~\"$instance\"}[$__interval])) == 1)\r\n  or\r\n  (avg by(instance, job, name) (avg_over_time(kubernetes_feature_enabled{name=~\"$feature\", instance=~\"$instance\"}[$__interval])) * 0 + 2)\r\n, \"human_name\", \": \", \"name\", \"job\", \"instance\"\r\n))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "features",
   "type": "table",
   "gridPos": { "h": 32, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "max by(instance, job, name, stage) (kubernetes_feature_enabled{name=~\"$feature\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}