{
 "title": "Network Details",
 "tags": [ "node" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "query_result(label_join(node_uname_info, \"human_name\", \"/\", \"cluster_type\", \"cluster\"))"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(node_uname_info{cluster=\"$cluster\"})"
    }
   },
   {
    "name": "device",
    "label": "Device",
    "query": {
     "query": "query_result(node_network_receive_bytes_total{instance=\"$instance\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "IP addresses",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "node_network_address_info{cluster=\"$cluster\", instance=\"$instance\", device=~\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Receive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{cluster=\"$cluster\", instance=\"$instance\", device=~\"$device\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Transmit",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{cluster=\"$cluster\", instance=\"$instance\", device=~\"$device\"}[$__rate_interval])",
     "legendFormat": "{{device}} "
    }
   ]
  },
  {
   "title": "Network Traffic Drop",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_drop_total{cluster=\"$cluster\", instance=\"$instance\", device=~\"$device\"}[$__rate_interval])",
     "legendFormat": "{{device}} Rx"
    },
    {
     "expr": "rate(node_network_transmit_drop_total{cluster=\"$cluster\", instance=\"$instance\", device=~\"$device\"}[$__rate_interval])",
     "legendFormat": "{{device}} Tx"
    }
   ]
  },
  {
   "title": "Network Traffic Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_errs_total{cluster=\"$cluster\", instance=\"$instance\", device=~\"$device\"}[$__rate_interval])",
     "legendFormat": "{{device}} Rx errors"
    },
    {
     "expr": "rate(node_network_transmit_errs_total{cluster=\"$cluster\", instance=\"$instance\", device=~\"$device\"}[$__rate_interval])",
     "legendFormat": "{{device}} Tx errors"
    }
   ]
  },
  {
   "title": "ARP Entries",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_arp_entries{cluster=\"$cluster\", instance=\"$instance\", device=~\"$device\"}",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Network Operational Status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_network_up{cluster=\"$cluster\", instance=\"$instance\", device=~\"$device\"}",
     "legendFormat": "{{device}} UP"
    },
    {
     "expr": "node_network_carrier{cluster=\"$cluster\", instance=\"$instance\", device=~\"$device\"}",
     "legendFormat": "{{device}} link"
    }
   ]
  }
 ]
}