{
 "title": "Overview",
 "tags": [ "node" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "query_result(label_join(last_over_time(node_uname_info[$__range]), \"human_name\", \"/\", \"cluster_type\", \"cluster\"))"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(last_over_time(node_uname_info{cluster=\"$cluster\"}[$__range]))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick CPU / Mem / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pressure",
   "type": "bargauge",
   "description": "Resource pressure via PSI",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_pressure_cpu_waiting_seconds_total{cluster=\"$cluster\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "CPU"
    },
    {
     "expr": "rate(node_pressure_memory_waiting_seconds_total{cluster=\"$cluster\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Mem"
    },
    {
     "expr": "rate(node_pressure_io_waiting_seconds_total{cluster=\"$cluster\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "I/O"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", cluster=\"$cluster\", instance=\"$instance\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{cluster=\"$cluster\", instance=\"$instance\"} / node_memory_MemTotal_bytes{cluster=\"$cluster\", instance=\"$instance\"})) * 100"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{cluster=\"$cluster\", instance=\"$instance\"} - node_memory_SwapFree_bytes{cluster=\"$cluster\", instance=\"$instance\"}) / (node_memory_SwapTotal_bytes{cluster=\"$cluster\", instance=\"$instance\"})) * 100"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{cluster=\"$cluster\", instance=\"$instance\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{cluster=\"$cluster\", instance=\"$instance\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{cluster=\"$cluster\", instance=\"$instance\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{cluster=\"$cluster\", instance=\"$instance\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{cluster=\"$cluster\", instance=\"$instance\"} - node_boot_time_seconds{cluster=\"$cluster\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{cluster=\"$cluster\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{cluster=\"$cluster\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "IP addresses",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 1, "y": 5 },
   "targets": [
    {
     "expr": "node_network_address_info{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU Overview",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "# usually this should not exist,\r\n# but in case node-exporter adds a new value for mode, show it\r\nsum(rate(node_cpu_seconds_total{cluster=\"$cluster\", instance=\"$instance\",  mode!~\"system|user|nice|iowait|softirq|irq|idle|steal\"}[$__rate_interval]))",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{cluster=\"$cluster\", instance=\"$instance\", mode=\"steal\"}[$__rate_interval]))",
     "legendFormat": "steal"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{cluster=\"$cluster\", instance=\"$instance\", mode=~\"user|nice\"}[$__rate_interval])) - (sum(rate(node_cpu_guest_seconds_total{cluster=\"$cluster\", instance=\"$instance\", mode=~\"user|nice\"}[$__rate_interval])) or vector(0))",
     "legendFormat": "user"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{cluster=\"$cluster\", instance=\"$instance\", mode=\"iowait\"}[$__rate_interval]))",
     "legendFormat": "iowait"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{cluster=\"$cluster\", instance=\"$instance\", mode=~\"softirq|irq\"}[$__rate_interval]))",
     "legendFormat": "irq"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{cluster=\"$cluster\", instance=\"$instance\", mode=\"system\"}[$__rate_interval]))",
     "legendFormat": "system"
    },
    {
     "expr": "sum(rate(node_cpu_guest_seconds_total{cluster=\"$cluster\", instance=\"$instance\", mode=~\"user|nice\"}[$__rate_interval]))",
     "legendFormat": "guest"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{cluster=\"$cluster\", instance=\"$instance\", mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "Memory Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{cluster=\"$cluster\", instance=\"$instance\"}\r\n-\r\nnode_memory_SwapFree_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "swap"
    },
    {
     "expr": "node_memory_MemFree_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "free"
    },
    {
     "expr": "node_memory_MemTotal_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "capacity"
    },
    {
     "expr": "node_memory_MemTotal_bytes{cluster=\"$cluster\", instance=\"$instance\"}\r\n-\r\nnode_memory_MemFree_bytes{cluster=\"$cluster\", instance=\"$instance\"}\r\n-\r\n(\r\n    node_memory_Cached_bytes{cluster=\"$cluster\", instance=\"$instance\"}\r\n    +\r\n    node_memory_Buffers_bytes{cluster=\"$cluster\", instance=\"$instance\"}\r\n    +\r\n    node_memory_SReclaimable_bytes{cluster=\"$cluster\", instance=\"$instance\"}\r\n)",
     "legendFormat": "used"
    },
    {
     "expr": "node_memory_Cached_bytes{cluster=\"$cluster\", instance=\"$instance\"}\r\n+\r\nnode_memory_Buffers_bytes{cluster=\"$cluster\", instance=\"$instance\"}\r\n+\r\nnode_memory_SReclaimable_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "cache"
    }
   ]
  },
  {
   "title": "Network Receive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{cluster=\"$cluster\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Transmit",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{cluster=\"$cluster\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{device}} "
    }
   ]
  },
  {
   "title": "Pressure Stall Information",
   "type": "timeseries",
   "description": "https://docs.kernel.org/accounting/psi.html",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_pressure_cpu_waiting_seconds_total{cluster=\"$cluster\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "CPU some"
    },
    {
     "expr": "rate(node_pressure_memory_waiting_seconds_total{cluster=\"$cluster\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Memory some"
    },
    {
     "expr": "rate(node_pressure_memory_stalled_seconds_total{cluster=\"$cluster\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Memory full"
    },
    {
     "expr": "rate(node_pressure_io_waiting_seconds_total{cluster=\"$cluster\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "I/O some"
    },
    {
     "expr": "rate(node_pressure_io_stalled_seconds_total{cluster=\"$cluster\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "I/O full"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Disk Space Usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by (mountpoint) (node_filesystem_size_bytes{instance=\"$instance\", cluster=\"$cluster\", fstype!=\"\", mountpoint!=\"\"})\n"
    },
    {
     "expr": "max by (mountpoint) (node_filesystem_avail_bytes{instance=\"$instance\", cluster=\"$cluster\", fstype!=\"\", mountpoint!=\"\"})\n"
    }
   ]
  },
  {
   "title": "Disk Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{cluster=\"$cluster\", instance=\"$instance\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - ((node_filesystem_avail_bytes{cluster=\"$cluster\", instance=\"$instance\",device!~'rootfs'}) / node_filesystem_size_bytes{cluster=\"$cluster\", instance=\"$instance\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Read / Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{cluster=\"$cluster\", instance=\"$instance\",device=~\"$diskdevices\"}[$__rate_interval]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{cluster=\"$cluster\", instance=\"$instance\",device=~\"$diskdevices\"}[$__rate_interval]))",
     "legendFormat": "Write"
    }
   ]
  },
  { "title": "System Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Processes Forks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_forks_total{cluster=\"$cluster\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "forks"
    }
   ]
  },
  {
   "title": "Seconds running",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_schedstat_running_seconds_total{cluster=\"$cluster\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "CPU {{ cpu }}"
    }
   ]
  },
  {
   "title": "Context Switches / Interrupts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_context_switches_total{cluster=\"$cluster\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Context switches"
    },
    {
     "expr": "rate(node_intr_total{cluster=\"$cluster\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Interrupts"
    }
   ]
  },
  {
   "title": "Seconds Waiting",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_schedstat_waiting_seconds_total{cluster=\"$cluster\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "CPU {{ cpu }}"
    }
   ]
  },
  {
   "title": "Entropy",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_entropy_available_bits{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "Entropy available bits"
    }
   ]
  },
  {
   "title": "Schedule timeslices executed by each cpu",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_schedstat_timeslices_total{cluster=\"$cluster\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "CPU {{ cpu }}"
    }
   ]
  }
 ]
}