{
 "title": "Memory Details",
 "tags": [ "node" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "query_result(label_join(node_uname_info, \"human_name\", \"/\", \"cluster_type\", \"cluster\"))"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(node_uname_info{cluster=\"$cluster\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{cluster=\"$cluster\", instance=\"$instance\"}\r\n-\r\nnode_memory_SwapFree_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "swap"
    },
    {
     "expr": "node_memory_MemFree_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "free"
    },
    {
     "expr": "node_memory_MemTotal_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "capacity"
    },
    {
     "expr": "node_memory_MemTotal_bytes{cluster=\"$cluster\", instance=\"$instance\"}\r\n-\r\nnode_memory_MemFree_bytes{cluster=\"$cluster\", instance=\"$instance\"}\r\n-\r\n(\r\n    node_memory_Cached_bytes{cluster=\"$cluster\", instance=\"$instance\"}\r\n    +\r\n    node_memory_Buffers_bytes{cluster=\"$cluster\", instance=\"$instance\"}\r\n    +\r\n    node_memory_SReclaimable_bytes{cluster=\"$cluster\", instance=\"$instance\"}\r\n)",
     "legendFormat": "used"
    },
    {
     "expr": "node_memory_Cached_bytes{cluster=\"$cluster\", instance=\"$instance\"}\r\n+\r\nnode_memory_Buffers_bytes{cluster=\"$cluster\", instance=\"$instance\"}\r\n+\r\nnode_memory_SReclaimable_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "cache"
    }
   ]
  },
  {
   "title": "Pressure Stall Information",
   "type": "timeseries",
   "description": "https://docs.kernel.org/accounting/psi.html",
   "gridPos": { "h": 7, "w": 12, "x": 1, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_pressure_cpu_waiting_seconds_total{cluster=\"$cluster\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "CPU some"
    },
    {
     "expr": "rate(node_pressure_memory_waiting_seconds_total{cluster=\"$cluster\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Memory some"
    },
    {
     "expr": "rate(node_pressure_memory_stalled_seconds_total{cluster=\"$cluster\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Memory full"
    },
    {
     "expr": "rate(node_pressure_io_waiting_seconds_total{cluster=\"$cluster\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "I/O some"
    },
    {
     "expr": "rate(node_pressure_io_stalled_seconds_total{cluster=\"$cluster\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "I/O full"
    }
   ]
  },
  { "title": "Memory Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Memory Details",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{cluster=\"$cluster\", instance=\"$instance\"} - node_memory_MemFree_bytes{cluster=\"$cluster\", instance=\"$instance\"} - node_memory_Buffers_bytes{cluster=\"$cluster\", instance=\"$instance\"} - node_memory_Cached_bytes{cluster=\"$cluster\", instance=\"$instance\"} - node_memory_Slab_bytes{cluster=\"$cluster\", instance=\"$instance\"} - node_memory_PageTables_bytes{cluster=\"$cluster\", instance=\"$instance\"} - node_memory_SwapCached_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "user-space"
    },
    {
     "expr": "node_memory_PageTables_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "PageTables"
    },
    {
     "expr": "node_memory_SwapCached_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "SwapCache - pages fetched from swap but not yet modified"
    },
    {
     "expr": "node_memory_Slab_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "Slab - kernel cache (inode, dentry, etc)"
    },
    {
     "expr": "node_memory_Cached_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "File Cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "Buffers: block device cache"
    },
    {
     "expr": "node_memory_MemFree_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{cluster=\"$cluster\", instance=\"$instance\"} - node_memory_SwapFree_bytes{cluster=\"$cluster\", instance=\"$instance\"})",
     "legendFormat": "Swap"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "Hardware Corrupted"
    }
   ]
  },
  {
   "title": "Memory Active / Inactive Detail",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Inactive_file_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "Inactive file"
    },
    {
     "expr": "node_memory_Inactive_anon_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "Inactive anon"
    },
    {
     "expr": "node_memory_Active_file_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "Active file"
    },
    {
     "expr": "node_memory_Active_anon_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "Active anon"
    }
   ]
  },
  {
   "title": "Memory Committed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Committed_AS_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "Committed_AS"
    },
    {
     "expr": "node_memory_CommitLimit_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "CommitLimit"
    }
   ]
  },
  {
   "title": "Memory Shared and Mapped",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Mapped_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "Mapped files"
    },
    {
     "expr": "node_memory_Shmem_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "Shmem"
    },
    {
     "expr": "node_memory_ShmemHugePages_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "ShmemHugePages"
    },
    {
     "expr": "node_memory_ShmemPmdMapped_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "ShmemPmdMapped"
    }
   ]
  },
  {
   "title": "Memory Slab",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_SUnreclaim_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "Slab Unreclaim"
    },
    {
     "expr": "node_memory_SReclaimable_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "Slab Reclaimable"
    }
   ]
  },
  {
   "title": "Memory Vmalloc",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_VmallocUsed_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "VmallocUsed"
    }
   ]
  },
  {
   "title": "Memory Writeback and Dirty",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Writeback_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "Writeback"
    },
    {
     "expr": "node_memory_WritebackTmp_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "WritebackTmp"
    },
    {
     "expr": "node_memory_Dirty_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "Dirty"
    }
   ]
  },
  {
   "title": "Memory Anonymous",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_AnonHugePages_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "AnonHugePages"
    },
    {
     "expr": "node_memory_AnonPages_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "AnonPages"
    }
   ]
  },
  {
   "title": "Memory Bounce",
   "type": "timeseries",
   "description": "Memory used for block device bounce buffers",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Bounce_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "Bounce"
    }
   ]
  },
  {
   "title": "Memory HugePages Counter",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_memory_HugePages_Free{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "HugePages_Free"
    },
    {
     "expr": "node_memory_HugePages_Rsvd{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "HugePages Reserved"
    },
    {
     "expr": "node_memory_HugePages_Surp{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "HugePages Surplus"
    }
   ]
  },
  {
   "title": "Memory Kernel / CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_KernelStack_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "KernelStack"
    },
    {
     "expr": "node_memory_Percpu_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "PerCPU"
    }
   ]
  },
  {
   "title": "Memory DirectMap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_DirectMap1G_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "DirectMap1G"
    },
    {
     "expr": "node_memory_DirectMap2M_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "DirectMap2M"
    },
    {
     "expr": "node_memory_DirectMap4k_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "DirectMap4K"
    }
   ]
  },
  {
   "title": "Memory HugePages Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_HugePages_Total{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "HugePages Total"
    },
    {
     "expr": "node_memory_Hugepagesize_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "Hugepage Size"
    }
   ]
  },
  {
   "title": "Memory Unevictable and MLocked",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Unevictable_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "Unevictable"
    },
    {
     "expr": "node_memory_Mlocked_bytes{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "MLocked"
    }
   ]
  },
  { "title": "Memory Vmstat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Memory Pages In / Out",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_vmstat_pgpgin{cluster=\"$cluster\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Page in operations"
    },
    {
     "expr": "rate(node_vmstat_pgpgout{cluster=\"$cluster\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Page out operations"
    }
   ]
  },
  {
   "title": "Memory Pages Swap In / Out",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_vmstat_pswpin{cluster=\"$cluster\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Pages swapped in"
    },
    {
     "expr": "rate(node_vmstat_pswpout{cluster=\"$cluster\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Pages swapped out"
    }
   ]
  },
  {
   "title": "Memory Page Faults",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_vmstat_pgfault{cluster=\"$cluster\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Total"
    },
    {
     "expr": "rate(node_vmstat_pgmajfault{cluster=\"$cluster\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Major fault ops"
    },
    {
     "expr": "rate(node_vmstat_pgfault{cluster=\"$cluster\", instance=\"$instance\"}[$__rate_interval])  - rate(node_vmstat_pgmajfault{cluster=\"$cluster\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Minor fault ops"
    }
   ]
  },
  {
   "title": "OOM Killer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_vmstat_oom_kill{cluster=\"$cluster\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "OOM"
    }
   ]
  }
 ]
}