{
 "title": "Node / Filesystem",
 "tags": [ "node" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(node_uname_info[$__range])))"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(last_over_time(node_uname_info{location=~\"$location\"}[$__range]))"
    }
   },
   { "name": "filesystem_include" },
   { "name": "filesystem_exclude" },
   {
    "name": "fstype",
    "label": "FS type",
    "query": {
     "query": "query_result(node_filesystem_size_bytes{instance=\"$instance\", mountpoint=~\".*${filesystem_include}.*\", mountpoint!~\"${filesystem_exclude}\"})"
    }
   },
   {
    "name": "filesystem",
    "label": "Filesystem",
    "query": {
     "query": "query_result(node_filesystem_size_bytes{instance=\"$instance\", mountpoint=~\".*${filesystem_include}.*\", mountpoint!~\"${filesystem_exclude}\", fstype=~\"$fstype\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disk Space Usage",
   "type": "table",
   "gridPos": { "h": 21, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (mountpoint) (node_filesystem_size_bytes{instance=\"$instance\", fstype!=\"\", mountpoint=~\"$filesystem\"})"
    },
    {
     "expr": "max by (mountpoint) (node_filesystem_avail_bytes{instance=\"$instance\", fstype!=\"\", mountpoint=~\"$filesystem\"})"
    },
    {
     "expr": "max by(mountpoint, device) (\r\n  label_replace(\r\n    node_filesystem_size_bytes{instance=\"$instance\", device=~\"/dev/.*\", mountpoint=~\"$filesystem\"},\r\n    \"device\",\r\n    \"$1\",\r\n    \"device\",\r\n    \"^/dev/(.*)$\"\r\n  ) * 0\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(mountpoint, fstype) (\r\n  label_replace(\r\n    node_filesystem_size_bytes{instance=\"$instance\", mountpoint=~\"$filesystem\"},\r\n    \"device\",\r\n    \"$1\",\r\n    \"device\",\r\n    \"^/dev/(.*)$\"\r\n  ) * 0\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (mountpoint) (1 - node_filesystem_files_free{instance=\"$instance\",device!~'rootfs', mountpoint=~\"$filesystem\"} / node_filesystem_files)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filesystem Status",
   "type": "state-timeline",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "node_filesystem_readonly{instance=\"$instance\",device!~'rootfs', mountpoint=~\"$filesystem\"}",
     "legendFormat": "{{mountpoint}} - ReadOnly"
    },
    {
     "expr": "node_filesystem_device_error{instance=\"$instance\",device!~'rootfs',fstype!~'tmpfs', mountpoint=~\"$filesystem\"} + 2",
     "legendFormat": "{{mountpoint}} - Device error"
    }
   ]
  },
  {
   "title": "Pressure Stall Information",
   "type": "timeseries",
   "description": "https://docs.kernel.org/accounting/psi.html",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_pressure_cpu_waiting_seconds_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "CPU some"
    },
    {
     "expr": "rate(node_pressure_memory_waiting_seconds_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Memory some"
    },
    {
     "expr": "rate(node_pressure_memory_stalled_seconds_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Memory full"
    },
    {
     "expr": "rate(node_pressure_io_waiting_seconds_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "I/O some"
    },
    {
     "expr": "rate(node_pressure_io_stalled_seconds_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "I/O full"
    }
   ]
  },
  {
   "title": "Used inodes %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - node_filesystem_files_free{instance=\"$instance\",device!~'rootfs', mountpoint=~\"$filesystem\"} / node_filesystem_files",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "Filesystem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - ((node_filesystem_avail_bytes{instance=\"$instance\",device!~'rootfs', mountpoint=~\"$filesystem\"}) / node_filesystem_size_bytes)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$instance\",device!~'rootfs', mountpoint=~\"$filesystem\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Space available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"$instance\",device!~'rootfs', mountpoint=~\"$filesystem\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Space Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$instance\",device!~'rootfs', mountpoint=~\"$filesystem\"} - node_filesystem_avail_bytes",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "Block device statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Notes",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 1, "y": 48 },
   "options": {
    "content": "Block device statistics may be missing if the device backing the filesystem is not a disk."
   }
  },
  {
   "title": "I/O Utilization",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 6, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "label_replace(\r\n  node_filesystem_size_bytes{instance=\"$instance\", device=~\"/dev/.*\", mountpoint=~\"$filesystem\"},\r\n  \"device\",\r\n  \"$1\",\r\n  \"device\",\r\n  \"^/dev/(.*)$\"\r\n) * 0\r\n+ on(instance, device) group_right(fstype, mountpoint)\r\nrate(node_disk_io_time_seconds_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Read rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(\r\n  node_filesystem_size_bytes{instance=\"$instance\", device=~\"/dev/.*\", mountpoint=~\"$filesystem\"},\r\n  \"device\",\r\n  \"$1\",\r\n  \"device\",\r\n  \"^/dev/(.*)$\"\r\n) * 0\r\n+ on(instance, device) group_right(fstype, mountpoint)\r\nrate(node_disk_read_bytes_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Write rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(\r\n  node_filesystem_size_bytes{instance=\"$instance\", device=~\"/dev/.*\", mountpoint=~\"$filesystem\"},\r\n  \"device\",\r\n  \"$1\",\r\n  \"device\",\r\n  \"^/dev/(.*)$\"\r\n) * 0\r\n+ on(instance, device) group_right(fstype, mountpoint)\r\nrate(node_disk_written_bytes_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "IOps read",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "label_replace(\r\n  node_filesystem_size_bytes{instance=\"$instance\", device=~\"/dev/.*\", mountpoint=~\"$filesystem\"},\r\n  \"device\",\r\n  \"$1\",\r\n  \"device\",\r\n  \"^/dev/(.*)$\"\r\n) * 0\r\n+ on(instance, device) group_right(fstype, mountpoint)\r\nrate(node_disk_reads_completed_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "IOps write",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "label_replace(\r\n  node_filesystem_size_bytes{instance=\"$instance\", device=~\"/dev/.*\", mountpoint=~\"$filesystem\"},\r\n  \"device\",\r\n  \"$1\",\r\n  \"device\",\r\n  \"^/dev/(.*)$\"\r\n) * 0\r\n+ on(instance, device) group_right(fstype, mountpoint)\r\nrate(node_disk_writes_completed_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "IOps read merged",
   "type": "timeseries",
   "description": "The number of read and write requests merged per second that were queued to the device",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "label_replace(\r\n  node_filesystem_size_bytes{instance=\"$instance\", device=~\"/dev/.*\", mountpoint=~\"$filesystem\"},\r\n  \"device\",\r\n  \"$1\",\r\n  \"device\",\r\n  \"^/dev/(.*)$\"\r\n) * 0\r\n+ on(instance, device) group_right(fstype, mountpoint)\r\nrate(node_disk_reads_merged_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "IOps write merged",
   "type": "timeseries",
   "description": "The number of read and write requests merged per second that were queued to the device",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "label_replace(\r\n  node_filesystem_size_bytes{instance=\"$instance\", device=~\"/dev/.*\", mountpoint=~\"$filesystem\"},\r\n  \"device\",\r\n  \"$1\",\r\n  \"device\",\r\n  \"^/dev/(.*)$\"\r\n) * 0\r\n+ on(instance, device) group_right(fstype, mountpoint)\r\nrate(node_disk_writes_merged_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Average Wait Time - Read",
   "type": "timeseries",
   "description": "The average time for requests issued to the device to be served. This includes the time spent by the requests in queue and the time spent servicing them.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(\r\n  node_filesystem_size_bytes{instance=\"$instance\", device=~\"/dev/.*\", mountpoint=~\"$filesystem\"},\r\n  \"device\",\r\n  \"$1\",\r\n  \"device\",\r\n  \"^/dev/(.*)$\"\r\n) * 0\r\n+ on(instance, device) group_right(fstype, mountpoint)\r\nrate(node_disk_read_time_seconds_total{instance=\"$instance\"}[$__rate_interval]) / (rate(node_disk_reads_completed_total{instance=\"$instance\"}[$__rate_interval]) + 1e-6)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Average Wait Time - Write",
   "type": "timeseries",
   "description": "The average time for requests issued to the device to be served. This includes the time spent by the requests in queue and the time spent servicing them.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(\r\n  node_filesystem_size_bytes{instance=\"$instance\", device=~\"/dev/.*\", mountpoint=~\"$filesystem\"},\r\n  \"device\",\r\n  \"$1\",\r\n  \"device\",\r\n  \"^/dev/(.*)$\"\r\n) * 0\r\n+ on(instance, device) group_right(fstype, mountpoint)\r\nrate(node_disk_write_time_seconds_total{instance=\"$instance\"}[$__rate_interval]) / (rate(node_disk_writes_completed_total{instance=\"$instance\"}[$__rate_interval]) + 1e-6)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "IOps Discards completed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "label_replace(\r\n  node_filesystem_size_bytes{instance=\"$instance\", device=~\"/dev/.*\", mountpoint=~\"$filesystem\"},\r\n  \"device\",\r\n  \"$1\",\r\n  \"device\",\r\n  \"^/dev/(.*)$\"\r\n) * 0\r\n+ on(instance, device) group_right(fstype, mountpoint)\r\nrate(node_disk_discards_completed_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "IOps Discards merged",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "label_replace(\r\n  node_filesystem_size_bytes{instance=\"$instance\", device=~\"/dev/.*\", mountpoint=~\"$filesystem\"},\r\n  \"device\",\r\n  \"$1\",\r\n  \"device\",\r\n  \"^/dev/(.*)$\"\r\n) * 0\r\n+ on(instance, device) group_right(fstype, mountpoint)\r\nrate(node_disk_discards_merged_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Average Queue Size",
   "type": "timeseries",
   "description": "The average queue length of the requests that were issued to the device",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\r\n  node_filesystem_size_bytes{instance=\"$instance\", device=~\"/dev/.*\", mountpoint=~\"$filesystem\"},\r\n  \"device\",\r\n  \"$1\",\r\n  \"device\",\r\n  \"^/dev/(.*)$\"\r\n) * 0\r\n+ on(instance, device) group_right(fstype, mountpoint)\r\nrate(node_disk_io_time_weighted_seconds_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Time Spent Doing I/Os",
   "type": "timeseries",
   "description": "Percentage of elapsed time during which I/O requests were issued to the device (bandwidth utilization for the device). Device saturation occurs when this value is close to 100% for devices serving requests serially.  But for devices  serving requests in parallel, such as RAID arrays and modern SSDs, this number does not reflect their performance limits.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(\r\n  node_filesystem_size_bytes{instance=\"$instance\", device=~\"/dev/.*\", mountpoint=~\"$filesystem\"},\r\n  \"device\",\r\n  \"$1\",\r\n  \"device\",\r\n  \"^/dev/(.*)$\"\r\n) * 0\r\n+ on(instance, device) group_right(fstype, mountpoint)\r\nrate(node_disk_io_time_seconds_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Time spent in discard",
   "type": "timeseries",
   "description": "Percentage of elapsed time during which I/O requests were issued to the device (bandwidth utilization for the device). Device saturation occurs when this value is close to 100% for devices serving requests serially.  But for devices  serving requests in parallel, such as RAID arrays and modern SSDs, this number does not reflect their performance limits.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(\r\n  node_filesystem_size_bytes{instance=\"$instance\", device=~\"/dev/.*\", mountpoint=~\"$filesystem\"},\r\n  \"device\",\r\n  \"$1\",\r\n  \"device\",\r\n  \"^/dev/(.*)$\"\r\n) * 0\r\n+ on(instance, device) group_right(fstype, mountpoint)\r\nrate(node_disk_discard_time_seconds_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}