{
 "title": "Node / Health",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(node_hwmon_temp_celsius[$__range])))"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "query_result(group by(instance) (last_over_time(node_hwmon_temp_celsius{location=~\"$location\"}[$__range])))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "cpu governor",
   "type": "state-timeline",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by(cpu, governor) ((max_over_time(node_cpu_scaling_governor{instance=\"$instance\"}[$__interval]) == 1))\r\nor on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "temperature sensors",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max by(instance, chip, sensor) (node_hwmon_temp_celsius{instance=\"$instance\"})\r\n* on(instance, chip, sensor) group_right\r\nmax by(instance, chip, sensor, label) (node_hwmon_sensor_label{instance=\"$instance\"})\r\n* on(instance, chip) group_left(chip_name)\r\nmax by(instance, chip, chip_name) (node_hwmon_chip_names{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "memory errors (total)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(controller, csrow) (rate(node_edac_uncorrectable_errors_total{instance=\"$instance\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "controller {{controller}}: uncorrectable"
    },
    {
     "expr": "sum by(controller, csrow) (rate(node_edac_correctable_errors_total{instance=\"$instance\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "controller {{controller}}: correctable"
    }
   ]
  },
  {
   "title": "temperature (max)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by(chip, chip_name, label) (\r\n  max_over_time(node_hwmon_temp_celsius{instance=\"$instance\"}[$__interval])\r\n* on(chip, sensor) group_right()\r\nlast_over_time(node_hwmon_sensor_label{instance=\"$instance\"}[$__interval])\r\n* on(chip) group_left(chip_name)\r\nlast_over_time(node_hwmon_chip_names{instance=\"$instance\"}[$__interval])\r\n)",
     "legendFormat": "{{chip}}/{{chip_name}}/{{label}}"
    }
   ]
  },
  {
   "title": "core frequency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "min(min_over_time(node_cpu_scaling_frequency_hertz{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "Min core"
    },
    {
     "expr": "max(max_over_time(node_cpu_scaling_frequency_hertz{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "Max core"
    },
    {
     "expr": "avg(avg_over_time(node_cpu_scaling_frequency_hertz{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "Avg core"
    },
    {
     "expr": "max(node_cpu_scaling_frequency_max_hertz{instance=\"$instance\"})",
     "legendFormat": "max"
    },
    {
     "expr": "min(node_cpu_scaling_frequency_min_hertz{instance=\"$instance\"})",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "temperature (avg)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by(chip, chip_name, label) (\r\n  avg_over_time(node_hwmon_temp_celsius{instance=\"$instance\"}[$__interval])\r\n* on(chip, sensor) group_right()\r\nlast_over_time(node_hwmon_sensor_label{instance=\"$instance\"}[$__interval])\r\n* on(chip) group_left(chip_name)\r\nlast_over_time(node_hwmon_chip_names{instance=\"$instance\"}[$__interval])\r\n)",
     "legendFormat": "{{chip}}/{{chip_name}}/{{label}}"
    }
   ]
  },
  {
   "title": "throttling (total events)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_package_throttles_total{instance=\"$instance\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "throttling"
    }
   ]
  }
 ]
}