{
 "title": "Node / CPU details",
 "tags": [ "node" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(node_uname_info[$__range])))"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "query_result(group by(instance) (last_over_time(node_uname_info{location=~\"$location\"}[$__range])))"
    }
   },
   {
    "name": "cpu",
    "query": {
     "query": "query_result(group by(cpu) (last_over_time(node_schedstat_running_seconds_total{instance=~\"$instance\"}[$__range])))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Overview",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "# usually this should not exist,\r\n# but in case node-exporter adds a new value for mode, show it\r\nsum by(mode) (rate(node_cpu_seconds_total{instance=\"$instance\", cpu=~\"$cpu\", mode!~\"system|user|nice|iowait|softirq|irq|idle|steal|interrupt\"}[$__rate_interval]))",
     "legendFormat": "Other: {{mode}}"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{instance=\"$instance\", cpu=~\"$cpu\", mode=\"steal\"}[$__rate_interval]))",
     "legendFormat": "steal"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{instance=\"$instance\", cpu=~\"$cpu\", mode=\"interrupt\"}[$__rate_interval]))",
     "legendFormat": "interrupt"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{instance=\"$instance\", cpu=~\"$cpu\", mode=~\"user|nice\"}[$__rate_interval])) - (sum(rate(node_cpu_guest_seconds_total{instance=\"$instance\", cpu=~\"$cpu\", mode=~\"user|nice\"}[$__rate_interval])) or vector(0))",
     "legendFormat": "user"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{instance=\"$instance\", cpu=~\"$cpu\", mode=\"iowait\"}[$__rate_interval]))",
     "legendFormat": "iowait"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{instance=\"$instance\", cpu=~\"$cpu\", mode=~\"softirq|irq\"}[$__rate_interval]))",
     "legendFormat": "irq"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{instance=\"$instance\", cpu=~\"$cpu\", mode=\"system\"}[$__rate_interval]))",
     "legendFormat": "system"
    },
    {
     "expr": "sum(rate(node_cpu_guest_seconds_total{instance=\"$instance\", cpu=~\"$cpu\", mode=~\"user|nice\"}[$__rate_interval]))",
     "legendFormat": "guest"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{instance=\"$instance\", cpu=~\"$cpu\", mode=~\"system|user|nice|iowait|softirq|irq\"}[$__rate_interval]))",
     "legendFormat": "full usage"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{instance=\"$instance\", cpu=~\"$cpu\", mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "idle"
    },
    {
     "expr": "count(node_cpu_seconds_total{instance=\"$instance\", cpu=~\"$cpu\", mode=\"idle\"})",
     "legendFormat": "cores"
    }
   ]
  },
  {
   "title": "Pressure Stall Information",
   "type": "timeseries",
   "description": "https://docs.kernel.org/accounting/psi.html",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(node_pressure_cpu_waiting_seconds_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "CPU some"
    },
    {
     "expr": "sum(rate(node_pressure_memory_waiting_seconds_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Memory some"
    },
    {
     "expr": "sum(rate(node_pressure_memory_stalled_seconds_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Memory full"
    },
    {
     "expr": "sum(rate(node_pressure_io_waiting_seconds_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "I/O some"
    },
    {
     "expr": "sum(rate(node_pressure_io_stalled_seconds_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "I/O full"
    }
   ]
  },
  {
   "title": "processes forks (without cpu selector)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(node_forks_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "forks"
    }
   ]
  },
  {
   "title": "context switches / Interrupts (without cpu selector)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(node_context_switches_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Context switches"
    },
    {
     "expr": "sum(rate(node_intr_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Interrupts"
    }
   ]
  },
  { "title": "per-cpu breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Core frequency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "min(min_over_time(node_cpu_scaling_frequency_hertz{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "Min core"
    },
    {
     "expr": "max(max_over_time(node_cpu_scaling_frequency_hertz{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "Max core"
    },
    {
     "expr": "avg(avg_over_time(node_cpu_scaling_frequency_hertz{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "Avg core"
    },
    {
     "expr": "max(node_cpu_scaling_frequency_max_hertz{instance=\"$instance\"})",
     "legendFormat": "max"
    },
    {
     "expr": "min(node_cpu_scaling_frequency_min_hertz{instance=\"$instance\"})",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Core frequency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "avg by(cpu) (avg_over_time(node_cpu_scaling_frequency_hertz{instance=\"$instance\", cpu=~\"$cpu\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "timeslices executed by cpu",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(cpu) (rate(node_schedstat_timeslices_total{instance=\"$instance\", cpu=~\"$cpu\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cpu governor",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "max by(cpu, governor) (\r\n  (max_over_time(node_cpu_scaling_governor{instance=\"$instance\", cpu=~\"$cpu\"}[$__interval]) == 1)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Seconds running by cpu",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(cpu) (rate(node_schedstat_running_seconds_total{instance=\"$instance\", cpu=~\"$cpu\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Seconds Waiting by cpu",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(cpu) (rate(node_schedstat_waiting_seconds_total{instance=\"$instance\", cpu=~\"$cpu\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}