{
 "title": "Disk Details",
 "tags": [ "node" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "query_result(label_join(node_uname_info, \"human_name\", \"/\", \"cluster_type\", \"cluster\"))"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(node_uname_info{cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "device_type",
    "label": "Device type",
    "query": "scsi : sd[a-z]+, scsi partition : sd[a-z]+[0-9]+, nvme : nvme[0-9]+n[0-9]+, nvme partition : nvme[0-9]+n[0-9]+p[0-9]+, mmc : mmcblk[0-9]+, zfs volume : zd.*"
   },
   {
    "name": "device",
    "label": "Device",
    "query": {
     "query": "query_result(node_disk_reads_completed_total{instance=\"$instance\", device=~\"${device_type:pipe}\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "I/O time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=\"$instance\", device=~\"$device\"}[$__rate_interval]) * on(instance, device) group_left(model, serial) node_disk_info{serial!=\"\"}",
     "legendFormat": "{{device}} {{model}} {{serial}}"
    },
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=\"$instance\", device=~\"$device\"}[$__rate_interval]) * on(instance, device) group_left(model, serial) node_disk_info{serial=\"\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Pressure Stall Information",
   "type": "timeseries",
   "description": "https://docs.kernel.org/accounting/psi.html",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_pressure_cpu_waiting_seconds_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "CPU some"
    },
    {
     "expr": "rate(node_pressure_memory_waiting_seconds_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Memory some"
    },
    {
     "expr": "rate(node_pressure_memory_stalled_seconds_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Memory full"
    },
    {
     "expr": "rate(node_pressure_io_waiting_seconds_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "I/O some"
    },
    {
     "expr": "rate(node_pressure_io_stalled_seconds_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "I/O full"
    }
   ]
  },
  { "title": "i/o", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "IOps read",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance=\"$instance\", device=~\"$device\"}[$__rate_interval]) * on(instance, device) group_left(model, serial) node_disk_info{serial!=\"\"}",
     "legendFormat": "{{device}} {{model}} {{serial}}"
    },
    {
     "expr": "rate(node_disk_reads_completed_total{instance=\"$instance\", device=~\"$device\"}[$__rate_interval]) * on(instance, device) group_left(model, serial) node_disk_info{serial=\"\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "IOps write",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(node_disk_writes_completed_total{instance=\"$instance\", device=~\"$device\"}[$__rate_interval]) * on(instance, device) group_left(model, serial) node_disk_info{serial!=\"\"}",
     "legendFormat": "{{device}} {{model}} {{serial}}"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{instance=\"$instance\", device=~\"$device\"}[$__rate_interval]) * on(instance, device) group_left(model, serial) node_disk_info{serial=\"\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "IOps read merged",
   "type": "timeseries",
   "description": "The number of read and write requests merged per second that were queued to the device",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_merged_total{instance=\"$instance\", device=~\"$device\"}[$__rate_interval]) * on(instance, device) group_left(model, serial) node_disk_info{serial!=\"\"}",
     "legendFormat": "{{device}} {{model}} {{serial}}"
    },
    {
     "expr": "rate(node_disk_reads_merged_total{instance=\"$instance\", device=~\"$device\"}[$__rate_interval]) * on(instance, device) group_left(model, serial) node_disk_info{serial=\"\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "IOps write merged",
   "type": "timeseries",
   "description": "The number of read and write requests merged per second that were queued to the device",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(node_disk_writes_merged_total{instance=\"$instance\", device=~\"$device\"}[$__rate_interval]) * on(instance, device) group_left(model, serial) node_disk_info{serial!=\"\"}",
     "legendFormat": "{{device}} {{model}} {{serial}}"
    },
    {
     "expr": "rate(node_disk_writes_merged_total{instance=\"$instance\", device=~\"$device\"}[$__rate_interval]) * on(instance, device) group_left(model, serial) node_disk_info{serial=\"\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "IOps Discards completed",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(node_disk_discards_completed_total{instance=\"$instance\", device=~\"$device\"}[$__rate_interval]) * on(instance, device) group_left(model, serial) node_disk_info{serial!=\"\"}",
     "legendFormat": "{{device}} {{model}} {{serial}}"
    },
    {
     "expr": "rate(node_disk_discards_completed_total{instance=\"$instance\", device=~\"$device\"}[$__rate_interval]) * on(instance, device) group_left(model, serial) node_disk_info{serial=\"\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "IOps Discards merged",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(node_disk_discards_merged_total{instance=\"$instance\", device=~\"$device\"}[$__rate_interval]) * on(instance, device) group_left(model, serial) node_disk_info{serial!=\"\"}",
     "legendFormat": "{{device}} {{model}} {{serial}}"
    },
    {
     "expr": "rate(node_disk_discards_merged_total{instance=\"$instance\", device=~\"$device\"}[$__rate_interval]) * on(instance, device) group_left(model, serial) node_disk_info{serial=\"\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "Storage Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Read bytes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=\"$instance\", device=~\"$device\"}[$__rate_interval]) * on(instance, device) group_left(model, serial) node_disk_info{serial!=\"\"}",
     "legendFormat": "{{device}} {{model}} {{serial}}"
    },
    {
     "expr": "rate(node_disk_read_bytes_total{instance=\"$instance\", device=~\"$device\"}[$__rate_interval]) * on(instance, device) group_left(model, serial) node_disk_info{serial=\"\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "average read wait time",
   "type": "timeseries",
   "description": "The average time for requests issued to the device to be served. This includes the time spent by the requests in queue and the time spent servicing them.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{instance=\"$instance\", device=~\"$device\"}[$__rate_interval]) / (rate(node_disk_reads_completed_total[$__rate_interval]) + 1e-6) * on(instance, device) group_left(model, serial) node_disk_info{serial!=\"\"}",
     "legendFormat": "{{device}} {{model}} {{serial}}"
    },
    {
     "expr": "rate(node_disk_read_time_seconds_total{instance=\"$instance\", device=~\"$device\"}[$__rate_interval]) / (rate(node_disk_reads_completed_total[$__rate_interval]) + 1e-6) * on(instance, device) group_left(model, serial) node_disk_info{serial=\"\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Write bytes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{instance=\"$instance\", device=~\"$device\"}[$__rate_interval]) * on(instance, device) group_left(model, serial) node_disk_info{serial!=\"\"}",
     "legendFormat": "{{device}} {{model}} {{serial}}"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance=\"$instance\", device=~\"$device\"}[$__rate_interval]) * on(instance, device) group_left(model, serial) node_disk_info{serial=\"\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "average write wait time",
   "type": "timeseries",
   "description": "The average time for requests issued to the device to be served. This includes the time spent by the requests in queue and the time spent servicing them.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_disk_write_time_seconds_total{instance=\"$instance\", device=~\"$device\"}[$__rate_interval]) / (rate(node_disk_writes_completed_total[$__rate_interval]) + 1e-6) * on(instance, device) group_left(model, serial) node_disk_info{serial!=\"\"}",
     "legendFormat": "{{device}} {{model}} {{serial}}"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{instance=\"$instance\", device=~\"$device\"}[$__rate_interval]) / (rate(node_disk_writes_completed_total[$__rate_interval]) + 1e-6) * on(instance, device) group_left(model, serial) node_disk_info{serial=\"\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Average Queue Size",
   "type": "timeseries",
   "description": "The average queue length of the requests that were issued to the device",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_weighted_seconds_total{instance=\"$instance\", device=~\"$device\"}[$__rate_interval]) * on(instance, device) group_left(model, serial) node_disk_info{serial!=\"\"}",
     "legendFormat": "{{device}} {{model}} {{serial}}"
    },
    {
     "expr": "rate(node_disk_io_time_weighted_seconds_total{instance=\"$instance\", device=~\"$device\"}[$__rate_interval]) * on(instance, device) group_left(model, serial) node_disk_info{serial=\"\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "average IO wait time",
   "type": "timeseries",
   "description": "Percentage of elapsed time during which I/O requests were issued to the device (bandwidth utilization for the device). Device saturation occurs when this value is close to 100% for devices serving requests serially.  But for devices  serving requests in parallel, such as RAID arrays and modern SSDs, this number does not reflect their performance limits.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=\"$instance\", device=~\"$device\"}[$__rate_interval]) * on(instance, device) group_left(model, serial) node_disk_info{serial!=\"\"}",
     "legendFormat": "{{device}} {{model}} {{serial}}"
    },
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=\"$instance\", device=~\"$device\"}[$__rate_interval]) * on(instance, device) group_left(model, serial) node_disk_info{serial=\"\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Instantaneous Queue Size",
   "type": "timeseries",
   "description": "The number of outstanding requests at the instant the sample was taken. Incremented as requests are given to appropriate struct request_queue and decremented as they finish.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max_over_time(node_disk_io_now{instance=\"$instance\", device=~\"$device\"}[$__interval]) * on(instance, device) group_left(model, serial) node_disk_info{serial!=\"\"}",
     "legendFormat": "{{device}} {{model}} {{serial}}"
    },
    {
     "expr": "max_over_time(node_disk_io_now{instance=\"$instance\", device=~\"$device\"}[$__interval]) * on(instance, device) group_left(model, serial) node_disk_info{serial=\"\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "average discard wait time",
   "type": "timeseries",
   "description": "Percentage of elapsed time during which I/O requests were issued to the device (bandwidth utilization for the device). Device saturation occurs when this value is close to 100% for devices serving requests serially.  But for devices  serving requests in parallel, such as RAID arrays and modern SSDs, this number does not reflect their performance limits.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "rate(node_disk_discard_time_seconds_total{instance=\"$instance\", device=~\"$device\"}[$__rate_interval]) * on(instance, device) group_left(model, serial) node_disk_info{serial!=\"\"}",
     "legendFormat": "{{device}} {{model}} {{serial}}"
    },
    {
     "expr": "rate(node_disk_discard_time_seconds_total{instance=\"$instance\", device=~\"$device\"}[$__rate_interval]) * on(instance, device) group_left(model, serial) node_disk_info{serial=\"\"}",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}