{
 "title": "Node multi-instance",
 "tags": [ "node" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "query_result(label_join(last_over_time(node_uname_info[$__range]), \"human_name\", \"/\", \"cluster_type\", \"cluster\") or label_join(last_over_time(windows_system_boot_time_timestamp[$__range]), \"human_name\", \"/\", \"cluster_type\", \"cluster\"))"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(last_over_time(node_uname_info{cluster=~\"$cluster\"}[$__range]) or last_over_time(windows_system_boot_time_timestamp{cluster=~\"$cluster\"}[$__range]))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "info",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "count by(cluster, instance) (last_over_time(node_scrape_collector_success{instance=~\"$instance\"}[$__range]))\r\nor\r\ncount by(cluster, instance) (last_over_time(windows_exporter_collector_success{instance=~\"$instance\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by(cluster, instance) (last_over_time(node_scrape_collector_success{instance=~\"$instance\"}[$__range]) == 0)\r\nor\r\ncount by(cluster, instance) (last_over_time(windows_exporter_collector_success{instance=~\"$instance\"}[$__range]) == 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(cluster, instance) (\r\n  (node_time_seconds{instance=~\"$instance\"} + time() - timestamp(node_time_seconds))\r\n  or\r\n  last_over_time(node_time_seconds{instance=~\"$instance\"}[$__range])\r\n) * 1000\r\nor\r\nmax by(cluster, instance) (\r\n  (windows_time_current_timestamp_seconds{instance=~\"$instance\"} + time() - timestamp(windows_time_current_timestamp_seconds))\r\n  or\r\n  last_over_time(windows_time_current_timestamp_seconds{instance=~\"$instance\"}[$__range])\r\n) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(cluster, instance) (\r\n  (node_time_seconds{instance=~\"$instance\"} - timestamp(node_time_seconds))\r\n)\r\nor\r\nmax by(cluster, instance) (\r\n  (windows_time_current_timestamp_seconds{instance=~\"$instance\"} - timestamp(windows_time_current_timestamp_seconds))\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(cluster, instance) (last_over_time(node_boot_time_seconds{instance=~\"$instance\"}[$__range])) * 1000\r\nor\r\nmax by(cluster, instance) (last_over_time(windows_system_boot_time_timestamp{instance=~\"$instance\"}[$__range])) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - max by(cluster, instance) (last_over_time(node_boot_time_seconds{instance=~\"$instance\"}[$__range]))\r\nor\r\ntime() - max by(cluster, instance) (last_over_time(windows_system_boot_time_timestamp{instance=~\"$instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "status",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "max by(cluster, instance) (min_over_time(up{job=~\"node-exporter\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "{{cluster}}/{{instance}}"
    },
    {
     "expr": "# this is a separate query to keep a consistent order or instances in match with \"boot time\" timeline\r\nmax by(cluster, instance) (min_over_time(up{job=\"windows-exporter\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "{{cluster}}/{{instance}}"
    }
   ]
  },
  {
   "title": "boot time (ago)",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "$__to / 1000 - max by(cluster, instance) (max_over_time(node_boot_time_seconds{instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "{{cluster}}/{{instance}}"
    },
    {
     "expr": "$__to / 1000 - max by(cluster, instance) (max_over_time(windows_system_boot_time_timestamp{instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "{{cluster}}/{{instance}}"
    }
   ]
  },
  {
   "title": "time offset",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(cluster, instance) (\r\n  (node_time_seconds{instance=~\"$instance\"} - timestamp(node_time_seconds))\r\n)\r\nor\r\nmax by(cluster, instance) (\r\n  (windows_time_current_timestamp_seconds{instance=~\"$instance\"} - timestamp(windows_time_current_timestamp_seconds))\r\n)",
     "legendFormat": "{{cluster}}/{{instance}}"
    }
   ]
  },
  {
   "title": "uptime",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - max by(cluster, instance) (last_over_time(node_boot_time_seconds{instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "{{cluster}}/{{instance}}"
    },
    {
     "expr": "time() - max by(cluster, instance) (last_over_time(windows_system_boot_time_timestamp{instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "{{cluster}}/{{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(cluster, instance) (avg_over_time(instance_mode:node_cpu_seconds:irate{instance=~\"$instance\", mode!~\"idle|steal\"}[$__interval]))",
     "legendFormat": "{{cluster}}/{{instance}}"
    },
    {
     "expr": "sum by(cluster, instance) (avg_over_time(instance_mode:windows_cpu_time:irate{instance=~\"$instance\", mode!=\"idle\"}[$__interval]))",
     "legendFormat": "{{cluster}}/{{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage %",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(cluster, instance) (avg_over_time(instance_mode:node_cpu_seconds:irate{instance=~\"$instance\", mode!~\"idle|steal\"}[$__interval]) / on(instance) group_left() node:cpu_cores)",
     "legendFormat": "{{cluster}}/{{instance}}"
    },
    {
     "expr": "sum by(cluster, instance) (avg_over_time(instance_mode:windows_cpu_time:irate{instance=~\"$instance\", mode!~\"idle|steal\"}[$__interval]) / on(instance) group_left() node:cpu_cores)",
     "legendFormat": "{{cluster}}/{{instance}}"
    }
   ]
  },
  {
   "title": "memory usage %",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(cluster, instance) (\r\n(\r\nnode_memory_MemTotal_bytes{instance=~\"$instance\"}\r\n-\r\nnode_memory_MemFree_bytes\r\n-\r\n(\r\n    node_memory_Cached_bytes\r\n    +\r\n    node_memory_Buffers_bytes\r\n    +\r\n    node_memory_SReclaimable_bytes\r\n)\r\n- (node_zfs_arc_size or node_memory_MemTotal_bytes * 0)\r\n) / node_memory_MemTotal_bytes\r\n)",
     "legendFormat": "{{cluster}}/{{instance}}"
    },
    {
     "expr": "max by(cluster, instance) (\r\n(\r\nnode_memory_size_bytes{instance=~\"$instance\"}\r\n-\r\nnode_memory_free_bytes\r\n-\r\n(\r\n    node_memory_inactive_bytes\r\n    +\r\n    node_memory_cache_bytes\r\n    +\r\n    node_memory_buffer_bytes\r\n)\r\n) / node_memory_size_bytes\r\n)",
     "legendFormat": "{{cluster}}/{{instance}}"
    },
    {
     "expr": "max by(cluster, instance) (\r\n(\r\nwindows_memory_physical_total_bytes{instance=~\"$instance\"}\r\n-\r\nwindows_memory_available_bytes\r\n) / windows_memory_physical_total_bytes\r\n)",
     "legendFormat": "{{cluster}}/{{instance}}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "Disk Space Usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by (mountpoint) (node_filesystem_size_bytes{instance=\"$instance\", fstype!=\"\", mountpoint!=\"\"})\n"
    },
    {
     "expr": "max by (mountpoint) (node_filesystem_avail_bytes{instance=\"$instance\", fstype!=\"\", mountpoint!=\"\"})\n"
    }
   ]
  },
  {
   "title": "Disk Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$instance\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - ((node_filesystem_avail_bytes{instance=\"$instance\",device!~'rootfs'}) / node_filesystem_size_bytes{instance=\"$instance\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Read / Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{instance=\"$instance\",device=~\"[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+\"}[$__rate_interval]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{instance=\"$instance\",device=~\"[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+\"}[$__rate_interval]))",
     "legendFormat": "Write"
    }
   ]
  },
  { "title": "System Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 } },
  {
   "title": "Processes Forks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_forks_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "forks"
    }
   ]
  },
  {
   "title": "Seconds running",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_schedstat_running_seconds_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "CPU {{ cpu }}"
    }
   ]
  },
  {
   "title": "Context Switches / Interrupts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_context_switches_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Context switches"
    },
    {
     "expr": "rate(node_intr_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Interrupts"
    }
   ]
  },
  {
   "title": "Seconds Waiting",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_schedstat_waiting_seconds_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "CPU {{ cpu }}"
    }
   ]
  },
  {
   "title": "Entropy",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_entropy_available_bits{instance=\"$instance\"}",
     "legendFormat": "Entropy available bits"
    }
   ]
  },
  {
   "title": "Schedule timeslices executed by each cpu",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_schedstat_timeslices_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "CPU {{ cpu }}"
    }
   ]
  }
 ]
}