{
 "title": "3x-ui instance details",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(x_ui_total_online_users[$__range])))"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(count_over_time(x_ui_total_online_users{location=~\"$location\"}[$__range]))"
    }
   },
   { "name": "inbound_filter" },
   {
    "name": "inbound_id",
    "label": "inbound",
    "query": {
     "query": "query_result(label_join(count_over_time(x_ui_inbound_down_bytes{instance=~\"$instance\", remark=~\".*($inbound_filter).*\"}[$__range]), \"human_name\", \"/\", \"id\", \"remark\"))"
    }
   }
  ]
 },
 "panels": [
  { "title": "overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "xray version history",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max by(instance, version) (last_over_time(x_ui_xray_version{instance=\"$instance\"}[$__interval]))\r\nor vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "inbounds traffic",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(id, remark) (increase(x_ui_inbound_down_bytes{instance=~\"$instance\", id=~\"$inbound_id\"}[$__range]))"
    },
    {
     "expr": "sum by(id, remark) (last_over_time(x_ui_inbound_down_bytes{instance=~\"$instance\", id=~\"$inbound_id\"}[$__range]))"
    },
    {
     "expr": "sum by(id, remark) (increase(x_ui_inbound_up_bytes{instance=~\"$instance\", id=~\"$inbound_id\"}[$__range]))"
    },
    {
     "expr": "sum by(id, remark) (last_over_time(x_ui_inbound_up_bytes{instance=~\"$instance\", id=~\"$inbound_id\"}[$__range]))"
    }
   ]
  },
  {
   "title": "instance throughput total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(x_ui_inbound_down_bytes{instance=~\"$instance\", id=~\"$inbound_id\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "down"
    },
    {
     "expr": "sum by(instance) (rate(x_ui_inbound_up_bytes{instance=~\"$instance\", id=~\"$inbound_id\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "up"
    }
   ]
  },
  {
   "title": "client traffic",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(id, email) (increase(x_ui_client_down_bytes{instance=~\"$instance\", id=~\"$inbound_id\"}[$__range]))"
    },
    {
     "expr": "sum by(id, email) (last_over_time(x_ui_client_down_bytes{instance=~\"$instance\", id=~\"$inbound_id\"}[$__range]))"
    },
    {
     "expr": "sum by(id, email) (increase(x_ui_client_up_bytes{instance=~\"$instance\", id=~\"$inbound_id\"}[$__range]))"
    },
    {
     "expr": "sum by(id, email) (last_over_time(x_ui_client_up_bytes{instance=~\"$instance\", id=~\"$inbound_id\"}[$__range]))"
    }
   ]
  },
  {
   "title": "instance throughput rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(x_ui_inbound_down_bytes{instance=~\"$instance\", id=~\"$inbound_id\"}[$__rate_interval]))",
     "legendFormat": "down"
    },
    {
     "expr": "sum by(instance) (rate(x_ui_inbound_up_bytes{instance=~\"$instance\", id=~\"$inbound_id\"}[$__rate_interval]))",
     "legendFormat": "up"
    }
   ]
  },
  { "title": "inbounds", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "down total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(id, remark) (rate(x_ui_inbound_down_bytes{instance=~\"$instance\", id=~\"$inbound_id\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "{{id}}/{{remark}}"
    }
   ]
  },
  {
   "title": "down rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(id, remark) (rate(x_ui_inbound_down_bytes{instance=~\"$instance\", id=~\"$inbound_id\"}[$__rate_interval]))",
     "legendFormat": "{{id}}/{{remark}}"
    }
   ]
  },
  {
   "title": "up total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(id, remark) (rate(x_ui_inbound_up_bytes{instance=~\"$instance\", id=~\"$inbound_id\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "{{id}}/{{remark}}"
    }
   ]
  },
  {
   "title": "up rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(id, remark) (rate(x_ui_inbound_up_bytes{instance=~\"$instance\", id=~\"$inbound_id\"}[$__rate_interval]))",
     "legendFormat": "{{id}}/{{remark}}"
    }
   ]
  },
  { "title": "clients", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "down total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(id, email) (rate(x_ui_client_down_bytes{instance=~\"$instance\", id=~\"$inbound_id\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "{{id}}/{{email}}"
    }
   ]
  },
  {
   "title": "up rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(id, email) (rate(x_ui_client_up_bytes{instance=~\"$instance\", id=~\"$inbound_id\"}[$__rate_interval]))",
     "legendFormat": "{{id}}/{{email}}"
    }
   ]
  },
  {
   "title": "up total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(id, email) (rate(x_ui_client_up_bytes{instance=~\"$instance\", id=~\"$inbound_id\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "{{id}}/{{email}}"
    }
   ]
  },
  {
   "title": "down rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(id, email) (rate(x_ui_client_down_bytes{instance=~\"$instance\", id=~\"$inbound_id\"}[$__rate_interval]))",
     "legendFormat": "{{id}}/{{email}}"
    }
   ]
  }
 ]
}