{
 "title": "3x-ui multi-instance",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(x_ui_total_online_users[$__range])))"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(count_over_time(x_ui_total_online_users{location=~\"$location\"}[$__range]))"
    }
   },
   { "name": "inbound_filter" },
   {
    "name": "inbound_id",
    "label": "inbound",
    "query": {
     "query": "query_result(label_join(count_over_time(x_ui_inbound_down_bytes{instance=~\"$instance\", remark=~\".*($inbound_filter).*\"}[$__range]), \"human_name\", \"/\", \"id\", \"remark\"))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(x_ui_total_online_users{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by(location, instance) (x_ui_panel_uptime{instance=~\"$instance\"})"
    },
    {
     "expr": "max by(location, instance, version) (x_ui_xray_version{instance=~\"$instance\"})"
    },
    {
     "expr": "sum by(location, instance) (increase(x_ui_inbound_down_bytes{instance=~\"$instance\"}[$__range]))"
    },
    {
     "expr": "sum by(location, instance) (increase(x_ui_inbound_up_bytes{instance=~\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "inbounds",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(location, instance, id, remark) (increase(x_ui_inbound_down_bytes{instance=~\"$instance\", id=~\"$inbound_id\"}[$__range]))"
    },
    {
     "expr": "sum by(location, instance, id, remark) (increase(x_ui_inbound_up_bytes{instance=~\"$instance\", id=~\"$inbound_id\"}[$__range]))"
    }
   ]
  },
  {
   "title": "throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(x_ui_inbound_down_bytes{instance=~\"$instance\", id=~\"$inbound_id\"}[$__rate_interval]))",
     "legendFormat": "down ${{instance}}"
    },
    {
     "expr": "sum by(instance) (rate(x_ui_inbound_up_bytes{instance=~\"$instance\", id=~\"$inbound_id\"}[$__rate_interval]))",
     "legendFormat": "up ${{instance}}"
    },
    {
     "expr": "sum(quantile_over_time(0.99, dimension:v2ray_traffic_downlink_bytes_total:irate{instance=~\"$instance\", dimension=\"inbound\"}[$__rate_interval]))",
     "legendFormat": "Downlink p99"
    },
    {
     "expr": "sum(quantile_over_time(0.99, dimension:v2ray_traffic_uplink_bytes_total:irate{instance=~\"$instance\", dimension=\"inbound\"}[$__rate_interval]))",
     "legendFormat": "Uplink p99"
    }
   ]
  },
  { "title": "$instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }, "repeat": "instance" },
  {
   "title": "down total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(id, remark) (rate(x_ui_inbound_down_bytes{instance=~\"$instance\", id=~\"$inbound_id\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "{{id}}/{{remark}}"
    }
   ]
  },
  {
   "title": "up total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(id, remark) (rate(x_ui_inbound_up_bytes{instance=~\"$instance\", id=~\"$inbound_id\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "{{id}}/{{remark}}"
    }
   ]
  },
  {
   "title": "Down speed / avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(id, remark) (rate(x_ui_inbound_down_bytes{instance=~\"$instance\", id=~\"$inbound_id\"}[$__rate_interval]))",
     "legendFormat": "{{id}}/{{remark}}"
    }
   ]
  },
  {
   "title": "Up speed / avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(id, remark) (rate(x_ui_inbound_up_bytes{instance=~\"$instance\", id=~\"$inbound_id\"}[$__rate_interval]))",
     "legendFormat": "{{id}}/{{remark}}"
    }
   ]
  },
  {
   "title": "Down speed / p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(dimension, target) (quantile_over_time(0.95, v2ray_traffic_downlink_bytes_total:irate{instance=~\"$instance\", target=~\"$target\"}[$__rate_interval]))",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Up speed / p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(dimension, target) (quantile_over_time(0.95, v2ray_traffic_uplink_bytes_total:irate{instance=~\"$instance\", target=~\"$target\"}[$__rate_interval]))",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Down speed / p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(dimension, target) (quantile_over_time(0.99, v2ray_traffic_downlink_bytes_total:irate{instance=~\"$instance\", target=~\"$target\"}[$__rate_interval]))",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Up speed / p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(dimension, target) (quantile_over_time(0.99, v2ray_traffic_uplink_bytes_total:irate{instance=~\"$instance\", target=~\"$target\"}[$__rate_interval]))",
     "legendFormat": "{{target}}"
    }
   ]
  }
 ]
}