{
 "title": "etcd",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "query_result(label_join(up{job=\"etcd\"}, \"human_name\", \"/\", \"cluster_type\", \"cluster\"))"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(etcd_server_has_leader,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(etcd_server_has_leader{cluster=\"$cluster\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk sync duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (instance) (max_over_time(etcd_disk_wal_fsync_duration_seconds:quantile_irate{quantile=\"0.99\", cluster=\"$cluster\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} WAL fsync"
    },
    {
     "expr": "max by (instance) (max_over_time(etcd_disk_backend_commit_duration_seconds:quantile_irate{quantile=\"0.99\", cluster=\"$cluster\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} DB fsync"
    }
   ]
  },
  {
   "title": "DB size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "etcd_mvcc_db_total_size_in_bytes{cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} DB size"
    }
   ]
  },
  {
   "title": "Raft proposals",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 9 },
   "targets": [
    {
     "expr": "min_over_time(rate(etcd_server_proposals_committed_total{cluster=\"$cluster\", instance=~\"$instance\"}[60s])[$__rate_interval:])",
     "legendFormat": "{{instance}} committed"
    },
    {
     "expr": "max_over_time(etcd_server_proposals_pending{cluster=\"$cluster\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} pending"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max_over_time(process_resident_memory_bytes{cluster=\"$cluster\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total leader elections per day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 19 },
   "targets": [
    {
     "expr": "changes(etcd_server_leader_changes_seen_total{cluster=\"$cluster\", instance=~\"$instance\"}[1d])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Peer round trip time",
   "type": "timeseries",
   "description": "disabled because:\n- etcd_network_peer_round_trip_time_seconds_bucket is buggy\n- - https://github.com/etcd-io/etcd/issues/17837\n- histogram_quantile is very slow\n- recording rule with histogram_quantile doesn't seem to work",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } }
  }
 ]
}