{
 "title": "etcd",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(etcd_server_is_leader[$__range])))"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "query_result(group by(instance) (last_over_time(etcd_server_is_leader{location=~\"$location\"}[$__range])))"
    }
   }
  ]
 },
 "panels": [
  { "title": "general", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "version history",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max by(instance, server_version) (last_over_time(etcd_server_version{instance=~\"$instance\"}[$__interval]))\r\nor on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "memory rss",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(instance) (max_over_time(process_resident_memory_bytes{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "leader state",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max by(instance) (min_over_time(etcd_server_is_leader{instance=~\"$instance\"}[$__interval]) == 1) * 2\r\nor\r\nmax by(instance) (min_over_time(etcd_server_has_leader{instance=~\"$instance\"}[$__interval]) + 3)\r\nor\r\nmax by(instance) (min_over_time(up{job=\"etcd\", instance=~\"$instance\"}[$__interval]) + 10)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "leader elections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max by(instance) (rate(etcd_server_leader_changes_seen_total{instance=~\"$instance\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "raft committed proposals",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "min by(instance) (rate(etcd_server_proposals_committed_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "db size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(instance) (max_over_time(etcd_mvcc_db_total_size_in_bytes{instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "raft pending proposals (max)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "max by(instance) (max_over_time(etcd_server_proposals_pending{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "db size in use",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(instance) (max_over_time(etcd_mvcc_db_total_size_in_use_in_bytes{instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "slow applies (total)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(etcd_server_slow_apply_total{instance=~\"$instance\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "db size quota",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(instance) (max_over_time(etcd_server_quota_backend_bytes{instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "fsync p99, p99 over 1h",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(instance) (avg_over_time(etcd_disk_wal_fsync_duration_seconds:irate_hour_p99{quantile=\"0.99\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "disk commit p99, p99 over 1h",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(instance) (avg_over_time(etcd_disk_backend_commit_duration_seconds:irate_hour_p99{quantile=\"0.99\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "fsync p99, instant peak",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(instance) (max_over_time(etcd_disk_wal_fsync_duration_seconds:quantile_irate{quantile=\"0.99\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "disk commit p99, instant peak",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(instance) (max_over_time(etcd_disk_backend_commit_duration_seconds:quantile_irate{quantile=\"0.99\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}