---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: enable-backend-tls
spec:
  targetRefs:
  - group: ''
    kind: Service
    name: s3xui
  validation:
    caCertificateRefs:
    - name: ca.trust-manager.default
      group: ''
      kind: ConfigMap
    hostname: x-panel.meoe.cloudns.be
