{
 "title": "cadvisor cgroup list",
 "tags": [
  "maintainer:danil",
  "k8s-cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(container_cpu_usage_seconds_total{namespace=\"\", container_label_com_docker_compose_project=\"\", cpu=\"total\"}[$__range])))"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "query_result(group by(instance) (last_over_time(container_cpu_usage_seconds_total{location=~\"$location\", namespace=\"\", container_label_com_docker_compose_project=\"\", cpu=\"total\"}[$__range])))"
    }
   },
   { "name": "prefix_filter" },
   {
    "name": "id_prefix",
    "query": {
     "query": "query_result(max by(id_prefix) (label_replace(label_replace(last_over_time(container_cpu_usage_seconds_total{instance=\"$instance\", namespace=\"\", container_label_com_docker_compose_project=\"\", cpu=\"total\", id=~\"($prefix_filter).*\"}[$__range]), \"id_prefix\", \"$1\", \"id\", \"(.*)\\\\/.*\"), \"id_prefix\", \"/\", \"id\", \"/\")))"
    }
   },
   {
    "name": "show_children",
    "query": "hide : $, direct children : /?[^/]*, all : .*"
   },
   { "name": "suffix_filter" },
   { "name": "suffix_antifilter", "query": "-" },
   {
    "name": "id",
    "query": {
     "query": "query_result(max by(human_name, id) (label_replace(label_replace(  last_over_time(container_cpu_usage_seconds_total{instance=\"$instance\", namespace=\"\", container_label_com_docker_compose_project=\"\", cpu=\"total\", id=~\"($id_prefix)$show_children\", id=~\"($id_prefix)|($id_prefix)(/.*($suffix_filter).*)?\", id!~\"($id_prefix)($suffix_antifilter)\"}[$__range])  or  (last_over_time(container_cpu_usage_seconds_total{instance=\"$instance\", namespace=\"\", container_label_com_docker_compose_project=\"\", cpu=\"total\", id=~\"($id_prefix)$show_children\", id=~\"($id_prefix)|($id_prefix).*($suffix_filter).*\", id!~\"($id_prefix)($suffix_antifilter)\"}[$__range]) + on() group_left() last_over_time(container_cpu_usage_seconds_total{instance=\"$instance\", namespace=\"\", container_label_com_docker_compose_project=\"\", cpu=\"total\", id=\"/\", id=\"$id_prefix\"}[$__range])), \"human_name\", \"$1\", \"id\", \"$id_prefix/?(.+)\"), \"human_name\", \"<exact-prefix>\", \"id\", \"$id_prefix\")) # the first part selects $prefix/suffix for general use-case, the second part selects ${prefix}suffix but only for the special case of prefix=/)"
    }
   }
  ]
 },
 "panels": [
  { "title": "info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "start time (ago)",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(\r\n$__to / 1000 - max by(id) (max_over_time(container_start_time_seconds{instance=\"$instance\", id=~\"$id\"}[$__interval]))\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "last seen",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "(max by(id) (\r\n  max_over_time(container_start_time_seconds{instance=\"$instance\", id=~\"$id\"}[$__range])\r\n)) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "(max by(id) (\r\n  max_over_time(container_last_seen{instance=\"$instance\", id=~\"$id\"}[$__range])\r\n)) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "(max by(id) (\r\n  timestamp(container_last_seen{instance=\"$instance\", id=~\"$id\"})\r\n  -\r\n  container_last_seen{instance=\"$instance\", id=~\"$id\"}\r\n  or\r\n  time() - max_over_time(container_last_seen{instance=\"$instance\", id=~\"$id\"}[$__range])\r\n))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "uptime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(\r\ntime() - max by(id) (last_over_time(container_start_time_seconds{instance=\"$instance\", id=~\"$id\"}[$__interval]))\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  { "title": "cpu", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "cpu usage average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "label_replace(\r\nsum by(id) (rate(container_cpu_usage_seconds_total{instance=\"$instance\", id=~\"$id\", cpu=\"total\"}[$__rate_interval]))\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "cpu limit %",
   "type": "timeseries",
   "description": "empty when cgroup doesn't have cpu limit",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(\r\nsum by(id) (\r\n    sum without(cpu) (\r\n        rate(container_cpu_usage_seconds_total{instance=\"$instance\", id=~\"$id\", cpu=\"total\"}[$__rate_interval])\r\n    )\r\n    /\r\n    (\r\n      container_spec_cpu_quota{instance=\"$instance\", id=~\"$id\"}\r\n      /\r\n      container_spec_cpu_period{instance=\"$instance\", id=~\"$id\"}\r\n    )\r\n)\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "memory summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "memory summary: rss",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(\r\nmax by(id) (\r\n  max_over_time(container_memory_rss{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n  or\r\n  container_memory_rss{instance=\"$instance\", id=~\"$id\"}\r\n)\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "memory summary: wss",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(\r\nmax by(id) (\r\n  max_over_time(container_memory_working_set_bytes{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n  or\r\n  container_memory_working_set_bytes{instance=\"$instance\", id=~\"$id\"}\r\n)\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "memory: rss / limit %",
   "type": "timeseries",
   "description": "empty when cgroup doesn't have memory limit",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(\r\nmax by(id) (\r\n  (\r\n    max_over_time(container_memory_rss{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n    or\r\n    container_memory_rss{instance=\"$instance\", id=~\"$id\"}\r\n  )\r\n/\r\n  (max_over_time(container_spec_memory_limit_bytes{instance=\"$instance\", id=~\"$id\"}[$__interval]) != 0)\r\n)\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "memory: wss / limit %",
   "type": "timeseries",
   "description": "empty when cgroup doesn't have memory limit",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(\r\nmax by(id) (\r\n  (\r\n    max_over_time(container_memory_working_set_bytes{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n    or\r\n    container_memory_working_set_bytes{instance=\"$instance\", id=~\"$id\"}\r\n  )\r\n/\r\n  (max_over_time(container_spec_memory_limit_bytes{instance=\"$instance\", id=~\"$id\"}[$__interval]) != 0)\r\n)\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  { "title": "network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "receive rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "label_replace(\r\nsum by(id) (rate(container_network_receive_bytes_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]))\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "transmit rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "label_replace(\r\nsum by(id) (rate(container_network_transmit_bytes_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]))\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "receive total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(\r\nsum by(id) (rate(container_network_receive_bytes_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval])) * $__interval_ms / 1000\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "transmit total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(\r\nsum by(id) (rate(container_network_transmit_bytes_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval])) * $__interval_ms / 1000\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Storage notes",
   "type": "text",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 61 },
   "options": {
    "content": "\nRead/write from NFS and SMB shares\nwill not be shown in the storage throughput.\n\nCadvisor exports data from cgroup io.stats,\nwhich are only calculated for block devices.\n"
   }
  },
  {
   "title": "disk read rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "label_replace(\r\nsum by(id) (rate(container_fs_reads_bytes_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]))\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "disk write rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "label_replace(\r\nsum by(id) (rate(container_fs_writes_bytes_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]))\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "disk read total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(\r\nsum by(id) (rate(container_fs_reads_bytes_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval])) * $__interval_ms / 1000\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "disk written total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(\r\nsum by(id) (rate(container_fs_writes_bytes_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval])) * $__interval_ms / 1000\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "disk read iops",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "label_replace(\r\nsum by(id) (rate(container_fs_reads_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]))\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "disk write iops",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "label_replace(\r\nsum by(id) (rate(container_fs_writes_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]))\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}