{
 "title": "cadvisor / cgroup details",
 "tags": [ "cgroup" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(cadvisor_version_info{}[$__range])))"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "query_result(group by(instance) (last_over_time(cadvisor_version_info{location=~\"$location\"}[$__range])))"
    }
   },
   { "name": "id", "query": "/system.slice/kubelet.service" }
  ]
 },
 "panels": [
  { "title": "info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "container info",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max by(id, name, container_label_com_docker_compose_project, container_label_com_docker_compose_service, pod, uid, node, container, image) (\r\n  max_over_time(container_start_time_seconds{instance=\"$instance\", id=~\"$id\"}[$__range])\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(id, name) (\r\n  max without(uid) (max_over_time(container_last_seen{instance=\"$instance\", id=~\"$id\"}[$__range]))\r\n) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(id, name) (\r\n  max_over_time(container_start_time_seconds{instance=\"$instance\", id=~\"$id\"}[$__range])\r\n) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "(min by(id, name) (\r\n  timestamp(container_last_seen{instance=\"$instance\", id=~\"$id\"})\r\n  -\r\n  container_last_seen{instance=\"$instance\", id=~\"$id\"}\r\n  or\r\n  time() - max_over_time(container_last_seen{instance=\"$instance\", id=~\"$id\"}[$__range])\r\n))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "start time (ago)",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "$__to / 1000 - max(max_over_time(container_start_time_seconds{instance=\"$instance\", id=~\"$id\"}[$__interval]))",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "uptime (logarithmic)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - max(last_over_time(container_start_time_seconds{instance=\"$instance\", id=~\"$id\"}[$__interval]))",
     "legendFormat": "value"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=\"$instance\", id=~\"$id\", cpu=\"total\"}[$__rate_interval]))",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "cpu kernel mode %",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(\r\n  (rate(container_cpu_system_seconds_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]) )\r\n  /\r\n  sum without(cpu) (rate(container_cpu_usage_seconds_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]) + 1e-12)\r\n)",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "cpu (total time)",
   "type": "timeseries",
   "description": "sum_over_time of seconds spent running",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=\"$instance\", id=~\"$id\", cpu=\"total\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "cpu throttled rate",
   "type": "timeseries",
   "description": "empty when cgroup doesn't have cpu limit",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "max(rate(container_cpu_cfs_throttled_seconds_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]))",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "cpu limit",
   "type": "timeseries",
   "description": "empty when cgroup doesn't have cpu limit",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum(\r\n  container_spec_cpu_quota{instance=\"$instance\", id=~\"$id\"}\r\n  /\r\n  container_spec_cpu_period{instance=\"$instance\", id=~\"$id\"}\r\n)",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "cpu throttled (total time)",
   "type": "timeseries",
   "description": "sum_over_time of seconds spent throtting. Empty is container doesn't have cpu limit.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(rate(container_cpu_cfs_throttled_seconds_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "CPU limit %",
   "type": "timeseries",
   "description": "empty when cgroup doesn't have cpu limit",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\r\n  sum without(cpu) (\r\n    rate(container_cpu_usage_seconds_total{instance=\"$instance\", id=~\"$id\", cpu=\"total\"}[$__rate_interval])\r\n  )\r\n  /\r\n  (\r\n    container_spec_cpu_quota{instance=\"$instance\", id=~\"$id\"}\r\n    /\r\n    container_spec_cpu_period{instance=\"$instance\", id=~\"$id\"}\r\n  )\r\n)",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "CPU throttling periods %",
   "type": "timeseries",
   "description": "empty when cgroup doesn't have cpu limit",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(\r\n  (increase(container_cpu_cfs_throttled_periods_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]) )\r\n  /\r\n  (increase(container_cpu_cfs_periods_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]) + 1e-12 )\r\n)",
     "legendFormat": "value"
    }
   ]
  },
  { "title": "pressure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "cpu pressure: stalled",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum(rate(container_pressure_cpu_stalled_seconds_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]))",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "memory pressure: stalled",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum(rate(container_pressure_memory_stalled_seconds_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]))",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "io pressure: stalled",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum(rate(container_pressure_io_stalled_seconds_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]))",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "cpu pressure: waiting",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum(rate(container_pressure_cpu_waiting_seconds_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]))",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "memory pressure: waiting",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum(rate(container_pressure_memory_waiting_seconds_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]))",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "io pressure: waiting",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum(rate(container_pressure_io_waiting_seconds_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]))",
     "legendFormat": "value"
    }
   ]
  },
  { "title": "memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Memory notes",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 40 },
   "options": {
    "content": "- `rss` is anon memory\n- `wss` = rss + active cache + kernel\n- `raw` = `rss` + full cache + kernel\n- Cache is active if it used _often_ (more than once?)\n\nWhat to look for:\n- WSS reaching limit causes file garbage collection\n- RSS reaching limit causes OOM kill\n"
   }
  },
  {
   "title": "memory levels",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(\r\n  max_over_time(container_memory_max_usage_bytes{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n  or\r\n  max_over_time(container_memory_max_usage_bytes{instance=\"$instance\", id=~\"$id\"}[$__rate_interval])\r\n)",
     "legendFormat": "max"
    },
    {
     "expr": "max(\r\n  max_over_time(container_memory_usage_bytes{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n  or\r\n  max_over_time(container_memory_usage_bytes{instance=\"$instance\", id=~\"$id\"}[$__rate_interval])\r\n)",
     "legendFormat": "raw"
    },
    {
     "expr": "max(\r\n  max_over_time(container_memory_working_set_bytes{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n  or\r\n  max_over_time(container_memory_working_set_bytes{instance=\"$instance\", id=~\"$id\"}[$__rate_interval])\r\n)",
     "legendFormat": "wss"
    },
    {
     "expr": "max(\r\n  max_over_time(container_memory_usage_bytes{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n  or\r\n  max_over_time(container_memory_usage_bytes{instance=\"$instance\", id=~\"$id\"}[$__rate_interval])\r\n)\r\n-\r\nmax(\r\n  avg_over_time(container_memory_cache{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n  or\r\n  avg_over_time(container_memory_cache{instance=\"$instance\", id=~\"$id\"}[$__rate_interval])\r\n)",
     "legendFormat": "rss+kernel"
    },
    {
     "expr": "max(\r\n  max_over_time(container_memory_rss{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n  or\r\n  max_over_time(container_memory_rss{instance=\"$instance\", id=~\"$id\"}[$__rate_interval])\r\n)",
     "legendFormat": "rss"
    },
    {
     "expr": "max(\r\n  max_over_time(container_spec_memory_limit_bytes{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n  or\r\n  max_over_time(container_spec_memory_limit_bytes{instance=\"$instance\", id=~\"$id\"}[$__rate_interval])\r\n) != 0",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "memory types",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(\r\n  avg_over_time(container_memory_rss{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n  or\r\n  avg_over_time(container_memory_rss{instance=\"$instance\", id=~\"$id\"}[$__rate_interval])\r\n)",
     "legendFormat": "rss"
    },
    {
     "expr": "# container_memory_usage_bytes = rss + cache + kernel\r\n# but container_memory_kernel_usage is broken in current version of cadvisor, it's always zero\r\nmax(\r\n  (\r\n    avg_over_time(container_memory_usage_bytes{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n    -\r\n    avg_over_time(container_memory_rss{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n    -\r\n    avg_over_time(container_memory_cache{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n  )\r\n  or\r\n  (\r\n    avg_over_time(container_memory_usage_bytes{instance=\"$instance\", id=~\"$id\"}[$__rate_interval])\r\n    -\r\n    avg_over_time(container_memory_rss{instance=\"$instance\", id=~\"$id\"}[$__rate_interval])\r\n    -\r\n    avg_over_time(container_memory_cache{instance=\"$instance\", id=~\"$id\"}[$__rate_interval])\r\n  )\r\n)",
     "legendFormat": "kernel"
    },
    {
     "expr": "max(\r\n  avg_over_time(container_memory_cache{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n  or\r\n  avg_over_time(container_memory_cache{instance=\"$instance\", id=~\"$id\"}[$__rate_interval])\r\n)",
     "legendFormat": "cache"
    },
    {
     "expr": "max(\r\n  avg_over_time(container_memory_usage_bytes{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n  or\r\n  avg_over_time(container_memory_usage_bytes{instance=\"$instance\", id=~\"$id\"}[$__rate_interval])\r\n)",
     "legendFormat": "raw"
    }
   ]
  },
  {
   "title": "memory / limit %",
   "type": "timeseries",
   "description": "empty when cgroup doesn't have memory limit",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(\r\n    (\r\n        max_over_time(container_memory_max_usage_bytes{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n        or\r\n        max_over_time(container_memory_max_usage_bytes{instance=\"$instance\", id=~\"$id\"}[$__rate_interval])\r\n    )\r\n/\r\n    (max_over_time(container_spec_memory_limit_bytes{instance=\"$instance\", id=~\"$id\"}[$__interval]) != 0)\r\n)",
     "legendFormat": "max"
    },
    {
     "expr": "max(\r\n    (\r\n        max_over_time(container_memory_usage_bytes{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n        or\r\n        max_over_time(container_memory_usage_bytes{instance=\"$instance\", id=~\"$id\"}[$__rate_interval])\r\n    )\r\n/\r\n    (max_over_time(container_spec_memory_limit_bytes{instance=\"$instance\", id=~\"$id\"}[$__interval]) != 0)\r\n)",
     "legendFormat": "raw"
    },
    {
     "expr": "max(\r\n    (\r\n        max_over_time(container_memory_working_set_bytes{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n        or\r\n        max_over_time(container_memory_working_set_bytes{instance=\"$instance\", id=~\"$id\"}[$__rate_interval])\r\n    )\r\n/\r\n    (max_over_time(container_spec_memory_limit_bytes{instance=\"$instance\", id=~\"$id\"}[$__interval]) != 0)\r\n)",
     "legendFormat": "wss"
    },
    {
     "expr": "max(\r\n    (\r\n        max_over_time(container_memory_rss{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n        or\r\n        max_over_time(container_memory_rss{instance=\"$instance\", id=~\"$id\"}[$__rate_interval])\r\n    )\r\n/\r\n    (max_over_time(container_spec_memory_limit_bytes{instance=\"$instance\", id=~\"$id\"}[$__interval]) != 0)\r\n)",
     "legendFormat": "rss"
    }
   ]
  },
  {
   "title": "cache [un]mapped",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(\r\n  avg_over_time(container_memory_cache{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n  or\r\n  avg_over_time(container_memory_cache{instance=\"$instance\", id=~\"$id\"}[$__rate_interval])\r\n)",
     "legendFormat": "total"
    },
    {
     "expr": "max(\r\n  avg_over_time(container_memory_mapped_file{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n  or\r\n  avg_over_time(container_memory_mapped_file{instance=\"$instance\", id=~\"$id\"}[$__rate_interval])\r\n)",
     "legendFormat": "mapped"
    },
    {
     "expr": "max(\r\n  (\r\n    avg_over_time(container_memory_cache{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n    -\r\n    avg_over_time(container_memory_mapped_file{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n  )\r\n  or\r\n  (\r\n    avg_over_time(container_memory_cache{instance=\"$instance\", id=~\"$id\"}[$__rate_interval])\r\n    -\r\n    avg_over_time(container_memory_mapped_file{instance=\"$instance\", id=~\"$id\"}[$__rate_interval])\r\n  )\r\n)",
     "legendFormat": "unmapped"
    }
   ]
  },
  {
   "title": "page fault rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "max by(id, failure_type)(rate(container_memory_failures_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]))",
     "legendFormat": "{{failure_type}}"
    }
   ]
  },
  {
   "title": "cache [in]active",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(\r\n  avg_over_time(container_memory_cache{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n  or\r\n  avg_over_time(container_memory_cache{instance=\"$instance\", id=~\"$id\"}[$__rate_interval])\r\n)",
     "legendFormat": "total"
    },
    {
     "expr": "max(\r\n  avg_over_time(container_memory_total_active_file_bytes{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n  or\r\n  avg_over_time(container_memory_total_active_file_bytes{instance=\"$instance\", id=~\"$id\"}[$__rate_interval])\r\n)",
     "legendFormat": "active"
    },
    {
     "expr": "max(\r\n  avg_over_time(container_memory_total_inactive_file_bytes{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n  or\r\n  avg_over_time(container_memory_total_inactive_file_bytes{instance=\"$instance\", id=~\"$id\"}[$__rate_interval])\r\n)",
     "legendFormat": "inactive"
    }
   ]
  },
  { "title": "network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "receive rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(interface) (rate(container_network_receive_bytes_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]))",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "transmit rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(interface) (rate(container_network_transmit_bytes_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]))",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "receive total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(interface) (rate(container_network_receive_bytes_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "transmit total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(interface) (rate(container_network_transmit_bytes_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  { "title": "disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "disk read rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(device) (rate(container_fs_reads_bytes_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]))",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "disk write rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(device) (rate(container_fs_writes_bytes_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]))",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "disk read total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(device) (rate(container_fs_reads_bytes_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "disk written total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(device) (rate(container_fs_writes_bytes_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "disk read iops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum by(device) (rate(container_fs_reads_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]))",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "disk write iops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum by(device) (rate(container_fs_writes_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]))",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}