{
 "title": "cadvisor cgroup",
 "tags": [
  "maintainer:danil",
  "k8s-cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(container_cpu_usage_seconds_total{namespace=\"\", cpu=\"total\"}[$__range])))"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "query_result(group by(instance) (last_over_time(container_cpu_usage_seconds_total{location=~\"$location\", namespace=\"\", cpu=\"total\"}[$__range])))"
    }
   },
   { "name": "prefix_filter" },
   {
    "name": "id_prefix",
    "query": {
     "query": "query_result(max by(id_prefix) (label_replace(label_replace(last_over_time(container_cpu_usage_seconds_total{instance=\"$instance\", namespace=\"\", cpu=\"total\", id=~\"($prefix_filter).*\"}[1h]), \"id_prefix\", \"$1\", \"id\", \"(.*)\\\\/.*\"), \"id_prefix\", \"/\", \"id\", \"/\")))"
    }
   },
   {
    "name": "show_children",
    "query": "hide : $, 1 level : /?[^/]*, all : .*"
   },
   { "name": "suffix_filter", "query": "docker" },
   {
    "name": "id",
    "query": {
     "query": "query_result(max by(human_name, id) (label_replace(last_over_time(container_cpu_usage_seconds_total{instance=\"$instance\", namespace=\"\", cpu=\"total\", id=~\"($id_prefix)$show_children\", id=~\"($id_prefix).*($suffix_filter).*\"}[$__range]), \"human_name\", \"$1\", \"id\", \"$id_prefix(.+)|($id_prefix)\")))"
    }
   }
  ]
 },
 "panels": [
  { "title": "info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "start time (ago)",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(\r\n$__to / 1000 - max by(id) (max_over_time(container_start_time_seconds{instance=\"$instance\", id=~\"$id\"}[$__interval]))\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "last seen (ago)",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "round(max by(id) (\r\n  timestamp(container_last_seen{instance=\"$instance\", id=~\"$id\"})\r\n  -\r\n  container_last_seen{instance=\"$instance\", id=~\"$id\"}\r\n  or\r\n  time() - last_over_time(container_last_seen{instance=\"$instance\", id=~\"$id\"}[$__range])\r\n))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "uptime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(\r\ntime() - max by(id) (last_over_time(container_start_time_seconds{instance=\"$instance\", id=~\"$id\"}[$__interval]))\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "label_replace(\r\nsum by(id) (rate(container_cpu_usage_seconds_total{instance=\"$instance\", id=~\"$id\", cpu=\"total\"}[$__rate_interval]))\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "cpu limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "label_replace(\r\nsum by(id) (\r\n  container_spec_cpu_quota{instance=\"$instance\", id=~\"$id\"}\r\n  /\r\n  container_spec_cpu_period{instance=\"$instance\", id=~\"$id\"}\r\n)\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "cpu kernel mode %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(\r\nmax by (id) (\r\n  (rate(container_cpu_system_seconds_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]) )\r\n  /\r\n  sum without(cpu) (rate(container_cpu_usage_seconds_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]) + 1e-12)\r\n)\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "CPU throttled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "label_replace(\r\nmax by (id) (\r\n  (rate(container_cpu_cfs_throttled_seconds_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]) )\r\n)\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "CPU limit %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(\r\nsum by(id) (\r\n    sum without(cpu) (\r\n        rate(container_cpu_usage_seconds_total{instance=\"$instance\", id=~\"$id\", cpu=\"total\"}[$__rate_interval])\r\n    )\r\n    /\r\n    (\r\n      container_spec_cpu_quota{instance=\"$instance\", id=~\"$id\"}\r\n      /\r\n      container_spec_cpu_period{instance=\"$instance\", id=~\"$id\"}\r\n    )\r\n)\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU throttling periods %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "# if container didn't run at some interval, you will have division by zero, so we do ` / increase + epsilon`\r\nlabel_replace(\r\nmax by(id) (\r\n  (increase(container_cpu_cfs_throttled_periods_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]) )\r\n/\r\n  (increase(container_cpu_cfs_periods_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]) + 1e-5 )\r\n)\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "pressure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "cpu pressure: stalled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "label_replace(\r\nsum by(id) (rate(container_pressure_cpu_stalled_seconds_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]))\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "io pressure: stalled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "label_replace(\r\nsum by(id) (rate(container_pressure_io_stalled_seconds_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]))\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "cpu pressure: waiting",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "label_replace(\r\nsum by(id) (rate(container_pressure_cpu_waiting_seconds_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]))\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "io pressure: waiting",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "label_replace(\r\nsum by(id) (rate(container_pressure_io_waiting_seconds_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]))\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "memory pressure: stalled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "label_replace(\r\nsum by(id) (rate(container_pressure_memory_stalled_seconds_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]))\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "memory pressure: waiting",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "label_replace(\r\nsum by(id) (rate(container_pressure_memory_waiting_seconds_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]))\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  { "title": "memory summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "memory summary: rss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(\r\nmax by(id) (\r\n  max_over_time(container_memory_rss{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n  or\r\n  container_memory_rss{instance=\"$instance\", id=~\"$id\"}\r\n)\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "memory summary: wss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(\r\nmax by(id) (\r\n  max_over_time(container_memory_working_set_bytes{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n  or\r\n  container_memory_working_set_bytes{instance=\"$instance\", id=~\"$id\"}\r\n)\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  { "title": "Memory $id", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 }, "repeat": "id" },
  {
   "title": "memory levels: $id",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(\r\nmax by(id) (\r\n  max_over_time(container_memory_max_usage_bytes{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n  or\r\n  container_memory_max_usage_bytes{instance=\"$instance\", id=~\"$id\"}\r\n)\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "max"
    },
    {
     "expr": "label_replace(\r\nmax by(id) (\r\n  max_over_time(container_memory_usage_bytes{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n  or\r\n  container_memory_usage_bytes{instance=\"$instance\", id=~\"$id\"}\r\n)\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "raw"
    },
    {
     "expr": "label_replace(\r\nmax by(id) (\r\n  max_over_time(container_memory_working_set_bytes{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n  or\r\n  container_memory_working_set_bytes{instance=\"$instance\", id=~\"$id\"}\r\n)\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "wss"
    },
    {
     "expr": "label_replace(\r\nmax by(id) (\r\n  max_over_time(container_memory_rss{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n  or\r\n  container_memory_rss{instance=\"$instance\", id=~\"$id\"}\r\n)\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "rss"
    },
    {
     "expr": "label_replace(\r\nmax by(id) (\r\n  max_over_time(container_spec_memory_limit_bytes{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n  or\r\n  container_spec_memory_limit_bytes{instance=\"$instance\", id=~\"$id\"}\r\n)\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory notes",
   "type": "text",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 93 },
   "options": {
    "content": "- `RSS` is memory allocated explicitly\n- `RSS` + Active   cache -> `WSS`\n- `WSS` + Inactive cache -> `Raw` memory usage\n- Formula: Cache = Active + Inactive\n- Cache is active if it used _often_ (more than once?)\n- RSS and cache are exact values\n- `Raw` is kernel approximation used for cache flushing and OOM killer\n- `WSS` is roughly `Raw` - Inactive cache\n\nWhat to look for:\n- WSS reaching limit causes file garbage collection\n- RSS reaching limit causes OOM kill\n"
   }
  },
  {
   "title": "memory / limit %: $id",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(id) (\r\n    (\r\n        max_over_time(container_memory_max_usage_bytes{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n        or\r\n        container_memory_max_usage_bytes{instance=\"$instance\", id=~\"$id\"}\r\n    )\r\n/\r\n    (max_over_time(container_spec_memory_limit_bytes{instance=\"$instance\", id=~\"$id\"}[$__interval]) != 0)\r\n)",
     "legendFormat": "max"
    },
    {
     "expr": "max by(id) (\r\n    (\r\n        max_over_time(container_memory_usage_bytes{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n        or\r\n        container_memory_usage_bytes{instance=\"$instance\", id=~\"$id\"}\r\n    )\r\n/\r\n    (max_over_time(container_spec_memory_limit_bytes{instance=\"$instance\", id=~\"$id\"}[$__interval]) != 0)\r\n)",
     "legendFormat": "raw"
    },
    {
     "expr": "max by(id) (\r\n    (\r\n        max_over_time(container_memory_working_set_bytes{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n        or\r\n        container_memory_working_set_bytes{instance=\"$instance\", id=~\"$id\"}\r\n    )\r\n/\r\n    (max_over_time(container_spec_memory_limit_bytes{instance=\"$instance\", id=~\"$id\"}[$__interval]) != 0)\r\n)",
     "legendFormat": "wss"
    },
    {
     "expr": "max by(id) (\r\n    (\r\n        max_over_time(container_memory_rss{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n        or\r\n        container_memory_rss{instance=\"$instance\", id=~\"$id\"}\r\n    )\r\n/\r\n    (max_over_time(container_spec_memory_limit_bytes{instance=\"$instance\", id=~\"$id\"}[$__interval]) != 0)\r\n)",
     "legendFormat": "rss"
    }
   ]
  },
  {
   "title": "memory types: $id",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(\r\nmax by(id) (\r\n  avg_over_time(container_memory_cache{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n  or\r\n  container_memory_cache{instance=\"$instance\", id=~\"$id\"}\r\n)\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "cache"
    },
    {
     "expr": "label_replace(\r\nmax by(id) (\r\n  avg_over_time(container_memory_rss{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n  or\r\n  container_memory_rss{instance=\"$instance\", id=~\"$id\"}\r\n)\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "rss"
    },
    {
     "expr": "# container_memory_usage_bytes = rss + cache + kernel\r\n# but container_memory_kernel_usage is broken in current version of cadvisor, it's always zero\r\nlabel_replace(\r\nmax by(id) (\r\n  (\r\n    avg_over_time(container_memory_usage_bytes{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n    -\r\n    avg_over_time(container_memory_rss{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n    -\r\n    avg_over_time(container_memory_cache{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n  )\r\n  or\r\n  (\r\n  container_memory_usage_bytes{instance=\"$instance\", id=~\"$id\"}\r\n  -\r\n  container_memory_rss{instance=\"$instance\", id=~\"$id\"}\r\n  -\r\n  container_memory_cache{instance=\"$instance\", id=~\"$id\"}\r\n  )\r\n)\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "kernel"
    },
    {
     "expr": "label_replace(\r\nmax by(id) (\r\n  avg_over_time(container_memory_usage_bytes{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n  or\r\n  container_memory_usage_bytes{instance=\"$instance\", id=~\"$id\"}\r\n)\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "raw"
    }
   ]
  },
  {
   "title": "Page fault rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "label_replace(\r\nmax by (id, failure_type)(rate(container_memory_failures_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]))\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "{{failure_type}}"
    }
   ]
  },
  {
   "title": "cache [un]mapped: $id",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(\r\nmax by(id) (\r\n  avg_over_time(container_memory_cache{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n  or\r\n  container_memory_cache{instance=\"$instance\", id=~\"$id\"}\r\n)\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "total"
    },
    {
     "expr": "label_replace(\r\nmax by(id) (\r\n  avg_over_time(container_memory_mapped_file{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n  or\r\n  container_memory_mapped_file{instance=\"$instance\", id=~\"$id\"}\r\n)\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "mapped"
    },
    {
     "expr": "label_replace(\r\nmax by(id) (\r\n  (\r\n  avg_over_time(container_memory_cache{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n  -\r\n  avg_over_time(container_memory_mapped_file{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n  )\r\n  or\r\n  (\r\n  container_memory_cache{instance=\"$instance\", id=~\"$id\"}\r\n  -\r\n  container_memory_mapped_file{instance=\"$instance\", id=~\"$id\"}\r\n  )\r\n)\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "unmapped"
    }
   ]
  },
  {
   "title": "cache [un]mapped: $id",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(\r\nmax by(id) (\r\n  avg_over_time(container_memory_cache{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n  or\r\n  container_memory_cache{instance=\"$instance\", id=~\"$id\"}\r\n)\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "total"
    },
    {
     "expr": "label_replace(\r\nmax by(id) (\r\n  avg_over_time(container_memory_total_inactive_file_bytes{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n  or\r\n  container_memory_total_inactive_file_bytes{instance=\"$instance\", id=~\"$id\"}\r\n)\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "inactive"
    },
    {
     "expr": "label_replace(\r\nmax by(id) (\r\n  avg_over_time(container_memory_total_active_file_bytes{instance=\"$instance\", id=~\"$id\"}[$__interval])\r\n  or\r\n  container_memory_total_active_file_bytes{instance=\"$instance\", id=~\"$id\"}\r\n)\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "active"
    }
   ]
  },
  {
   "title": "Network (shared between containers)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 121 }
  },
  {
   "title": "Receive Bandwidth by interface",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "label_replace(\r\nsum by(id, interface) (rate(container_network_receive_bytes_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]))\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "{{id}} {{interface}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth by interface",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "label_replace(\r\nsum by(id, interface) (rate(container_network_transmit_bytes_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]))\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "{{id}} {{interface}}"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 129 } },
  {
   "title": "Storage IO (average over time range)",
   "type": "table",
   "gridPos": { "h": 7, "w": 17, "x": 1, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(container, device) (rate(container_fs_reads_total{container!=\"\", container=~\"$container\", location=\"$location\", namespace=\"$namespace\", pod=\"$pod\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(container, device) (rate(container_fs_writes_total{container!=\"\", container=~\"$container\", location=\"$location\", namespace=\"$namespace\", pod=\"$pod\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(container, device) (rate(container_fs_reads_total{container!=\"\", container=~\"$container\", location=\"$location\", namespace=\"$namespace\", pod=\"$pod\"}[$__range]) + rate(container_fs_writes_total{container!=\"\", container=~\"$container\", location=\"$location\", namespace=\"$namespace\", pod=\"$pod\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(container, device) (rate(container_fs_reads_bytes_total{container!=\"\", container=~\"$container\", location=\"$location\", namespace=\"$namespace\", pod=\"$pod\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(container, device) (rate(container_fs_writes_bytes_total{container!=\"\", container=~\"$container\", location=\"$location\", namespace=\"$namespace\", pod=\"$pod\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(container, device) (rate(container_fs_reads_bytes_total{container!=\"\", container=~\"$container\", location=\"$location\", namespace=\"$namespace\", pod=\"$pod\"}[$__range]) + rate(container_fs_writes_bytes_total{container!=\"\", container=~\"$container\", location=\"$location\", namespace=\"$namespace\", pod=\"$pod\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage notes",
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 18, "y": 130 },
   "options": {
    "content": "\nRead/write from NFS and SMB shares\nwill not be shown in the storage throughput.\n\nCadvisor exports data from cgroup io.stats,\nwhich are only calculated for block devices.\n"
   }
  },
  {
   "title": "Disk read",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "label_replace(\r\nsum by(id) (rate(container_fs_reads_bytes_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]))\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Disk write",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "label_replace(\r\nsum by(id) (rate(container_fs_writes_bytes_total{instance=\"$instance\", id=~\"$id\"}[$__rate_interval]))\r\n, \"id\", \"$1\", \"id\", \"$id_prefix/?(.*)\"\r\n)",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}