{
 "title": "cadvisor / docker compose multi-instance",
 "tags": [
  "cgroup",
  "docker"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(container_cpu_usage_seconds_total{container_label_com_docker_compose_project!=\"\", cpu=\"total\"}[$__range])))"
    }
   },
   {
    "name": "project",
    "query": {
     "query": "query_result(group by(instance, container_label_com_docker_compose_project) (last_over_time(container_cpu_usage_seconds_total{container_label_com_docker_compose_project!=\"\", cpu=\"total\"}[$__range])))"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "query_result(group by(instance) (last_over_time(container_cpu_usage_seconds_total{location=~\"$location\", container_label_com_docker_compose_project=~\"$project\", cpu=\"total\"}[$__range])))"
    }
   },
   {
    "name": "name",
    "query": {
     "query": "query_result(group by(name) (last_over_time(container_cpu_usage_seconds_total{instance=~\"$instance\", container_label_com_docker_compose_project=~\"$project\", cpu=\"total\"}[$__range])))"
    }
   },
   {
    "name": "show_total",
    "query": "show : \"\", hide : \"invalid123\""
   }
  ]
 },
 "panels": [
  { "title": "info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "container info",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max by(instance, container_label_com_docker_compose_project) (\r\n  max_over_time(container_start_time_seconds{instance=~\"$instance\", name=~\"$name\"}[$__range])\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, container_label_com_docker_compose_project) (\r\n  max without(uid) (max_over_time(container_last_seen{instance=~\"$instance\", name=~\"$name\"}[$__range]))\r\n) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, container_label_com_docker_compose_project) (\r\n  max_over_time(container_start_time_seconds{instance=~\"$instance\", name=~\"$name\"}[$__range])\r\n) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "(min by(instance, container_label_com_docker_compose_project) (\r\n  timestamp(container_last_seen{instance=~\"$instance\", name=~\"$name\"})\r\n  -\r\n  container_last_seen{instance=~\"$instance\", name=~\"$name\"}\r\n  or\r\n  time() - max_over_time(container_last_seen{instance=~\"$instance\", name=~\"$name\"}[$__range])\r\n))",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by(instance, container_label_com_docker_compose_project) (\r\n  max by(instance, container_label_com_docker_compose_project, name) (max_over_time(container_start_time_seconds{instance=~\"$instance\", name=~\"$name\"}[$__range]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "last restart (ago)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "$__to / 1000 - max by(instance, container_label_com_docker_compose_project) (max_over_time(container_start_time_seconds{instance=~\"$instance\", name=~\"$name\"}[$__interval]))",
     "legendFormat": "{{container_label_com_docker_compose_project}} @ {{instance}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "cpu usage (average)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(instance, container_label_com_docker_compose_project) (rate(container_cpu_usage_seconds_total{instance=~\"$instance\", name=~\"$name\", cpu=\"total\"}[$__rate_interval]))",
     "legendFormat": "{{container_label_com_docker_compose_project}} @ {{instance}}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=~\"$instance\", name=~\"$name\", invalid=$show_total}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "CPU throttled (average)",
   "type": "timeseries",
   "description": "Empty is container doesn't have cpu limit.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "max by(instance, container_label_com_docker_compose_project) (\r\n  (rate(container_cpu_cfs_throttled_seconds_total{instance=~\"$instance\", name=~\"$name\"}[$__rate_interval]) )\r\n)",
     "legendFormat": "{{container_label_com_docker_compose_project}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "cpu usage (total time)",
   "type": "timeseries",
   "description": "sum_over_time of seconds spent running",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(instance, container_label_com_docker_compose_project) (rate(container_cpu_usage_seconds_total{instance=~\"$instance\", name=~\"$name\", cpu=\"total\"}[$__rate_interval]) * $__interval_ms / 1000)",
     "legendFormat": "{{container_label_com_docker_compose_project}} @ {{instance}}"
    },
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{instance=~\"$instance\", name=~\"$name\", invalid=$show_total}[$__rate_interval]) * $__interval_ms / 1000)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "CPU throttled (total time)",
   "type": "timeseries",
   "description": "sum_over_time of seconds spent throtting. Empty is container doesn't have cpu limit.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(instance, container_label_com_docker_compose_project) (\r\n  (rate(container_cpu_cfs_throttled_seconds_total{instance=~\"$instance\", name=~\"$name\"}[$__rate_interval]) * $__interval_ms / 1000 )\r\n)",
     "legendFormat": "{{container_label_com_docker_compose_project}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "cpu kernel mode %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(instance, container_label_com_docker_compose_project) (\r\n  (rate(container_cpu_system_seconds_total{instance=~\"$instance\", name=~\"$name\"}[$__rate_interval]))\r\n  /\r\n  sum without(cpu) (rate(container_cpu_usage_seconds_total{instance=~\"$instance\", name=~\"$name\", cpu=\"total\"}[$__rate_interval]) + 1e-12)\r\n)",
     "legendFormat": "{{container_label_com_docker_compose_project}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "CPU throttling periods %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "# if container didn't run at some interval, you will have division by zero, so we do ` / increase + epsilon`\r\nmax by(instance, container_label_com_docker_compose_project) (\r\n  (increase(container_cpu_cfs_throttled_periods_total{instance=~\"$instance\", name=~\"$name\"}[$__rate_interval]) )\r\n/\r\n  (increase(container_cpu_cfs_periods_total{instance=~\"$instance\", name=~\"$name\"}[$__rate_interval]) + 1e-5 )\r\n)",
     "legendFormat": "{{container_label_com_docker_compose_project}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "cpu spec: limit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(instance, container_label_com_docker_compose_project) (\r\n  container_spec_cpu_quota{instance=~\"$instance\", name=~\"$name\"}\r\n  /\r\n  container_spec_cpu_period{instance=~\"$instance\", name=~\"$name\"}\r\n)",
     "legendFormat": "{{container_label_com_docker_compose_project}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "CPU limit %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance, container_label_com_docker_compose_project) (\r\n    sum without(cpu) (\r\n        rate(container_cpu_usage_seconds_total{instance=~\"$instance\", name=~\"$name\", cpu=\"total\"}[$__rate_interval])\r\n    )\r\n    /\r\n    (\r\n      container_spec_cpu_quota{instance=~\"$instance\", name=~\"$name\"}\r\n      /\r\n      container_spec_cpu_period{instance=~\"$instance\", name=~\"$name\"}\r\n    )\r\n)",
     "legendFormat": "{{container_label_com_docker_compose_project}} @ {{instance}}"
    }
   ]
  },
  { "title": "memory summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "notes: memory types",
   "type": "text",
   "gridPos": { "h": 4, "w": 7, "x": 3, "y": 45 },
   "options": {
    "content": "- `rss` is anon memory\n- `wss` = rss + active cache\n- Cache is active if it used _often_ (more than once?)"
   }
  },
  {
   "title": "notes: memory events",
   "type": "text",
   "gridPos": { "h": 4, "w": 7, "x": 11, "y": 45 },
   "options": {
    "content": "- WSS reaching limit causes file cache garbage collection\n- RSS reaching limit causes OOM kill\n"
   }
  },
  {
   "title": "memory rss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(instance, container_label_com_docker_compose_project) (\r\n  max by(instance, container_label_com_docker_compose_project, name) (\r\n    max_over_time(container_memory_rss{instance=~\"$instance\", name=~\"$name\"}[$__interval])\r\n    or\r\n    container_memory_rss{instance=~\"$instance\", name=~\"$name\"}\r\n  )\r\n)",
     "legendFormat": "{{container_label_com_docker_compose_project}} @ {{instance}}"
    },
    {
     "expr": "sum(\r\n  max by(instance, container_label_com_docker_compose_project, name) (\r\n    max_over_time(container_memory_rss{instance=~\"$instance\", name=~\"$name\", invalid=$show_total}[$__interval])\r\n    or\r\n    container_memory_rss{instance=~\"$instance\", name=~\"$name\", invalid=$show_total}\r\n  )\r\n)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "memory wss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(instance, container_label_com_docker_compose_project) (\r\n  max by(instance, container_label_com_docker_compose_project, name) (\r\n    max_over_time(container_memory_working_set_bytes{instance=~\"$instance\", name=~\"$name\"}[$__interval])\r\n    or\r\n    container_memory_working_set_bytes{instance=~\"$instance\", name=~\"$name\"}\r\n  )\r\n)",
     "legendFormat": "{{container_label_com_docker_compose_project}} @ {{instance}}"
    },
    {
     "expr": "sum(\r\n  max by(instance, container_label_com_docker_compose_project, name) (\r\n    max_over_time(container_memory_working_set_bytes{instance=~\"$instance\", name=~\"$name\", invalid=$show_total}[$__interval])\r\n    or\r\n    container_memory_working_set_bytes{instance=~\"$instance\", name=~\"$name\", invalid=$show_total}\r\n  )\r\n)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "memory rss / limit %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(instance, container_label_com_docker_compose_project) (\r\n    (\r\n        max_over_time(container_memory_rss{instance=~\"$instance\", name=~\"$name\"}[$__interval])\r\n        or\r\n        container_memory_rss{instance=~\"$instance\", name=~\"$name\"}\r\n    )\r\n/\r\n    (max_over_time(container_spec_memory_limit_bytes{instance=~\"$instance\", name=~\"$name\"}[$__interval]) != 0)\r\n)",
     "legendFormat": "{{container_label_com_docker_compose_project}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "memory wss / limit %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(instance, container_label_com_docker_compose_project) (\r\n    (\r\n        max_over_time(container_memory_working_set_bytes{instance=~\"$instance\", name=~\"$name\"}[$__interval])\r\n        or\r\n        container_memory_working_set_bytes{instance=~\"$instance\", name=~\"$name\"}\r\n    )\r\n/\r\n    (max_over_time(container_spec_memory_limit_bytes{instance=~\"$instance\", name=~\"$name\"}[$__interval]) != 0)\r\n)",
     "legendFormat": "{{container_label_com_docker_compose_project}} @ {{instance}}"
    }
   ]
  },
  { "title": "network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "receive rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance, container_label_com_docker_compose_project) (rate(container_network_receive_bytes_total{instance=~\"$instance\", name=~\"$name\"}[$__rate_interval]))",
     "legendFormat": "{{container_label_com_docker_compose_project}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "transmit rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance, container_label_com_docker_compose_project) (rate(container_network_transmit_bytes_total{instance=~\"$instance\", name=~\"$name\"}[$__rate_interval]))",
     "legendFormat": "{{container_label_com_docker_compose_project}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "received total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(instance, container_label_com_docker_compose_project) (rate(container_network_receive_bytes_total{instance=~\"$instance\", name=~\"$name\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "{{container_label_com_docker_compose_project}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "transmit total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(instance, container_label_com_docker_compose_project) (rate(container_network_transmit_bytes_total{instance=~\"$instance\", name=~\"$name\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "{{container_label_com_docker_compose_project}} @ {{instance}}"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "notes: storage metrics limitations",
   "type": "text",
   "gridPos": { "h": 4, "w": 9, "x": 8, "y": 81 },
   "options": {
    "content": "\nRead/write from NFS and SMB shares\nwill not be shown in the storage throughput.\n\nCadvisor exports data from cgroup io.stats,\nwhich are only calculated for block devices.\n"
   }
  },
  {
   "title": "disk read rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance, container_label_com_docker_compose_project)(rate(container_fs_reads_bytes_total{instance=~\"$instance\", name=~\"$name\"}[$__rate_interval]))",
     "legendFormat": "{{container_label_com_docker_compose_project}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "disk write rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance, container_label_com_docker_compose_project)(rate(container_fs_writes_bytes_total{instance=~\"$instance\", name=~\"$name\"}[$__rate_interval]))",
     "legendFormat": "{{container_label_com_docker_compose_project}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "disk read total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(instance, container_label_com_docker_compose_project)(rate(container_fs_reads_bytes_total{instance=~\"$instance\", name=~\"$name\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "{{container_label_com_docker_compose_project}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "disk written total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(instance, container_label_com_docker_compose_project)(rate(container_fs_writes_bytes_total{instance=~\"$instance\", name=~\"$name\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "{{container_label_com_docker_compose_project}} @ {{instance}}"
    }
   ]
  }
 ]
}