{
 "title": "Pod / Containers",
 "tags": [
  "maintainer:danil",
  "k8s-cluster"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(up{job=\"kube-state-metrics\", endpoint=\"\"}[$__range])))"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "query_result(group by(namespace) (last_over_time(kube_namespace_created{location=\"$location\"}[$__range])))"
    }
   },
   {
    "name": "workload",
    "query": {
     "query": "query_result(label_join(last_over_time(namespace_workload_pod:kube_pod_owner:relabel{location=\"$location\", namespace=\"$namespace\"}[$__range]), \"human_name\", \"/\", \"workload_type\", \"workload\"))"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "query_result(group by(pod) (last_over_time( namespace_workload_pod:kube_pod_owner:relabel{location=\"$location\",namespace=\"$namespace\",workload=~\"$workload\"}[$__range])))"
    }
   },
   {
    "name": "pod_uid",
    "label": "UID",
    "query": {
     "query": "query_result(last_over_time(kube_pod_info{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\"}[$__range]))"
    }
   },
   {
    "name": "container",
    "label": "container",
    "query": {
     "query": "query_result(group by(human_name, container) (  label_replace(    last_over_time(      kube_pod_container_info{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\"}[$__range]    ),    \"human_name\",    \"main/$1\",    \"container\",    \"(.*)\"  )or  (        (            max_over_time(              kube_pod_status_phase{location=\"$location\", namespace=\"$namespace\", phase=\"Pending\", pod=~\"$pod\", uid=~\"$pod_uid\"}[$__range]            )          ==            1        )      *        0    + on (uid) group_right()      label_replace(        last_over_time(          kube_pod_init_container_info{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", restart_policy!=\"Always\"}[$__range]        ),        \"human_name\",        \"init/$1\",        \"container\",        \"(.*)\"      )  )  or (      label_replace(        last_over_time(          kube_pod_init_container_info{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", restart_policy=\"Always\"}[$__range]        ),        \"human_name\",        \"sidecar/$1\",        \"container\",        \"(.*)\"      )      )))"
    }
   },
   {
    "name": "container_name",
    "query": {
     "query": "query_result(label_replace((last_over_time(kube_pod_container_info{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"}[$__range])or last_over_time(kube_pod_init_container_info{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"}[$__range])), \"name\", \"$1\", \"container_id\", \"containerd://(.*)\"))"
    }
   },
   {
    "name": "id",
    "query": {
     "query": "query_result(label_replace(last_over_time(container_cpu_usage_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$container_name\"}[$__range]),\"human_name\", \"$1\",\"name\", \"(.*)\"))"
    }
   },
   {
    "name": "split_ids",
    "label": "Split IDs",
    "query": "United : container, Split : container\\, name"
   },
   {
    "name": "pod_nodes",
    "query": {
     "query": "query_result(last_over_time(kube_pod_info{location=\"$location\", namespace=\"$namespace\", uid=~\"$pod_uid\"}[$__range]))"
    }
   }
  ]
 },
 "panels": [
  { "title": "info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "container info",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max by(pod, uid, node, container, name, image, id, instance, restart_policy) (\r\n  # kube-state-metrics sometimes prints different image_spec for the same container ID,\r\n  # which causes errors with duplicate entries.\r\n  # This is probably related to using AdvancedDaemonSet from OpenKruise\r\n  max by(namespace, pod, uid, node, container, name, image, restart_policy) (label_replace((\r\n    # when pod name is the same (for example, for static pods, like kube-apiserver)\r\n    # sometimes kube-state-metrics updates only UID, while still keeping old container_id\r\n    # which leads to many-to-one matching in join queries like this one\r\n    # topk(count_over_time) ensures that we pick metrics that were present for the longest interval\r\n    # container_id!=\"\" is required to skip containers that never started because of failed dependency, like image pull failed or mounted configmap/secret missing\r\n    topk by(namespace, pod, uid, node, container, container_id) (1,\r\n      count_over_time(kube_pod_container_info{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", container=~\"$container\", container_id!=\"\"}[$__range])\r\n      or\r\n      count_over_time(kube_pod_init_container_info{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", container=~\"$container\", container_id!=\"\"}[$__range])\r\n    )\r\n  ), \"name\", \"$1\", \"container_id\", \"containerd://(.*)\")) * 0\r\n  + on(namespace, pod, container, name) group_left(id)\r\n  max by(namespace, pod, container, name, id) (max_over_time(container_start_time_seconds{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", name=~\"$id\"}[$__range]))\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "# we need cadvisor instance for cgroup details link\r\nmax by(pod, container, name, instance) (\r\n  max without(uid) (max_over_time(container_last_seen{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", name=~\"$id\"}[$__range]))\r\n) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(pod, container, name, instance) (\r\n  max_over_time(container_start_time_seconds{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", name=~\"$id\"}[$__range])\r\n) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "(min by(pod, container, name, instance) (\r\n  timestamp(container_last_seen{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", name=~\"$id\"})\r\n  -\r\n  container_last_seen{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", name=~\"$id\"}\r\n  or\r\n  time() - max_over_time(container_last_seen{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", name=~\"$id\"}[$__range])\r\n))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pod info",
   "type": "text",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 13 },
   "options": {
    "content": "# - status\r\n# - uid\r\n# - ip\r\n# - node"
   }
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 2, "w": 10, "x": 2, "y": 13 },
   "targets": [
    {
     "expr": "min by(pod) (\r\n(\r\n    (max_over_time(kube_pod_status_phase{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", phase=\"Failed\"}[$__interval]) == 1) * 2\r\n    or\r\n    (max_over_time(kube_pod_status_phase{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", phase=\"Succeeded\"}[$__interval]) == 1) * 3\r\n    or\r\n    (max_over_time(kube_pod_status_phase{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", phase=\"Pending\"}[$__interval]) == 1) * 4\r\n    or\r\n    (\r\n        max_over_time(kube_pod_status_phase{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", phase=\"Running\"}[$__interval]) == 1\r\n        and on(namespace, pod, uid)\r\n        min_over_time(kube_pod_status_ready{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", condition=\"true\"}[$__interval]) == 1\r\n    ) * 5\r\n    or\r\n    (\r\n        max_over_time(kube_pod_status_phase{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", phase=\"Running\"}[$__interval]) == 1\r\n        and on(namespace, pod, uid)\r\n        min_over_time(kube_pod_status_ready{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", condition=\"true\"}[$__interval]) == 0\r\n    ) * 6\r\n    or\r\n    (max_over_time(kube_pod_status_phase{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", phase=\"Unknown\"}[$__interval]) == 1) * 7\r\n    or\r\n    # when no condition above satisfied, use this as a fallback\r\n    (max_over_time(kube_pod_status_phase{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", phase=\"Unknown\"}[$__interval]) * 0 + 8)\r\n)\r\n* on(namespace, pod, uid) group_left(node)\r\nkube_pod_info{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "exit statuses",
   "type": "table",
   "description": "Requires a custom recording rule. Empty if containers never restarted.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "max by(uid, container, exit_code, reason, timestamp) (last_over_time(reason:kube_pod_container_status_last_terminated_timestamp{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\"}[$__range]))\r\n* 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 2, "w": 10, "x": 2, "y": 15 },
   "targets": [
    {
     "expr": "max by(pod, uid) (\r\n  last_over_time(kube_pod_info{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\"}[$__interval])\r\n)\r\nor on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 2, "w": 10, "x": 2, "y": 17 },
   "targets": [
    {
     "expr": "max by(pod, readable_pod_ip) (\r\n  label_replace(\r\n    last_over_time(kube_pod_info{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\"}[$__interval])\r\n    , \"readable_pod_ip\", \"$1\", \"pod_ip\", \"(.*)\"\r\n  )\r\n  or\r\n  # grafana breaks when the only value is empty\r\n  label_replace(\r\n    last_over_time(kube_pod_info{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\"}[$__interval])\r\n    , \"readable_pod_ip\", \"-\", \"invalid\", \"\"\r\n  ) * 0\r\n)\r\nor on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 2, "w": 10, "x": 2, "y": 19 },
   "targets": [
    {
     "expr": "max by(pod, node) (\r\n  last_over_time(kube_pod_info{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\"}[$__interval])\r\n)\r\nor on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container status",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "min by(container) (\r\n    (\r\n        max_over_time(kube_pod_container_status_terminated{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"}[$__interval]) == 1\r\n        and\r\n        min_over_time(kube_pod_container_status_last_terminated_exitcode{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"}[$__interval]) == 0\r\n    ) * 10\r\n    or\r\n    (\r\n        max_over_time(kube_pod_container_status_terminated{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"}[$__interval]) == 1\r\n        and\r\n        min_over_time(kube_pod_container_status_last_terminated_exitcode{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"}[$__interval]) != 0\r\n    ) * 11\r\n    or\r\n    (\r\n        max_over_time(kube_pod_container_status_waiting{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"}[$__interval]) == 1\r\n        and ignoring(reason)\r\n        max_over_time(kube_pod_container_status_waiting_reason{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\", reason=\"CrashLoopBackOff\"}[$__interval]) == 1\r\n    ) * 20\r\n    or\r\n    (\r\n        max_over_time(kube_pod_container_status_waiting{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"}[$__interval]) == 1\r\n        and ignoring(reason)\r\n        max_over_time(kube_pod_container_status_waiting_reason{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\", reason=~\"ErrImagePull|ImagePullBackOff\"}[$__interval]) == 1\r\n    ) * 21\r\n    or\r\n    (\r\n        max_over_time(kube_pod_container_status_waiting{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"}[$__interval]) == 1\r\n    ) * 29\r\n    or\r\n    (\r\n        min_over_time(kube_pod_container_status_ready{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"}[$__interval]) == 1\r\n        and\r\n        min_over_time(kube_pod_container_status_running{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"}[$__interval]) == 1\r\n    ) * 30\r\n    or\r\n    (\r\n        min_over_time(kube_pod_container_status_ready{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"}[$__interval]) == bool 0\r\n        and\r\n        min_over_time(kube_pod_container_status_running{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"}[$__interval]) == 1\r\n    ) * 31\r\n    or\r\n    # for some reason I don't see kube_pod_container_status_last_terminated_exitcode on some job containers\r\n    (\r\n        (kube_pod_container_status_terminated{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"}) == 1\r\n    ) * 40\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "# group by(container) (\r\n#   max_over_time(kube_pod_status_phase{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", phase=\"Pending\"}[$__interval]) == 1\r\n#   or\r\n#   max_over_time(kube_pod_init_container_info{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", restart_policy=\"Always\"}[$__interval])\r\n# ) * 0\r\n# +\r\nlabel_replace(\r\nmin by(container) (\r\n    (\r\n        max_over_time(kube_pod_init_container_status_terminated{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"}[$__interval]) == 1\r\n        and on(namespace, pod, container)\r\n        max_over_time(kube_pod_init_container_status_terminated_reason{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\", reason=\"Completed\"}[$__interval]) == 1\r\n    ) * 10\r\n    or\r\n    (\r\n        max_over_time(kube_pod_init_container_status_terminated{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\"}[$__interval]) == 1\r\n        and on(namespace, pod, container)\r\n        count by(namespace, pod, container) (\r\n            max_over_time(kube_pod_init_container_status_terminated_reason{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\", reason!=\"Completed\"}[$__interval]) == 1\r\n        ) > 0\r\n    ) * 11\r\n    or\r\n    (\r\n        max_over_time(kube_pod_init_container_status_waiting{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"}[$__interval]) == 1\r\n    ) * 29\r\n    or\r\n    (\r\n        min_over_time(kube_pod_init_container_status_ready{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"}[$__interval]) == 1\r\n        and\r\n        min_over_time(kube_pod_init_container_status_running{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"}[$__interval]) == 1\r\n    ) * 30\r\n    or\r\n    (\r\n        (min_over_time(kube_pod_init_container_status_ready{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"}[$__interval]) == bool 0)\r\n        and\r\n        min_over_time(kube_pod_init_container_status_running{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"}[$__interval]) == 1\r\n    ) * 31\r\n    or\r\n    (\r\n        (kube_pod_init_container_status_terminated{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"} == 1)\r\n    ) * 40\r\n)\r\n, \"container\", \"_init/$1\", \"container\", \"(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "last exit status history",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "topk by(container) (1,\r\nmax by(container, info) (\r\n  label_join(\r\n    count_values without() (\"exit_code\",\r\n      last_over_time(kube_pod_container_status_last_terminated_exitcode{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\"}[$__interval])\r\n    )\r\n    * on(location, namespace, pod, uid, container) group_left(reason)\r\n    topk by(location, namespace, pod, uid, container) (1,\r\n      count_over_time(kube_pod_container_status_last_terminated_reason{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\"}[$__interval])\r\n    )\r\n    , \"info\", \": \", \"exit_code\", \"reason\"\r\n  )\r\n  or\r\n  label_join(\r\n    topk by(location, namespace, pod, uid, container) (1,\r\n      # kube-state-metrics doesn't expose last_terminated_exitcode for init containers\r\n      count_over_time(kube_pod_init_container_status_last_terminated_reason{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\"}[$__interval])\r\n    )\r\n    , \"info\", \": \", \"reason\"\r\n  )\r\n  or\r\n  label_replace(\r\n    last_over_time(kube_pod_container_info{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\"}[$__interval])\r\n    or\r\n    last_over_time(kube_pod_init_container_info{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", restart_policy=\"Always\"}[$__interval])\r\n    , \"info\", \"no restarts\", \"invalid\", \"\"\r\n  ) * 0\r\n)\r\n)\r\nor on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container id history",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "max by(container, readable_container_id) (\r\n  label_replace(\r\n    last_over_time(kube_pod_container_info{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[$__interval])\r\n    or\r\n    label_replace(last_over_time(kube_pod_init_container_info{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[$__interval]), \"container\", \"_init/$1\", \"container\", \"(.*)\")\r\n    , \"readable_container_id\", \"$1\", \"container_id\", \"containerd://(.*)\"\r\n  )\r\n  or\r\n  # grafana breaks when the only value is empty\r\n  label_replace(\r\n    last_over_time(kube_pod_container_info{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[$__interval])\r\n    or\r\n    label_replace(last_over_time(kube_pod_init_container_info{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[$__interval]), \"container\", \"_init/$1\", \"container\", \"(.*)\")\r\n    , \"readable_container_id\", \"-\", \"invalid\", \"\"\r\n  ) * 0\r\n)\r\nor on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "start time",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "targets": [
    {
     "expr": "max by(container) (max_over_time(container_start_time_seconds{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__interval])) * 1000\r\nor\r\nmax by(container) (max_over_time(kube_pod_container_state_started{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\"}[$__interval])) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "image version history",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "max by(container, image_spec) (\r\n  last_over_time(kube_pod_container_info{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[$__interval])\r\n  or\r\n  label_replace(last_over_time(kube_pod_init_container_info{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[$__interval]), \"container\", \"_init/$1\", \"container\", \"(.*)\")\r\n)\r\nor on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "start time (ago)",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "$__to / 1000 - max by(container) (max_over_time(container_start_time_seconds{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__interval]))\r\nor\r\n$__to / 1000 - max by(container) (max_over_time(kube_pod_container_state_started{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container restarts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum by(container) (\r\n  rate(kube_pod_container_status_restarts_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"}[$__rate_interval])\r\n  or\r\n  rate(kube_pod_init_container_status_restarts_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"}[$__rate_interval])\r\n  * on(pod, uid, container) group_left()\r\n  max by(pod, uid, container) (last_over_time(kube_pod_init_container_info{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\", restart_policy=\"Always\"}[$__rate_interval]))\r\n) * $__interval_ms / 1000\r\n# sum by(container) (max_over_time(kube_pod_container_status_restarts_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "uptime (logarithmic)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - max by($split_ids) (last_over_time(container_start_time_seconds{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__interval]))",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by($split_ids) (rate(container_cpu_usage_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", cpu=\"total\"}[$__rate_interval]))",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  {
   "title": "cpu kernel mode %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by($split_ids) (\r\n  (rate(container_cpu_system_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__rate_interval]))\r\n  /\r\n  sum without(cpu) (rate(container_cpu_usage_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", cpu=\"total\"}[$__rate_interval]) + 1e-12)\r\n)",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  {
   "title": "cpu spec: request",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "max by(container) (\r\n  avg_over_time(kube_pod_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", resource=\"cpu\", container=~\"$container\", uid=~\"$pod_uid\"}[$__interval])\r\n  or\r\n  avg_over_time(kube_pod_init_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", resource=\"cpu\", container=~\"$container\", uid=~\"$pod_uid\"}[$__interval])\r\n)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "cpu usage / request %",
   "type": "timeseries",
   "description": "clamped at 300%",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by($split_ids) (rate(container_cpu_usage_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", cpu=\"total\"}[$__rate_interval]))\r\n/ on(container) group_left()\r\navg by(container) (\r\n  avg_over_time(kube_pod_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", resource=\"cpu\", container=~\"$container\", uid=~\"$pod_uid\"}[$__interval]) != 0\r\n  or\r\n  avg_over_time(kube_pod_init_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", resource=\"cpu\", container=~\"$container\", uid=~\"$pod_uid\"}[$__interval]) != 0\r\n)",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  {
   "title": "cpu (related to limit, empty when limit is not set)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 }
  },
  {
   "title": "spec: cpu limit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "max by($split_ids) (\r\n  container_spec_cpu_quota{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}\r\n  /\r\n  container_spec_cpu_period{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}\r\n)",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  {
   "title": "spec: cpu burst",
   "type": "timeseries",
   "description": "empty is cgroup-burst metrics are not configured, of if container doesn't have burst",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(container) (\r\n    kube_pod_container_cgroup_burst{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\"}\r\n)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "cpu usage / limit %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by($split_ids) (\r\n  sum without(cpu) (rate(container_cpu_usage_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", cpu=\"total\"}[$__rate_interval]))\r\n  * avg_over_time(container_spec_cpu_period{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__rate_interval])\r\n  / avg_over_time(container_spec_cpu_quota{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__rate_interval])\r\n)\r\nor\r\n# when container_spec_cpu_quota is missing\r\nsum by($split_ids) (rate(container_cpu_usage_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", cpu=\"total\"}[$__rate_interval]))\r\n/ on(container) group_left()\r\nsum by(container) (avg_over_time(kube_pod_container_resource_limits{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", resource=\"cpu\",container=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  {
   "title": "CPU throttled (average)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by($split_ids) (rate(container_cpu_cfs_throttled_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__rate_interval]))",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  {
   "title": "CPU throttling periods %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by($split_ids) (\r\n  + increase(container_cpu_cfs_throttled_periods_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__rate_interval])\r\n  / clamp_min(increase(container_cpu_cfs_periods_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__rate_interval]), 1)\r\n)",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  {
   "title": "CPU throttled (total time)",
   "type": "timeseries",
   "description": "sum_over_time of seconds spent throtting",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by($split_ids) (\r\n  (rate(container_cpu_cfs_throttled_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__rate_interval]) * $__interval_ms / 1000 )\r\n)",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  {
   "title": "CPU burst periods %",
   "type": "timeseries",
   "description": "empty is cgroup-burst metrics are not configured, of if container doesn't have burst",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "# if container didn't run at some interval, you will have division by zero, so we do ` / increase + epsilon`\r\n# sometimes burst reporting is slightly misaligned with cadvisor reporting,\r\n# and you get non-zero burst with (zero+epsilon) cfs_periods, which results in unrealistic peak\r\n# using clamp_max fixes this, although overall result can be a bit inaccurate\r\nclamp_max(\r\n  avg by($split_ids) (\r\n    (increase(container_cpu_cgroup_burst_periods_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__rate_interval]))\r\n    / on(name) group_left()\r\n    clamp_min(increase(container_cpu_cfs_periods_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__rate_interval]), 1)\r\n  )\r\n, 1)",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  {
   "title": "CPU burst usage (total time)",
   "type": "timeseries",
   "description": "sum_over_time of seconds spent bursting. Empty is cgroup-burst metrics are not configured, of if container doesn't have burst.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by($split_ids) (rate(container_cpu_cgroup_burst_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  { "title": "memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "notes: memory types",
   "type": "text",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 88 },
   "options": {
    "content": "- `rss` is anon memory\n- `wss` = rss + active cache + kernel\n- `raw` = `rss` + full cache + kernel\n- Cache is active if it used _often_ (more than once?)\n"
   }
  },
  {
   "title": "notes: memory events",
   "type": "text",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 88 },
   "options": {
    "content": "What to look for:\n- WSS reaching limit causes file garbage collection\n- RSS reaching limit causes OOM kill\n"
   }
  },
  {
   "title": "memory request",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(container) (\r\n  max_over_time(kube_pod_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\", container=~\"$container\"}[$__interval])\r\n  or\r\n  max_over_time(kube_pod_init_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\", container=~\"$container\"}[$__interval])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "memory limit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by($split_ids) (\r\n  max_over_time(container_spec_memory_limit_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__rate_interval])\r\n  # if container is not running but exist in apiserver\r\n  # we still want to show it in limits graph, so we fall back to metrics from ksm\r\n  or on(location, namespace, pod, container)\r\n  (\r\n    max_over_time(kube_pod_container_resource_limits{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\", container=~\"$container\"}[$__interval])\r\n    or\r\n    max_over_time(kube_pod_init_container_resource_limits{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\", container=~\"$container\"}[$__interval])\r\n  )\r\n) != 0",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  {
   "title": "rss",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by($split_ids) (avg_over_time(container_memory_rss{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__interval]))\r\nor\r\navg by($split_ids) (avg_over_time(container_memory_rss{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__rate_interval]))",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  {
   "title": "rss + kernel - request",
   "type": "timeseries",
   "description": "negative values means request is higher than usage; positive values mean your request is too small; empty if container doesn't have memory request",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\r\n  avg by($split_ids) (\r\n    + avg_over_time(container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__interval])\r\n    - avg_over_time(container_memory_cache{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__interval])\r\n  )\r\n  or\r\n  avg by($split_ids) (\r\n    + avg_over_time(container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__rate_interval])\r\n    - avg_over_time(container_memory_cache{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__rate_interval])\r\n  )\r\n)\r\n- on(container) group_left()\r\navg by(container) (\r\n  avg_over_time(kube_pod_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\", container=~\"$container\"}[$__interval]) != 0\r\n  or\r\n  max_over_time(kube_pod_init_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\", container=~\"$container\"}[$__interval]) != 0\r\n)",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  {
   "title": "rss + kernel",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by($split_ids) (\r\n  + avg_over_time(container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__interval])\r\n  - avg_over_time(container_memory_cache{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__interval])\r\n)\r\nor\r\navg by($split_ids) (\r\n  + avg_over_time(container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__rate_interval])\r\n  - avg_over_time(container_memory_cache{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__rate_interval])\r\n)",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  {
   "title": "rss + kernel / request %",
   "type": "timeseries",
   "description": "empty if container doesn't have memory request",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\r\n  avg by($split_ids) (\r\n    + avg_over_time(container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__interval])\r\n    - avg_over_time(container_memory_cache{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__interval])\r\n  )\r\n  or\r\n  avg by($split_ids) (\r\n    + avg_over_time(container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__rate_interval])\r\n    - avg_over_time(container_memory_cache{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__rate_interval])\r\n  )\r\n)\r\n/ on(container) group_left()\r\navg by(container) (\r\n  avg_over_time(kube_pod_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\", container=~\"$container\"}[$__interval]) != 0\r\n  or\r\n  max_over_time(kube_pod_init_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\", container=~\"$container\"}[$__interval]) != 0\r\n)",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  {
   "title": "wss",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by($split_ids) (avg_over_time(container_memory_working_set_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__interval]))\r\nor\r\navg by($split_ids) (avg_over_time(container_memory_working_set_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__rate_interval]))",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  {
   "title": "rss + kernel / limit %",
   "type": "timeseries",
   "description": "empty if container doesn't have memory limit",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by($split_ids) (\r\n  (\r\n  + avg_over_time(container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__interval])\r\n  - avg_over_time(container_memory_cache{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__interval])\r\n  )\r\n  / (avg_over_time(container_spec_memory_limit_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__interval]) != 0)\r\n)\r\nor\r\navg by($split_ids) (\r\n  (\r\n  + avg_over_time(container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__rate_interval])\r\n  - avg_over_time(container_memory_cache{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__rate_interval])\r\n  )\r\n  / (avg_over_time(container_spec_memory_limit_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__rate_interval]) != 0)\r\n)",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  {
   "title": "full usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by($split_ids) (avg_over_time(container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__interval]))\r\nor\r\navg by($split_ids) (avg_over_time(container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__rate_interval]))",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  {
   "title": "wss / limit %",
   "type": "timeseries",
   "description": "empty if container doesn't have memory limit",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by($split_ids) (\r\n  + avg_over_time(container_memory_working_set_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__interval])\r\n  / (avg_over_time(container_spec_memory_limit_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__interval]) != 0)\r\n)\r\nor\r\navg by($split_ids) (\r\n  + avg_over_time(container_memory_working_set_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__rate_interval])\r\n  / (avg_over_time(container_spec_memory_limit_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__rate_interval]) != 0)\r\n)",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  {
   "title": "max over container lifetime",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by($split_ids) (avg_over_time(container_memory_max_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__interval]))\r\nor\r\navg by($split_ids) (avg_over_time(container_memory_max_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__rate_interval]))",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  {
   "title": "minor page fault rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "+ sum by($split_ids) (rate(container_memory_failures_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", failure_type=\"pgfault\"}[$__rate_interval]))\r\n- sum by($split_ids) (rate(container_memory_failures_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", failure_type=\"pgmajfault\"}[$__rate_interval]))",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  {
   "title": "active cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by($split_ids) (avg_over_time(container_memory_total_active_file_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__interval]))\r\nor\r\navg by($split_ids) (avg_over_time(container_memory_total_active_file_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__rate_interval]))",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  {
   "title": "major page fault rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by($split_ids) (rate(container_memory_failures_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", failure_type=\"pgmajfault\"}[$__rate_interval]))",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  {
   "title": "network (shared between containers)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 134 }
  },
  {
   "title": "receive rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(interface) (rate(container_network_receive_bytes_total{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "receive total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(interface) (rate(container_network_receive_bytes_total{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "transmit rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(interface) (rate(container_network_transmit_bytes_total{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "transmit total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(interface) (rate(container_network_transmit_bytes_total{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 149 } },
  {
   "title": "notes: storage",
   "type": "text",
   "gridPos": { "h": 7, "w": 5, "x": 2, "y": 150 },
   "options": {
    "content": "\nRead/write rate counts only block devices present on the node.\n\nIt will be missing NFS and SMB shares, as well as any other\nvirtual filesystems not backed by a device.\n"
   }
  },
  {
   "title": "ephemeral storage pod summary",
   "type": "timeseries",
   "description": "volumes can be above actual usage because memory-baked volumes don't use storage but there is no metadata to exclude them here",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (avg_over_time(kube_summary_pod_ephemeral_storage_used_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\"}[$__interval]))\r\nor\r\n# fall back to ephemeral-storage exporter in case kube-summary is missing\r\nmax by(pod) (avg_over_time(ephemeral_storage_pod_usage{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\"}[$__interval]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum by(pod) (max by(pod, container) (avg_over_time(kube_summary_container_logs_used_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\"}[$__interval])))",
     "legendFormat": "logs"
    },
    {
     "expr": "sum by(pod) (max by(pod, container) (avg_over_time(kube_summary_container_rootfs_used_bytes{container=~\"$container\", location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\"}[$__interval])))",
     "legendFormat": "rootfs"
    },
    {
     "expr": "sum by(pod) (max by(pod, volume_name) (avg_over_time(ephemeral_storage_container_volume_usage{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\"}[$__interval])))",
     "legendFormat": "volumes"
    }
   ]
  },
  {
   "title": "disk read rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(container) (rate(container_fs_reads_bytes_total{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", name=~\"$id\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "disk usage: rootfs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(container) (avg_over_time(kube_summary_container_rootfs_used_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "disk write rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(container) (rate(container_fs_writes_bytes_total{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", name=~\"$id\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "disk usage: volumes",
   "type": "timeseries",
   "description": "empty if pod doesn't have volumes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(volume_name) (avg_over_time(ephemeral_storage_container_volume_usage{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "logs: written",
   "type": "timeseries",
   "description": "best-effort approximation for volume of written logs; can break in many cases",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 171 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(container) (\r\n+ sum by(pod, uid, container) (rate(kube_summary_container_logs_used_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[$__rate_interval])) * $__interval_ms / 1000\r\n# when logs are rotated, last 10MiB seems to be kept, so we need to account for this\r\n# this is a best-effort approximation, it's brittle\r\n- (\r\n  0 * (sum by(pod, uid, container) (\r\n    rate(kube_pod_container_status_restarts_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"}[$__rate_interval])\r\n    or\r\n    rate(kube_pod_init_container_status_restarts_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"}[$__rate_interval])\r\n    * on(pod, uid, container) group_left()\r\n    max by(pod, uid, container) (last_over_time(kube_pod_init_container_info{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\", restart_policy=\"Always\"}[$__rate_interval]))\r\n  ) != 0)\r\n  or\r\n  sum by(pod, uid, container) (resets(kube_summary_container_logs_used_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"}[$__rate_interval]))\r\n  / on() group_left()\r\n  round(clamp_max(vector($__rate_interval_ms / $__interval_ms), 3))\r\n)\r\n* 1024 * 1024 * 10\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "disk usage: logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 171 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(container) (avg_over_time(kube_summary_container_logs_used_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}