{
 "title": "Namespace / Pods",
 "tags": [
  "maintainer:danil",
  "k8s-cluster"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(up{job=\"kube-state-metrics\", endpoint=\"\"}[$__range])))"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "query_result(group by(namespace) (last_over_time(kube_namespace_status_phase{location=\"$location\"}[$__range])))"
    }
   },
   {
    "name": "workload",
    "query": {
     "query": "query_result(group by(human_name, workload) (label_join(last_over_time(namespace_workload_pod:kube_pod_owner:relabel{location=\"$location\", namespace=\"$namespace\"}[$__range]), \"human_name\", \"/\", \"workload_type\", \"workload\")))"
    }
   },
   {
    "name": "node_selector",
    "label": "Node",
    "query": {
     "query": "query_result(group by(node) (max by(location, uid, node) (last_over_time(kube_pod_info{location=\"$location\", namespace=\"$namespace\"}[$__range])) * on(location, uid) group_left() max by(location, uid) (last_over_time(namespace_workload_pod:kube_pod_owner:relabel{location=\"$location\",namespace=\"$namespace\",workload=~\"$workload\"}[$__range]))))"
    }
   },
   { "name": "pod_filter", "label": "Pod filter" },
   { "name": "pod_anti_filter" },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "query_result(group by(pod) (last_over_time(        namespace_workload_pod:kube_pod_owner:relabel{location=\"$location\",namespace=\"$namespace\",workload=~\"$workload\", pod=~\".*($pod_filter).*\", pod!~\"$pod_anti_filter\"}[$__range]      )    * on (location, namespace, pod, uid) group_left ()      max by(location, namespace, pod, uid) (        last_over_time(kube_pod_container_status_ready{location=\"$location\",namespace=\"$namespace\"}[$__range])      )  * on (location, namespace, pod, uid) group_left (node)    max by(location, namespace, pod, uid, node) (      last_over_time(kube_pod_info{location=\"$location\",namespace=\"$namespace\",node=~\"$node_selector\"}[$__range])    )))"
    }
   },
   {
    "name": "pod_uid",
    "label": "uid",
    "query": {
     "query": "query_result(group by(uid) (last_over_time(kube_pod_info{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\"}[$__range])))"
    }
   },
   {
    "name": "container_name",
    "query": {
     "query": "query_result(group by(name) (  label_replace(    last_over_time(kube_pod_container_info{location=\"$location\",namespace=\"$namespace\",pod=~\"$pod\",uid=~\"$pod_uid\", container_id!=\"\"}[$__range])    or    last_over_time(kube_pod_init_container_info{location=\"$location\",namespace=\"$namespace\",pod=~\"$pod\",uid=~\"$pod_uid\", container_id!=\"\", restart_policy!=\"Always\"}[$__range])    * on(location, namespace, pod, uid, container) group_left()    (max_over_time(kube_pod_init_container_status_running{location=\"$location\",namespace=\"$namespace\",pod=~\"$pod\",uid=~\"$pod_uid\"}[$__range]) == 1)    or    last_over_time(kube_pod_init_container_info{location=\"$location\",namespace=\"$namespace\",pod=~\"$pod\",uid=~\"$pod_uid\", container_id!=\"\", restart_policy=\"Always\"}[$__range])    , \"name\", \"$1\", \"container_id\", \"containerd://(.*)\"  )))"
    }
   },
   {
    "name": "total",
    "query": "Show : \"\", Hide : \"invalid123\""
   },
   {
    "name": "pod_nodes",
    "query": {
     "query": "query_result(group by(node) (last_over_time(kube_pod_info{location=\"$location\", namespace=\"$namespace\", uid=~\"$pod_uid\"}[$__range])))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "pod info",
   "type": "table",
   "gridPos": { "h": 10, "w": 20, "x": 1, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod, uid, node) (\r\n  last_over_time(kube_pod_info{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\"}[$__range])\r\n) * on(pod, uid) group_left(workload_type, workload)\r\nmax by(pod, uid, workload_type, workload) (\r\n  last_over_time(namespace_workload_pod:kube_pod_owner:relabel{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid!=\"\"}[$__range])\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(pod, uid) (\r\n  max_over_time(kube_pod_created{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\"}[$__range])\r\n) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(pod, uid) (\r\n  # when pod name is the same (for example, for static pods, like kube-apiserver)\r\n  # sometimes kube-state-metrics updates only UID, while still keeping old container_id\r\n  # which leads to many-to-one matching in join queries like this one\r\n  # topk(count_over_time) ensures that we pick metrics that were present for the longest interval\r\n  topk by(namespace, pod, container, name) (1, label_replace((\r\n    count_over_time(kube_pod_container_info{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", container_id!=\"\"}[$__range])\r\n    or\r\n    count_over_time(kube_pod_init_container_info{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", container_id!=\"\"}[$__range])\r\n  ), \"name\", \"$1\", \"container_id\", \"containerd://(.*)\")) * 0\r\n  + on(namespace, pod, container, name) group_right(uid)\r\n  max without(uid) (max_over_time(container_last_seen{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\"}[$__range]))\r\n) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\r\n  min by(pod, uid) (\r\n    # when pod name is the same (for example, for static pods, like kube-apiserver)\r\n    # sometimes kube-state-metrics updates only UID, while still keeping old container_id\r\n    # which leads to many-to-one matching in join queries like this one\r\n    # topk(count_over_time) ensures that we pick metrics that were present for the longest interval\r\n    topk by(namespace, pod, container, name) (1, label_replace((\r\n      count_over_time(kube_pod_container_info{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", container_id!=\"\"}[$__range])\r\n      or\r\n      count_over_time(kube_pod_init_container_info{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", container_id!=\"\"}[$__range])\r\n    ), \"name\", \"$1\", \"container_id\", \"containerd://(.*)\")) * 0\r\n    + on(namespace, pod, container, name) group_right(uid)\r\n    min by(namespace, pod, container, name) (\r\n      (\r\n        timestamp(container_last_seen{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\"})\r\n        -\r\n        last_over_time(container_last_seen{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\"}[1m])\r\n      )\r\n      or\r\n      (time() - max_over_time(container_last_seen{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\"}[$__range]))\r\n    )\r\n  )\r\n  or\r\n  # when no container_last_seen_time exist for selected pod, fall back to pod creation time\r\n  max by(pod, uid) (time() - max_over_time(kube_pod_created{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\"}[$__range]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "status",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "min by(pod) (\r\n    (max_over_time(kube_pod_status_phase{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", phase=\"Failed\"}[$__interval]) == 1) * 2\r\n    or\r\n    (max_over_time(kube_pod_status_phase{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", phase=\"Succeeded\"}[$__interval]) == 1) * 3\r\n    or\r\n    (max_over_time(kube_pod_status_phase{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", phase=\"Pending\"}[$__interval]) == 1) * 4\r\n    or\r\n    (\r\n        max_over_time(kube_pod_status_phase{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", phase=\"Running\"}[$__interval]) == 1\r\n        and on(namespace, pod, uid)\r\n        min_over_time(kube_pod_status_ready{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", condition=\"true\"}[$__interval]) == 1\r\n    ) * 5\r\n    or\r\n    (\r\n        max_over_time(kube_pod_status_phase{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", phase=\"Running\"}[$__interval]) == 1\r\n        and on(namespace, pod, uid)\r\n        min_over_time(kube_pod_status_ready{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", condition=\"true\"}[$__interval]) == 0\r\n    ) * 6\r\n    or\r\n    (max_over_time(kube_pod_status_phase{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", phase=\"Unknown\"}[$__interval]) == 1) * 7\r\n    or\r\n    # when no condition above satisfied, use this as a fallback\r\n    (max_over_time(kube_pod_status_phase{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", phase=\"Unknown\"}[$__interval]) * 0 + 8)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pod uid history",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "max by(pod, uid) (\r\n  last_over_time(kube_pod_info{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\"}[$__interval])\r\n)\r\nor on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pod-to-node mapping",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "max by(pod, node) (\r\n  last_over_time(kube_pod_info{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\"}[$__interval])\r\n)\r\nor on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pod created",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "targets": [
    {
     "expr": "max by(pod) (max_over_time(kube_pod_created{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\"}[$__interval])) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pod IP history",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "max by(pod, readable_pod_ip) (\r\n  label_replace(\r\n    last_over_time(kube_pod_info{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", pod_ip!=\"\", host_network=\"true\"}[$__interval])\r\n    , \"readable_pod_ip\", \"[host network] $1\", \"pod_ip\", \"(.*)\"\r\n  )\r\n  or\r\n  label_replace(\r\n    last_over_time(kube_pod_info{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", pod_ip!=\"\", host_network=\"false\"}[$__interval])\r\n    , \"readable_pod_ip\", \"$1\", \"pod_ip\", \"(.*)\"\r\n  )\r\n  or\r\n  # grafana breaks when the only value is empty\r\n  label_replace(\r\n    last_over_time(kube_pod_info{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", pod_ip=\"\"}[$__interval])\r\n    , \"readable_pod_ip\", \"-\", \"invalid\", \"\"\r\n  ) * 0\r\n)\r\nor on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "last container restart (ago)",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "$__to / 1000 - max by(pod) (max_over_time(container_start_time_seconds{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "containers (running)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum by(pod) (group by(pod, container) (last_over_time(container_cpu_usage_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "uptime (logarithmic)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - max by(pod) (avg_over_time(container_start_time_seconds{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "containers (scheduled)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum by(pod) (group by(pod, container) (\r\n    last_over_time(kube_pod_container_info{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])\r\n    or\r\n    last_over_time(kube_pod_init_container_info{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", restart_policy=\"Always\"}[$__rate_interval])\r\n))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container restarts (sum over time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(kube_pod_container_status_restarts_total{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "cpu", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "container cpu request",
   "type": "timeseries",
   "description": "empty is containers in pod don't have cpu request",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(pod) (\r\n  # max by(pod, container) eliminates artifacts when pod UID changes\r\n  max by(pod, container) (\r\n    sum_over_time(kube_pod_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", resource=\"cpu\"}[$__interval])\r\n    / on(job) group_left()\r\n    sum_over_time(up{job=\"kube-state-metrics\", location=\"$location\"}[$__interval])\r\n    # avg_over_time(kube_pod_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", resource=\"memory\"}[$__interval])\r\n    or\r\n    (\r\n      sum_over_time(kube_pod_init_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", resource=\"cpu\"}[$__interval])\r\n      / on(job) group_left()\r\n      sum_over_time(up{job=\"kube-state-metrics\", location=\"$location\"}[$__interval])\r\n      # avg_over_time(kube_pod_init_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", resource=\"memory\"}[$__interval])\r\n      and on(location, namespace, pod, uid, container)\r\n      (max_over_time(kube_pod_init_container_status_running{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\"}[$__interval]) == 1)\r\n    )\r\n  )\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\r\n  # max by(pod, container) eliminates artifacts when pod UID changes\r\n  max by(pod, container) (\r\n    sum_over_time(kube_pod_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", resource=\"cpu\"}[$__interval])\r\n    / on(job) group_left()\r\n    sum_over_time(up{job=\"kube-state-metrics\", location=\"$location\"}[$__interval])\r\n    # avg_over_time(kube_pod_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", resource=\"memory\"}[$__interval])\r\n    or\r\n    (\r\n      sum_over_time(kube_pod_init_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", resource=\"cpu\"}[$__interval])\r\n      / on(job) group_left()\r\n      sum_over_time(up{job=\"kube-state-metrics\", location=\"$location\"}[$__interval])\r\n      # avg_over_time(kube_pod_init_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", resource=\"memory\"}[$__interval])\r\n      and on(location, namespace, pod, uid, container)\r\n      (max_over_time(kube_pod_init_container_status_running{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\"}[$__interval]) == 1)\r\n    )\r\n  )\r\n)",
     "legendFormat": "Total"
    },
    {
     "expr": "max(kube_resourcequota{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", type=\"hard\", resource=\"requests.cpu\"})",
     "legendFormat": "quota"
    }
   ]
  },
  {
   "title": "container cpu limit",
   "type": "timeseries",
   "description": "empty is containers in pod don't have cpu limit",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(pod) (\r\n  # max by(pod, container) eliminates artifacts when pod UID changes\r\n  max by(pod, container) (\r\n    sum_over_time(kube_pod_container_resource_limits{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", resource=\"cpu\"}[$__interval])\r\n    / on(job) group_left()\r\n    sum_over_time(up{job=\"kube-state-metrics\", location=\"$location\"}[$__interval])\r\n    # avg_over_time(kube_pod_container_resource_limits{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", resource=\"memory\"}[$__interval])\r\n    or\r\n    (\r\n      sum_over_time(kube_pod_init_container_resource_limits{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", resource=\"cpu\"}[$__interval])\r\n      / on(job) group_left()\r\n      sum_over_time(up{job=\"kube-state-metrics\", location=\"$location\"}[$__interval])\r\n      # avg_over_time(kube_pod_init_container_resource_limits{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", resource=\"memory\"}[$__interval])\r\n      and on(location, namespace, pod, uid, container)\r\n      (max_over_time(kube_pod_init_container_status_running{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\"}[$__interval]) == 1)\r\n    )\r\n  )\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\r\n  # max by(pod, container) eliminates artifacts when pod UID changes\r\n  max by(pod, container) (\r\n    sum_over_time(kube_pod_container_resource_limits{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", resource=\"cpu\"}[$__interval])\r\n    / on(job) group_left()\r\n    sum_over_time(up{job=\"kube-state-metrics\", location=\"$location\"}[$__interval])\r\n    # avg_over_time(kube_pod_container_resource_limits{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", resource=\"memory\"}[$__interval])\r\n    or\r\n    (\r\n      sum_over_time(kube_pod_init_container_resource_limits{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", resource=\"cpu\"}[$__interval])\r\n      / on(job) group_left()\r\n      sum_over_time(up{job=\"kube-state-metrics\", location=\"$location\"}[$__interval])\r\n      # avg_over_time(kube_pod_init_container_resource_limits{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", resource=\"memory\"}[$__interval])\r\n      and on(location, namespace, pod, uid, container)\r\n      (max_over_time(kube_pod_init_container_status_running{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\"}[$__interval]) == 1)\r\n    )\r\n  )\r\n)",
     "legendFormat": "Total"
    },
    {
     "expr": "max(kube_resourcequota{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", type=\"hard\", resource=\"limits.cpu\"})",
     "legendFormat": "quota"
    }
   ]
  },
  {
   "title": "total cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\", cpu=\"total\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\", cpu=\"total\", invalid=$total}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "total cpu usage / total request",
   "type": "timeseries",
   "description": "clamped at 300%; empty if containers in pod don't have cpu request",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\", cpu=\"total\"}[$__rate_interval]))\r\n/\r\nsum by(pod) (\r\n  # max by(pod, container) eliminates artifacts when pod UID changes\r\n  max by(pod, container) (\r\n    avg_over_time(kube_pod_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", resource=\"cpu\"}[$__rate_interval]) != 0\r\n    or\r\n    (\r\n      avg_over_time(kube_pod_init_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", resource=\"cpu\"}[$__interval]) != 0\r\n      and on(location, namespace, pod, uid, container)\r\n      (max_over_time(kube_pod_init_container_status_running{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\"}[$__interval]) == 1)\r\n    )\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cpu throttled (average)",
   "type": "timeseries",
   "description": "empty is containers in pod don't have cpu limit",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_cfs_throttled_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "max(cpu usage / limit) %",
   "type": "timeseries",
   "description": "empty if containers in pod don't have cpu limit",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(pod) (\r\n  sum without(cpu) (rate(container_cpu_usage_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\", cpu=\"total\"}[$__rate_interval]))\r\n  * avg_over_time(container_spec_cpu_period{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\"}[$__rate_interval])\r\n  / avg_over_time(container_spec_cpu_quota{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\"}[$__rate_interval])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "container memory request",
   "type": "timeseries",
   "description": "empty is containers in pod don't have memory request",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (\r\n  # max by(pod, container) eliminates artifacts when pod UID changes\r\n  max by(pod, container) (\r\n    sum_over_time(kube_pod_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", resource=\"memory\"}[$__interval])\r\n    / on(job) group_left()\r\n    sum_over_time(up{job=\"kube-state-metrics\", location=\"$location\"}[$__interval])\r\n    # avg_over_time(kube_pod_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", resource=\"memory\"}[$__interval])\r\n    or\r\n    (\r\n      sum_over_time(kube_pod_init_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", resource=\"memory\"}[$__interval])\r\n      / on(job) group_left()\r\n      sum_over_time(up{job=\"kube-state-metrics\", location=\"$location\"}[$__interval])\r\n      # avg_over_time(kube_pod_init_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", resource=\"memory\"}[$__interval])\r\n      and on(location, namespace, pod, uid, container)\r\n      (max_over_time(kube_pod_init_container_status_running{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\"}[$__interval]) == 1)\r\n    )\r\n  )\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\r\n  # max by(pod, container) eliminates artifacts when pod UID changes\r\n  max by(pod, container) (\r\n    sum_over_time(kube_pod_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", resource=\"memory\", invalid=$total}[$__interval])\r\n    / on(job) group_left()\r\n    sum_over_time(up{job=\"kube-state-metrics\", location=\"$location\", invalid=$total}[$__interval])\r\n    # avg_over_time(kube_pod_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", resource=\"memory\"}[$__interval])\r\n    or\r\n    (\r\n      sum_over_time(kube_pod_init_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", resource=\"memory\", invalid=$total}[$__interval])\r\n      / on(job) group_left()\r\n      sum_over_time(up{job=\"kube-state-metrics\", location=\"$location\", invalid=$total}[$__interval])\r\n      # avg_over_time(kube_pod_init_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", resource=\"memory\"}[$__interval])\r\n      and on(location, namespace, pod, uid, container)\r\n      (max_over_time(kube_pod_init_container_status_running{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\"}[$__interval]) == 1)\r\n    )\r\n  )\r\n)",
     "legendFormat": "Total"
    },
    {
     "expr": "max(kube_resourcequota{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", type=\"hard\", resource=\"requests.memory\"})",
     "legendFormat": "quota"
    }
   ]
  },
  {
   "title": "container memory limit",
   "type": "timeseries",
   "description": "empty is containers in pod don't have memory limit",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (\r\n  # max by(pod, container) eliminates artifacts when pod UID changes\r\n  max by(pod, container) (\r\n    sum_over_time(kube_pod_container_resource_limits{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", resource=\"memory\"}[$__interval])\r\n    / on(job) group_left()\r\n    sum_over_time(up{job=\"kube-state-metrics\", location=\"$location\"}[$__interval])\r\n    # avg_over_time(kube_pod_container_resource_limits{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", resource=\"memory\"}[$__interval])\r\n    or\r\n    (\r\n      sum_over_time(kube_pod_init_container_resource_limits{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", resource=\"memory\"}[$__interval])\r\n      / on(job) group_left()\r\n      sum_over_time(up{job=\"kube-state-metrics\", location=\"$location\"}[$__interval])\r\n      # avg_over_time(kube_pod_init_container_resource_limits{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", resource=\"memory\"}[$__interval])\r\n      and on(location, namespace, pod, uid, container)\r\n      (max_over_time(kube_pod_init_container_status_running{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\"}[$__interval]) == 1)\r\n    )\r\n  )\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\r\n  # max by(pod, container) eliminates artifacts when pod UID changes\r\n  max by(pod, container) (\r\n    sum_over_time(kube_pod_container_resource_limits{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", resource=\"memory\", invalid=$total}[$__interval])\r\n    / on(job) group_left()\r\n    sum_over_time(up{job=\"kube-state-metrics\", location=\"$location\", invalid=$total}[$__interval])\r\n    # avg_over_time(kube_pod_container_resource_limits{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", resource=\"memory\"}[$__interval])\r\n    or\r\n    (\r\n      sum_over_time(kube_pod_init_container_resource_limits{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", resource=\"memory\", invalid=$total}[$__interval])\r\n      / on(job) group_left()\r\n      sum_over_time(up{job=\"kube-state-metrics\", location=\"$location\", invalid=$total}[$__interval])\r\n      # avg_over_time(kube_pod_init_container_resource_limits{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", resource=\"memory\"}[$__interval])\r\n      and on(location, namespace, pod, uid, container)\r\n      (max_over_time(kube_pod_init_container_status_running{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\"}[$__interval]) == 1)\r\n    )\r\n  )\r\n)",
     "legendFormat": "Total"
    },
    {
     "expr": "max(kube_resourcequota{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", type=\"hard\", resource=\"limits.memory\"})",
     "legendFormat": "quota"
    }
   ]
  },
  {
   "title": "rss",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "# max by(pod, container) should fix overlapping data on container restarts\r\nsum by(pod) (\r\n  max by(pod, container) (\r\n    avg_over_time(container_memory_rss{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\"}[$__interval])\r\n  )\r\n  or\r\n  max by(pod, container) (\r\n    avg_over_time(container_memory_rss{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\"}[$__rate_interval])\r\n  )\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(max by(pod, container) (\r\n  sum_over_time(container_memory_rss{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\", invalid=$total}[$__rate_interval])\r\n  / on(job, instance, node) group_left()\r\n  sum_over_time(up{location=\"$location\", node=~\"$pod_nodes\", invalid=$total}[$__rate_interval])\r\n  and on() vector($__interval_ms / 1000) >= 60\r\n  or\r\n  avg_over_time(container_memory_rss{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\", invalid=$total}[$__rate_interval])\r\n))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "total rss + kernel / total request %",
   "type": "timeseries",
   "description": "empty if containers in pod don't have memory request",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "# max by(pod, container) should fix overlapping data on container restarts\r\nsum by(pod) (\r\n  max by(pod, container) (\r\n    + avg_over_time(container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\"}[$__interval])\r\n    - avg_over_time(container_memory_cache{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\"}[$__interval])\r\n  )\r\n  or\r\n  max by(pod, container) (\r\n    + avg_over_time(container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\"}[$__rate_interval])\r\n    - avg_over_time(container_memory_cache{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\"}[$__rate_interval])\r\n  )\r\n)\r\n/\r\nsum by(pod) (\r\n  # max by(pod, container) eliminates artifacts when pod UID changes\r\n  max by(pod, container) (\r\n    avg_over_time(kube_pod_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", resource=\"memory\"}[$__interval])\r\n    or\r\n    (\r\n      avg_over_time(kube_pod_init_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", resource=\"memory\"}[$__interval])\r\n      and on(location, namespace, pod, uid, container)\r\n      (max_over_time(kube_pod_init_container_status_running{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\"}[$__interval]) == 1)\r\n    )\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rss + kernel",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "# max by(pod, container) should fix overlapping data on container restarts\r\nsum by(pod) (\r\n  max by(pod, container) (\r\n    + avg_over_time(container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\"}[$__interval])\r\n    - avg_over_time(container_memory_cache{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\"}[$__interval])\r\n  )\r\n  or\r\n  max by(pod, container) (\r\n    + avg_over_time(container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\"}[$__rate_interval])\r\n    - avg_over_time(container_memory_cache{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\"}[$__rate_interval])\r\n  )\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(max by(pod, container) (\r\n  (\r\n    + sum_over_time(container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\", invalid=$total}[$__rate_interval])\r\n    - sum_over_time(container_memory_cache{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\", invalid=$total}[$__rate_interval])\r\n  )\r\n  / on(job, instance, node) group_left()\r\n  sum_over_time(up{location=\"$location\", node=~\"$pod_nodes\", invalid=$total}[$__rate_interval])\r\n  and on() vector($__interval_ms / 1000) >= 60\r\n  or\r\n  + avg_over_time(container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\", invalid=$total}[$__rate_interval])\r\n  - avg_over_time(container_memory_cache{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\", invalid=$total}[$__rate_interval])\r\n))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "max(rss + kernel / limit %)",
   "type": "timeseries",
   "description": "empty if containers in pod don't have memory limit",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "# max by(pod, container) should fix overlapping data on container restarts\r\nmax by(pod) (\r\n  max by(pod, container) (\r\n    (\r\n    + avg_over_time(container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\"}[$__interval])\r\n    - avg_over_time(container_memory_cache{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\"}[$__interval])\r\n    )\r\n    / (max_over_time(container_spec_memory_limit_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\"}[$__interval]) != 0)\r\n  )\r\n  or\r\n  max by(pod, container) (\r\n    (\r\n    + avg_over_time(container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\"}[$__rate_interval])\r\n    - avg_over_time(container_memory_cache{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\"}[$__rate_interval])\r\n    )\r\n    / (max_over_time(container_spec_memory_limit_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\"}[$__rate_interval]) != 0)\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "wss",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "# max by(pod, container) should fix overlapping data on container restarts\r\nsum by(pod) (\r\n  max by(pod, container) (\r\n    avg_over_time(container_memory_working_set_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\"}[$__interval])\r\n  )\r\n  or\r\n  max by(pod, container) (\r\n    avg_over_time(container_memory_working_set_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\"}[$__rate_interval])\r\n  )\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(max by(pod, container) (\r\n  sum_over_time(container_memory_working_set_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\", invalid=$total}[$__rate_interval])\r\n  / on(job, instance, node) group_left()\r\n  sum_over_time(up{location=\"$location\", node=~\"$pod_nodes\", invalid=$total}[$__rate_interval])\r\n  and on() vector($__interval_ms / 1000) >= 60\r\n  or\r\n  avg_over_time(container_memory_working_set_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\", invalid=$total}[$__rate_interval])\r\n))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "total wss / total request",
   "type": "timeseries",
   "description": "empty if containers in pod don't have memory limit",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "# max by(pod, container) should fix overlapping data on container restarts\r\nsum by(pod) (\r\n  max by(pod, container) (\r\n    avg_over_time(container_memory_working_set_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\"}[$__interval])\r\n  )\r\n  or\r\n  max by(pod, container) (\r\n    avg_over_time(container_memory_working_set_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\"}[$__rate_interval])\r\n  )\r\n)\r\n/\r\nsum by(pod) (\r\n  # max by(pod, container) eliminates artifacts when pod UID changes\r\n  max by(pod, container) (\r\n    avg_over_time(kube_pod_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", resource=\"memory\"}[$__interval])\r\n    or\r\n    (\r\n      avg_over_time(kube_pod_init_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", resource=\"memory\"}[$__interval])\r\n      and on(location, namespace, pod, uid, container)\r\n      (max_over_time(kube_pod_init_container_status_running{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\"}[$__interval]) == 1)\r\n    )\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "raw",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "# max by(pod, container) should fix overlapping data on container restarts\r\nsum by(pod) (\r\n  max by(pod, container) (\r\n    avg_over_time(container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\"}[$__interval])\r\n  )\r\n  or\r\n  max by(pod, container) (\r\n    avg_over_time(container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\"}[$__rate_interval])\r\n  )\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(max by(pod, container) (\r\n  sum_over_time(container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\", invalid=$total}[$__rate_interval])\r\n  / on(job, instance, node) group_left()\r\n  sum_over_time(up{location=\"$location\", node=~\"$pod_nodes\", invalid=$total}[$__rate_interval])\r\n  and on() vector($__interval_ms / 1000) >= 60\r\n  or\r\n  avg_over_time(container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\", invalid=$total}[$__rate_interval])\r\n))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "max(wss / limit %)",
   "type": "timeseries",
   "description": "empty if containers in pod don't have memory limit",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "# max by(pod, container) should fix overlapping data on container restarts\r\nmax by(pod) (\r\n  max by(pod, container) (\r\n    + avg_over_time(container_memory_working_set_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\"}[$__interval])\r\n    / (max_over_time(container_spec_memory_limit_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\"}[$__interval]) != 0)\r\n  )\r\n  or\r\n  max by(pod, container) (\r\n    + avg_over_time(container_memory_working_set_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\"}[$__rate_interval])\r\n    / (max_over_time(container_spec_memory_limit_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\"}[$__rate_interval]) != 0)\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 } },
  {
   "title": "receive rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "# if we try to use container ID, like with other graphs, query will fail because network statistics have pod sandbox ID\r\n# we can't correlate sandbox ID with pod UID, so there is nothing we can do here\r\nsum by(pod) (rate(container_network_receive_bytes_total{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", invalid=$total}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "receive total",
   "type": "timeseries",
   "description": "Absolute values will change based on time scale, because it's showing total increase over an interval.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "# if we try to use container ID, like with other graphs, query will fail because network statistics have pod sandbox ID\r\n# we can't correlate sandbox ID with pod UID, so there is nothing we can do here\r\nsum by(pod) (rate(container_network_receive_bytes_total{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", invalid=$total}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "transmit rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_network_transmit_bytes_total{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", invalid=$total}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "transmit total",
   "type": "timeseries",
   "description": "Absolute values will change based on time scale, because it's showing total increase over an interval.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "# if we try to use container ID, like with other graphs, query will fail because network statistics have pod sandbox ID\r\n# we can't correlate sandbox ID with pod UID, so there is nothing we can do here\r\nsum by(pod) (rate(container_network_transmit_bytes_total{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", invalid=$total}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 } },
  {
   "title": "Storage notes",
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 133 },
   "options": {
    "content": "\nRead/write from NFS and SMB shares\nwill not be shown in the storage throughput.\n\nCadvisor exports data from cgroup io.stats,\nwhich are only calculated for block devices.\n"
   }
  },
  {
   "title": "disk read rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{container!=\"\", location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "disk read total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{container!=\"\", location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "disk write rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_fs_writes_bytes_total{container!=\"\", location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "disk written total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_fs_writes_bytes_total{container!=\"\", location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$container_name\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ephemeral storage total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (\r\n  sum_over_time(kube_summary_pod_ephemeral_storage_used_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\"}[$__interval])\r\n  / on(job) group_left()\r\n  sum by(job) (count_over_time(up{location=\"$location\", job=\"kube-summary-exporter\", invalid=$total}[$__interval]))\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(max by(pod) (\r\n  sum_over_time(kube_summary_pod_ephemeral_storage_used_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\"}[$__interval])\r\n  / on(job) group_left()\r\n  sum by(job) (count_over_time(up{location=\"$location\", job=\"kube-summary-exporter\", invalid=$total}[$__interval]))\r\n))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "ephemeral storage (without logs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (\r\n  sum_over_time(kube_summary_pod_ephemeral_storage_used_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\"}[$__interval])\r\n  / on(job) group_left()\r\n  sum by(job) (count_over_time(up{location=\"$location\", job=\"kube-summary-exporter\"}[$__interval]))\r\n)\r\n-\r\nmax by(pod) (\r\n  sum_over_time(kube_summary_container_logs_used_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", container!=\"\"}[$__interval])\r\n  / on(job) group_left()\r\n  sum by(job) (count_over_time(up{location=\"$location\", job=\"kube-summary-exporter\"}[$__interval]))\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\r\n+ max by(pod) (\r\n  sum_over_time(kube_summary_pod_ephemeral_storage_used_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", invalid=$total}[$__interval])\r\n  / on(job) group_left()\r\n  sum by(job) (count_over_time(up{location=\"$location\", job=\"kube-summary-exporter\", invalid=$total}[$__interval]))\r\n)\r\n- max by(pod) (\r\n  sum_over_time(kube_summary_container_logs_used_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", container!=\"\", invalid=$total}[$__interval])\r\n  / on(job) group_left()\r\n  sum by(job) (count_over_time(up{location=\"$location\", job=\"kube-summary-exporter\", invalid=$total}[$__interval]))\r\n))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "logs used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (\r\n  sum_over_time(kube_summary_container_logs_used_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\"}[$__interval])\r\n  / on(job) group_left()\r\n  sum by(job) (count_over_time(up{location=\"$location\", job=\"kube-summary-exporter\"}[$__interval]))\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(max by(pod) (\r\n  sum_over_time(kube_summary_container_logs_used_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", invalid=$total}[$__interval])\r\n  / on(job) group_left()\r\n  sum by(job) (count_over_time(up{location=\"$location\", job=\"kube-summary-exporter\", invalid=$total}[$__interval]))\r\n))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "rootfs used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (\r\n  sum_over_time(kube_summary_container_rootfs_used_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", container!=\"\"}[$__interval])\r\n  / on(job) group_left()\r\n  sum by(job) (count_over_time(up{location=\"$location\", job=\"kube-summary-exporter\"}[$__interval]))\r\n)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(max by(pod) (\r\n  sum_over_time(kube_summary_container_rootfs_used_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", container!=\"\", invalid=$total}[$__interval])\r\n  / on(job) group_left()\r\n  sum by(job) (count_over_time(up{location=\"$location\", job=\"kube-summary-exporter\", invalid=$total}[$__interval]))\r\n))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "logs written",
   "type": "timeseries",
   "description": "Absolute values will change based on time scale, because it's showing total increase over an interval.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (\r\n+ sum by(pod, uid, container) (rate(kube_summary_container_logs_used_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\"}[$__rate_interval])) * $__interval_ms / 1000\r\n# when logs are rotated, last 10MiB seems to be kept, so we need to account for this\r\n# this is best-effort approximation, it's brittle\r\n- (\r\n  0 * (sum by(pod, uid, container) (\r\n    rate(kube_pod_container_status_restarts_total{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\"}[$__rate_interval])\r\n    or\r\n    rate(kube_pod_init_container_status_restarts_total{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\"}[$__rate_interval])\r\n    * on(pod, uid, container) group_left()\r\n    rate(kube_pod_init_container_info{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", restart_policy=\"Always\"}[$__rate_interval])\r\n  ) != 0)\r\n  or\r\n  sum by(pod, uid, container) (resets(kube_summary_container_logs_used_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\"}[$__rate_interval]))\r\n  / on() group_left()\r\n  round(clamp_max(vector($__rate_interval_ms / $__interval_ms), 3))\r\n)\r\n* 1024 * 1024 * 10\r\n)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(\r\n+ sum by(pod, uid, container) (rate(kube_summary_container_logs_used_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", invalid=$total}[$__rate_interval])) * $__interval_ms / 1000\r\n# when logs are rotated, last 10MiB seems to be kept, so we need to account for this\r\n# this is best-effort approximation, it's brittle\r\n- (\r\n  0 * (sum by(pod, uid, container) (\r\n    rate(kube_pod_container_status_restarts_total{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", invalid=$total}[$__rate_interval])\r\n    or\r\n    rate(kube_pod_init_container_status_restarts_total{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", invalid=$total}[$__rate_interval])\r\n    * on(pod, uid, container) group_left()\r\n    rate(kube_pod_init_container_info{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", restart_policy=\"Always\", invalid=$total}[$__rate_interval])\r\n  ) != 0)\r\n  or\r\n  sum by(pod, uid, container) (resets(kube_summary_container_logs_used_bytes{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", invalid=$total}[$__rate_interval]))\r\n  / on() group_left()\r\n  round(clamp_max(vector($__rate_interval_ms / $__interval_ms), 3))\r\n)\r\n* 1024 * 1024 * 10\r\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "volume usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "# max by(pod) (avg_over_time(ephemeral_storage_container_volume_usage{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\"}[$__interval]))\r\nsum by(pod) (max by(pod, volume_name) (\r\n  sum_over_time(ephemeral_storage_container_volume_usage{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\"}[$__interval])\r\n  / on(job) group_left()\r\n  sum by(job) (count_over_time(up{location=\"$location\", job=\"kube-ephemeral-storage\"}[$__interval]))\r\n))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(sum by(pod) (max by(pod, volume_name) (\r\n  sum_over_time(ephemeral_storage_container_volume_usage{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\"}[$__interval])\r\n  / on(job) group_left()\r\n  sum by(job) (count_over_time(up{location=\"$location\", job=\"kube-ephemeral-storage\", invalid=$total}[$__interval]))\r\n)))",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}