{
 "title": "Cluster / Nodes",
 "tags": [
  "maintainer:danil",
  "k8s-cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(up{job=\"kube-state-metrics\", endpoint=\"\"}[$__range])))"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_info{location=\"$location\"},node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "info",
   "type": "table",
   "gridPos": { "h": 11, "w": 22, "x": 1, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(instance, node, internal_ip, pod_cidr, system_uuid) (last_over_time(kube_node_info{location=\"$location\", node=~\"$node\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(instance, node) (avg_over_time(node_namespace:container_cpu_usage_seconds:irate{location=\"$location\", node=~\"$node\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(instance,node) (avg_over_time(node_namespace:kube_pod_container_resource_requests{location=\"$location\", node=~\"$node\", resource=\"cpu\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, node) (last_over_time(kube_node_status_allocatable{location=\"$location\", node=~\"$node\", resource=\"cpu\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(instance, node) (avg_over_time(node_namespace:container_memory_rss{location=\"$location\", node=~\"$node\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(instance, node) (avg_over_time(node_namespace:kube_pod_container_resource_requests{location=\"$location\", node=~\"$node\", resource=\"memory\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, node) (last_over_time(kube_node_status_allocatable{location=\"$location\", node=~\"$node\", resource=\"memory\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, node) (last_over_time(node_memory_MemTotal_bytes{location=\"$location\", node=~\"$node\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, node) (max_over_time(kube_node_created{location=\"$location\", node=~\"$node\"}[$__range])) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "(max by(instance, node) (\r\n  timestamp(kube_node_created:last_seen{location=\"$location\", node=~\"$node\"}) - kube_node_created:last_seen{location=\"$location\", node=~\"$node\"}\r\n  or\r\n  time() - max_over_time(kube_node_created:last_seen{location=\"$location\", node=~\"$node\"}[$__range])\r\n))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(instance, node) (kube_pod_info{location=\"$location\", node=~\"$node\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, node) (last_over_time(kube_node_status_allocatable{location=\"$location\", node=~\"$node\", resource=\"pods\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\r\n    max by(node) (\r\n        timestamp(kube_node_created{location=\"$location\", node=~\"$node\"})\r\n    )\r\n    -\r\n    max by(node) (\r\n        node_boot_time_seconds{location=\"$location\", node=~\"$node\"}\r\n    )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ready status",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "min by(node) (min_over_time(kube_node_status_condition{location=\"$location\", node=~\"$node\", condition=\"Ready\", status=\"true\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "os image history",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "max by(node, os_image) (last_over_time(kube_node_info{location=\"$location\", node=~\"$node\"}[$__interval]))\r\nor on()\r\n(\r\n  vector(0) unless on() last_over_time(kube_node_info{location=\"$location\", node=~\"$node\"}[$__interval])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kubelet version history",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "max by(node, kubelet_version) (last_over_time(kube_node_info{location=\"$location\", node=~\"$node\"}[$__interval]))\r\nor on()\r\n(\r\n  vector(0) unless on() last_over_time(kube_node_info{location=\"$location\", node=~\"$node\"}[$__interval])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "internal IP history",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "max by(node, internal_ip) (last_over_time(kube_node_info{location=\"$location\", node=~\"$node\"}[$__interval]))\r\nor on()\r\n(\r\n  vector(0) unless on() last_over_time(kube_node_info{location=\"$location\", node=~\"$node\"}[$__interval])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kernel version history",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "max by(node, kernel_version) (last_over_time(kube_node_info{location=\"$location\", node=~\"$node\"}[$__interval]))\r\nor on()\r\n(\r\n  vector(0) unless on() last_over_time(kube_node_info{location=\"$location\", node=~\"$node\"}[$__interval])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pods",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum by(node) (max_over_time(kube_pod_info{location=\"$location\", node=~\"$node\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ephemeral storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (node) (max_over_time(ephemeral_storage_pod_usage{location=\"$location\", node=~\"$node\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "compute", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(node) (avg_over_time(node_namespace:container_cpu_usage_seconds:irate{location=\"$location\", node=~\"$node\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cpu usage %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(node) (max_over_time(node_namespace:container_cpu_usage_seconds:irate{location=\"$location\", node=~\"$node\"}[$__interval]))\r\n/\r\nmax by(node) (max_over_time(kube_node_status_allocatable{location=\"$location\", node=~\"$node\", resource=\"cpu\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "memory: raw",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (node) (max_over_time(node_namespace:container_memory_usage_bytes{location=\"$location\", node=~\"$node\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "memory: rss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (node) (max_over_time(node_namespace:container_memory_rss{location=\"$location\", node=~\"$node\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "memory: rss / capacity %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (node) (max_over_time(node_namespace:container_memory_rss{location=\"$location\", node=~\"$node\"}[$__interval]))\r\n/\r\nmax by(node) (max_over_time(kube_node_status_allocatable{location=\"$location\", node=~\"$node\", resource=\"memory\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "receive rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (node) (avg_over_time(node_namespace:container_network_receive_bytes:irate{location=\"$location\", node=~\"$node\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "transmit rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (node) (avg_over_time(node_namespace:container_network_transmit_bytes:irate{location=\"$location\", node=~\"$node\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}