{
 "title": "Namespace / PVC",
 "tags": [
  "maintainer:danil",
  "k8s-cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(up{job=\"kube-state-metrics\", endpoint=\"\"}[$__range])))"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "query_result(group by(namespace) (last_over_time(kube_namespace_status_phase{location=\"$location\"}[$__range])))"
    }
   },
   { "name": "pvc_filter", "label": "PVC filter" },
   {
    "name": "volume",
    "label": "PersistentVolumeClaim",
    "query": {
     "query": "query_result(last_over_time(kubelet_volume_stats_capacity_bytes{location=\"$location\", namespace=\"$namespace\", persistentvolumeclaim=~\".*($pvc_filter).*\"}[$__range]))"
    }
   },
   {
    "name": "pv_name",
    "query": {
     "query": "query_result(last_over_time(kube_persistentvolume_claim_ref{location=\"$location\", claim_namespace=\"$namespace\", name=~\"$volume\"}[$__range]))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "PVC list",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 1, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(namesapce, persistentvolumeclaim) (last_over_time(kubelet_volume_stats_capacity_bytes{location=\"$location\", namespace=\"$namespace\", persistentvolumeclaim=~\"$volume\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(namesapce, persistentvolumeclaim) (\r\n  last_over_time(kube_persistentvolumeclaim_resource_requests_storage_bytes{location=\"$location\", namespace=\"$namespace\", persistentvolumeclaim=~\"$volume\"}[$__range])\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(namesapce, persistentvolumeclaim) (last_over_time(kubelet_volume_stats_available_bytes{location=\"$location\", namespace=\"$namespace\", persistentvolumeclaim=~\"$volume\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(namesapce, persistentvolumeclaim) (last_over_time(kubelet_volume_stats_used_bytes{location=\"$location\", namespace=\"$namespace\", persistentvolumeclaim=~\"$volume\", persistentvolumeclaim=~\"$volume\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(namesapce, persistentvolumeclaim) (last_over_time(kubelet_volume_stats_inodes{location=\"$location\", namespace=\"$namespace\", persistentvolumeclaim=~\"$volume\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PVC to Volume mapping",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(persistentvolumeclaim, namespace, persistentvolume) (\r\nlabel_replace(\r\nlabel_replace(\r\nlast_over_time(kube_persistentvolume_claim_ref{location=\"$location\", claim_namespace=\"$namespace\", name=~\"$volume\"}[$__range]),\r\n\"persistentvolumeclaim\", \"$1\", \"name\", \"(.*)\"\r\n),\r\n\"namespace\", \"$1\", \"claim_namespace\", \"(.*)\"\r\n)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mounts",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 18, "x": 1, "y": 8 },
   "targets": [
    {
     "expr": "count by(namespace, persistentvolumeclaim, instance) (last_over_time(kubelet_volume_stats_capacity_bytes{location=\"$location\", namespace=\"$namespace\", persistentvolumeclaim=~\"$volume\"}[$__interval]))",
     "legendFormat": "{{persistentvolumeclaim}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Pod PVC usage",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 18, "x": 1, "y": 16 },
   "targets": [
    {
     "expr": "count by(persistentvolumeclaim, pod) (last_over_time(kube_pod_spec_volumes_persistentvolumeclaims_info{location=\"$location\", namespace=\"$namespace\", persistentvolumeclaim=~\"$volume\"}[$__interval]))",
     "legendFormat": "{{persistentvolumeclaim}} @ {{pod}}"
    }
   ]
  },
  {
   "title": "Volume Size (spec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 1, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(name) (\r\n  max_over_time(kube_persistentvolume_capacity_bytes{location=\"$location\", persistentvolume=~\"$pv_name\"}[$__interval])\r\n  * on(persistentvolume) group_left(name)\r\n  last_over_time(kube_persistentvolume_claim_ref{location=\"$location\", claim_namespace=\"$namespace\", name=~\"$volume\"}[$__interval])\r\n)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Volume Size (mounted)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 1, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(persistentvolumeclaim) (max_over_time(kubelet_volume_stats_capacity_bytes{location=\"$location\", namespace=\"$namespace\", persistentvolumeclaim=~\"$volume\"}[$__interval]))",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Volume Space Usage Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 1, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(persistentvolumeclaim) (max_over_time(kubelet_volume_stats_used_bytes{location=\"$location\", namespace=\"$namespace\", persistentvolumeclaim=~\"$volume\"}[$__interval]))",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Volume Space Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 1, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(persistentvolumeclaim) (\r\n  max_over_time(kubelet_volume_stats_used_bytes{location=\"$location\", namespace=\"$namespace\", persistentvolumeclaim=~\"$volume\"}[$__interval])\r\n  /\r\n  max_over_time(kubelet_volume_stats_capacity_bytes{location=\"$location\", namespace=\"$namespace\", persistentvolumeclaim=~\"$volume\"}[$__interval])\r\n)",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Volume inodes Usage %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 1, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(persistentvolumeclaim) (\r\n  max_over_time(kubelet_volume_stats_inodes_used{location=\"$location\", namespace=\"$namespace\", persistentvolumeclaim=~\"$volume\"}[$__interval])\r\n  /\r\n  max_over_time(kubelet_volume_stats_inodes{location=\"$location\", namespace=\"$namespace\", persistentvolumeclaim=~\"$volume\"}[$__interval])\r\n)",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}