{
 "title": "Cluster Overview",
 "tags": [
  "maintainer:danil",
  "k8s-cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(up{job=\"kube-state-metrics\", endpoint=\"\"}[$__range])))"
    }
   }
  ]
 },
 "panels": [
  { "title": "overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "namespaces",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_namespace_status_phase{location=\"$location\", phase=\"Active\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pods",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(location) (kube_pod_info{location=\"$location\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "containers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(location) (kube_pod_container_info{location=\"$location\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cpu usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(location) (node_namespace:container_cpu_usage_seconds:irate{location=\"$location\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(location) (node_namespace:container_memory_rss{location=\"$location\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kubelet versions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(kubelet_version) (kube_node_info{location=\"$location\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Images (used now) by registry",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "expr": "count by(image_registry) (\r\n  label_replace(\r\n    label_replace(kube_pod_container_info{location=\"$location\"}, \"image_registry\", \"$1\", \"image\", \"([^/]*)/.*\")\r\n    , \"image_registry\", \"$1\", \"image_id\", \"([^/]*)/.*\")\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ephemeral storage usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(location) (ephemeral_storage_pod_usage{location=\"$location\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "control plane versions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(git_version) (kubernetes_build_info{location=\"$location\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "control  plane version history",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max by(instance, git_version) (\r\n  label_join(\r\n    last_over_time(kubernetes_build_info{location=\"$location\"}[$__interval])\r\n    , \"instance\", \": \", \"job\", \"instance\"\r\n  )\r\n)\r\nor on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Images (used now)",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "count by(image_registry, image) (\r\n  label_replace(\r\n    label_replace(kube_pod_container_info{location=\"$location\"}, \"image_registry\", \"$1\", \"image\", \"([^/]*)/.*\")\r\n    , \"image_registry\", \"$1\", \"image_id\", \"([^/]*)/.*\")\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pods",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by(location) (max_over_time(kube_pod_info{location=\"$location\"}[$__interval]))",
     "legendFormat": "pods"
    },
    {
     "expr": "sum by(location) (max_over_time(kube_pod_container_info{location=\"$location\"}[$__interval]))",
     "legendFormat": "containers"
    }
   ]
  },
  {
   "title": "ephemeral Storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(max_over_time(ephemeral_storage_pod_usage{location=\"$location\"}[$__interval]))",
     "legendFormat": "pod usage"
    },
    {
     "expr": "sum(ephemeral_storage_node_capacity{location=\"$location\"})",
     "legendFormat": "node capacity"
    },
    {
     "expr": "sum(ephemeral_storage_node_capacity{location=\"$location\"} - ephemeral_storage_node_available{location=\"$location\"})",
     "legendFormat": "node used"
    }
   ]
  },
  {
   "title": "image registries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "count by(image_registry) (\r\n  label_replace(last_over_time(kube_pod_container_info{location=\"$location\", image_id!=\"\"}[$__interval]), \"image_registry\", \"$1\", \"image_id\", \"([^/]*)/.*\")\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "compute", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum(max_over_time(node_namespace:container_cpu_usage_seconds:irate{location=\"$location\"}[$__interval]))",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(kube_node_status_capacity{location=\"$location\", resource=\"cpu\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(last_over_time(node_namespace:kube_pod_container_resource_requests{location=\"$location\", resource=\"cpu\"}[$__rate_interval]))",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{location=\"$location\", resource=\"memory\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(max_over_time(node_namespace:container_memory_rss{location=\"$location\"}[$__interval]))",
     "legendFormat": "rss"
    },
    {
     "expr": "sum(max_over_time(node_namespace:container_memory_usage_bytes{location=\"$location\"}[$__interval]))",
     "legendFormat": "raw"
    },
    {
     "expr": "sum(node_namespace:kube_pod_container_resource_requests{location=\"$location\", resource=\"memory\"})",
     "legendFormat": "request"
    }
   ]
  },
  { "title": "network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "receive rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(max_over_time(node_namespace:container_network_receive_bytes:irate{location=\"$location\"}[$__interval]))",
     "legendFormat": "receive"
    }
   ]
  },
  {
   "title": "transmit rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(max_over_time(node_namespace:container_network_transmit_bytes:irate{location=\"$location\"}[$__interval]))",
     "legendFormat": "transmit"
    }
   ]
  }
 ]
}