{
 "title": "Pod / Containers",
 "tags": [
  "maintainer:danil",
  "k8s-cluster"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(up{job=\"kube-state-metrics\", endpoint=\"\"}[$__range])))"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_namespace_status_phase{location=\"$location\"}, namespace)"
   },
   {
    "name": "workload",
    "query": {
     "query": "query_result(label_join(last_over_time(namespace_workload_pod:kube_pod_owner:relabel{location=\"$location\", namespace=\"$namespace\"}[$__range]), \"human_name\", \"/\", \"workload_type\", \"workload\"))"
    }
   },
   {
    "name": "node_selector",
    "label": "Node",
    "query": {
     "query": "query_result(last_over_time(kube_pod_info{location=\"$location\", namespace=\"$namespace\"}[$__range]))"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "query_result(label_replace(label_join(      last_over_time(        namespace_workload_pod:kube_pod_owner:relabel{location=\"$location\",namespace=\"$namespace\",workload=~\"$workload\"}[$__range]      )    * on (namespace, pod, uid) group_left ()      max by (namespace, pod, uid) (        last_over_time(kube_pod_container_status_ready{location=\"$location\",namespace=\"$namespace\"}[$__range])      )  * on (namespace, pod, uid) group_left (node)    max by (namespace, pod, uid, node) (      last_over_time(kube_pod_info{location=\"$location\",namespace=\"$namespace\",node!=\"\"}[$__range])    ),  \"human_name\",  \"/\",  \"node\",  \"pod\"),  \"human_name\",  \"$2 ($1)\",  \"human_name\",  \"(.*)/(.*)\"))"
    }
   },
   {
    "name": "pod_uid",
    "label": "UID",
    "query": {
     "query": "query_result(last_over_time(kube_pod_info{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\"}[$__range]))"
    }
   },
   {
    "name": "container",
    "label": "container",
    "query": {
     "query": "query_result(label_replace(last_over_time(kube_pod_container_info{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\"}[$__range]), \"human_name\", \"main/$1\", \"container\", \"(.*)\")or (  (max_over_time(kube_pod_status_phase{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", phase=\"Pending\"}[$__range]) == 1) * 0  + on(uid) group_right label_replace(last_over_time(kube_pod_init_container_info{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\"}[$__range]), \"human_name\", \"init/$1\", \"container\", \"(.*)\")))"
    }
   },
   {
    "name": "container_name",
    "query": {
     "query": "query_result(label_replace((last_over_time(kube_pod_container_info{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"}[$__range])or last_over_time(kube_pod_init_container_info{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"}[$__range])), \"name\", \"$1\", \"container_id\", \"containerd://(.*)\"))"
    }
   },
   {
    "name": "id",
    "query": {
     "query": "query_result(label_replace(last_over_time(container_cpu_usage_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$container_name\"}[$__range]),\"human_name\", \"$1\",\"name\", \"(.*)\"))"
    }
   },
   {
    "name": "enableLimits",
    "label": "Show limits",
    "query": "Show : \"\", Hide : \"invalid123\""
   },
   {
    "name": "split_ids",
    "label": "Split IDs",
    "query": "Unite : \"\", Split : \"invalid123\""
   }
  ]
 },
 "panels": [
  { "title": "info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "container info",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max by(pod, uid, node, container, name, image) (\r\n  # kube-state-metrics sometimes prints different image_spec for the same container ID,\r\n  # which causes errors with duplicate entries.\r\n  # This is probably related to using AdvancedDaemonSet from OpenKruise\r\n  max by(namespace, pod, uid, node, container, name, image) (label_replace((\r\n    # when pod name is the same (for example, for static pods, like kube-apiserver)\r\n    # sometimes kube-state-metrics updates only UID, while still keeping old container_id\r\n    # which leads to many-to-one matching in join queries like this one\r\n    # topk(count_over_time) ensures that we pick metrics that were present for the longest interval\r\n    # container_id!=\"\" is required to skip containers that never started because of failed dependency, like image pull failed or mounted configmap/secret missing\r\n    topk by(namespace, pod, uid, node, container, container_id, image) (1, count_over_time(kube_pod_container_info{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", container_id!=\"\"}[$__range]))\r\n    or\r\n    topk by(namespace, pod, uid, node, container, container_id, image) (1, count_over_time(kube_pod_init_container_info{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", container_id!=\"\"}[$__range]))\r\n  ), \"name\", \"$1\", \"container_id\", \"containerd://(.*)\")) * 0\r\n  + on(namespace, pod, container, name) group_right(uid)\r\n  max without(uid) (max_over_time(container_start_time_seconds{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", name=~\"$id\"}[$__range]))\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(pod, container, name) (\r\n  max without(uid) (max_over_time(container_last_seen{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", name=~\"$id\"}[$__range]))\r\n) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(pod, container, name) (\r\n  max_over_time(container_start_time_seconds{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", name=~\"$id\"}[$__range])\r\n) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "(min by(pod, container, name) (\r\n  timestamp(container_last_seen{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", name=~\"$id\"})\r\n  -\r\n  container_last_seen{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", name=~\"$id\"}\r\n  or\r\n  time() - max_over_time(container_last_seen{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", name=~\"$id\"}[$__range])\r\n))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last exit status",
   "type": "table",
   "description": "empty if containers never restarted",
   "gridPos": { "h": 9, "w": 14, "x": 1, "y": 11 },
   "targets": [
    {
     "expr": "max by(uid, container, exit_code) (last_over_time(reason:kube_pod_container_status_last_terminated_timestamp{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\"}[$__range]))\r\n* 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "notes",
   "type": "text",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 11 },
   "options": {
    "content": "This dashboard is intended to debug issues with a particular container.\n\nWhen pod has many containers, and all are shown, most graphs will be hard to read.\n\nTo make it more readble you can:\n- Select a single container\n- Disable \"Show limits\"\n- DIsable \"Split IDs\"\n\nIf you want a summary about the pod, go to `Namespace / Pods` dashboard and select a single pod.\nThere is a `Namespace` link in the upper right to do this quickly."
   }
  },
  {
   "title": "status",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "min by(pod) (\r\n    (kube_pod_status_phase{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", phase=\"Failed\"} == 1) * 2\r\n    or\r\n    (kube_pod_status_phase{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", phase=\"Pending\"} == 1) * 3\r\n    or\r\n    (\r\n        kube_pod_status_phase{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", phase=\"Running\"} == 1\r\n        and on(namespace, pod)\r\n        min_over_time(kube_pod_status_ready{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", condition=\"true\"}[$__interval]) == 1\r\n    ) * 4\r\n    or\r\n    (\r\n        kube_pod_status_phase{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", phase=\"Running\"} == 1\r\n        and on(namespace, pod)\r\n        min_over_time(kube_pod_status_ready{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", condition=\"true\"}[$__interval]) == 0\r\n    ) * 5\r\n    or\r\n    (kube_pod_status_phase{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", phase=\"Succeeded\"} == 1) * 6\r\n    or\r\n    (kube_pod_status_phase{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", phase=\"Unknown\"} == 1) * 7\r\n)",
     "legendFormat": "Pod"
    },
    {
     "expr": "min by(container) (\r\n    (\r\n        kube_pod_container_status_waiting{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"} == 1\r\n    ) * 3\r\n    or\r\n    (\r\n        min_over_time(kube_pod_container_status_ready{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"}[$__interval]) == 1\r\n        and\r\n        kube_pod_container_status_running{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"} == 1\r\n    ) * 4\r\n    or\r\n    (\r\n        min_over_time(kube_pod_container_status_ready{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"}[$__interval]) == bool 0\r\n        and\r\n        kube_pod_container_status_running{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"} == 1\r\n    ) * 5\r\n    or\r\n    (\r\n        (kube_pod_container_status_terminated{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"} == 1)\r\n        and\r\n        kube_pod_container_status_last_terminated_exitcode{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"} == 0\r\n    ) * 6\r\n    or\r\n    (\r\n        (kube_pod_container_status_terminated{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"} == 1)\r\n        and\r\n        kube_pod_container_status_last_terminated_exitcode{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"} != 0\r\n    ) * 2\r\n    or\r\n    # for some reason I don't see kube_pod_container_status_last_terminated_exitcode on some job containers\r\n    (\r\n        (kube_pod_container_status_terminated{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"} == 1)\r\n    ) * 8\r\n)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "(kube_pod_status_phase{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", uid=~\"$pod_uid\", phase=\"Pending\"} == 1) * 0\r\n+ on() group_right\r\nmin by(container) (\r\n    (\r\n        kube_pod_init_container_status_waiting{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"} == 1\r\n        and on(namespace, pod, container)\r\n        kube_pod_init_container_status_waiting_reason{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"}\r\n    ) * 3\r\n    or\r\n    (\r\n        kube_pod_init_container_status_waiting{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"} == 1\r\n    ) * 3\r\n    or\r\n    (\r\n        kube_pod_init_container_status_ready{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"} == 1\r\n        and\r\n        kube_pod_init_container_status_running{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"} == 1\r\n    ) * 4\r\n    or\r\n    (\r\n        kube_pod_init_container_status_ready{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"} != 1\r\n        and\r\n        kube_pod_init_container_status_running{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"} == 1\r\n    ) * 5\r\n    or\r\n    (\r\n        (kube_pod_init_container_status_terminated{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"} == 1)\r\n        and on(namespace, pod, container)\r\n        kube_pod_init_container_status_terminated_reason{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\", reason=\"Completed\"} == 1\r\n    ) * 6\r\n    or\r\n    (\r\n        (kube_pod_init_container_status_terminated{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\"} == 1)\r\n        and on(namespace, pod, container)\r\n        count by(namespace, pod, container) (\r\n            kube_pod_init_container_status_terminated_reason{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\", reason!=\"Completed\"} == 1\r\n        ) > 0\r\n    ) * 2\r\n    or\r\n    (\r\n        (kube_pod_init_container_status_terminated{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"} == 1)\r\n    ) * 8\r\n)",
     "legendFormat": "init/{{container}}"
    }
   ]
  },
  {
   "title": "start time (ago)",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "$__to / 1000 - max by(container) (max_over_time(container_start_time_seconds{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__interval]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Container restarts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "max by (pod, container) (max_over_time(kube_pod_container_status_restarts_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", uid=~\"$pod_uid\", container=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "uptime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - max by(container, name) (last_over_time(container_start_time_seconds{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__interval]))\r\nor\r\ntime() - max by(container) (last_over_time(container_start_time_seconds{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__interval]))",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(container, name) (rate(container_cpu_usage_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", cpu=\"total\", invalid!=$split_ids}[$__rate_interval]))\r\nor\r\nsum by(container) (rate(container_cpu_usage_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", cpu=\"total\", invalid=$split_ids}[$__rate_interval]))",
     "legendFormat": "{{container}}, name={{name}}"
    },
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "CPU throttled (average)",
   "type": "timeseries",
   "description": "Empty is container doesn't have cpu limit.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "max by (container, name) (\r\n  (rate(container_cpu_cfs_throttled_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__rate_interval]) )\r\n)\r\nor\r\nmax by (container) (\r\n  (rate(container_cpu_cfs_throttled_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__rate_interval]) )\r\n)",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  {
   "title": "cpu kernel mode %",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (container, name) (\r\n  (rate(container_cpu_system_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__rate_interval]))\r\n  /\r\n  sum without(cpu) (rate(container_cpu_usage_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", cpu=\"total\", invalid!=$split_ids}[$__rate_interval]) + 1e-12)\r\n)\r\nor\r\nmax by (container) (\r\n  (rate(container_cpu_system_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__rate_interval]))\r\n  /\r\n  sum without(cpu) (rate(container_cpu_usage_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", cpu=\"total\", invalid=$split_ids}[$__rate_interval]) + 1e-12)\r\n)",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  {
   "title": "CPU throttled (total time)",
   "type": "timeseries",
   "description": "sum_over_time of seconds spent throtting. Empty is container doesn't have cpu limit.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (container, name) (\r\n  (rate(container_cpu_cfs_throttled_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__rate_interval]) * $__interval_ms / 1000 )\r\n)\r\nor\r\nmax by (container) (\r\n  (rate(container_cpu_cfs_throttled_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__rate_interval]) * $__interval_ms / 1000 )\r\n)",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  {
   "title": "cpu spec: request",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "max by(container) (\r\n    kube_pod_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", resource=\"cpu\", container=~\"$container\", uid=~\"$pod_uid\"}\r\n)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU burst usage (total time)",
   "type": "timeseries",
   "description": "sum_over_time of seconds spent bursting. Empty is cgroup-burst metrics are not configured, of if container doesn't have burst.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (container, name) (\r\n  (rate(container_cpu_cgroup_burst_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__rate_interval]) * $__interval_ms / 1000 )\r\n)\r\nor\r\nmax by (container) (\r\n  (rate(container_cpu_cgroup_burst_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__rate_interval]) * $__interval_ms / 1000 )\r\n)",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  {
   "title": "CPU request %",
   "type": "timeseries",
   "description": "clamped at 300%",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(container, name) (rate(container_cpu_usage_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", cpu=\"total\", invalid!=$split_ids}[$__rate_interval]))\r\n/ on(container) group_left\r\nsum by(container) (\r\n    kube_pod_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", resource=\"cpu\",container=~\"$container\"}\r\n)\r\nor\r\nsum by(container) (rate(container_cpu_usage_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", cpu=\"total\", invalid=$split_ids}[$__rate_interval]))\r\n/\r\nsum by(container) (\r\n    kube_pod_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", resource=\"cpu\", container=~\"$container\"}\r\n)",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  {
   "title": "spec: cpu burst",
   "type": "timeseries",
   "description": "empty is cgroup-burst metrics are not configured, of if container doesn't have burst",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(container) (\r\n    kube_pod_container_cgroup_burst{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\"}\r\n)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "cpu spec: limit",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "max by(container, name) (\r\n  container_spec_cpu_quota{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}\r\n  /\r\n  container_spec_cpu_period{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}\r\n)\r\nor\r\nmax by(container) (\r\n  container_spec_cpu_quota{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}\r\n  /\r\n  container_spec_cpu_period{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}\r\n)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU throttling periods %",
   "type": "timeseries",
   "description": "empty is container doesn't have cpu limit",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "# if container didn't run at some interval, you will have division by zero, so we do ` / increase + epsilon`\r\nmax by (container, name) (\r\n  (increase(container_cpu_cfs_throttled_periods_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__rate_interval]) )\r\n/\r\n  (increase(container_cpu_cfs_periods_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__rate_interval]) + 1e-5 )\r\n)\r\nor\r\nmax by (container) (\r\n  (increase(container_cpu_cfs_throttled_periods_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__rate_interval]) )\r\n/\r\n  (increase(container_cpu_cfs_periods_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__rate_interval]) + 1e-5 )\r\n)",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  {
   "title": "CPU limit %",
   "type": "timeseries",
   "description": "empty is container doesn't have cpu limit",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(container, name) (\r\n    sum without(cpu) (\r\n        rate(container_cpu_usage_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", cpu=\"total\", invalid!=$split_ids}[$__rate_interval])\r\n    )\r\n    /\r\n    (\r\n      container_spec_cpu_quota{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", cpu=\"total\", invalid!=$split_ids}\r\n      /\r\n      container_spec_cpu_period{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", cpu=\"total\", invalid!=$split_ids}\r\n    )\r\n)\r\nor\r\n# when container_spec_cpu_quota is missing\r\nsum by(container, name) (\r\n    rate(container_cpu_usage_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", cpu=\"total\", invalid!=$split_ids}[$__rate_interval])\r\n)\r\n/ on(container) group_left\r\nsum by(container) (\r\n    kube_pod_container_resource_limits{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", resource=\"cpu\",container=~\"$container\", invalid!=$split_ids}\r\n)\r\nor\r\n# united\r\nsum by(container) (\r\n    sum without(cpu) (\r\n        rate(container_cpu_usage_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", cpu=\"total\", invalid=$split_ids}[$__rate_interval])\r\n    )\r\n    /\r\n    (\r\n      container_spec_cpu_quota{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", cpu=\"total\", invalid!=$split_ids}\r\n      /\r\n      container_spec_cpu_period{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", cpu=\"total\", invalid!=$split_ids}\r\n    )\r\n)\r\nor\r\nsum by(container) (\r\n    rate(container_cpu_usage_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", cpu=\"total\", invalid=$split_ids}[$__rate_interval])\r\n)\r\n/ on(container) group_left\r\nsum by(container) (\r\n    kube_pod_container_resource_limits{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", resource=\"cpu\",container=~\"$container\", invalid=$split_ids}\r\n)",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  {
   "title": "CPU burst periods %",
   "type": "timeseries",
   "description": "empty is cgroup-burst metrics are not configured, of if container doesn't have burst",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "# if container didn't run at some interval, you will have division by zero, so we do ` / increase + epsilon`\r\n# sometimes burst reporting is alightly misaligned with cadvisor reporting,\r\n# and you get non-zero burst with (zero+epsilon) cfs_periods, which results in peak at ~1e5\r\n# using clamp_max fixes this, although overall result can be a bit inaccurate\r\nclamp_max(\r\n  max by (container, name) (\r\n    (increase(container_cpu_cgroup_burst_periods_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__rate_interval]) )\r\n  / on(container, name)\r\n    (increase(container_cpu_cfs_periods_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__rate_interval]) + 1e-5 )\r\n  ),\r\n1)\r\nor\r\nclamp_max(\r\n  max by(container) (\r\n    max by (container, name) (\r\n      (increase(container_cpu_cgroup_burst_periods_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__rate_interval]) )\r\n    / on(container, name)\r\n      (increase(container_cpu_cfs_periods_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__rate_interval]) + 1e-5 )\r\n    )\r\n  ),\r\n  1\r\n)",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  {
   "title": "pressure (requires custom cadvisor config, missing in k8s)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 }
  },
  {
   "title": "cpu pressure: stalled",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(container, name) (rate(container_pressure_cpu_stalled_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__rate_interval]))\r\nor\r\nsum by(container) (rate(container_pressure_cpu_stalled_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__rate_interval]))",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  {
   "title": "memory pressure: stalled",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(container, name) (rate(container_pressure_memory_stalled_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__rate_interval]))\r\nor\r\nsum by(container) (rate(container_pressure_memory_stalled_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__rate_interval]))",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  {
   "title": "io pressure: stalled",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(container, name) (rate(container_pressure_io_stalled_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__rate_interval]))\r\nor\r\nsum by(container) (rate(container_pressure_io_stalled_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__rate_interval]))",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  {
   "title": "cpu pressure: waiting",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(container, name) (rate(container_pressure_cpu_waiting_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__rate_interval]))\r\nor\r\nsum by(container) (rate(container_pressure_cpu_waiting_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__rate_interval]))",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  {
   "title": "memory pressure: waiting",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(container, name) (rate(container_pressure_memory_waiting_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__rate_interval]))\r\nor\r\nsum by(container) (rate(container_pressure_memory_waiting_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__rate_interval]))",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  {
   "title": "io pressure: waiting",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(container, name) (rate(container_pressure_io_waiting_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__rate_interval]))\r\nor\r\nsum by(container) (rate(container_pressure_io_waiting_seconds_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__rate_interval]))",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  { "title": "memory summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "memory summary: rss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (container, name) (\r\n  max_over_time(container_memory_rss{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__interval])\r\n  or\r\n  container_memory_rss{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}\r\n)\r\nor\r\nmax by (container) (\r\n  max_over_time(container_memory_rss{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__interval])\r\n  or\r\n  container_memory_rss{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}\r\n)",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  {
   "title": "Memory notes",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 82 },
   "options": {
    "content": "- `rss` is anon memory\n- `wss` = rss + active cache\n- `raw` = `rss` + full cache + kernel\n- Cache is active if it used _often_ (more than once?)\n\nWhat to look for:\n- WSS reaching limit causes file garbage collection\n- RSS reaching limit causes OOM kill\n"
   }
  },
  {
   "title": "memory summary: wss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (container, name) (\r\n  max_over_time(container_memory_working_set_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__interval])\r\n  or\r\n  container_memory_working_set_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}\r\n)\r\nor\r\nmax by (container) (\r\n  max_over_time(container_memory_working_set_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__interval])\r\n  or\r\n  container_memory_working_set_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}\r\n)",
     "legendFormat": "{{container}}, name={{name}}"
    }
   ]
  },
  { "title": "memory details: $container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 }, "repeat": "container" },
  {
   "title": "memory levels: $container",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (container, name) (\r\n  max_over_time(container_memory_max_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__interval])\r\n  or\r\n  container_memory_max_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}\r\n)\r\nor\r\nmax by (container) (\r\n  max_over_time(container_memory_max_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__interval])\r\n  or\r\n  container_memory_max_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}\r\n)",
     "legendFormat": "max, name={{name}}"
    },
    {
     "expr": "max by (container, name) (\r\n  max_over_time(container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__interval])\r\n  or\r\n  container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}\r\n)\r\nor\r\nmax by (container) (\r\n  max_over_time(container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__interval])\r\n  or\r\n  container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}\r\n)",
     "legendFormat": "raw, name={{name}}"
    },
    {
     "expr": "max by (container, name) (\r\n  max_over_time(container_memory_working_set_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__interval])\r\n  or\r\n  container_memory_working_set_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}\r\n)\r\nor\r\nmax by (container) (\r\n  max_over_time(container_memory_working_set_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__interval])\r\n  or\r\n  container_memory_working_set_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}\r\n)",
     "legendFormat": "wss, name={{name}}"
    },
    {
     "expr": "max by (container, name) (\r\n  max_over_time(container_memory_rss{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__interval])\r\n  or\r\n  container_memory_rss{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}\r\n)\r\nor\r\nmax by (container) (\r\n  max_over_time(container_memory_rss{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__interval])\r\n  or\r\n  container_memory_rss{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}\r\n)",
     "legendFormat": "rss, name={{name}}"
    },
    {
     "expr": "max by (container) (kube_pod_container_resource_limits{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\", container=~\"$container\", uid=~\"$pod_uid\", invalid=$enableLimits})",
     "legendFormat": "limit"
    },
    {
     "expr": "max by (container) (kube_pod_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\", container=~\"$container\", uid=~\"$pod_uid\", invalid=$enableLimits})",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "memory / request: $container",
   "type": "timeseries",
   "description": "empty is container doesn't have memory request",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (container, name) (\r\n  max_over_time(container_memory_max_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__interval])\r\n  or\r\n  container_memory_max_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}\r\n)\r\n/ on(container) group_left\r\nmax by (container) (max_over_time(kube_pod_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\", container=~\"$container\"}[$__interval]))\r\nor\r\nmax by (container) (\r\n  max_over_time(container_memory_max_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__interval])\r\n  or\r\n  container_memory_max_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}\r\n)\r\n/\r\nmax by (container) (max_over_time(kube_pod_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\", container=~\"$container\"}[$__interval]))",
     "legendFormat": "max, name={{name}}"
    },
    {
     "expr": "max by (container, name) (\r\n  max_over_time(container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__interval])\r\n  or\r\n  container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}\r\n)\r\n/ on(container) group_left\r\nmax by (container) (max_over_time(kube_pod_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\", container=~\"$container\"}[$__interval]))\r\nor\r\nmax by (container) (\r\n  max_over_time(container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__interval])\r\n  or\r\n  container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}\r\n)\r\n/\r\nmax by (container) (max_over_time(kube_pod_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\", container=~\"$container\"}[$__interval]))",
     "legendFormat": "raw, name={{name}}"
    },
    {
     "expr": "max by (container, name) (\r\n  max_over_time(container_memory_working_set_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__interval])\r\n  or\r\n  container_memory_working_set_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}\r\n)\r\n/ on(container) group_left\r\nmax by (container) (max_over_time(kube_pod_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\", container=~\"$container\"}[$__interval]))\r\nor\r\nmax by (container) (\r\n  max_over_time(container_memory_working_set_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__interval])\r\n  or\r\n  container_memory_working_set_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}\r\n)\r\n/\r\nmax by (container) (max_over_time(kube_pod_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\", container=~\"$container\"}[$__interval]))",
     "legendFormat": "wss, name={{name}}"
    },
    {
     "expr": "max by (container, name) (\r\n  max_over_time(container_memory_rss{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__interval])\r\n  or\r\n  container_memory_rss{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}\r\n)\r\n/ on(container) group_left\r\nmax by (container) (max_over_time(kube_pod_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\", container=~\"$container\"}[$__interval]))\r\nor\r\nmax by (container) (\r\n  max_over_time(container_memory_rss{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__interval])\r\n  or\r\n  container_memory_rss{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}\r\n)\r\n/\r\nmax by (container) (max_over_time(kube_pod_container_resource_requests{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\", container=~\"$container\"}[$__interval]))",
     "legendFormat": "rss, name={{name}}"
    }
   ]
  },
  {
   "title": "memory types: $container",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (container, name) (\r\n  avg_over_time(container_memory_cache{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__interval])\r\n  or\r\n  container_memory_cache{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}\r\n)\r\nor\r\nmax by (container) (\r\n  avg_over_time(container_memory_cache{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__interval])\r\n  or\r\n  container_memory_cache{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}\r\n)",
     "legendFormat": "cache, name={{name}}"
    },
    {
     "expr": "max by (container, name) (\r\n  avg_over_time(container_memory_rss{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__interval])\r\n  or\r\n  container_memory_rss{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}\r\n)\r\nor\r\nmax by (container) (\r\n  avg_over_time(container_memory_rss{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__interval])\r\n  or\r\n  container_memory_rss{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}\r\n)",
     "legendFormat": "rss, name={{name}}"
    },
    {
     "expr": "# container_memory_usage_bytes = rss + cache + kernel\r\n# but container_memory_kernel_usage is broken in current version of cadvisor, it's always zero\r\nmax by (container, name) (\r\n  (\r\n    avg_over_time(container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__interval])\r\n    -\r\n    avg_over_time(container_memory_rss{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__interval])\r\n    -\r\n    avg_over_time(container_memory_cache{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__interval])\r\n  )\r\n  or\r\n  (\r\n  container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}\r\n  -\r\n  container_memory_rss{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}\r\n  -\r\n  container_memory_cache{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}\r\n  )\r\n)\r\nor\r\nmax by (container) (\r\n  (\r\n    avg_over_time(container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__interval])\r\n    -\r\n    avg_over_time(container_memory_rss{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__interval])\r\n    -\r\n    avg_over_time(container_memory_cache{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__interval])\r\n  )\r\n  or\r\n  (\r\n  container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}\r\n  -\r\n  container_memory_rss{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}\r\n  -\r\n  container_memory_cache{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}\r\n  )\r\n)",
     "legendFormat": "kernel, name={{name}}"
    },
    {
     "expr": "max by (container, name) (\r\n  avg_over_time(container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__interval])\r\n  or\r\n  container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}\r\n)\r\nor\r\nmax by (container) (\r\n  avg_over_time(container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__interval])\r\n  or\r\n  container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}\r\n)",
     "legendFormat": "raw total, name={{name}}"
    }
   ]
  },
  {
   "title": "memory / limit: $container",
   "type": "timeseries",
   "description": "empty is container doesn't have memory limit",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (container, name) (\r\n    (\r\n        max_over_time(container_memory_max_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__interval])\r\n        or\r\n        container_memory_max_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}\r\n    )\r\n/\r\n    (max_over_time(container_spec_memory_limit_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\"}[$__interval]) != 0)\r\n)\r\nor\r\nmax by (container) (\r\n    (\r\n        max_over_time(container_memory_max_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__interval])\r\n        or\r\n        container_memory_max_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}\r\n    )\r\n/\r\n    (max_over_time(container_spec_memory_limit_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\"}[$__interval]) != 0)\r\n)",
     "legendFormat": "max, name={{name}}"
    },
    {
     "expr": "max by (container, name) (\r\n    (\r\n        max_over_time(container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__interval])\r\n        or\r\n        container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}\r\n    )\r\n/\r\n    (max_over_time(container_spec_memory_limit_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\"}[$__interval]) != 0)\r\n)\r\nor\r\nmax by (container) (\r\n    (\r\n        max_over_time(container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__interval])\r\n        or\r\n        container_memory_usage_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}\r\n    )\r\n/\r\n    (max_over_time(container_spec_memory_limit_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\"}[$__interval]) != 0)\r\n)",
     "legendFormat": "raw, name={{name}}"
    },
    {
     "expr": "max by (container, name) (\r\n    (\r\n        max_over_time(container_memory_working_set_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__interval])\r\n        or\r\n        container_memory_working_set_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}\r\n    )\r\n/\r\n    (max_over_time(container_spec_memory_limit_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\"}[$__interval]) != 0)\r\n)\r\nor\r\nmax by (container) (\r\n    (\r\n        max_over_time(container_memory_working_set_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__interval])\r\n        or\r\n        container_memory_working_set_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}\r\n    )\r\n/\r\n    (max_over_time(container_spec_memory_limit_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\"}[$__interval]) != 0)\r\n)",
     "legendFormat": "wss, name={{name}}"
    },
    {
     "expr": "max by (container, name) (\r\n    (\r\n        max_over_time(container_memory_rss{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__interval])\r\n        or\r\n        container_memory_rss{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}\r\n    )\r\n/\r\n    (max_over_time(container_spec_memory_limit_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\"}[$__interval]) != 0)\r\n)\r\nor\r\nmax by (container) (\r\n    (\r\n        max_over_time(container_memory_rss{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__interval])\r\n        or\r\n        container_memory_rss{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}\r\n    )\r\n/\r\n    (max_over_time(container_spec_memory_limit_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\"}[$__interval]) != 0)\r\n)",
     "legendFormat": "rss, name={{name}}"
    }
   ]
  },
  {
   "title": "cache [in]active: $container",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (container, name) (\r\n  avg_over_time(container_memory_cache{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__interval])\r\n  or\r\n  container_memory_cache{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}\r\n)\r\nor\r\nmax by (container) (\r\n  avg_over_time(container_memory_cache{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__interval])\r\n  or\r\n  container_memory_cache{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}\r\n)",
     "legendFormat": "total, name={{name}}"
    },
    {
     "expr": "max by (container, name) (\r\n  avg_over_time(container_memory_total_inactive_file_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__interval])\r\n  or\r\n  container_memory_total_inactive_file_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}\r\n)\r\nor\r\nmax by (container) (\r\n  avg_over_time(container_memory_total_inactive_file_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__interval])\r\n  or\r\n  container_memory_total_inactive_file_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}\r\n)",
     "legendFormat": "inactive, name={{name}}"
    },
    {
     "expr": "max by (container, name) (\r\n  avg_over_time(container_memory_total_active_file_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__interval])\r\n  or\r\n  container_memory_total_active_file_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}\r\n)\r\nor\r\nmax by (container) (\r\n  avg_over_time(container_memory_total_active_file_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__interval])\r\n  or\r\n  container_memory_total_active_file_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}\r\n)",
     "legendFormat": "active, name={{name}}"
    }
   ]
  },
  {
   "title": "page fault rate: $container",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "max by (container, name, failure_type)(rate(container_memory_failures_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__rate_interval]))\r\nor\r\nmax by (container, failure_type)(rate(container_memory_failures_total{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__rate_interval]))",
     "legendFormat": "{{failure_type}}, name={{name}}"
    }
   ]
  },
  {
   "title": "cache [un]mapped: $container",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (container, name) (\r\n  avg_over_time(container_memory_cache{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__interval])\r\n  or\r\n  container_memory_cache{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}\r\n)\r\nor\r\nmax by (container) (\r\n  avg_over_time(container_memory_cache{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__interval])\r\n  or\r\n  container_memory_cache{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}\r\n)",
     "legendFormat": "total cache, name={{name}}"
    },
    {
     "expr": "max by (container, name) (\r\n  avg_over_time(container_memory_mapped_file{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__interval])\r\n  or\r\n  container_memory_mapped_file{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}\r\n)\r\nor\r\nmax by (container) (\r\n  avg_over_time(container_memory_mapped_file{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__interval])\r\n  or\r\n  container_memory_mapped_file{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}\r\n)",
     "legendFormat": "mapped, name={{name}}"
    },
    {
     "expr": "max by (container, name) (\r\n  (\r\n    avg_over_time(container_memory_cache{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__interval])\r\n    -\r\n    avg_over_time(container_memory_mapped_file{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}[$__interval])\r\n  )\r\n  or\r\n  (\r\n    container_memory_mapped_file{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}\r\n    -\r\n    container_memory_mapped_file{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid!=$split_ids}\r\n  )\r\n)\r\nor\r\nmax by (container) (\r\n  (\r\n    avg_over_time(container_memory_cache{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__interval])\r\n    -\r\n    avg_over_time(container_memory_mapped_file{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}[$__interval])\r\n  )\r\n  or\r\n  (\r\n    container_memory_mapped_file{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}\r\n    -\r\n    container_memory_mapped_file{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", name=~\"$id\", invalid=$split_ids}\r\n  )\r\n)",
     "legendFormat": "unmapped, name={{name}}"
    }
   ]
  },
  {
   "title": "Network (shared between containers)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 202 }
  },
  {
   "title": "Receive Bandwidth by interface",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 203 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(interface) (rate(container_network_receive_bytes_total{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth by interface",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 203 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(interface) (rate(container_network_transmit_bytes_total{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 210 } },
  {
   "title": "Storage IO (average over time range)",
   "type": "table",
   "gridPos": { "h": 7, "w": 17, "x": 1, "y": 211 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(container, device) (rate(container_fs_reads_total{container!=\"\", container=~\"$container\", location=\"$location\", namespace=\"$namespace\", pod=\"$pod\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(container, device) (rate(container_fs_writes_total{container!=\"\", container=~\"$container\", location=\"$location\", namespace=\"$namespace\", pod=\"$pod\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(container, device) (rate(container_fs_reads_total{container!=\"\", container=~\"$container\", location=\"$location\", namespace=\"$namespace\", pod=\"$pod\"}[$__range]) + rate(container_fs_writes_total{container!=\"\", container=~\"$container\", location=\"$location\", namespace=\"$namespace\", pod=\"$pod\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(container, device) (rate(container_fs_reads_bytes_total{container!=\"\", container=~\"$container\", location=\"$location\", namespace=\"$namespace\", pod=\"$pod\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(container, device) (rate(container_fs_writes_bytes_total{container!=\"\", container=~\"$container\", location=\"$location\", namespace=\"$namespace\", pod=\"$pod\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(container, device) (rate(container_fs_reads_bytes_total{container!=\"\", container=~\"$container\", location=\"$location\", namespace=\"$namespace\", pod=\"$pod\"}[$__range]) + rate(container_fs_writes_bytes_total{container!=\"\", container=~\"$container\", location=\"$location\", namespace=\"$namespace\", pod=\"$pod\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage notes",
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 18, "y": 211 },
   "options": {
    "content": "\nRead/write from NFS and SMB shares\nwill not be shown in the storage throughput.\n\nCadvisor exports data from cgroup io.stats,\nwhich are only calculated for block devices.\n"
   }
  },
  {
   "title": "Disk read",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 218 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(container) (rate(container_fs_reads_bytes_total{container!=\"\", container=~\"$container\", location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$id\"}[$__rate_interval]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Disk write",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 218 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(container) (rate(container_fs_writes_bytes_total{container!=\"\", container=~\"$container\", location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\", name=~\"$id\"}[$__rate_interval]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "ephemeral storage total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 225 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (kube_summary_pod_ephemeral_storage_used_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\"})\r\nor\r\nsum by(pod) (ephemeral_storage_pod_usage{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ephemeral storage (without logs)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 225 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (kube_summary_pod_ephemeral_storage_used_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\"})\r\n-\r\nsum by(pod) (kube_summary_container_logs_used_bytes{location=\"$location\", namespace=\"$namespace\", pod=\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "logs: current",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 232 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(container) (kube_summary_container_logs_used_bytes{container!=\"\", container=~\"$container\", location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "rootfs used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 232 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(container) (kube_summary_container_rootfs_used_bytes{container!=\"\", container=~\"$container\", location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "logs written",
   "type": "timeseries",
   "description": "Absolute values will change based on time scale, because it's showing total increase over an interval.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 239 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(container) (rate(kube_summary_container_logs_used_bytes{container!=\"\", container=~\"$container\", location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "volume usage",
   "type": "timeseries",
   "description": "empty if pod doesn't have volumes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 239 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod, volume_name) (ephemeral_storage_container_volume_usage{location=\"$location\", namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{volume_name}}"
    }
   ]
  }
 ]
}