{
 "title": "Cluster / Namespaces",
 "tags": [
  "maintainer:danil",
  "k8s-cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(up{job=\"kube-state-metrics\", endpoint=\"\"}[$__range])))"
    }
   },
   { "name": "namespace_filter", "label": "filter" },
   {
    "name": "namespace",
    "query": {
     "query": "query_result(group by(namespace) (last_over_time(kube_namespace_created{location=\"$location\", namespace=~\".*($namespace_filter).*\"}[$__range])))"
    }
   },
   {
    "name": "_safe_interval_200",
    "query": {
     "query": "query_result(((($__range_ms / 200) > bool ($__interval_ms * 2))* scalar(round(vector($__range_ms / 200 / 1000)))+(($__range_ms / 200) <= bool ($__interval_ms * 2))* scalar(round(vector($__interval_ms * 2 / 1000))))# original structure of query is here because in the query input panel line breaks are automatically removed# scalar(round(vector)) is needed because prometheus 2 can't use intervals with non-integer values)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 11, "w": 18, "x": 1, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by (namespace) (last_over_time(kube_pod_owner{location=\"$location\", namespace=~\"$namespace\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(namespace) (avg_over_time(node_namespace:container_cpu_usage_seconds:irate{location=\"$location\", namespace=~\"$namespace\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (namespace) (last_over_time(node_namespace:kube_pod_container_resource_requests{location=\"$location\", namespace=~\"$namespace\", resource=\"cpu\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (namespace) (last_over_time(node_namespace:container_memory_rss{location=\"$location\", namespace=~\"$namespace\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (namespace) (last_over_time(node_namespace:kube_pod_container_resource_requests{location=\"$location\", namespace=~\"$namespace\", resource=\"memory\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (namespace) (last_over_time(kube_namespace_created{location=\"$location\", namespace=~\"$namespace\"}[$__range])) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(namespace) (kube_pod_info{location=\"$location\", namespace=~\"$namespace\"} unless on(cluster, namespace, pod) kube_pod_container_resource_requests{location=\"$location\", namespace=~\"$namespace\", resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by(namespace) (max_over_time(kube_pod_owner{location=\"$location\", namespace=~\"$namespace\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(kube_pod_container_status_restarts_total{location=\"$location\", namespace=~\"$namespace\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ephemeral Storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "# both metrics include all of the ephemeral storage\r\nsum by (namespace) (max_over_time(kube_summary_pod_ephemeral_storage_used_bytes{location=\"$location\", namespace=~\"$namespace\"}[$__interval]))\r\nor\r\nsum by (namespace) (max_over_time(ephemeral_storage_pod_usage{location=\"$location\", namespace=~\"$namespace\"}[$__interval]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Ephemeral Storage: logs written",
   "type": "timeseries",
   "description": "Absolute values will change based on time scale, because it's showing total increase over an interval.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace) (rate(kube_summary_container_logs_used_bytes{location=\"$location\", namespace=~\"$namespace\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Compute", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(namespace) (max_over_time(node_namespace:container_cpu_usage_seconds:irate{location=\"$location\", namespace=~\"$namespace\"}[${_safe_interval_200}s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory RAW",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace) (max_over_time(node_namespace:container_memory_usage_bytes{location=\"$location\", namespace=~\"$namespace\"}[$__interval]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory RSS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace) (max_over_time(node_namespace:container_memory_rss{location=\"$location\", namespace=~\"$namespace\"}[$__interval]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (namespace) (max_over_time(node_namespace:container_network_receive_bytes:irate{location=\"$location\", namespace=~\"$namespace\"}[$_safe_interval_200]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (namespace) (max_over_time(node_namespace:container_network_transmit_bytes:irate{location=\"$location\", namespace=~\"$namespace\"}[$_safe_interval_200]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}