{
 "title": "Node / Pods",
 "tags": [
  "maintainer:danil",
  "k8s-cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(up{job=\"kube-state-metrics\", endpoint=\"\"}[$__range])))"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(kube_node_info{location=\"$location\"}, node)"
   },
   {
    "name": "namespace",
    "query": {
     "query": "query_result(group by(namespace) (last_over_time(kube_namespace_status_phase{location=\"$location\"}[$__range])))"
    }
   },
   {
    "name": "capacity",
    "query": "Show : \"\", Hide : \"invalid123\""
   },
   {
    "name": "pod",
    "query": {
     "query": "query_result(group by(pod) (last_over_time(kube_pod_info{location=\"$location\", namespace=~\"$namespace\"}[$__range])))"
    }
   }
  ]
 },
 "panels": [
  { "title": "summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod info",
   "type": "table",
   "gridPos": { "h": 28, "w": 21, "x": 1, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(namespace, pod) (\r\n  max by(namespace, pod, container) (rate(container_cpu_usage_seconds_total{location=\"$location\", node=~\"$node\", namespace=~\"$namespace\"}[$__range]))\r\n)"
    },
    {
     "expr": "sum by(namespace, pod) (\r\n  max by(namespace, pod, container) (last_over_time(kube_pod_container_resource_requests{location=\"$location\", node=~\"$node\", namespace=~\"$namespace\", resource=\"cpu\"}[$__range]))\r\n)"
    },
    {
     "expr": "sum by(node, namespace, pod) (\r\n  max by(node, namespace, pod, container) (last_over_time(kube_pod_container_resource_requests{location=\"$location\", node=~\"$node\", namespace=~\"$namespace\", resource=\"cpu\"}[$__range]))\r\n) / on(node) group_left\r\nsum by(node) (\r\n  kube_node_status_capacity{location=\"$location\", node=~\"$node\", resource=\"cpu\"}\r\n)"
    },
    {
     "expr": "sum by(namespace, pod) (\r\n  max by(namespace, pod, container) (last_over_time(kube_pod_container_resource_limits{location=\"$location\", node=~\"$node\", namespace=~\"$namespace\", resource=\"cpu\"}[$__range]))\r\n)"
    },
    {
     "expr": "sum by(namespace, pod) (\r\n+ max by(namespace, pod, container) (last_over_time(container_memory_usage_bytes{location=\"$location\", node=\"$node\", namespace=~\"$namespace\"}[$__range]))\r\n- max by(namespace, pod, container) (last_over_time(container_memory_cache{location=\"$location\", node=\"$node\", namespace=~\"$namespace\"}[$__range]))\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(namespace, pod) (\r\n  max by(namespace, pod, container) (last_over_time(container_memory_usage_bytes{location=\"$location\", node=\"$node\", namespace=~\"$namespace\"}[$__range]))\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(namespace, pod) (\r\n  max by(namespace, pod, container) (last_over_time(kube_pod_container_resource_requests{location=\"$location\", node=\"$node\", namespace=~\"$namespace\", resource=\"memory\"}[$__range]))\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(node, namespace, pod) (\r\n  max by(node, namespace, pod, container) (kube_pod_container_resource_requests{location=\"$location\", node=\"$node\", namespace=~\"$namespace\", resource=\"memory\"})\r\n) / on(node) group_left\r\nsum by(node) (\r\n  kube_node_status_capacity{location=\"$location\", node=~\"$node\", resource=\"memory\"}\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(namespace, pod) (\r\n  max by(namespace, pod, container) (last_over_time(kube_pod_container_resource_limits{location=\"$location\", node=\"$node\", namespace=~\"$namespace\", resource=\"memory\"}[$__range]))\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(namespace, pod) (\r\n  last_over_time(container_last_seen{location=\"$location\", node=\"$node\", namespace=~\"$namespace\"}[$__range])\r\n) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pods count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "count(group by(pod) (last_over_time(kube_pod_info{location=\"$location\", node=\"$node\", namespace=~\"$namespace\"}[$__interval])))",
     "legendFormat": "running"
    },
    {
     "expr": "avg(avg_over_time(kube_node_status_capacity{location=\"$location\", node=\"$node\", resource=\"pods\", invalid=$capacity}[$__interval]))",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "PVC mounts",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "group by(namespace, persistentvolumeclaim) (last_over_time(kubelet_volume_stats_capacity_bytes{location=\"$location\", node=\"$node\", namespace=~\"$namespace\"}[$__interval]))",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "CPU summary",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{location=\"$location\", node=~\"$node\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "pods"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{location=\"$location\", node=\"$node\", mode!~\"idle|iowait|steal\"}[$__rate_interval]))",
     "legendFormat": "node"
    },
    {
     "expr": "max(max_over_time(kube_node_status_capacity{location=\"$location\", node=~\"$node\", resource=\"cpu\", invalid=$capacity}[$__interval]))",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Memory Summary",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "+ node_memory_MemTotal_bytes{location=\"$location\", node=\"$node\"}\r\n- node_memory_MemFree_bytes{location=\"$location\", node=\"$node\"}\r\n- node_memory_Buffers_bytes{location=\"$location\", node=\"$node\"}\r\n- node_memory_Cached_bytes{location=\"$location\", node=\"$node\"}",
     "legendFormat": "node RSS"
    },
    {
     "expr": "+ node_memory_MemTotal_bytes{location=\"$location\", node=\"$node\",}\r\n- node_memory_MemFree_bytes{location=\"$location\", node=\"$node\",}",
     "legendFormat": "node RAW"
    },
    {
     "expr": "sum(max by(pod, container) (avg_over_time(container_memory_rss{location=\"$location\", node=\"$node\", namespace=~\"$namespace\"}[$__interval])))",
     "legendFormat": "pod rss"
    },
    {
     "expr": "sum(max by(pod, container) (avg_over_time(container_memory_usage_bytes{location=\"$location\", node=\"$node\", namespace=~\"$namespace\"}[$__interval])))",
     "legendFormat": "pod raw"
    },
    {
     "expr": "sum(\r\n  # max by(pod, container) eliminates artifacts when pod UID changes\r\n  max by(namespace, pod, container) (\r\n    sum_over_time(kube_pod_container_resource_requests{location=\"$location\", node=\"$node\", namespace=~\"$namespace\", resource=\"memory\"}[$__interval])\r\n    / on(job) group_left()\r\n    count_over_time(up{job=\"kube-state-metrics\", location=\"$location\"}[$__interval])\r\n    or\r\n    (\r\n      sum_over_time(kube_pod_init_container_resource_requests{location=\"$location\", node=\"$node\", namespace=~\"$namespace\", resource=\"memory\"}[$__interval])\r\n      / on(job) group_left()\r\n      count_over_time(up{job=\"kube-state-metrics\", location=\"$location\"}[$__interval])\r\n      and on(location, namespace, pod, uid, container)\r\n      (max_over_time(kube_pod_init_container_info{location=\"$location\", namespace=~\"$namespace\", restart_policy=\"Always\"}[$__interval]))\r\n      and on(location, namespace, pod, uid)\r\n      (max_over_time(kube_pod_info{location=\"$location\", node=\"$node\", namespace=~\"$namespace\"}[$__interval]))\r\n    )\r\n  )\r\n)",
     "legendFormat": "pod requests"
    },
    {
     "expr": "sum(\r\n  # max by(pod, container) eliminates artifacts when pod UID changes\r\n  max by(namespace, pod, container) (\r\n    sum_over_time(kube_pod_container_resource_limits{location=\"$location\", node=\"$node\", namespace=~\"$namespace\", resource=\"memory\"}[$__interval])\r\n    / on(job) group_left()\r\n    count_over_time(up{job=\"kube-state-metrics\", location=\"$location\"}[$__interval])\r\n    or\r\n    (\r\n      sum_over_time(kube_pod_init_container_resource_limits{location=\"$location\", node=\"$node\", namespace=~\"$namespace\", resource=\"memory\"}[$__interval])\r\n      / on(job) group_left()\r\n      count_over_time(up{job=\"kube-state-metrics\", location=\"$location\"}[$__interval])\r\n      and on(location, namespace, pod, uid, container)\r\n      (max_over_time(kube_pod_init_container_info{location=\"$location\", namespace=~\"$namespace\", restart_policy=\"Always\"}[$__interval]))\r\n      and on(location, namespace, pod, uid)\r\n      (max_over_time(kube_pod_info{location=\"$location\", node=\"$node\", namespace=~\"$namespace\"}[$__interval]))\r\n    )\r\n  )\r\n)",
     "legendFormat": "pod limits"
    },
    {
     "expr": "avg(avg_over_time(kube_node_status_allocatable{location=\"$location\", node=~\"$node\", resource=\"memory\", invalid=$capacity}[$__interval]))",
     "legendFormat": "allocatable"
    }
   ]
  },
  { "title": "pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "pod: cpu request (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(namespace, pod) (\r\n  # max by(namespace, pod, container) helps to avoid artifacts when pod is restarted and max_over_time fetches both old and new pod info\r\n  max by(namespace, pod, container) (max_over_time(kube_pod_container_resource_requests{location=\"$location\", node=\"$node\", namespace=~\"$namespace\", resource=\"cpu\"}[$__interval]))\r\n)",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "pod: memory request (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(namespace, pod) (\r\n  # max by(pod, container) eliminates artifacts when pod UID changes\r\n  max by(namespace, pod, container) (\r\n    sum_over_time(kube_pod_container_resource_requests{location=\"$location\", node=\"$node\", namespace=~\"$namespace\", resource=\"memory\"}[$__interval])\r\n    / on(job) group_left()\r\n    count_over_time(up{job=\"kube-state-metrics\", location=\"$location\"}[$__interval])\r\n    or\r\n    (\r\n      sum_over_time(kube_pod_init_container_resource_requests{location=\"$location\", node=\"$node\", namespace=~\"$namespace\", resource=\"memory\"}[$__interval])\r\n      / on(job) group_left()\r\n      count_over_time(up{job=\"kube-state-metrics\", location=\"$location\"}[$__interval])\r\n      and on(location, namespace, pod, uid, container)\r\n      (max_over_time(kube_pod_init_container_info{location=\"$location\", namespace=~\"$namespace\", restart_policy=\"Always\"}[$__interval]))\r\n      and on(location, namespace, pod, uid)\r\n      (max_over_time(kube_pod_info{location=\"$location\", node=\"$node\", namespace=~\"$namespace\"}[$__interval]))\r\n    )\r\n  )\r\n)",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "pod: cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(namespace, pod) (rate(container_cpu_usage_seconds_total{location=\"$location\", node=~\"$node\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "pod: memory rss",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(namespace, pod) (\r\n  # avg by(namespace, pod, container) helps to avoid artifacts when pod is restarted and max_over_time fetches both old and new pod info\r\n  avg by(namespace, pod, container) (max_over_time(container_memory_rss{location=\"$location\", node=~\"$node\", namespace=~\"$namespace\"}[$__interval]))\r\n)",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "pod: ephemeral storage usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(namespace, pod) (ephemeral_storage_pod_usage{location=\"$location\", node=~\"$node\", namespace=~\"$namespace\"})",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "pod: memory raw",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(namespace, pod) (\r\n  # avg by(namespace, pod, container) helps to avoid artifacts when pod is restarted and max_over_time fetches both old and new pod info\r\n  avg by(namespace, pod, container) (avg_over_time(container_memory_usage_bytes{location=\"$location\", node=~\"$node\", namespace=~\"$namespace\"}[$__interval]))\r\n)",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  }
 ]
}