---
apiVersion: v1
kind: Service
metadata:
  name: immich-server
  labels:
    app: immich
spec:
  selector:
    app: immich
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: metrics2
    port: 8082
    targetPort: metrics2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
  labels:
    app: immich
spec:
  selector:
    matchLabels:
      app: immich
  template:
    metadata:
      labels:
        app: immich
    spec:
      containers:
      - name: immich-server
        image: ghcr.io/immich-app/immich-server:v2.0.1
        ports:
        - name: http
          containerPort: 2283
        - name: metrics2
          containerPort: 8082
        env:
        # - name: IMMICH_LOG_LEVEL
        #   value: verbose
        - name: DB_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: pg-immich-app
              key: host
        - name: DB_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: pg-immich-app
              key: dbname
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: pg-immich-app
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-immich-app
              key: password
        - name: IMMICH_MACHINE_LEARNING_URL
          value: http://immich-machine-learning:3003
        - name: IMMICH_TELEMETRY_INCLUDE
          # https://docs.immich.app/install/environment-variables/#prometheus
          value: host
        - name: IMMICH_TRUSTED_PROXIES
          value: 10.0.0.0/8,192.168.0.0/16,172.16.0.0/12
        - name: REDIS_HOSTNAME
          value: df-immich
        - name: REDIS_PORT
          value: '6379'
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dragonfly-auth
              key: password
        volumeMounts:
        - mountPath: /usr/src/app/upload
          name: library
        # immich spends like 10 minutes in initial startup
        # livenessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /api/server/ping
        #     port: http
        #   initialDelaySeconds: 0
        #   periodSeconds: 10
        #   timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/server/ping
            port: http
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
        # startupProbe:
        #   failureThreshold: 30
        #   httpGet:
        #     path: /api/server/ping
        #     port: http
        #   initialDelaySeconds: 0
        #   periodSeconds: 10
        #   timeoutSeconds: 1
        resources:
          requests:
            memory: 400Mi
          limits:
            memory: 1000Mi
      volumes:
      - name: library
        persistentVolumeClaim:
          claimName: user-data
