---
apiVersion: v1
kind: Service
metadata:
  name: immich-machine-learning
spec:
  selector:
    app: machine-learning
  ports:
  - name: http
    port: 3003
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-machine-learning
  labels:
    app: machine-learning
spec:
  selector:
    matchLabels:
      app: machine-learning
  template:
    metadata:
      labels:
        app: machine-learning
    spec:
      containers:
      - name: immich-machine-learning
        image: ghcr.io/immich-app/immich-machine-learning:v2.0.1
        ports:
        - name: http
          containerPort: 3003
        env:
        - name: DB_HOSTNAME
          value: immich-postgresql
        - name: DB_DATABASE_NAME
          value: immich
        - name: DB_USERNAME
          value: immich
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-password
              key: password
        - name: IMMICH_MACHINE_LEARNING_URL
          value: http://immich-machine-learning:3003
        - name: REDIS_HOSTNAME
          value: redis
        - name: TRANSFORMERS_CACHE
          value: /cache
        volumeMounts:
        - mountPath: /cache
          name: cache
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
        startupProbe:
          failureThreshold: 60
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
        resources:
          requests:
            memory: 200Mi
          limits:
            # when doing active work, machine-learning uses a lot of memory for cache
            memory: 1024Mi
      volumes:
      - name: cache
        emptyDir: {}
