{
 "title": "Node / Windows / Details",
 "description": "Windows monitoring Dashboard.\r\n\r\n(Translated StarsL.cn's work. ID: 10467)",
 "tags": [
  "Prometheus",
  "windows_exporter"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "query_result(label_join(last_over_time(windows_os_info[$__range]), \"human_name\", \"/\", \"cluster_type\", \"cluster\"))"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "query_result(label_join(last_over_time(windows_os_hostname{cluster=~\"$cluster\"}[$__range]), \"human_name\", \": \", \"instance\", \"hostname\"))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Details of resources 【$show_hostname：$instance】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Number of CPU cores",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "windows_cpu_logical_processor{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 2, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "windows_memory_physical_total_bytes{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "cpu details",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum by (mode) (rate(windows_cpu_time_total{instance=~\"$instance\"}[$__rate_interval]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{mode}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "time() - windows_system_boot_time_timestamp{instance=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "uptime",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_memory_physical_total_bytes{instance=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "total",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "windows_memory_physical_free_bytes{instance=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "free",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "windows_memory_committed_bytes{instance=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "committed",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "windows_memory_available_bytes{instance=~\"$instance\"}",
     "legendFormat": "available"
    },
    {
     "expr": "windows_pagefile_limit_bytes{instance=~\"$instance\"}",
     "legendFormat": "pagefile size"
    },
    {
     "expr": "windows_pagefile_limit_bytes{instance=~\"$instance\"} - windows_pagefile_free_bytes",
     "legendFormat": "pagefile used"
    }
   ]
  },
  {
   "title": "network transmit",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(windows_net_bytes_sent_total{instance=~\"$instance\",nic!~'isatap.*|VPN.*'}[$__rate_interval])>0\r\n",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{nic}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "network transmit (switches)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(windows_hyperv_virtual_network_adapter_sent_bytes_total{instance=~\"$instance\",nic!~'isatap.*|VPN.*'}[$__rate_interval]) != 0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{adapter}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "network receive",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(windows_net_bytes_received_total{instance=~\"$instance\",nic!~'isatap.*|VPN.*'}[$__rate_interval]) != 0\n",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{nic}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "network receive (switches)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(windows_hyperv_virtual_network_adapter_received_bytes_total{instance=~\"$instance\",nic!~'isatap.*|VPN.*'}[$__rate_interval]) != 0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{adapter}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "disk read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(windows_logical_disk_read_bytes_total{instance=~\"$instance\"}[$__rate_interval])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "disk write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(windows_logical_disk_write_bytes_total{instance=~\"$instance\"}[$__rate_interval])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Network discarded/error packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate(windows_net_packets_outbound_discarded_total{instance=~\"$instance\", nic!~'isatap.*|VPN.*'}[$__rate_interval]) + rate(windows_net_packets_outbound_errors_total{instance=~\"$instance\"}[$__rate_interval]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "outbound",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "sum(rate(windows_net_packets_received_discarded_total{instance=~\"$instance\", nic!~'isatap.*|VPN.*'}[$__rate_interval]) + rate(windows_net_packets_received_errors_total{instance=~\"$instance\"}[$__rate_interval]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "received",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Process count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_system_threads{instance=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "threads",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "windows_system_processes{instance=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "processes",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "rate(windows_system_exception_dispatches_total{instance=~\"$instance\"}[$__rate_interval])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "exceptions",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "disk space",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "max by(volume) (windows_logical_disk_size_bytes{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(volume) (windows_logical_disk_free_bytes{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "1 - max by(volume) (windows_logical_disk_free_bytes{instance=~\"$instance\"} / windows_logical_disk_size_bytes{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "disk read IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(windows_logical_disk_reads_total{instance=~\"$instance\"}[$__rate_interval])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "free disk space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_logical_disk_free_bytes{instance=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "disk write io",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(windows_logical_disk_writes_total{instance=~\"$instance\"}[$__rate_interval])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  }
 ]
}