{
 "title": "Node / Windows / Cluster",
 "description": "Windows monitoring Dashboard.\r\n\r\n(Translated StarsL.cn's work. ID: 10467)",
 "tags": [
  "Prometheus",
  "windows_exporter"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": {
     "query": "label_values(windows_os_info,job)"
    }
   },
   {
    "name": "hostname",
    "label": "hostname",
    "query": {
     "query": "label_values(windows_os_info{job=~\"$job\"},hostname)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(windows_os_info{job=~\"$job\", hostname=~\"$hostname\"},instance)"
    }
   },
   {
    "name": "show_hostname",
    "label": "show_hostname",
    "query": {
     "query": "label_values(windows_os_hostname{job=~\"$job\", instance=~\"$instance\"},hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Resource overview. Currently selected host:【$show_hostname】 Instance: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "$job:Overview of Server Resources",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by(instance) (windows_os_info)"
    },
    {
     "expr": "max by(instance) (windows_os_hostname)"
    },
    {
     "expr": "max by(instance) (time() - windows_system_boot_time_timestamp)"
    },
    {
     "expr": "max by(instance) (windows_cpu_logical_processor)"
    },
    {
     "expr": "avg by (instance) (windows_cpu_core_frequency_mhz)"
    },
    {
     "expr": "1 - avg by (instance) (irate(windows_cpu_time_total{mode=\"idle\"}[$__range]))",
     "legendFormat": "CPU Utilization"
    },
    {
     "expr": "avg by (instance) (windows_memory_physical_total_bytes)"
    },
    {
     "expr": "1 - max by (instance) (windows_memory_physical_free_bytes{volume=~\"C:\"} / windows_memory_physical_total_bytes)",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "1 - max by (instance) (windows_logical_disk_free_bytes{volume=~\"C:\"} / windows_logical_disk_size_bytes)"
    },
    {
     "expr": "1 - max by (instance) (windows_logical_disk_free_bytes / windows_logical_disk_size_bytes)"
    }
   ]
  },
  {
   "title": "cpu %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "1 - avg by (instance) (rate(windows_cpu_time_total{job=~\"$job\", mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "memory %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - max_over_time(windows_memory_physical_free_bytes[$__rate_interval]) / max_over_time(windows_memory_physical_total_bytes[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "network transmit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum by (instance) (rate(windows_net_bytes_sent_total{nic!~'isatap.*|VPN.*'}[$__rate_interval]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "network receive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum by (instance) (rate(windows_net_bytes_received_total{nic!~'isatap.*|VPN.*'}[$__rate_interval]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "disk read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum by (instance) (rate(windows_logical_disk_read_bytes_total[$__rate_interval]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}_Read",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "disk write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum by (instance) (rate(windows_logical_disk_write_bytes_total[$__rate_interval]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}_Writing",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "disk read IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum by (instance) (rate(windows_logical_disk_reads_total[$__rate_interval]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}_Read",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "disk write IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum by (instance) (rate(windows_logical_disk_writes_total[$__rate_interval]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}_Writing",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  }
 ]
}