{
 "title": "Proxmox / Nodes",
 "tags": [
  "prometheus",
  "proxmox"
 ],
 "time": { "from": "2024-06-03T22:53:44.776Z", "to": "2024-06-03T23:05:14.501Z" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Cluster",
    "query": {
     "query": "label_values(pve_node_info, instance)"
    }
   },
   { "name": "node_name", "label": "Nodes", "query": { "query": "label_values(pve_node_info,id)" } }
  ]
 },
 "panels": [
  {
   "title": "Node info",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pve_node_info{instance=\"$instance\", id=~\"node/$node_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pve_up{instance=\"$instance\", id=~\"node/$node_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pve_uptime_seconds{instance=\"$instance\", id=~\"node/$node_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pve_memory_size_bytes{instance=\"$instance\", id=~\"node/$node_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pve_cpu_usage_limit{instance=\"$instance\", id=~\"node/$node_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pve_memory_usage_bytes{instance=\"$instance\", id=~\"node/$node_name\"} / pve_memory_size_bytes",
     "legendFormat": "{{id}} Memory Usage"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max_over_time(pve_cpu_usage_ratio{instance=\"$instance\", id=~\"node/$node_name\"}[$__rate_interval]) * 100",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Guests",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by (id, name, type) (pve_guest_info{instance=\"$instance\", node=~\"$node_name\"})"
    },
    {
     "expr": "sum by (id) (pve_up{instance=\"$instance\"} and on (id, instance) pve_guest_info{instance=\"$instance\", node=~\"$node_name\"})"
    },
    {
     "expr": "sum by (id) (pve_cpu_usage_limit{instance=\"$instance\"} and on (id, instance) pve_guest_info{instance=\"$instance\", node=~\"$node_name\"})"
    },
    {
     "expr": "sum by (id) (pve_cpu_usage_ratio{instance=\"$instance\"} and on (id, instance) pve_guest_info{instance=\"$instance\", node=~\"$node_name\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (id) (pve_memory_size_bytes{instance=\"$instance\"} and on (id, instance) pve_guest_info{instance=\"$instance\", node=~\"$node_name\"})"
    },
    {
     "expr": "sum by (id) (pve_memory_usage_bytes{instance=\"$instance\",template!=\"1\"} / pve_memory_size_bytes and on (id, instance) pve_guest_info{instance=\"$instance\", node=~\"$node_name\"} and on (id) pve_up==1)"
    },
    {
     "expr": "sum by (id) (pve_disk_size_bytes{instance=\"$instance\"} and on (id, instance) pve_guest_info{instance=\"$instance\", node=~\"$node_name\"})"
    },
    {
     "expr": "sum by (id) (pve_disk_usage_bytes{instance=\"$instance\"} / pve_disk_size_bytes and on (id, instance) pve_guest_info{instance=\"$instance\", node=~\"$node_name\", type=\"lxc\"})"
    }
   ]
  },
  {
   "title": "Storage usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(pve_disk_usage_bytes{instance=\"$instance\", id=~\"storage/$node_name/.+\"} / pve_disk_size_bytes) * on (id, instance) group_left(storage) pve_storage_info",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Guests CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(max_over_time(pve_cpu_usage_ratio{instance=\"$instance\"}[$__rate_interval]) * on(id, instance) group_left(name, type) pve_guest_info{instance=\"$instance\", node=~\"$node_name\"}) and on(id, instance) pve_up == 1",
     "legendFormat": "{{name}} ({{type}})"
    }
   ]
  },
  {
   "title": "Guests memory usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(pve_memory_usage_bytes{instance=\"$instance\"} / pve_memory_size_bytes * on(id, instance) group_left(name, type) pve_guest_info{instance=\"$instance\", node=~\"$node_name\"}) and on(id, instance) pve_up == 1",
     "legendFormat": "{{name}} ({{type}})"
    }
   ]
  },
  {
   "title": "Network IO/s",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "((rate(pve_network_receive_bytes{instance=\"$instance\"}[$__rate_interval])+rate(pve_network_transmit_bytes{instance=\"$instance\"}[$__rate_interval])) * on(id, instance) group_left(name, type) pve_guest_info{instance=\"$instance\", node=~\"$node_name\"}) and on(id, instance) pve_up == 1",
     "legendFormat": "{{name}} ({{type}})"
    }
   ]
  },
  {
   "title": "Disk IO/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(\r\n        (\r\n            rate(pve_disk_write_bytes{instance=\"$instance\"}[$__rate_interval])\r\n            +\r\n            rate(pve_disk_read_bytes[$__rate_interval])\r\n        )\r\n        *\r\n        on(id, instance) group_left(name, type) pve_guest_info{instance=\"$instance\", node=~\"$node_name\"}\r\n        \r\n    \r\n) and on(id, instance) pve_up == 1",
     "legendFormat": "{{name}} ({{type}})"
    }
   ]
  }
 ]
}