---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: alert-zfs-vdev
  labels:
    prometheus.io/instance: main
    instance.prometheus.io/main: enable
    instance.prometheus.io/prompp: enable
spec:
  groups:
  - name: alert-zfs-vdev
    rules:
    - alert: ZfsVdevErrors
      expr: zfs_vdev_errors{path!=""} > 0
      labels:
        severity: warning
      annotations:
        summary: ZFS vdev has errors
        description: >-
          {{ $labels.instance }}:
          pool {{ $labels.zpool }}:
          device {{ $labels.path }}:
          {{ $value }} {{ $labels.type }} errors
    - alert: ZfsVdevSlow
      expr: increase(zfs_vdev_slow_ios{path!=""}[1m]) > 0
      labels:
        severity: critical
      annotations:
        summary: ZFS vdev had I/O operations that are slower than 30 seconds in last 1 minute
        description: >-
          {{ $labels.instance }}:
          pool {{ $labels.zpool }}:
          device {{ $labels.path }}:
          {{ $value }} operations
    - alert: ZfsTrimErrors
      expr: zfs_vdev_trim_errors{path!=""} > 0
      labels:
        severity: critical
      annotations:
        summary: ZFS vdev trim has errors
        description: >-
          {{ $labels.instance }}:
          pool {{ $labels.zpool }}:
          device {{ $labels.path }}:
          {{ $value }} errors
    - alert: ZfsVdevNotHealthy
      expr: zfs_vdev_state{path=""} != 7
      labels:
        severity: critical
      annotations:
        summary: ZFS vdev is in bad state
        description: >-
          {{ $labels.instance }}:
          pool {{ $labels.zpool }}:
          vdev {{ $labels.vdev }}:
          {{ if eq $value 0.0 }}unknown{{ end }}
          {{ if eq $value 1.0 }}closed{{ end }}
          {{ if eq $value 2.0 }}offline{{ end }}
          {{ if eq $value 3.0 }}removed{{ end }}
          {{ if eq $value 4.0 }}can't open{{ end }}
          {{ if eq $value 5.0 }}faulted{{ end }}
          {{ if eq $value 6.0 }}degraded{{ end }}
    - alert: ZfsDeviceNotHealthy
      expr: zfs_vdev_state{path!=""} != 7
      labels:
        severity: critical
      annotations:
        summary: ZFS disk is in bad state
        description: >-
          {{ $labels.instance }}:
          pool {{ $labels.zpool }}:
          vdev {{ $labels.vdev }}:
          path {{ $labels.path }}:
          {{ if eq $value 0.0 }}unknown{{ end }}
          {{ if eq $value 1.0 }}closed{{ end }}
          {{ if eq $value 2.0 }}offline{{ end }}
          {{ if eq $value 3.0 }}removed{{ end }}
          {{ if eq $value 4.0 }}can't open{{ end }}
          {{ if eq $value 5.0 }}faulted{{ end }}
          {{ if eq $value 6.0 }}degraded{{ end }}
    - alert: ZfsOldScan
      expr: (time() - (zfs_pool_scan_end_time_seconds != 0)) / (60 * 60 * 24) > 35
      labels:
        severity: info
      annotations:
        summary: Last ZFS pool scrub was more than 35 days ago
        description: >-
          {{ $labels.instance }}:
          pool {{ $labels.zpool }}:
          {{ $value | humanize }}
    - alert: ZfsNoScan
      expr: zfs_pool_config_txg unless zfs_pool_scan_state
      for: 1h
      labels:
        severity: info
      annotations:
        summary: ZFS pool was never scraped
        description: >-
          {{ $labels.instance }}:
          pool {{ $labels.zpool }}
    - alert: ZfsOldTrim
      # "monthly" trim seems to happen every 35 days
      expr: (time() - (zfs_vdev_trim_action_time{path!=""} != 0)) / (60 * 60 * 24) > 40
      labels:
        severity: info
      annotations:
        summary: Last ZFS pool vdev TRIM was more than 30 days ago
        description: >-
          {{ $labels.instance }}:
          pool {{ $labels.zpool }}:
          device {{ $labels.path }}
          {{ $value | humanize }}
    - alert: ZfsNoTrim
      expr: |-
        zfs_vdev_trim_state{path!=""} == 0
        unless
        zfs_vdev_trim_unsupported == 1
      for: 1h
      labels:
        severity: info
      annotations:
        summary: ZFS pool vdev was never trimmed
        description: >-
          {{ $labels.instance }}:
          pool {{ $labels.zpool }}:
          device {{ $labels.path }}
