{
 "title": "immich",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "query": "prometheus" },
   {
    "name": "immich_cluster",
    "query": {
     "query": "query_result(group by(immich_cluster) (last_over_time(immich_storage_disk_size{location!=\"\"}[$__range])))"
    }
   },
   {
    "name": "user",
    "query": {
     "query": "query_result(group by(user_id, user_name) (last_over_time(immich_statistics_user_usage{immich_cluster=\"$immich_cluster\"}[$__range])))"
    }
   }
  ]
 },
 "panels": [
  { "title": "general", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "version history",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max by(instance, service_version) (last_over_time(target_info{immich_cluster=\"$immich_cluster\"}[$__interval]))\r\nor on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "disk size",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(max_over_time(immich_storage_disk_size{immich_cluster=\"$immich_cluster\"}[$__interval]))",
     "legendFormat": "disk size"
    }
   ]
  },
  {
   "title": "storage used",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(avg_over_time(immich_storage_disk_use{immich_cluster=\"$immich_cluster\"}[$__interval]))",
     "legendFormat": "disk"
    },
    {
     "expr": "max(avg_over_time(immich_statistics_usage{immich_cluster=\"$immich_cluster\"}[$__interval]))",
     "legendFormat": "files"
    }
   ]
  },
  {
   "title": "users",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(user_id, user_name) (immich_statistics_user_usage{immich_cluster=\"$immich_cluster\", user_id=~\"$user\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by(user_id, user_name) (immich_statistics_user_photo_count{immich_cluster=\"$immich_cluster\", user_id=~\"$user\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by(user_id, user_name) (immich_statistics_user_video_count{immich_cluster=\"$immich_cluster\", user_id=~\"$user\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by(user_id, user_name) (immich_statistics_user_quota_bytes{immich_cluster=\"$immich_cluster\", user_id=~\"$user\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "by user", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "user: space used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(user_name) (avg_over_time(immich_statistics_user_usage{immich_cluster=\"$immich_cluster\", user_id=~\"$user\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "user: quota",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(user_name) (avg_over_time(immich_statistics_user_quota_bytes{immich_cluster=\"$immich_cluster\", user_id=~\"$user\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "user: space used 24h delta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(user_name) (\r\n+ (avg_over_time(immich_statistics_user_usage{immich_cluster=\"$immich_cluster\", user_id=~\"$user\"}[$__interval]))\r\n- (avg_over_time(immich_statistics_user_usage{immich_cluster=\"$immich_cluster\", user_id=~\"$user\"}[$__interval] offset 24h))\r\nand (last_over_time(immich_statistics_user_usage{immich_cluster=\"$immich_cluster\", user_id=~\"$user\"}[$__interval]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "user: quota %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(user_name) (\r\n  + avg_over_time(immich_statistics_user_usage{immich_cluster=\"$immich_cluster\", user_id=~\"$user\"}[$__interval])\r\n  / avg_over_time(immich_statistics_user_quota_bytes{immich_cluster=\"$immich_cluster\", user_id=~\"$user\"}[$__interval])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}