{
 "title": "Kubernetes: Cluster / Ephemeral Storage Nodes",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "query_result(label_join(up{job=\"esm\"}, \"human_name\", \"/\", \"cluster_type\", \"cluster\"))"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(ephemeral_storage_node_capacity{cluster=~\"$cluster\"},node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Storage Usage in Bytes by Namespace",
   "type": "timeseries",
   "description": "Storage usage in bytes by namespaces on the Kubernetes cluster",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace) (ephemeral_storage_pod_usage{node=~\"${node}\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Node Storage Usage Bytes",
   "type": "timeseries",
   "description": "Total capacity of the ephemeral storage for nodes with their usage bytes",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(node) (ephemeral_storage_node_capacity{node=~\"${node}\"})",
     "legendFormat": "Total of {{node}}"
    },
    {
     "expr": "sum by(node) (ephemeral_storage_node_capacity{node=~\"${node}\"} - ephemeral_storage_node_available{node=~\"${node}\"})",
     "legendFormat": "Used by {{node}}"
    }
   ]
  },
  {
   "title": "Node Storage Usage Percentage",
   "type": "timeseries",
   "description": "Percentage of ephemeral storage used on nodes",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(node) (ephemeral_storage_node_percentage{node=~\"${node}\"})",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}